### ISSUE TITLE
Configuring default rstudio user

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker#101]
Dear @ihrke ,

I think you recently came across a problem regarding the default user for the rocker/rstudio Docker image that led to your edit on the wiki? 

My apologies for any trouble, I may have inadvertently broken the default user login as rstudio for a time yesterday, but this should be fixed.  Please let me know if you encounter any issues.  

We really appreciate folks jumping in and editing the wiki.  However, we do try not to change default configurations on people without good reason and clear notification.  If you encounter issues where the wiki seems to be wrong, please file a bug report here first.  

Thanks,

Your friendly rocker maintainers

**Comment by ihrke** [comment]
Hi, 

sorry for the trouble. I was just `docker pull`ing the image and couldn't log in. In the `Dockerfile` I saw that the username was set to `docker` so I changed the wiki accordingly. Sorry if I was hasty, I will file a bug report next time...

Cheers,

Matthias

**Comment by cboettig** [comment]
No problem, I should have tested that out on a branch first anyhow.  all
fixed now.
