### ISSUE TITLE
Running RStudio and RStudio-Daily images side-by-side.

### ISSUE THREAD

**Issue by Thell** [rocker-org/rocker#104]
Is this doable? When I try with RStudio on port 8080:8787 and daily on 8787:8787 then whichever I log into bumps the other off. Shouldn't they be completely distinct?

**Comment by eddelbuettel** [comment]
Well on the same (normal) host you can run only one RServer instance per user, so given that Docker is "merely" process namespacing etc pp I am not sure you can.

**Comment by cboettig** [comment]
This is possible, but you will need to use different browsers for the
different sessions (eg one in Chrome & one in Firefox, not simply different
windows).  This is a known issue in Rstudio server and not unique to rocker
so it might be good to follow up with them.

**Comment by Thell** [comment]
I had _just_ seen your post on stackoverflow regarding [running multiple instances](http://stackoverflow.com/questions/22938305/run-multiple-instances-of-rstudio-in-a-web-browser). I'm thinking perhaps that using a different hostname for each container may allow for the single browser concept... Will update after testing.

**Comment by eddelbuettel** [comment]
(Nobody asked about this but let me mention that ESS let's you have as many _concurrent_ R sessions as you please, and I frequently have half a dozen or more in the session running at work.)

**Comment by Thell** [comment]
OK, so this turns out to pretty pretty easy for as many sessions as desired. If each container uses a different host port then within chrome a new profile can be made for each and they wont clobber each other. I assume chromium and if firefox doesn't have launching issues should work as well.

Perhaps altering the rserver.conf on each would be more effective. Next up is to see if different R versions can be running in the different containers using the rsession-which-r setting in /etc/rstudio/rserver.conf.

BTW - given the description of rstudio-daily:

> Daily builds of pre-release RStudio, built on daily builds of pre-release R. Live on the bleeding edge.

I'd think that Rdevel would be used by default.

**Comment by cboettig** [comment]
Thell,

Thanks for digging into this, that workaround sounds promising but I'm
afraid  I don't follow.  Are you suggesting that the container call
`rserver` with a different option than the default 8787 for the
`--www-port` argument?

Oh, good catch, forgot about the aliases.  I've just pushed a fix so
rstudio-daily will use unsuffering-consequences by default

**Comment by Thell** [comment]
@cboettig I'm still fleshing this out, my current line of thought is that on the rstudio images there (perhaps) should be a rserverconf.sh along with the userconf.sh that could be populated with env variables when provided.

**Comment by Thell** [comment]
@cboettig I went to try out the 'latest' with unsuffering-consequences yet it seems there is a tag issue... According to the [tag history for latest](https://index.docker.io/v1/repositories/rocker/rstudio-daily/tags/latest) it is still pointing to the build from a few days ago. Should I just work off of master?

**Comment by Thell** [comment]
No matter as the dockerfile hadn't been updated on dockerhub, so I built from the git master... Looks good except for an rstudio error output. Here's three sessions with two different R versions and three different RStudio versions...

![Imgur](http://i.imgur.com/qQERMJG.png)

**Comment by eddelbuettel** [comment]
Nice. Now waiting for ports 9090 and 10010 :)

**Comment by Thell** [comment]
LOL, yeah something like nginx-proxy might help with that.

**Comment by cboettig** [comment]
@Thell Thanks, nice to see this working.  A PR for this would be welcome.  I'm still not clear on what you're adjusting to get this to work: are you just changing the port _inside_ the container from the default 8787? (I agree that we can set this up to work with environmental variables / conf script but just trying to understand what it takes to get this working first.  (Presumably that would break the `-P` flag on `docker run` since we couldn't explicitly `EXPOSE` the right port in the Dockerfile?)  Or maybe I'm just confused.

**Comment by Thell** [comment]
@cboettig the above example was simply a matter of using '-p 6060:8787', '-p 7070:8787', etc... for each different container along with using a different browser profile so as to not clash.

----

That's too manual and too much effort IMO. I tested a setup this morning using fig, the NetworkManager dnsmasq, and nginx-proxy which worked nicely without having to setup browser profiles or alter the ports. It is still too manual but handles the container control very nicely (and a little bash script should completely automated it).

Essentially what I did was create a [fig.yml(gist)](https://gist.github.com/Thell/f658cc175b37adc61261) which uses locally tagged images. Then, after doing `fig up -d` the address of the nginx-proxy from

    docker inspect rocker_nginxproxy_1 | grep IPA

is updated in `/etc/NetworkManager/dnsmasq.d/docker.localhost` like

    # Resolve to localhost nginx-proxy container.
    address=/docker.localhost/172.17.0.44

followed by

    sudo service network-manager restart

and lastly I open chrome where I restore a SessionBuddy session with

````
RStudio daily
http://daily.docker.localhost/
RStudio prev
http://preview.docker.localhost/
RStudio prev
http://preview2.docker.localhost/
RStudio stable
http://stable.docker.localhost/
````

where the tab names are defined using `Tab Title Tweaker` with the rules

````
suffix, stable*, stable
suffix, daily*, daily
suffix, preview*, prev
````

After logging in with `Thell/Thell` into each of them quick navigation while in full-screen comes from using `Quick Tabs` by simply doing `[alt][j]` and any of the short names.

**Comment by Thell** [comment]
I forgot to mention that I also had added

    DOCKER_OPTS="--bip=172.17.42.1/24 --dns=127.0.1.1"

to `/etc/default/docker`.

**Comment by eddelbuettel** [comment]
Looks like a very nice and comprehensive local configuration but really something we can (or should) push out.  I may of course be wrong.  Thoughts, @cboettig ?

**Comment by Thell** [comment]
@eddelbuettel, a setup like that, while definitely directly related to the topic of this issue, seems well outside the scope of rocker except as far as the supporting images go. Which, to me, means the rstudio images should be tagged at stable, preview, and daily and (without a doubt) should include the requisite packages and user-land programs to make use of its main features for reproducible research and package development.

Perhaps, beyond being the official R containers, rocker could be the official RStudio containers too...

**Comment by eddelbuettel** [comment]
(Thanks. I think you caught that I missing a critical _not_ which I now added.)

**Comment by Thell** [comment]
The original question seems to have been answered...

**Comment by cboettig** [comment]
@Thell , or anyone following this thread:

Just a note that this seem to no longer be an issue, at least in Chrome Version 40.0.2214.111 (64-bit) and RStudio Version 0.98.1102. I can launch multiple Rstudio docker containers and open each in the same Chrome session without needing multiple chrome user profiles now, and I'm no longer signed out of one as I interact with the other. Haven't tried with other browsers and not sure what change was responsible for making this "just work", so I'd be curious if others can confirm if it works for them now as well.

**Comment by Thell** [comment]
@cboettig Did you happen to change your docker networking setup? Are you accessing both on the same IP?

**Comment by cboettig** [comment]
ha, your right.  Nothing changed in my docker setup, but I had one on
0.0.0.0 and one on 127.0.0.1
