### ISSUE TITLE
Base images R package installation

### ISSUE THREAD

**Issue by Thell** [rocker-org/rocker#106]
What do you think of taking up a *_little_* bit more space in the rocker base image for installation (or non-removal in some cases) of the system lib/lib*-dev files that are needed to allow for source installation of R packages (CRAN, Bioconductor and Omegahat packages) without requiring the multi-step process required now.

The idea covers use cases and diversity that the `verse` images don't, lowers the barrier for new users on both the `verse` and base images and takes advantage of the efforts of the [cran2deb](http://r-forge.r-project.org/projects/cran2deb/) and [Debian R Package Archive](http://debian-r.debian.net/) while still keeping in line with the docker/rocker goals of small, layered, ephemeral containers. 

With the hope that you would be accepting of the idea [a gist](https://gist.github.com/Thell/ddf09e296d12a4d74d1b) has been created with a simple shell script that scrapes the dependencies from  the [Debian R Package Archive](http://debian-r.debian.net/).

The preliminary summary output is:

```
8653 pkg-urls
36966 dsc-urls
8645 filtered-dsc-urls

93 SystemRequirements (non R package depends) 
57 lib* requirements.
46 lib*dev requirements.

The estimated space requirement on installed lib* is: 236K

Where a few had one issue or another...

libgcj10-dev No packages found
libtktable2.9 Installed-Size not found
libtiff4-dev Installed-Size not found
libgmp3c2 No packages found
libmpich1.0-dev Installed-Size not found
libgd2-noxpm No packages found
```

The space requirement should be even smaller than stated as some of the required libs may already be present. (The unfiltered list is at the bottom of the post.)

An email is being sent to Don Armstrong, the maintainer of the Debian R Package Archive, to find out about the feasibility of directly parsing out a dependency list from the archive instead of scraping it.

-----
```
The non-filtered full dependency list...
antiword
autotools-dev
blacsgf-mpich-dev
bwidget
cdbs
debhelper(>>4.1.0)
fftw-dev
ggobi
graphviz
grass-dev
imagemagick
jags
libarmadillo-dev
libatk1.0-dev
libbam-dev
libblas-dev
libboost-dev
libboost-graph-dev
libcairo2-dev
libc-dev-bin
libcurl4-openssl-dev
libdieharder-dev
libfftw3-dev
libfontconfig1
libfontconfig1-dev
libfreetype6
libfreetype6-dev
libgcj10-dev
libgd2-noxpm
libgd2-noxpm-dev
libgdal1-dev
libgl1-mesa-dev
libglade2-dev
libglib2.0-dev
libglu1-mesa-dev
libgmp3c2
libgmp3-dev
libgraphviz-dev
libgsl0-dev
libgsl0ldbl
libgtk2.0-0
libgtk2.0-dev
libhdf5-serial-dev
libitpp-dev
libjpeg62
libjpeg62-dev
libmagick++-dev
libmpfr-dev
libmpich1.0-dev
libmysqlclient-dev
libnetcdf-dev
libopenmpi-dev
libpango1.0-dev
libperl-dev
libpg-java
libpng12-dev
libpq-dev
libprotobuf-dev
libprotoc-dev
libquantlib0-dev
libsprng2-dev
libsqlite3-dev
libtext-csv-xs-perl
libtiff4-dev
libtk-img-dev
libtktable2.9
libxml2
libxml2-dev
libxt-dev
netcdf-bin
openjdk-6-jdk
openjdk-6-jre
pari-gp
perl
pkg-config
poppler-utils
proj
protobuf-compiler
pvm-dev
scalapack-mpich-dev
tcl8.5-dev
tcsh|csh|c-shell
tk8.5-dev
ttf-liberation
udunits
unixodbc-dev
wordnet-base
xauth
xclip
xfonts-base
xvfb
zlib1g
zlib1g-dev
```

**Comment by eddelbuettel** [comment]
I am not sure.

Base images are, well, base images.  Docker excels at many things, and one of them is _layering_ just how Carl and I build other containers on top of base.

So instead of inflating base, can't you just create "the Thell dev basis container" with whatever lib*-dev packages you feel like?

**Comment by Thell** [comment]
@eddelbuettel This isn't about me. It's about you providing an image that _stays_ as nice as you have so carefully layered it to be and matches up with the vision of _EASY_ and reproducible that docker professes and @cboettig describes as the motivation behind rocker.

It is supposed to be usable, yes?

----

How do you handle needing to install dependencies onto images?  What steps do you go through to do `install.packages("httr")`?

Perhaps...
- start container
- issue install command and get error on xml2-config not being found
- open root terminal to container
- apt-cache search xml2-config <ohhh, that isn't helpful>
  _Look up online, use apt-file on host, or whatever to identify provider_
- apt-get update <ruining _your_ nice layered setup and making mine harder to maintain>
- apt-get install libxml2-dev -y --no-install-recommends
- go back to userspace and try again, repeat until successful.

_That was to work with the super duper simple `latest.R` from *this project* on a *provided* image._

__What, specifically, would you tell an end user, who wanted to create a small reproducible image to accompany the publishing of their research, to do?__

 <_BTW - this was only one example, building Rcpp within an image, installing other simple CRAN packages like gmp, Rmpfr and a few others each required this on fresh containers._>

**Comment by eddelbuettel** [comment]
Yes, I obviously install iteratively until requirements are met.  Why would that be different from interactive work on a normal machine?   And I even do it interactively: fire up base container, install what is needed, get work done, store result outside of container ... and remove (temp.) container.

Base is meant to be _minimal_.

**Comment by cboettig** [comment]
@Thell Thanks for your suggestion.  Figuring out just what and how many containers to provide in rocker is a challenging thing, and we welcome community input in striking that balance well.  We also thought quite a bit about this at the start of the rocker project. We wanted to provide 'batteries included' packages that meet a variety of needs, but we also decided that we had to avoid creating an alphabet-soup of different Rocker containers that would be difficult for a new user to choose between and more difficult for us to maintain well.

Our solution was to provide base images that are well-suited for a range of people developing R-flavored Docker containers. These containers are meant to be minimal, the assumption being that people would use them primarily when they know just how to go about adding additional packages to a Debian-based system and just want a robust, maintained, lightweight and ready-to-go solution.  

Someone building a Dockerfile on r-base should simply install the Debian binaries for the R package directly (e.g. as we do in hadleyverse by adding Don Armstrong's repo to sources.list), e.g. `apt-get install r-cran-httr`.  This will also avoid having to install the larger dev libraries needed to compile the packages from source.  If I understand how you are generating it, your list only covers the dependencies of packages that can be installed that way anyhow, so it seems both lighter and simpler to just grab the R binaries in the first place. 

Of course there will always be packages that have to be installed from source and need external libraries.  As always, we assume someone writing a Dockerfile knows how to install their packages from source with the libraries they need, and probably doesn't want a whole lot of extra libraries they don't need.  

For end-users just looking for a batteries-included solution, we have packages like hadleyverse. I must say it seems a bit weird to provide the binary libraries for something like `libxml2-dev` without having the corresponding R package installed.  Users can safely guess that `hadleyverse` has `httr` installed already.  If one was to make a Docker container with all these libraries already installed, why not also install the corresponding R packages?  It doesn't add that much more space.  `hadleyverse` is our attempt at a sensible subset of this -- it has many (like the java runtime libraries) but not all of the more specialized libraries (jags) already installed.  When I have a project that uses the R package `R2jags`, I frequently build on `hadleyverse` and just `apt-get install` the package: e.g. https://github.com/cboettig/nonparametric-bayes/blob/master/manuscripts/Dockerfile

Anyway, hope this helps.  Maybe there's a case to be made to add Don's repository to the sources.list in r-base, or something lighter than hadleyverse at any rate (LaTeX deps; also required for building CRAN packages just to build the manuals, is the biggest culprit on bloating `hadleyverse`).

**Comment by Thell** [comment]
Thanks for the thoughtful and complete reply Carl. In reading your and Dirks blog posts and articles I had the impression that the goal keywords would be easy, reproducible, shareable and archivable. If I'm wrong in that I'll shut up now, if not then your are missing _easy_; simple, yes, easy, no.

It seems, as is mentioned, that there must indeed be a balance struck between the minimal image and the "batteries included" images. Much like mounting a tex providing container gives us. Perhaps the balance isn't about _what_ is already there as much as it is the _ease of getting_ from where you start to where you want to be. If each of us is doing an iterative approach to the simplest of installs each time we update our images then that seems to indicate that something is askew. I imagine most of us that are using the docker images (now) are the same ones that built our kernels from scratch years back and boot-strapped gentoo to the specs of our hardware, but that doesn't mean things didn't evolve to get _easier_!

It is understandable that docker best practices recommend against sudoers (disallowing the use of Rstudio's shell or of using `system`) and that having a minimal size indicates purging and cleaning out apt-cache and listings. Even if Don's repository was included in sources.list users would still need to jump ship to the host and back via a root terminal to `apt-get install`; could a user-land method  be given permission to get and install the dependencies from a blessed repository without opening a can of worms? Is that even possible? (Just throwing it out there.)

**Comment by cboettig** [comment]
Note that Docker is just discouraging sudo in Dockerfiles, not in general.
The `rstudio` instances-based instances can all take the flag `-e
ROOT=TRUE` to add the default user to sudoers automatically, and can
`system(sudo apt-get install r-cran-httr)` or whatever they need to.

All of the Dockerfiles have root permission user implicitly anyway, so a
Dockerfile building on any of our images would just do a `RUN apt-get
update && apt-get -y install r-cran-httr` etc without needing sudo.  So I'm
not sure what the difficulty is.

**Comment by Thell** [comment]
Thanks Carl, yes I've seen the RStudio flag and actively use it but I did think the reason it wasn't the default was a best practice issue so I have been attempting to use it sparingly. Regarding the base image I have been attempting to use it as an interactive user to do requirement installs, where-as from your comment it seems I should setup the environment first via a Dockerfile then do whatever needs doing.

My experience as portrayed in my second post illustrates what I considered a difficulty. I didn't think I'd be the only one encountering such an issue. Be it as it is, perhaps I am...

**Comment by Thell** [comment]
Regardless of the direction investigated it seems there isn't a general solution that is _easier_ than what currently exists unless around 700MB of space is used (which is out of the question), and that is just for the dependencies of the lib*dev files... I concede.
