### ISSUE TITLE
Missing manuals

### ISSUE THREAD

**Issue by IainColledge** [rocker-org/rocker#108]
Hi,

The package manuals seem to be there but when I click on the Introduction for example it is missing, URL /doc/manual/R-intro.html was not found

Please can you advise how to install?

**Comment by eddelbuettel** [comment]
There are three packages starting with `r-doc-*`; you want to install `r-doc-html` for the html version. 

So do

     apt-get install r-doc-html

inside the container.

**Comment by IainColledge** [comment]
Perfect, thank you, had to do an apt-get update beforehand for anyone reading this.

**Comment by eddelbuettel** [comment]
Yes, sorry, that is always implied.  So as you seem to be taken care of, I'll close this.

**Comment by IainColledge** [comment]
Understood, never hurts to write it down though :) Thanks again for your swift help.
