### ISSUE TITLE
Build request - Add java to the build

### ISSUE THREAD

**Issue by IainColledge** [rocker-org/rocker#109]
Hi, 

Wanted to say thanks very much for putting this together as really find it useful, would just like to suggest adding java for Spark R is all as part of the image.

Iain

**Comment by eddelbuettel** [comment]
Which build did you have in mind?   

We aim to keep the basic Rocker image fairly minimal, and would prefer not to include Java in it, just how we do not include LaTeX.   But it may be worth discussing another Dockerfile with Hadoopy or Sparky things.

**Comment by IainColledge** [comment]
Actually that would be best I think, Hadoop and Spark as well as you say to keep things clean, anyway was just a suggestion and thanks very much for doing this on docker in the first place, just makes life so easy when trying out rstudio!

**Comment by daroczig** [comment]
Here's a strip-down version of a Dockerfile that I use as the base image for hadoopish R stuff: https://gist.github.com/daroczig/9c6b2f0d1020f84f60a0

@eddelbuettel I'd be happy to add this as a new variant of `rocker` if you consider this as being useful -- just let me know how to proceed please.

**Comment by eddelbuettel** [comment]
@cboettig and I are having our hands full with the existing ones.  Maybe an entry in the wiki plus maybe your entry at the hub for builds is a good solution offering folks access to this?

**Comment by daroczig** [comment]
Sure, thank you @eddelbuettel for the suggestions.
Sorry that it took so long, it's pretty slow to get this "officially" approved, but the Java container is available now at https://registry.hub.docker.com/u/cardcorp/r-java
I will update the wiki once I managed to add some other (hopefully generally useful) R-related images as well to the org Docker account.

**Comment by cboettig** [comment]
Very nice!  Note that we have always had rJava available in the `rocker/hadleyverse` container as well.

**Comment by daroczig** [comment]
Yeah, although the `hadleyverse` image is rather overkill for some for Hadoop-related task, like when you only need some JDBC driver. That's why I also have a separate build for e.g. `r-pandoc`, which is a minimal image for R-based reporting. Maybe I should simply switch to one "rule them all" Docker image :)

Anyway, not sure why this ticket is open -- you already provided a solution (`hadleyverse`) for the request, and it seems that there are some third-party alternatives as well :)

**Comment by cboettig** [comment]
yes indeed, great to have the lighter weight options from the community for these things.

**Comment by daroczig** [comment]
I've [updated](https://github.com/rocker-org/rocker/wiki/Home/_compare/417df314de9227d2ded5037dcdbe50eb81f9fb44...75decbb7ac9efa18b149156462bcd6ba493c8eb1) the wiki based on @eddelbuettel's above suggestion. Please let me know if there's anything else to be added/removed, and I'm happy to create a pull request to update the `README.md` as well, not sure if you think it would be useful or rather not.
