### ISSUE TITLE
RStudio-Daily image: library /usr/local/lib/... _and_ /usr/lib/...

### ISSUE THREAD

**Issue by Thell** [rocker-org/rocker#111]
I just noticed multiple duplicate packages in the rstudio-daily and `library()` shows both paths /usr/... and /usr/local/... are populated.

I haven't researched as of yet, and before doing so thought I'd ask what is already known. An issue search didn't give a good hit...

```
~$ du -Hs /usr/lib/R/library
49592	/usr/lib/R/library
~$ du -Hs /usr/local/lib/R/library
27476	/usr/local/lib/R/library
```

It looks like all of the packages in '/usr/local/lib/R/library/' are also in '/usr/lib/R/library/', but the ones in '/usr/local/lib/R/library/' are later versions.

**Comment by eddelbuettel** [comment]
No magic there:  
+ packages installed via `apt-get install r-cran-*` populate `/usr/lib` as packages do
+ packages installed by R via `install.packages()` go to `/usr/local/lib`

It's been like that for over a decade.

**Comment by Thell** [comment]
kk, thanks for that @eddelbuettel, do we want those dupes in the image though?

**Comment by eddelbuettel** [comment]
If it bothers you greatly you could provide a PR against the Dockerfile.

**Comment by Thell** [comment]
Roger that. Thanks.
