### ISSUE TITLE
install_github not working

### ISSUE THREAD

**Issue by ignacio82** [rocker-org/rocker#113]
I am not able to install DT in my docker [rocker/hadleyverse] image

    > devtools::install_github('rstudio/DT')
    Downloading github repo rstudio/DT@master
    Error in download(dest, src, auth) : client error: (403) Forbidden
    
Any ideas about how to solve this problem?

Thanks!

**Comment by cboettig** [comment]
curious, works for me.  Can you try again?  Can you install other images from github?  Is the same command working for you outside of docker (e.g. not a connectivity problem?)

Also, please see our [CONTRIBUTING.md](https://github.com/rocker-org/rocker/blob/master/CONTRIBUTING.md) guidelines which has some advice about helpful information you should provide so we can better troubleshoot your problem.  Thanks.

**Comment by ignacio82** [comment]
Running ubuntu 14.04, and the latest rocker/hadleyverse image 

Is some networking issue, but no clue what. I can do everything but install stuff from github (install libraries, access github.com, google, etc)

After connecting to a vpn i was able to install the package...

Thanks for you great work! This must be a problem on my side...

**Comment by daroczig** [comment]
FTR I think this happened to  hitting the GitHub rate limits from the given IP -- that's why it was resolved after connecting to a VPN. More details at https://github.com/ramnathv/rMaps/issues/82#issuecomment-66712999 (sorry for the necromancer post, but I hope future visitors will find this comment useful)
