### ISSUE TITLE
FYI: rstudio-preview VER acquisition

### ISSUE THREAD

**Issue by Thell** [rocker-org/rocker#115]
RStudio doesn't publish a json to retrieve the preview version. I was interested in having a `rstudio-preview` image for a cutting edge and not bleeding edge image. Swapping out the `VER` string commands in the rstudio Dockerfile is working good...

````
  && dpkg -i libssl0.9.8_0.9.8o-4squeeze14_amd64.deb && rm libssl0.9.8_0.9.8o-4squeeze14_amd64.deb \
  && VER=$(wget --no-check-certificate -qO- http://www.rstudio.com/products/rstudio/download/preview/) \
  && VER=$(echo $VER | grep -oE "http([[:alnum:]]|[[:punct:]])*server-([.]|[[:digit:]])*-amd64.deb" | cut -d- -f4) \
  && wget -q https://s3.amazonaws.com/rstudio-dailybuilds/rstudio-server-${VER}-amd64.deb \
  && dpkg -i rstudio-server-${VER}-amd64.deb \
````

What do you think... one more rstudio image?

**Comment by eddelbuettel** [comment]
Seems like you can even leave out the `cut -d- -f4` part:

```{.sh}
file=$(wget --no-check-certificate -qO- http://www.rstudio.com/products/rstudio/download/preview/ | \
       grep -oE "http([[:alnum:]]|[[:punct:]])*server-([.]|[[:digit:]])*-amd64.deb")
echo "File: $file"
```

I am not sure it makes sense for to wrap up daily pre-release builds though.

**Comment by Thell** [comment]
:)

I don't think it really makes sense either, I'm using it instead of daily because there is a bit of a lag between the daily and preview builds and when RStudio updates the preview I at least know _they_ feel users should see it versus developers (daily). That's just an opinion though.
