### ISSUE TITLE
install.r docopt error

### ISSUE THREAD

**Issue by k-hu** [rocker-org/rocker#116]
Hi there,

I was trying to use the Dockerfile under Rbase to set up a baseline docker image for my R environment. However, it failed at the step of doing "install.r docopt" which gave me this error message:
<pre>
install.r docopt
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
</pre>

Is there anything missing? Any help would be appreciated.

- K

**Comment by cboettig** [comment]
@k-hu Looking into it.  Just a note though: It's not clear to me why you're building the r-base dockerfile directly.  You can pull this image from the hub and/or use it as the base image of your own Dockerfile with the `FROM` directive. (Sorry if I'm misunderstanding what you're trying to do here)

@eddelbuettel I've noticed this too with `install2.r` recently, I now have to set the cran mirror explicitly.  Did something change in littler that it no longer reads our default profile / cran mirror set in `/etc/R/Rprofile.site`  https://github.com/rocker-org/rocker/blob/master/r-base/Dockerfile#L55

**Comment by k-hu** [comment]
@cboettig Yes I just realized I could just use the r-base image as a baseline, instead of doing all over again using that Dockerfile.

Thanks for your help.

**Comment by cboettig** [comment]
@eddelbuettel The same error seems to be occurring on the Hub now: https://registry.hub.docker.com/u/rocker/r-base/build_id/20027/code/bt5cxkj9tcynxggvjzxszkx/

**Comment by eddelbuettel** [comment]
Yes, we need `/etc/littler.r` to set up `options("repos")`.  My bad.  I'll fix in base.   

For testing here is my home one.

```{.sh}
edd@max:~$ cat .littler.r

## add RStudio CRAN mirror
drat:::add("CRAN", "http://cran.rstudio.com")

## add Dirk's drat
drat:::add("eddelbuettel")

edd@max:~$ 
```

Remind again, please, which repos we'd want for base.  Just CRAN, or also a default BioC?

**Comment by cboettig** [comment]
I think just CRAN is what we had before

**Comment by eddelbuettel** [comment]
Ok.  The easiest way now to add repos, by the way, is to just append to `/etc/littler.r`.  It also overcomes the "multiple -r calls" issue as we can now (via this file) set multiple repos which even `install.r` will know.

**Comment by cboettig** [comment]
nice!

**Comment by eddelbuettel** [comment]
This is now taken care of (without needing drat at the first stage).
