### ISSUE TITLE
Error listing packages?

### ISSUE THREAD

**Issue by ignacio82** [rocker-org/rocker#117]
When I log into my rstudio server [hadleyverse] I'm getting this error 
    Error listing packages?
    R code execution error

Not sure how to diagnose it nor fix it. 

Thanks for the help!

**Comment by cboettig** [comment]
@ignacio82 I'm afraid I cannot reproduce this error; the current image works fine for me.  When posting a bug report, please provide all the information we request in [CONTRIBUTING](https://github.com/rocker-org/rocker/blob/master/CONTRIBUTING.md) so we can better help troubleshoot the issue.
