### ISSUE TITLE
Images for RStudio desktop

### ISSUE THREAD

**Issue by krlmlr** [rocker-org/rocker#118]
I wanted to test a bleeding-edge version of RStudio desktop, but there seems to be no image for that -- only for RStudio server.

Would the `Dockerfile` for such an image live in a separate repository, or somewhere in the main rocker repository?

**Comment by eddelbuettel** [comment]
As we never said we had such a container, I see no issue here and close this.

Feel free to reopen if I misunderstood anything.

**Comment by krlmlr** [comment]
This was not a bug report, just an attempt to start a discussion. Would you be willing to support such a container?

**Comment by eddelbuettel** [comment]
Then your wording was poor, and my three coffees were not strong enough.

Speaking for myself only, Carl and I are in "holding mode" as we may have kept the door a little too wide open.  We have real jobs, dozens of other open source projects and families all competing for our time and attention, so there is very little upside for us in spreading the goods too thinly here.

Bluntly put:  Why can't you just host your own container?  hub.docker.com is open for all.

**Comment by krlmlr** [comment]
I'll try to find a better wording next time. Thanks again for providing rocker, sure I can host my own RStudio desktop container.

**Comment by eddelbuettel** [comment]
Sounds like a good approach. And we would of course welcome use of our base containers if they are useful to you, and definitely welcome patches, bug reports, etc pp.

**Comment by wch** [comment]
@krlmlr How do you imagine an RStudio desktop would work? That is, how would it display the window?

**Comment by krlmlr** [comment]
A  [coarse search](https://startpage.com/do/search?query=docker+x+forwarding) shows a few options:

http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/
http://stackoverflow.com/questions/25281992/alternatives-to-ssh-x11-forwarding-for-docker-containers
http://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container

You can use `ssh -X`, or map the local X11 sockets to the container.

**Comment by cboettig** [comment]
@krlmlr Yes, there's some discussion of those already in issue #110.
Unfortunately, these work-arounds are not particularly platform independent
-- I believe Mac and Windows users would need yet more virtualization
layering to do anything with X11; and X-forwarding on remote machines will
be much too slow to be practical.

Perhaps @wch can correct me, but feature-wise RStudio-server and
RStudio-desktop are functionally equivalent, and were designed to be.  We
provide nightly builds of the bleeding edge of rstudio-server in the
rocker/rstudio-daily image.

Don't mean to discourage you here, just tossing out some thoughts.  Like
Dirk says, we're focused on maintaining the core images due to time
constraints right now,. though happy for others who already are maintaining
mature images to become part of rocker-org and host them here.  Just trying
to avoid rocker-org accumulating more things than are being looked after.

Thanks for your interest and your note!

**Comment by krlmlr** [comment]
Thanks for the heads-up and for the insights, @cboettig. Yes, running a GUI will require extra work on non-Linux systems, just like running Docker in the first place.

A desktop image could be used as a drop-in replacement for the "regular" RStudio: Work "bleeding edge", easy to update via `docker pull`, but keep it simple to revert to a more stable version if necessary. (As far as I am aware, RStudio server allows only one project per user.)

**Comment by cboettig** [comment]
@krlmlr You can have multiple projects per user in RStudio-server.  

You can also just pull rocker/rstudio-daily to get the bleeding edge each day (the docker image is rebuilt by a cron job trigger) and run rocker/rstudio for the stable version simultaneously if you like.  

Docker is really well-designed for running web apps like rstudio-server, and not desktop apps.  As they are functionally equivalent, I think you mostly gain a big headache of X forwarding and platform incompatibility by having containers with the rstudio-desktop version as well as the server version. Is there something about RStudio-server that motivates you to want to run the desktop client instead?

**Comment by eddelbuettel** [comment]
:+1: to what @cboettig said.  

Personally speaking I can see no use case for getting into "x11 exporting headaches" when Docker excels at a) command-line / terminal interfaces and b) networking.  But to each his own...

**Comment by krlmlr** [comment]
I'm just so much used to running the desktop version. On second thought, there really seems to be no compelling reason to do this with docker, too. Thanks for your feedback.

Multiple projects can be opened simultaneously in the desktop version. Even if RStudio Server doesn't allow this (as @cboettig [said](http://stackoverflow.com/a/27284840/946850) four months ago), I can start multiple containers that listen to different ports.

**Comment by wch** [comment]
AFAIK, the server and desktop version have exactly the same features. The only difference is that some of the keybindings may be different because, for the server version, some of the keys may be used by the browser. And of course there's all the extra browser UI when you visit the server version in a browser.

**Comment by cboettig** [comment]
@krlmlr Apologies if my comments at that SO question were confusing.  

RStudio server does allow you to have an arbitrary number of projects under a given user, just like RStudio desktop.  Note that when you "switch projects" in the RStudio menu (desktop or server, it's the same) the code in the previous project does not continue to execute, which is what that SO question was asking about.  So you can have multiple projects "open" in that they are listed in the "projects" menu in RStudio, but they are not simultaneous in the sense that they are simultaneously executing different, long-running R code.   You can have this simultaneous code execution happening just fine with multiple RStudio containers on different ports (e.g. works just like having multiple instances of "R" running in different terminals).  

If you just want the RStudio desktop project behavior, that already works identically in rstudio server-- go ahead and try it out.

**Comment by eddelbuettel** [comment]
@krlmlr I reverted your wiki change. Please do not do that.  There were three (3) people in this thread telling you that maybe going desktop app was not such a stellar idea.  We did not mean that as an invitation to add the opposite of what we suggested here to the wiki.

**Comment by krlmlr** [comment]
@cboettig: Thanks, will do.

@eddelbuettel: Probably a misunderstanding. Quoting from my text:

> [might work](http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/) on a Linux system, but is almost certainly going to become a nightmare on Windows or OS X systems

How is this suggesting the opposite?

**Comment by eddelbuettel** [comment]
We do not need a wiki entry for every possible exportable x11 app. Your hot button issue is the RStudio desktop, for the next guy is texstudio, for another retext for markdown etc pp.   We simply do not recommend x11 forwarding as it is to marginal an issue, documented elsewhere and orthogonal to what we do here.  So methinks it is cleanest to just leave it off.
