### ISSUE TITLE
Error when running docker: FATA[0001] Error: image library/rocker:r-base not found

### ISSUE THREAD

**Issue by lckarssen** [rocker-org/rocker#121]
When trying to run `r-base` or `r-devel` I get the following error:

    $ docker run --rm  -it  rocker:r-base bash
    Unable to find image 'rocker:r-base' locally
    Pulling repository rocker
    FATA[0001] Error: image library/rocker:r-base not found

However, I just updated my images:

    $ docker pull rocker/r-base
    Pulling repository rocker/r-base
    119cf916a7b6: Download complete
    511136ea3c5a: Download complete
    d338bb63f151: Download complete
    65688f7c61c4: Download complete
    0fd733e8d724: Download complete
    0468b9322615: Download complete
    5ea9ae3d3d68: Download complete
    15796e780ac5: Download complete
    d8b3ccf99925: Download complete
    b0482ab12284: Download complete
    e815c21da931: Download complete
    f015cfd25eab: Download complete
    ae4f2ebcea93: Download complete
    Status: Downloaded newer image for rocker/r-base:latest

    $ docker images 
    REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
    rocker/r-base       latest              119cf916a7b6        2 weeks ago         516.6 MB
    ubuntu              14.04.2             d0955f21bf24        3 weeks ago         188.3 MB
    ubuntu              latest              d0955f21bf24        3 weeks ago         188.3 MB
    ubuntu              trusty              d0955f21bf24        3 weeks ago         188.3 MB
    ubuntu              trusty-20150320     d0955f21bf24        3 weeks ago         188.3 MB
    ubuntu              14.04               d0955f21bf24        3 weeks ago         188.3 MB
    ubuntu              14.10               59a878f244f6        3 weeks ago         194.4 MB
    ubuntu              utopic              59a878f244f6        3 weeks ago         194.4 MB
    ubuntu              utopic-20150319     59a878f244f6        3 weeks ago         194.4 MB

 I already removed the images for `r-base` and `r-devel` and pulled them back in again. Running bash in one of the Ubuntu images works fine.

 This is on an Ubuntu 14.10 system, with docker v1.5.0 from the docker repo.  Several weeks ago both images worked fine, but that was before I upgraded from Ubuntu 14.04 to 14.10 (not sure if that's related). I'm quite new to Docker, so I may have made a simple mistake.

**Comment by cboettig** [comment]
You seem to be using a `:` instead of a `/`?

try: `docker run --rm -it rocker/r-base` 

or: `docker run --rm -it rocker/r-devel`

**Comment by lckarssen** [comment]
Thanks! That did the trick. Not sure how the `:` slipped in; probably because of the Ubuntu images which I start with `docker run -it ubuntu:14.04.2`.
