### ISSUE TITLE
R desktop gui

### ISSUE THREAD

**Issue by Thell** [rocker-org/rocker#122]
This isn't an _issue_. It was mentioned to me by @eddelbuettel  to possibly make a wiki entry regarding an image I was playing with that runs RStudio preview on the desktop but IMO it wasn't even close to being generalized enough so....

I'm running Ubuntu Gnome 15.04 and docker master with a docker group instead of sudo...

The containers need to have access to the xhost...

```
xhost local:docker
```

_R base gui_  
( interactive plotting works as expected too. )

```
docker run --rm -it -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix \
rocker/r-base /usr/bin/R --gui=tk
```

_R-base ESS - Dockerfile_  

```
# To use:
#  build:
#   docker build -t $USER/r-base-ess-desktop .
#  run:
#   docker run --rm -it \
#    -e DISPLAY=unix$DISPLAY \
#    -e NO_AT_BRIDGE=1 \
#    -v /tmp/.X11-unix:/tmp/.X11-unix \
#    --device /dev/snd \
#    --device /dev/dri \
#    --name ess
#    $USER/r-base-ess-desktop

FROM rocker/r-base

RUN apt-get update -qq && apt-get install -qqy \
    dbus-x11 \
    emacs24 \
    ess \
    libcanberra-gtk-module \
    libcanberra-gtk3-module

CMD ["emacs"]
```

Other simple tk interfaces seem to be equally as easy. No xvfb needed. When playing with RStudio it is more involved and quite a bit more stuff is needed to make use of the full IDE, I'm guessing that is also true for the ESS example, but it _is_ just an example. :)

If these types of things are a fit for the wiki, would a page along the lines of 'Rocker Desktop' work?

**Comment by cboettig** [comment]
I think a wiki page on how to do display forwarding would be of valuable,
particularly if it flushed out a few use cases.

For instance, I run the r-base images like this all the time in terminal
mode, just so I can have graphics work on a container (to be specific, I've
aliased "R" to a `docker run` command that forwards the display port)

It would be good to document what platforms it has been tested on though at
least.  Users tend to expect docker to be pretty host-agnostic, which
clearly isn't the case when you start linking all these host-specific
elements.

**Comment by Thell** [comment]
> Users tend to expect docker to be pretty host-agnostic, which
clearly isn't the case when you start linking all these host-specific
elements.

That's exactly what I was thinking regarding 'generalized'. Perhaps even the simple R-base gui version isn't truly general enough... I have __no__ clue how this would work on Mac or Windows. These types of setups do make working with 'rgl' nice and easy though. :)

**Comment by cboettig** [comment]
Looks like on Ubuntu >= 15.04 you now need to deal with XAuthority permissions as well to get this to work, as described here: http://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container/25280523#25280523

Also, I've made a very brief page on the Wiki to address this, please edit as you see fit.

**Comment by Thell** [comment]
@cboettig Interesting. I've not had a need to mess with anything but `xhost local:docker`. Sometimes, rarely,  I do get a `qxcbconnection xcb error` with video garbage on menu items.

**Comment by Thell** [comment]
@cboettig I finally got around to posting some [dockerfiles](https://github.com/Thell/dockerfiles) particularly a [RStudio Desktop Preview dockerfile](https://github.com/Thell/dockerfiles/blob/master/thell-rstudio.dockerfile) that gives what I believe to be everything required to use all of the builtin features of RStudio with only a few additional things (ccache, clang-format, some cli utils).

The `user.dockerfile` takes advantage of dockers new build variables ability, and in the `/scripts` are some helpers to __really__ make builds faster. (a full build of all of my normal containers used to take just over an hour _with_ squid, and now takes ~20 minutes _without_ it and ~ 8 minutes with. :smiley: 

I've been using this setup for a couple of months now and through each update of RStudio Preview and have been real happy with it.

**Comment by Thell** [comment]
wrong button... still want further discussion, ideas and such
