### ISSUE TITLE
Can't load rJava in RStudioServer of rocker/rstudio. In a R shell works fine.

### ISSUE THREAD

**Issue by gmgall** [rocker-org/rocker#126]
Hi everybody,

I don't know if what I will report is really a bug, but is a behaviour I never saw before and googling wasn't helpful.

The situation is that I'm able to install and load ``rJava`` in a R shell both as ``root`` and ``rstudio`` users. In RStudioServer itself, I receive the following error:

```
> library("rJava")
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/usr/local/lib/R/site-library/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory
Error: package or namespace load failed for ‘rJava’
```

The other R packages installed by ``root`` are loaded by the ``rstudio`` user without problems. Both in a R shell and in RStudioServer.

---------------

I will describe how I get to this point from a **fresh** rocker/rstudio container that I started just to test that:

1. The [Oracle Java 8 from Webupd8] (http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html) was installed. 
2. As root, I tried to install ``rJava`` the first time. It hasn't worked this time:
```
[...]
checking Java support in R... present:
interpreter : '/usr/lib/jvm/default-java/jre/bin/java'
archiver    : '/usr/lib/jvm/default-java/bin/jar'
compiler    : '/usr/lib/jvm/default-java/bin/javac'
header prep.: '/usr/lib/jvm/default-java/bin/javah'
cpp flags   : '-I/usr/lib/jvm/default-java/include'
java libs   : '-L/usr/lib/jvm/default-java/jre/lib/amd64/server -ljvm'
checking whether Java run-time works... ./configure: line 3729: /usr/lib/jvm/default-java/jre/bin/java: No such file or directory
no
configure: error: Java interpreter '/usr/lib/jvm/default-java/jre/bin/java' does not work
ERROR: configuration failed for package ‘rJava’
* removing ‘/usr/local/lib/R/site-library/rJava’

The downloaded source packages are in
        ‘/tmp/RtmpylntPm/downloaded_packages’
Warning message:
In install.packages("rJava") :
  installation of package ‘rJava’ had non-zero exit status
```
3. I used the command ``R CMD javareconf`` and from that point I was able to **install and load** ``rJava`` as ``root``.
4. I switched to ``rstudio`` user, opened a R shell and was able to load ``rJava`` too.
5. I logged in as ``rstudio`` in RStudioServer and then tried to load the package. The error was the one I provided above:
```
> library("rJava")
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/usr/local/lib/R/site-library/rJava/libs/rJava.so':
  libjvm.so: cannot open shared object file: No such file or directory
Error: package or namespace load failed for ‘rJava’
```
6. I thought this behaviour was strange, since all other R packages installed by ``root`` were loadable by ``rstudio`` in RStudioServer. I tried to install it from RStudioServer as ``rstudio`` anyway:
```
[...]
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (rJava)

The downloaded source packages are in
	‘/tmp/Rtmp4DGgCx/downloaded_packages’
```
Oddly, the messages suggest that the package can be loaded even though I can not do it manually.

Do you know what's going on?

Thanks in advance.

**Comment by cboettig** [comment]
@gmgall Sorry for the slow reply here.  

You haven't told me what rocker image you are using.  Note that `rJava` is already set up in the `rocker/hadleyverse` image and is working for me just fine (in RStudio or just R).  

Note that java requires additional libraries and some configuration, you cannot just `install.packages('rJava')` on rocker/rstudio image.  If you want to see how we do this, just consult the hadleyverse Dockerfile which adds rJava (and other stuff) on top of the rstudio image.

**Comment by gmgall** [comment]
Hi @cboettig, thanks for replying. The problem was noted in the ``rocker/rstudio`` image. But since your reply the machine I was using for the tests was switched off due a electrical fault. It got powered on again just now. And I wasn't able to reproduce the problem that I reported myself. It seems that restarting the containers solved the issue. I will try one more time with a fresh container and I let you know if problem still occurs or not.

**Comment by gmgall** [comment]
I managed to reproduce the problem. I did not need to restart the container after all. It was enough to restart RStudioServer. These were the steps*:

1. start a new ``rocker/rstudio`` container
2. install Java 8 from webupd8
3. run ``R CMD javareconf``
4. start a R shell
5. ``install.packages("rJava")``
6. switch to ``rstudio`` user
7. start a R shell
8. load rJava

Up to this point, everything works as expected. I then logged in RStudioServer. I wasn't able to load ``rJava`` from there **even though it was loaded without errors in the shell**.

I switched back to the shell where RStudioServer was stopped and then started again. Now, I was able to load rJava from both the shell and RStudioServer. Is this behaviour expected? I believe is not because other packages don't require restarting RStudioServer to work. ``dplyr``, the package I tested right after rJava, is an example. I was able to install it and it became available without restarting.

-----------------

 *I "recorded" the commands I used with the ``script`` program: http://pastebin.ca/3025635

**Comment by eddelbuettel** [comment]
May we call this a local problem which you created at your end?   

Debian/Ubuntu use OpenJDK and AFAIK everything works with it.  We can promise to have things work magically with other parts we do not have.  If you need rJava to work Java 8, you may have to create some patches first.

**Comment by gmgall** [comment]
Yes, we can call this a local problem. Other packages don't seem to be affected. We can close this issue if you must.

As I said in the first message, I don't even know if I can call this is a bug. I decided to report it here because is a behaviour I never saw before when using RStudioServer and my research on the problem was unsuccessful.

**Comment by eddelbuettel** [comment]
I don't do much Java but maybe there is a relevant Debian list or group that can help, or is working on it.  For the R package, I have the benefit of just being able to rely on the defaults - which nowadays work pretty reliably.

**Comment by gmgall** [comment]
I'll lead this issue to a relevant list and try to use OpenJDK in my next images. Thanks for the tip.

In the last weekend I was able to reproduce the problem I reported here in another machine (not a container). So I can definitely affirm that isn't something concerning the ``rocker/rstudio`` image.

**Comment by eddelbuettel** [comment]
Yes, Java can be tricky. It tooks years to get the rJava package (for the prinicipal interface) working / building reliably across Debian build systems.    

I'll close this then as it is not a rocker issue.

**Comment by Ishanmahajan04** [comment]
sudo apt-get install r-cran-rjava

By this command we can install rjava directly on ubuntu.

**Comment by eddelbuettel** [comment]
@Ishanmahajan04   We know. I am the maintainer of that package. That is what it for.  

The discussion here was broader, and for something entirely different. You comment adds little to that discussion.

**Comment by paulozullu** [comment]
[Stackoverflow link](https://stackoverflow.com/questions/12872699/error-unable-to-load-installed-packages-just-now/25932828#25932828)

**For Ubuntu, oracle-java (7/8) installed. It'll be at this location /usr/lib/jvm and sudo access is required.**

Create the file /etc/ld.so.conf.d/java.conf with the following entries:

```
/usr/lib/jvm/java-8-oracle/jre/lib/amd64
/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server
```

**(Replace java-8-oracle with java-7-oracle or java-7-openjdk-amd64 depending on your java version)**

Then:
```
sudo ldconfig
```
Restart RStudio and then install the rJava package.

**Comment by nemanjasvaba** [comment]
Thank you. @paulozullu This helped me in fixing the issue of 'missing' file (error: unable to load shared object '/usr/local/lib/R/site-library/rJava/libs/rJava.so':).
