### ISSUE TITLE
r-devel image is outdated

### ISSUE THREAD

**Issue by sheffien** [rocker-org/rocker#127]
Just wanted to point out that the r-devel image doesn't seem to be building correctly at the moment; r-base has 3.2.0 but r-devel is stuck at 3.1.3, and it looks like the most recent builds are getting errors at Dockerhub, so the latest build is based on an older r-base...

**Comment by eddelbuettel** [comment]
I actually committed a fix on May 27 and didn't realize we had turned off auto-build.

But I triggered one today and there is now a new build.
