### ISSUE TITLE
Ability to run rstudio on a different path

### ISSUE THREAD

**Issue by rgbkrk** [rocker-org/rocker#128]
Is there a way to tell rstudio (through the rocker image) to run on a different root path?

**Comment by cboettig** [comment]
Not sure I follow, what do you mean "run on a different root path"?  Are trying to change the working directory rstudio opens in?

**Comment by rgbkrk** [comment]
Ah, no. More like:

```
/rstudio/
```

Ended up noticing that rstudio required an underlying rewrite if used with nginx:

```
location /rstudio/ {
  rewrite ^/rstudio/(.*)$ /$1 break;
  proxy_pass http://localhost:8787;
  proxy_redirect http://localhost:8787/ $scheme://$host/rstudio/;
}
```

**Comment by cboettig** [comment]
Ah, right, you're referring to the host URL. Right, with nginx proxy you can obviously redirect to your heart's content, including https proxy etc.  This works really well by just coupling the rstudio container to a nginx Docker container, as documented elsewhere, but doesn't really have anything to do with the rstudio container per se.  I think we can close?

**Comment by rgbkrk** [comment]
> I think we can close?

Totally.

I was trying to see if I could use the rocker images with [tmpnb](https://github.com/jupyter/tmpnb) to provide a temporary demo. The stopgap was RStudio being routed on `/user/random8739sdgjaf/`.
