### ISSUE TITLE
Error : cannot allocate buffer --- using rocker/ropensci when using `devtools::install_github()`

### ISSUE THREAD

**Issue by alanarnholt** [rocker-org/rocker#131]
First, thanks for all of the work behind rocker! Using the container `rocker/ropensci` 
running on Mac OS X with Boot2Docker (1.7.0) [Virtual Box Version 4.3.28 r100309]
returns a `Error : cannot allocate buffer` when I type 
`devtools::install_github('alanarnholt/PDS')` at the R prompt inside the Console pane of RStudio.

```
> devtools::install_github('alanarnholt/PDS')
Downloading github repo alanarnholt/PDS@master
Installing PDS
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
INSTALL '/tmp/RtmpJJb26s/devtools2a5e23a6de/alanarnholt-PDS-38b3dff'  \
--library='/usr/local/lib/R/site-library' --install-tests 

* installing *source* package ‘PDS’ ...
** R
** data
*** moving datasets to lazyload DB
Warning: object ‘.Traceback’ is created by more than one data call
Error : cannot allocate buffer
ERROR: lazydata failed for package ‘PDS’
* removing ‘/usr/local/lib/R/site-library/PDS’
Warning in q("no", status = 1, runLast = FALSE) :
  system call failed: Cannot allocate memory
Error: Command failed (1)
```

Browsing through the docker manual seems to indicate that the default 
setting for memory...is that there is no memory limit for the container.  
Any pointers to what I should read or try to be able to `allocate buffer` are most appreciated.

TIA,
Alan-

**Comment by cboettig** [comment]
Alan,

You probably need to check and adjust the memory allocated by VirtualBox to
the virtual instance.
Sorry for the delay, I've been travelling.


On Sat, Jul 4, 2015 at 12:16 PM Alan Arnholt <notifications@github.com>
wrote:

> First, thanks for all of the work behind rocker! Using the container
> rocker/ropensci
> running on Mac OS X with Boot2Docker (1.7.0) [Virtual Box Version 4.3.28
> r100309]
> returns a Error : cannot allocate buffer when I type
> devtools::install_github('alanarnholt/PDS') at the R prompt inside the
> Console pane of RStudio.
>
> > devtools::install_github('alanarnholt/PDS')
> Downloading github repo alanarnholt/PDS@master
> Installing PDS
> '/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
> INSTALL '/tmp/RtmpJJb26s/devtools2a5e23a6de/alanarnholt-PDS-38b3dff'  \
> --library='/usr/local/lib/R/site-library' --install-tests
>
> * installing *source* package ‘PDS’ ...
> ** R
> ** data
> *** moving datasets to lazyload DB
> Warning: object ‘.Traceback’ is created by more than one data call
> Error : cannot allocate buffer
> ERROR: lazydata failed for package ‘PDS’
> * removing ‘/usr/local/lib/R/site-library/PDS’
> Warning in q("no", status = 1, runLast = FALSE) :
>   system call failed: Cannot allocate memory
> Error: Command failed (1)
>
> Browsing through the docker manual seems to indicate that the default
> setting for memory...is that there is no memory limit for the container.
>
> Any pointers to what I should read or try to be able to allocate buffer
> are most appreciated.
>
> TIA,
> Alan-
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rocker-org/rocker/issues/131>.
>
-- 

http://carlboettiger.info
