### ISSUE TITLE
Support for Revolution R Open

### ISSUE THREAD

**Issue by abhishek0** [rocker-org/rocker#132]
It would be really nice to have support for Revolution [R Open](http://mran.revolutionanalytics.com) along with there MKL intel library for multi processing.

**Comment by eddelbuettel** [comment]
There are a number of prior discussions here concerning suggestions for _oh wouldn't it be nice if_ questions.  Carl and I generally try to politely explain that _we_ focus on the core and that users like _you_ are welcome to rework things based on our containers.  We simply cannot follow all suggestions.

Here, you also may want to check about redistribution and trademarking issues.  We cleared those _explicitly_ for the RStudio products we containerized.
