### ISSUE TITLE
E: The value 'testing' is invalid for APT::Default-Release as such a release is not available in the sources

### ISSUE THREAD

**Issue by bachmeil** [rocker-org/rocker#134]
I went through the Docker tutorial and am now trying to use rocker/rstudio. I got the above error while attempting to follow the steps on [this page](https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image).

Host OS: Linux Mint 17
Docker container: rocker/rstudio
Commands:
```
docker pull rocker/rstudio
sudo docker run -d -p 8787:8787 -v ~/dockerdata:/home/rstudio/dockerdata rocker/rstudio
docker ps
docker exec -it fae0 bash
apt-get install libgsl0-dev
```

Error message:

`E: The value 'testing' is invalid for APT::Default-Release as such a release is not available in the sources`

**Solution**

This is something of an ugly error because Google does not help (at least it didn't help me). Eventually I thought to do

`apt-get update`

and it worked. It would be nice to add a sentence to the wiki in case someone else experiences this error.

**Comment by cboettig** [comment]
@bachmeil Thanks for the issue report.  Yes, that error is more cryptic than it should be do to an issue we should resolve soon; however, note that in general with docker images you are expected to run `apt-get update` before installing -- most official images at least purge the packages lists to keep the image small anyway.  

Anyone with a GitHub account should be able to edit the wiki, so feel free to do so -- often other users have a better sense of what is missing and where they would look for that information than we do!

Cheers,

**Comment by bachmeil** [comment]
Thanks. I didn't know that I could edit the wiki (though obviously that makes sense). I've added a brief note to that section.

**Comment by kuamit5516** [comment]
root@kalilinux:/home/user# sudo apt-get install aptitude
Reading package lists... Done
E: The value '“testing”' is invalid for APT::Default-Release as such a release is not available in the sources

**Comment by eddelbuettel** [comment]
I just answered this [here](https://github.com/rocker-org/rocker/issues/167#issuecomment-387374954), and I really do not think you need to post the _exact same issue_ three times.

**Comment by ErikEngerd** [comment]
How would one fix the error without having to do an 'apt-get update'? Even though this works, it will break reproducibility since every time the same docker image is built, it can get different versions of packages.

**Comment by eddelbuettel** [comment]
_If_ you plan to _pull_ packages via `apt` you _also need an updated index_.  Can't have one without the other.

**Comment by cboettig** [comment]
> it can get different versions of packages.

How different depends on your apt sources.  If reproducibility is your primary concern, you might want to consider using the rocker-versioned stack instead, which builds on debian stable releases.  The r-base images build on `debian:testing`, which always has the most recent/latest versions of things like compilers, etc.  We discuss this at more length in: https://doi.org/10.32614/RJ-2017-065

**Comment by ErikEngerd** [comment]
That is helpful, I will have a look at it. Thanks.
