### ISSUE TITLE
lgfortran error

### ISSUE THREAD

**Issue by cancandan** [rocker-org/rocker#137]
inside rstudio container while trying to install some packages from source within R using install.packages, I've got an error from the compiler saying it cant find lgfortan. I think devel container has fortran stuff. So is changing the line in the docker file of rstudio from `FROM r-base:latest`  to `FROM r-devel:latest` the solution?

**Comment by eddelbuettel** [comment]
Containers are not all supersets of each other.   

If *you* find a package is missing for *your* work and circumstances, we feel *you* are best qualified to add it.  What we provide should be considered a basic framework (or set of frameworks) which you can adapt.

So just do `sudo apt-get install libgfortran-4.9-dev` (adjust the release if need be) and possibly re-commit the modified container.

**Comment by cancandan** [comment]
I see, thanks :)
