### ISSUE TITLE
can't set user or system-wide environmental variables at login

### ISSUE THREAD

**Issue by dvera** [rocker-org/rocker#138]
I can't seem to set environmental variables for the rstudio user or system-wide at login with the rstudio image.

Here's a Dockerfile to test if the PATH variable can be modified using various shell config files:
```
$ cat Dockerfile
FROM rocker/rstudio
RUN echo 'export PATH=/opt:$PATH' >> /etc/environment
RUN echo 'export PATH=/opt:$PATH' >> /etc/profile
RUN echo 'export PATH=/opt:$PATH' >> /home/rstudio/.profile
```

On my host in the directory with the Dockerfile:
```
$ docker build -t test .
$ sudo docker run -d -p 8787:8787 test
```
Navigate in browser to 127.0.0.1:8787, log in with the rstudio user, and enter at the R prompt:
```
> Sys.getenv("PATH")
[1] "/usr/lib/rstudio-server/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
> system("cat /etc/environment")
export PATH=/opt:$PATH
> system("tail -n 1 /etc/profile")
export PATH=/opt:$PATH
> system("cat .profile")
export PATH=/opt:$PATH
```

Am I missing something?

**Comment by cboettig** [comment]
In your Dockerfile, you want to use `ENV`, not `RUN` commands to set environmental variables. You can see an example of setting PATH this way in the rstudio Dockerfile: https://github.com/rocker-org/rocker/blob/master/rstudio/Dockerfile#L7

At runtime, you can pass environmental variables with the `-e` flag to `docker run`.  These are really just docker questions though, so you can check out the official Docker documentation for more details.
