### ISSUE TITLE
Multiple users permanently

### ISSUE THREAD

**Issue by mictadlo** [rocker-org/rocker#141]
Hello, how could I keep multiple users after docker restart, because at the moment I loose them?

    $ docker exec -it e230d32a0609 bash
    # adduser lorencm

**Comment by cboettig** [comment]
Use `docker commit <container>`

On Thu, Sep 10, 2015, 6:37 PM Michał T. Lorenc <notifications@github.com>
wrote:

> Hello, how could I keep multiple users after docker restart, because at
> the moment I loose them?
>
> $ docker exec -it e230d32a0609 bash
> # adduser lorencm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rocker-org/rocker/issues/141>.
>
-- 

http://carlboettiger.info
