### ISSUE TITLE
Cross-compiling for Windows

### ISSUE THREAD

**Issue by lgautier** [rocker-org/rocker#142]
Setting up a Linux environment to cross-compile for Windows is rather painful.

A docker container to do so would be extremely helpful.

**Comment by eddelbuettel** [comment]
True.  And there are existing cross-compilers in the distro. 

But please see previous discussions concerning "ample spare time" of @cboettig and myself.  We simply cannot create new containers.    We will help, as best as we can, others do this.

@jeroenooms @kevinushey @thirdwing:  As you all have cross-compiler experience, any interest?

**Comment by cboettig** [comment]
@richfitz is also interested in this I think.  Contributions / pull requests welcome...

**Comment by thirdwing** [comment]
@lgautier  Can you give more info on what you want in the cross-compiling docker?

A cross-complier and related libraries? Or a cross-compiling environment to compile R packages for Windows?

**Comment by lgautier** [comment]
@thirdwing if only about cross-compiling for Windows in general, this would be if more general scope than rocker.

The idea is to be able to compile R packages with C or C++ extensions using a container. 

With Microsoft declared interest in Docker, and in R through Revolution Computing, it might be possible to get someone there interested in the idea as well...

**Comment by lgautier** [comment]
@thirdwing if only about cross-compiling for Windows in general, this would be of more general scope than rocker.

The idea is to be able to compile R packages with C or C++ extensions using a container. 

With Microsoft declared interest in Docker, and in R through Revolution Computing, it might be possible to get someone there interested in the idea as well...

**Comment by thirdwing** [comment]
OK. I know what you want.

I am not sure the Makefile[1] on CRAN still works well, I might give a try in next week. 

If works, I will send a Dockerfile as the PR.

[1] https://cran.r-project.org/doc/contrib/Makefile-rcb

**Comment by lgautier** [comment]
Great if you can get anywhere near "almost working". It is almost certainly not working "as is" any longer (it is from 2007).

**Comment by thirdwing** [comment]
Just have a try. It is annoying :( .

I will try to spend some more time.
