### ISSUE TITLE
Add svn to container

### ISSUE THREAD

**Issue by dnadave** [rocker-org/rocker#145]
We use subversion for our version control.  Is it possible to add the svn service to the rocker containers, in addition to github?

**Comment by eddelbuettel** [comment]
We try to keep rocker's r-base (also becomes the official r-base) to be 'compact'.  It is tempting with the 20+ thousand apt-get package to always desire something extra.  For you right now: subversion, for the next person maybe an editor.  It's tough.   Could you consider 'deriving' from r-base and just adding subversion?

**Comment by dnadave** [comment]
I suppose we could add it in.  We just need the client.   This is based on
Ubuntu, correct?   If so, then an apt-get should work?

**Comment by cboettig** [comment]
It's based on [`debian:testing`](https://hub.docker.com/_/debian/) (lighter than Ubuntu and used by most official images as the base), but yes, `apt-get` works.  Be sure to run `apt-get update` in the same `RUN` line first, see [Best Practices](https://docs.docker.com/articles/dockerfile_best-practices/)

**Comment by eddelbuettel** [comment]
And in general see any of _our_ Dockerfiles which generally build on top of r-base.
