### ISSUE TITLE
[r-base] docker user created but not used

### ISSUE THREAD

**Issue by jangorecki** [rocker-org/rocker#146]
In dockerfile we create `docker` user
```
RUN useradd docker \
	&& mkdir /home/docker \
	&& chown docker:docker /home/docker \
	&& addgroup docker staff
```
But it is not used later.
```r
Sys.info()[["user"]]
# [1] "root"
```
Is there any purpose for creating the user and not using it? if there is you can close this false bug report.

**Comment by eddelbuettel** [comment]
Have you read [this wiki page](https://github.com/rocker-org/rocker/wiki/managing-users-in-docker) ?

**Comment by jangorecki** [comment]
just now, thanks for pointing :)
