### ISSUE TITLE
[r-base] remove multiple dependencies due docopt

### ISSUE THREAD

**Issue by jangorecki** [rocker-org/rocker#147]
The `r-base` is not so much *base* due to one dependency which brings small chain of dependencies.
Dockerfile installs `docopt` package with line
```
&& install.r docopt \
```
The `docopt` deps are `stringr`, `stringi`, `magrittr`.
Is it possible to have `docopt` removed from the `r-base`. It can be migrated to other images.

**Comment by eddelbuettel** [comment]
We use it for littler.
