### ISSUE TITLE
Minor wiki fix

### ISSUE THREAD

**Issue by java4africa** [rocker-org/rocker#148]
The "-e USERID = $UID will give errors if there are spaces. I would also normally add "--name=rstudio" to the docker commands, but that's not a real issue.

$ git diff Sharing-files-with-host-machine.md

diff --git a/Sharing-files-with-host-machine.md b/Sharing-files-with-host-machine.md
index 38d49a2..6ba154f 100644
--- a/Sharing-files-with-host-machine.md
+++ b/Sharing-files-with-host-machine.md
@@ -48,7 +48,7 @@ If the host machine user has a UID other than 1000 (or 0, for root), the user sh
 
 ```
 docker run -d -P -v $(pwd):/home/$USER/foo \
--e USER=$USER  -e USERID = $UID rocker/rstudio
+-e USER=$USER  -e USERID=$UID rocker/rstudio
 ```
 
 to avoid changing the permissions in the linked volume on the host.  This is designed for `rstudio`-based logins and runs only when the container is executed without a default command.

**Comment by cboettig** [comment]
Thanks! The wiki's a wiki, feel free to edit it directly.

**Comment by java4africa** [comment]
Fixed in wiki.
