### ISSUE TITLE
fix install2.r links?

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker#149]
Hi @eddelbuettel ,

I'm guessing the re-packaging of littler has broken the symlinking for the `install.r` / `install2.r` scripts we had done in `r-base`?  Any thoughts on how those should be re-mapped?

**Comment by cboettig** [comment]
Or maybe I'm just confused.  `rocker/hadleyverse` container is failing to build for me with a `/bin/sh -c install2.r` not found error, but `install2.r` is working happily on `rocker/rstudio`...

**Comment by eddelbuettel** [comment]
We can do one of two things:
- install the `littler.r` (virtual package with a depends on the actual package) and `r-cran-littler` packages from Michael's CRAN-mirrored repo -- that makes it `/usr/lib/R/site-library`
- or install directly from CRAN which puts it into `/usr/local/lib/R/site-library`

But I thought I had taken care of it.

**Comment by cboettig** [comment]
Hmm, so I think it is failing in `hadleyverse` because I still have an `apt-get dist-upgrade` command which installs `r-cran-littler`? will see if dropping the `dist-upgrade` line fixes that...

**Comment by eddelbuettel** [comment]
So `r-base` has the old `littler` -- which seems fine as it did not rebuild.
`rocker/r-base` has the new `littler`.  It may need a softlink refresher.

```sh
edd@max:~$ docker run --rm -ti rocker/r-base /bin/bash
root@db3c5414136d:/# r --version
r ('littler') version 0.3.0

using GNU R Version 3.2.2 (2015-08-14)

Copyright (C) 2006 - 2015  Jeffrey Horner and Dirk Eddelbuettel

r is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License.  For more information about
these matters, see http://www.gnu.org/copyleft/gpl.html.

root@db3c5414136d:/# which install.r
/usr/local/bin/install.r
root@db3c5414136d:/# 
```

**Comment by eddelbuettel** [comment]
Yes if you replace littler you need to replace the links.  Or just copy the scripts into `/usr/local/bin` -- I think all shebang lines to `#!/usr/bin/env r` which gets `r` itself from `/usr/bin`, `/usr/local/bin` or wherever in the `$PATH` we put it.

**Comment by cboettig** [comment]
Very good, thanks!

**Comment by eddelbuettel** [comment]
Suggestions welcome for how to do this better. But hopefully I only change littler once every nine years that way :)
