### ISSUE TITLE
Error with supervisord ?

### ISSUE THREAD

**Issue by cteyton** [rocker-org/rocker#152]
Ubuntu 14.04 / Docker 1.9.0

When running 
```
docker run -p 8787:8787 rocker/rstudio
```

I have the following issue : 
```
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

and the container just stops. 

It seems related to a package called `python-setuptools` needed by supervisord at runtime.

**Comment by cboettig** [comment]
Thanks, fixed now. 

(Not sure why that dependency wasn't grabbed by supervisord, but I guess those things shift around during updates)

**Comment by eddelbuettel** [comment]
:+1:

**Comment by cteyton** [comment]
You're welcome ! Is the docker image supposed to be updated ?

**Comment by cboettig** [comment]
@cteyton yup, the commit should have automatically triggered the rebuild of the image on the hub (and it looks like it did), so the fix should now be in the rstudio image (and downstream images like hadleyverse) if you just `docker pull rocker/rstudio` to update...
