### ISSUE TITLE
possible edge case: segfault on hadleyverse passing values to eigen

### ISSUE THREAD

**Issue by zkamvar** [rocker-org/rocker#156]
## Description of problem

I have found some strange behavior on https://github.com/NESCent/popgen-docker and have traced the origin of the behavior to rocker/hadleyverse. There appears to be a segfault of unknown origin that was found here (log of backtrace): https://github.com/NESCent/popgenInfo/pull/86#issuecomment-166030603

## System and docker version

I am on mid-2012 macbook pro 13" with OSX 10.11.2 (15C50) and a 2.9 GHz Intel Core i7
Docker version: 1.8.1, build d12ea79

## Minimum Working Example

A MWE is here: https://gist.github.com/zkamvar/94c9b51b90aa7c74b066
These commands were launched with: `docker run --rm -ti <image>:latest /bin/bash` and followed by calling R from within the container.

This example works on r-base and rstudio, but fails in hadleyverse. 

## Docker Images Used

```
REPOSITORY           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
hlapp/rpopgen        latest              7b48c7d611ea        18 hours ago        2.714 GB
rocker/hadleyverse   latest              1d713efa07b0        6 days ago          2.547 GB
rocker/r-base        latest              abed2d1b00d1        6 days ago          1.058 GB
rocker/rstudio       latest              ba939a8f4592        6 days ago          1.37 GB
```

**Comment by cboettig** [comment]
Hmm, does seem strange, but would need more bisecting to discover the differences.  You might start by comparing `sessionInfo()` under rstudio case and `hadleyverse` case

**Comment by eddelbuettel** [comment]
:+1: I am also unsure it is us -- as opposed to a random interaction between other packages which happen to be coinstalled.

**Comment by zkamvar** [comment]
### rocker/rstudio

```
> sessionInfo()
R version 3.2.3 RC (2015-12-03 r69731)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux stretch/sid

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] adegenet_2.0.0 ade4_1.7-3

loaded via a namespace (and not attached):
 [1] spdep_0.5-88     igraph_1.0.1     Rcpp_0.12.2      magrittr_1.5
 [5] splines_3.2.3    MASS_7.3-45      munsell_0.4.2    xtable_1.8-0
 [9] colorspace_1.2-6 ape_3.4          lattice_0.20-33  R6_2.1.1
[13] stringr_1.0.0    plyr_1.8.3       dplyr_0.4.3      tools_3.2.3
[17] parallel_3.2.3   grid_3.2.3       gtable_0.1.2     nlme_3.1-122
[21] coda_0.18-1      DBI_0.3.1        deldir_0.1-9     seqinr_3.1-3
[25] htmltools_0.2.6  assertthat_0.1   digest_0.6.8     Matrix_1.2-3
[29] shiny_0.12.2     reshape2_1.4.1   ggplot2_2.0.0    mime_0.4
[33] sp_1.2-1         stringi_1.0-1    LearnBayes_2.15  scales_0.3.0
[37] boot_1.3-17      httpuv_1.3.3
```

## rocker/hadleyverse
```
> sessionInfo()
R version 3.2.3 RC (2015-12-03 r69731)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux stretch/sid

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] adegenet_2.0.0 ade4_1.7-3

loaded via a namespace (and not attached):
 [1] spdep_0.5-88     igraph_1.0.1     Rcpp_0.12.2      magrittr_1.5
 [5] splines_3.2.3    MASS_7.3-45      munsell_0.4.2    xtable_1.8-0
 [9] colorspace_1.2-6 ape_3.4          lattice_0.20-33  R6_2.1.1
[13] stringr_1.0.0    plyr_1.8.3       dplyr_0.4.3      tools_3.2.3
[17] parallel_3.2.3   grid_3.2.3       gtable_0.1.2     nlme_3.1-122
[21] coda_0.18-1      DBI_0.3.1        deldir_0.1-9     seqinr_3.1-3
[25] htmltools_0.2.6  assertthat_0.1   digest_0.6.8     Matrix_1.2-3
[29] shiny_0.12.2     reshape2_1.4.1   ggplot2_1.0.1    mime_0.4
[33] sp_1.2-1         stringi_1.0-1    LearnBayes_2.15  scales_0.3.0
[37] boot_1.3-17      httpuv_1.3.3     proto_0.3-10
```

## Diff

```diff
-[29] shiny_0.12.2     reshape2_1.4.1   ggplot2_1.0.1    mime_0.4
+[29] shiny_0.12.2     reshape2_1.4.1   ggplot2_2.0.0    mime_0.4
[33] sp_1.2-1         stringi_1.0-1    LearnBayes_2.15  scales_0.3.0
-[37] boot_1.3-17      httpuv_1.3.3     proto_0.3-10
+[37] boot_1.3-17      httpuv_1.3.3
```

**Comment by zkamvar** [comment]
But can weird package interactions screw up a call to `eigen()`?

```

Traceback:
 1: eigen(df, symmetric = TRUE)
 2: as.dudi(df, col.w, row.w, scannf = scannf, nf = nf, call = match.call(),     type = "pca")
 3: dudi.pca(x, center = center, scale = scale, scannf = FALSE, nf = maxRank)
 4: dapc.data.frame(as.data.frame(x), ...)
 5: dapc(as.data.frame(x), ...)
 6: dapc.matrix(X, grp = pop.fac, n.pca = n.pca, n.da = n.da, center = FALSE,     scale = FALSE, var.contrib = var.contrib, var.loadings = var.loadings,     pca.select = pca.select, perc.pca = perc.pca)
 7: dapc(X, grp = pop.fac, n.pca = n.pca, n.da = n.da, center = FALSE,     scale = FALSE, var.contrib = var.contrib, var.loadings = var.loadings,     pca.select = pca.select, perc.pca = perc.pca)
 8: dapc.genind(microbov, n.pca = 100, n.da = 4)
 9: dapc(microbov, n.pca = 100, n.da = 4)
```

**Comment by eddelbuettel** [comment]
If you have a _reproducible_ bug report against RcppEigen I as its maintainer will gladly look at it over at the RcppEigen GitHub repo and issue tracker.    Over here, it feels a little scattershot.

Minimally reproducible examples really are best.  And we stress both adjectives equally.

**Comment by zkamvar** [comment]
No worries. My MWE was a WE at best :smiley: I'm coming up with a true MWE without loading any extra packages as we speak. FWIW, there has been an issue brought up on something similar with OpenBLAS: https://github.com/xianyi/OpenBLAS/issues/703

**Comment by eddelbuettel** [comment]
We had issues with OpenBLAS at work in an already-parallel setup.  Try swapping them for Atlas BLAS just to see.

**Comment by zkamvar** [comment]
Please bear with me, because I'm about to ask a newb question. For some context, our [Docker image](https://hub.docker.com/r/hlapp/rpopgen/~/dockerfile/) imports rocker/hadleyverse. This image [explicitly installs openBLAS](https://github.com/rocker-org/hadleyverse/blob/master/Dockerfile#L44). Are you suggesting we add
```
apt-get install libatlas-base-dev
```
to our Dockerfile to replace openBLAS that was installed previously by rocker/hadleyverse? 

FWIW, [I created the MWE here](https://github.com/zkamvar/mwe_eigen_segfault):

```sh
git clone https://github.com/zkamvar/mwe_eigen_segfault.git
cd mwe_eigen_segfaut

# Works
docker run --rm -ti -v $(pwd):/mwe rocker/rstudio:ba939a8f4592 /bin/bash
cd mwe; R
source("mwe.R", echo = TRUE)

# Fails
docker run --rm -ti -v $(pwd):/mwe rocker/hadleyverse:1d713efa07b0 /bin/bash
cd mwe; R
source("mwe.R", echo = TRUE)
```

**Comment by eddelbuettel** [comment]
Yes. 

It may also be easier to just 'much about' on a normal machine, or interactively in a Docker container.

**Comment by zkamvar** [comment]
Thanks for the tip! I'll try it out tomorrow and see if it works.

**Comment by zkamvar** [comment]
Just checked it out. I did the following commands to replace openBLAS with Atlas BLAS on `rocker/hadleyverse:1d713efa07b0`

```
apt-get update
apt-get remove -y libopenblas-base
apt-get install -y libatlas-base-dev
```

No segfault after this. 

Clearly this is an openBLAS issue. What would you do in this situation? Should I submit some sort of bug report to openBLAS or +1 the previously reported issue with my MWE (which I found also works with random numbers)?

**Comment by eddelbuettel** [comment]
It's probably complicated, but I guess it should somehow get to the OpenBLAS maintainer.

Can we close this here?

**Comment by zkamvar** [comment]
> It's probably complicated, but I guess it should somehow get to the OpenBLAS maintainer.
>
> Can we close this here?

Yes. Thank you for your time and patience.

**Comment by cboettig** [comment]
@zkamvar @eddelbuettel nice work figuring that one out.  Perhaps we should just have Atlas instead of openBLAS on hadleyverse?  Dirk knows a lot more about BLAS libraries & R than I do...

**Comment by eddelbuettel** [comment]
That is what I usually do when I have trouble with OpenBLAS.  Doesn't exactly _fix_ the issue but avoids it.  Would be nice to know more...
