### ISSUE TITLE
jessie no longer accepts APT::Default-Release "testing"

### ISSUE THREAD

**Issue by dnadave** [rocker-org/rocker#159]
We are building our own Docker containers with R using your Dockerfile tacked on to a Wetty build and are running into the following problem installing the unstable packages on jessie:

Step 29 : RUN apt-get install -y util-linux bash && cp /opt/rtg/scripts/rtg-bash-completion /etc/bash_completion.d/rtg
---> Running in db36109d65ab
Reading package lists...
[91mE: The value 'testing' is invalid for APT::Default-Release as such a release is not available in the sources
[0mThe command '/bin/sh -c apt-get install -y util-linux bash && cp /opt/rtg/scripts/rtg-bash-completion /etc/bash_completion.d/rtg' returned a non-zero code: 100
Build step 'Docker Build and Publish' marked build as failure
Finished: FAILURE

It seems that over the Christmas holidays, jessie no longer has “testing” as an option in APT::Default-Release.  Any ideas on how to get around this?

I've attached a copy of my Dockerfile for reference.

[Dockerfile.txt](https://github.com/rocker-org/rocker/files/80301/Dockerfile.txt)

**Comment by cboettig** [comment]
Always run `apt-get update -y` first!

On Wed, Jan 6, 2016, 12:11 PM David Henderson <notifications@github.com>
wrote:

> We are building our own Docker containers with R using your Dockerfile
> tacked on to a Wetty build and are running into the following problem
> installing the unstable packages on jessie:
>
> Step 29 : RUN apt-get install -y util-linux bash && cp
> /opt/rtg/scripts/rtg-bash-completion /etc/bash_completiond/rtg
> ---> Running in db36109d65ab
> Reading package lists
> [91mE: The value 'testing' is invalid for APT::Default-Release as such a
> release is not available in the sources
> [0mThe command '/bin/sh -c apt-get install -y util-linux bash && cp
> /opt/rtg/scripts/rtg-bash-completion /etc/bash_completiond/rtg' returned a
> non-zero code: 100
> Build step 'Docker Build and Publish' marked build as failure
> Finished: FAILURE
>
> It seems that over the Christmas holidays, jessie no longer has “testing”
> as an option in APT::Default-Release Any ideas on how to get around this?
>
> I've attached a copy of my Dockerfile for reference
>
> Dockerfiletxt
> <https://githubcom/rocker-org/rocker/files/80301/Dockerfiletxt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rocker-org/rocker/issues/159>.
>
-- 

http://carlboettiger.info

**Comment by dnadave** [comment]
That doesn't fix the problem:

Step 30 : RUN apt-get update -y
 ---> Running in 95016a384e7b
Ign http://httpredir.debian.org jessie InRelease
Get:1 http://httpredir.debian.org jessie-updates InRelease [136 kB]
Get:2 http://httpredir.debian.org jessie Release.gpg [2,373 B]
Get:3 http://httpredir.debian.org jessie Release [148 kB]
Get:4 http://httpredir.debian.org jessie-updates/main amd64 Packages [3,619 B]
Get:5 http://httpredir.debian.org jessie/main amd64 Packages [9,035 kB]
Get:6 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:7 http://security.debian.org jessie/updates/main amd64 Packages [230 kB]
Get:8 http://http.debian.net sid InRelease [277 kB]
Get:9 http://http.debian.net sid/main amd64 Packages [10.6 MB]
Fetched 20.5 MB in 16s (1,223 kB/s)
Reading package lists...
 ---> 9ffd97efb30e
Removing intermediate container 95016a384e7b
Step 31 : RUN apt-get install -y util-linux bash && cp /opt/rtg/scripts/rtg-bash-completion /etc/bash_completion.d/rtg
 ---> Running in c886d4558a49
Reading package lists...
[91mE[0m[91m: The value 'testing' is invalid for APT::Default-Release as such a release is not available in the sources
[0mThe command '/bin/sh -c apt-get install -y util-linux bash && cp /opt/rtg/scripts/rtg-bash-completion /etc/bash_completion.d/rtg' returned a non-zero code: 100
Build step 'Docker Build and Publish' marked build as failure
Finished: FAILURE

**Comment by cboettig** [comment]
You're still not using `apt-get update -y` before *all of* your `apt-get install` commands, and you have lines in your Dockerfile that clean out the apt-get record that are causing the error.  

I recommend following [Docker best practices](https://docs.docker.com/engine/articles/dockerfile_best-practices/#apt-get) and do as we do, always running `apt-get update -y && apt-get install ...` in each layer.    

I was able to build your image just fine after adding `apt-get update -y`.

**Comment by dnadave** [comment]
WHAT LINE??!!??  I have apt-get update-y on the line JUST BEFORE THE ERROR!!!  Your post is most unhelpful.  If you're going to treat me like an idiot, at least point out what I need to fix!

**Comment by eddelbuettel** [comment]
Ok, I do see it on line 11.

But we do not know what it is inside `FROM krishnasrinivas/wetty` -- maybe testing is no longer in the sources?  In any event, that one is NOT our Dockerfile so ... consider our motivation somewhat muted in trying to chase this.

**Comment by eddelbuettel** [comment]
So: jessie is a _named_ release aka "stable". No testing there:

```
edd@max:~$ docker pull debian:jessie
jessie: Pulling from debian
6d1ae97ee388: Already exists 
8b9a99209d5c: Already exists 
Digest: sha256:24a900d1671b269d6640b4224e7b63801880d8e3cb2bcbfaa10a5dddcf4469ed
Status: Image is up to date for debian:jessie
edd@max:~$ docker run --rm -ti debian:jessie /bin/bash
root@36dd56aa23bd:/# apt-get update           
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://httpredir.debian.org jessie InRelease             
Get:2 http://httpredir.debian.org jessie-updates InRelease [136 kB]
Get:3 http://security.debian.org jessie/updates/main amd64 Packages [230 kB]             
Get:4 http://httpredir.debian.org jessie Release.gpg [2373 B]                            
Get:5 http://httpredir.debian.org jessie Release [148 kB]                                     
Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [3619 B]        
Get:7 http://httpredir.debian.org jessie/main amd64 Packages [9035 kB]
Fetched 9619 kB in 5s (1756 kB/s)   
Reading package lists... Done
root@36dd56aa23bd:/# 
```

If you want testing, start with testing (which is what AFAIK all our images do):

```
edd@max:~$ docker run --rm -ti debian:testing /bin/bash                                                                                                                                                             
root@0d2423eb93a2:/# apt-get update
Get:1 http://security.debian.org testing/updates InRelease [62.8 kB]
Get:2 http://httpredir.debian.org testing InRelease [201 kB]                             
Get:3 http://httpredir.debian.org testing-updates InRelease [113 kB]
Get:4 http://security.debian.org testing/updates/main amd64 Packages [20 B]
Get:5 http://httpredir.debian.org testing-updates/main amd64 Packages [20 B]
Get:6 http://httpredir.debian.org testing/main amd64 Packages [9939 kB]
Fetched 10.3 MB in 6s (1493 kB/s)                                                                                                                                                                                  
Reading package lists... Done
root@0d2423eb93a2:/# 
```

AFAICT there is bug here, but maybe a misconceptions.  I think you now know what you to either decide to live on jessie, or switch to testing, or go hybrid. 

None of that needs our help, so closing this.

**Comment by cboettig** [comment]
Very sorry, I didn't mean to be terse or condescending & you're right to call me out on it.  Just short on time here (and this isn't a rocker issue but a general Docker thing).  

I read from your error message:

```
Step 31 : RUN apt-get install -y util-linux bash && cp /opt/rtg/scripts/rtg-bash-completion /etc/bash_completion.d/rtg
```

it should be: `RUN apt-get update -y && apt-get install ....`.  And I was wrong, because I also had to add `-t unstable` on that line:

```
RUN apt-get update -y && apt-get install -t unstable util-linux bash 
```

to pull from the right sources so that it built for me.  sorry, that should fix it.

**Comment by dnadave** [comment]
Thanks!!
