### ISSUE TITLE
R package builder/tester without RStudio Server

### ISSUE THREAD

**Issue by jangorecki** [rocker-org/rocker#164]
I'm looking for an image to use for *build* & *check* that will be capable to build vignettes and manuals. From what I've found, the available official images that could be used for that are all shipped together with RStudio Server. While I like and use RStudio, for such workflow it is totally redundant. Shouldn't we have another docker image, something like `r-pkg` (and maybe `r-pkg-devel` for R devel)?
I'm managing some of my docker images but now for purpose of *canonical example* I'm writing I would prefer to use official images.

**Comment by eddelbuettel** [comment]
Could do -- in fact I fairly recently explained in the [Rcpp FAQ](https://github.com/RcppCore/Rcpp/blob/master/vignettes/Rcpp-FAQ.Rnw#L1029-L1055) how to get a full texlive environment.   I have been thinking about a container for package testing, maybe we just need to bite the bullet and build something 'big enough' test most things -- ie maybe with `libssl-dev` but excluding more esoteric things `libgdal-dev`....

**Comment by cboettig** [comment]
:+1: having the super-common libraries and basic tex required to build vignettes & manuals would probably make for a good intermediate layer.  

Still, I'm not sure how much of a win it would be -- bear in mind that RStudio is pretty small, and full texlive is huge (> 4 GB).  

@jangorecki Just curious if you could explain a bit more about what the issue is.  You know you can run the containers that have RStudio without actually running RStudio, just giving `R` as the default command, right?  Having RStudio on the image means an extra 367 MB of image-size you don't need.  Granted that's not nothing, but it's contributing only ~ 12% of the size of the Hadleyverse image.  We're pretty selective about how we install tex libraries on Hadleyverse to cover common situations while keeping the package size down, but most of its almost 3 GB image size is coming from tex, rather than from RStudio or the other libs & packages it ships with.  I haven't crunched all the numbers really recently, but earlier on my thinking was something like: "if you're committed to ship with a non-trivial tex environment, may as well throw in a couple extra libraries and RStudio since in relative terms your image isn't much bigger".

**Comment by eddelbuettel** [comment]
Good thinking.  Relative to the total size, RStudio is tiny -- and that container exists _now_ and is tested.

**Comment by jangorecki** [comment]
It's not much about size but more about the layers. The gap is here, for any automated workflow it will add an overhead. Reducing the deps when possible is a good practice, reducing when it is desired is even better practice.
Consider scenario: there was RStudio update, but no updates to R, tex, etc. In your workflow you will need docker pull to update layer. Just one changed layer of course, but still why you should do that if you are not even using it.
Having layers well isolated we could start to combine scenarios `r+tex+hadleyverse` or `hadleyverse+rstudio`, etc. Now there is not much to config.
Great to hear you are maintaining tex deps carefully, R's tex dep is scary to setup.

**Comment by cboettig** [comment]
@jangorecki Thanks for explaining, that is certainly a good point.  In practice I have found that obtaining good layer isolation so you can just update one thing is tough.  I usually bite the bullet and update, or just stick with my current image (where I can always pull in updates the ol' manual way).  Pulling some extra bits over the network doesn't bother me any more than having a few extra bits sitting around on my disk.  

I'm wondering if you could expand on the "combining scenarios".  Given the linear structure of `FROM` I haven't found a good way to do this (see #107 re: doing this via compose/orchestration -- not practical or elegant in my opinion).  Alternately you end up with a proliferation of dockerfiles / images that use different base images; e.g. the `r-base+tex+rstudio` image, the `r-base+rstudio`, `r-base+r-dev`, `r-base+r-dev+tex+rstudio`, `r-base+hadleyverse`, `r-base+hadleyverse+tex+rstudio`,  `r-base+r-dev+rstudio`, etc. Maybe that's the right thing to do, but t here's a lot of possible combinations and it seems like that might confuse the user. Given the ease in which a user can create a custom image on `rocker` image, we've aimed to just cover the most common cases.  Still, we do already have a bit of this mess (e.g. `rocker/rstudio-daily:verse` is `r-base+drd+rstudio-daily+hadleyverse`), and your suggestion of a `tex` layer for package dev/testing is probably a very common use case.  https://github.com/hadley/docker/blob/master/rdevel/Dockerfile

**Comment by jangorecki** [comment]
> Maybe that's the right thing to do, but t here's a lot of possible combinations and it seems like that might confuse the user.

So just defining consistency in naming. then it can grow slowly with the contribution from users. I'm also thinking the R package builder light would be nice, handling rendering Rmarkdown but not tex.

**Comment by eddelbuettel** [comment]
This is getting off-topic so I plan to close this.  We don't currently have bandwidth to construct a package builder; but you are certainly welcome to try.

**Comment by jangorecki** [comment]
OK, so closing. Also leaving for reference if anyone interested.
Minimal setup for pkg building with vignettes.
```
ubuntu14 + qpdf + pandoc + knitr + rmarkdown + drat@artifacts
```
Available in hub as [jangorecki/r-pkg](https://hub.docker.com/r/jangorecki/r-pkg).
Usage:
```
R CMD build .
R CMD check $(ls -1t *.tar.gz | head -n 1) --no-manual --as-cran
```
Just tested on drat which has few vignettes, all passed fine and vignettes looks [OK](https://jangorecki.gitlab.io/drat/) - to access vignette just remote `/library` from its url path.

**Comment by eddelbuettel** [comment]
Works for _your_ vignettes (using Rmd) but won't work for _all_ vignettes so need to qualify ...

**Comment by jangorecki** [comment]
That's correct, it is a lightweight setup to build pkgs with Rmd vignettes.
