### ISSUE TITLE
Fail to find attached folder in rstudio server

### ISSUE THREAD

**Issue by tengpeng** [rocker-org/rocker#165]
I have successfully attached folders from host. However, in rstudio server, there is no file or folders.

**Comment by cboettig** [comment]
Check that you have mapped them to the right place, E.g. `-v $(pwd):/home/rstudio/foo` if you are using the default user.   Other than that, you haven't really given us enough information to know what you've done or reproduce the error, so it is hard to give more constructive advice.

**Comment by eddelbuettel** [comment]
And please see the [wiki](https://github.com/rocker-org/rocker/wiki) for advice on how to map in general.  If it still fails, try to construct a [minimal working example](http://sscce.org/) showing the problem.

**Comment by tengpeng** [comment]
I fooled myself for typing an extra `~`.

To passby
```
# Wrong
sudo docker run -d -p 1111:8787 -v ~/:/home/ rocker/rstudio

#Right
sudo docker run -d -p 1111:8787 -v ~:/home/rstudio rocker/rstudio
```

**Comment by tengpeng** [comment]
@cboettig Most of the people who are familiar with R are not quiet familiar with docker. Recommend put `-v $(pwd):/home/rstudio/foo` into the "getting started section".
