### ISSUE TITLE
Use tags for docker images

### ISSUE THREAD

**Issue by JStumpp** [rocker-org/rocker#166]
Please create tags for your docker images on docker hub. We depend on both r-shiny and r-studio and without tags it is hard to stay at the same version.

Please take a look at the awesome nodejs tags: https://hub.docker.com/_/node/

**Comment by eddelbuettel** [comment]
Please old issues here. This has been discussed a bazillion times.

**Comment by JStumpp** [comment]
Yes, I have seen that. But it was all about the r-base image. Getting a specific version of the r-base image works great! 
But my issue is about the r-shiny and r-studio tags. Is there a possibility to get specific versions? If not, can you provide them or do I have to build my own images?

Thanks!

**Comment by eddelbuettel** [comment]
I think our aim here is to provide working _current_ packages at any point in time.

Your demand is for a time machine to preserve this feature back to any given snapshot.  That is simply different.  We accomodate where we can -- r-versioned was one such help -- but you need to understand that we have day jobs and many other open source projects to juggle.   So in short: yes, you may need to build that yourself.   Or just commit locally to whichever tags you prefer.

**Comment by JStumpp** [comment]
Sure, I totally understand. Just wanted to ask if there is a official solution. 

By the way, the rocker images are amazing, we use it in production and apart from that we need a pinned version of R have been a huge help!

Thanks!

**Comment by eddelbuettel** [comment]
Thanks for your understanding.  And great to hear you are putting the images to good use!
