### ISSUE TITLE
Tags for rocker/r-base images

### ISSUE THREAD

**Issue by skptic** [rocker-org/rocker#168]
Sorry if this is the incorrect place for this.

Would it be possible to have version tags of the rocker images? 

Eg here: https://hub.docker.com/r/rocker/r-base/tags/

We had a project using the r-base image and when the latest version of R was used in the last build, some libraries where not compatible.

**Comment by eddelbuettel** [comment]
Please read previous (closed) issue tickets for why the answer is 'probably not / nope'.

**Comment by cboettig** [comment]
@skptic see https://github.com/rocker-org/rocker-versioned for tagged versioned images.
