### ISSUE TITLE
New wiki page: "Extending rocker with Non-CRAN Sources"

### ISSUE THREAD

**Issue by 1beb** [rocker-org/rocker#172]
Rather than just add it, I figured you may like to think if it's appropriate for the wiki: 

---------------------

# Extending rocker with Non-CRAN Sources

This short example based guide will show you how to extend rocker-org dockerfiles in order to use non-CRAN repositories. This is especially useful if your organization does not necessarily submit to CRAN or uses private repositories. Below, you will find a `dockerfile` for each example that builds on `rocker/rstudio`.

## Using a Public Github Repo

```
FROM rocker/rstudio
RUN installGithub.r rstudio/profvis
```

Alternatively: 

```
FROM rocker/rstudio
RUN install2.r --error \
    -r "https://cran.rstudio.com" \
    devtools
  && R -e 'devtools::install_github("rstudio/profvis")' \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds
```

## Using Private Sources

Some users will need to pull from a private repository, be it: github, gitlab, bitbucket or a private repo on an ssh server. The example below shows you how to use private keys in your `dockerfile`. 

This assumes you already have appropriate private ssh keys on your machine. Before you start, move the contents of `.ssh` into the `dockerfile` folder, docker `ADD` uses the context of the directory from which `docker build .` was called.

```bash
$ cp ~/.ssh ~/path/to/dockerfile/folder
```

Then we can use the keys in our `dockerfile`:

```
FROM rocker/rstudio

RUN mkdir -p /root/.ssh
ADD .ssh /root/.ssh
RUN chmod 700 /root/.ssh/id_rsa

RUN mkdir ws \ 
  && cd ws \
  && git clone git@github.com:username/repo.git \ 
  && cd repo \
  && R -e 'devtools::install_deps(pkg = "repo")' \
  && cd .. && R CMD INSTALL repo \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds \
  && rm -rf repo
  && rm -rf /root/.ssh 
```

Note: Some dependencies may fail if they rely on Java or MySQL as the distribution may require additional libraries to support these packages. Good examples for including these additional libraries can be found in the [hadleyverse dockerfile](https://github.com/rocker-org/hadleyverse/blob/master/Dockerfile#L29-L60)

**Comment by cboettig** [comment]
@1beb no need to add private key just to install a package from github.  I assume your use case in "using private keys" is to install a _private_ package you own from github, but this isn't mentioned in your notes here.  In general installing a private package onto a Docker image seems like a bit of a special case.  

your first two examples are good, though you might want to document the use of `install2.r` to install packages from CRAN and CRAN-like (e.g. drat) repos before showing it there.  

You might also document installing packages via `apt-get`, which will handle the additional dependencies mentioned (provided the package has a debian binary built for it)

You only document installing packages at the Dockerfile level here.  That's useful for users seeking to extend rocker (as you note, we hope examples like the hadleyverse Dockerfile already provide some clue as to how to do this), though users could do this in other ways, e.g. interactively installing and then using `docker commit` to save the setup.

**Comment by 1beb** [comment]
@cboettig Yes, I moved the copying part down into the appropriate section. The motivation is not just a private package from github, but really any provider (bitbucket/gitlab/private repo on an ssh server).

I've chosen a very narrow focus for this wiki page "extending rocker using non-cran sources", I'm not sure how much benefit would be found from adding how to install from CRAN when the point of the information provided is the opposite. I also agree with you with respect to using the hadleyverse as an example for packages that require additional libraries which is why I've linked to it. The note is more of an aside as the focus is non-cran sources. 

If you'd like, I can rewrite this with a larger scope and include the items you've mentioned. Instead of labelling it as "Extending rocker using Non-CRAN sources" it would be more like "Extending rocker"

**Comment by cboettig** [comment]
@1beb sure, your focus is fine, after all the wiki is meant as a wiki, anyone can edit and contribute whatever they find to be helpful.  

still, I think this is a bit narrower than your title suggests (many non-cran sources won't be installed by install_github, but instead use a drat repo, install from bioconductor, or a local package archive; and may prefer to just use https and PTA rather than copying you ssh key temporarily into an image). At the same time, all of these tricks are also broader than just rocker, so it's not clear where the line is from 'installing non-cran packages on rocker ends' and 'installing non-cran packages on Linux / Debian' begins... 

Still, if you think others might also find this useful please add it to the wiki, that's what it's for.

**Comment by 1beb** [comment]
@cboettig I agree with you. Perhaps changing the title would be clearer to other readers. Suggestions?

**Comment by eddelbuettel** [comment]
There is no such thing as `ssh sources` unless you refer to the sources of `ssh` the program.

**Comment by 1beb** [comment]
I'm not sure what a good name would be. Perhaps just leave it as "extending rocker" and in the future it could be expanded with some of the suggestions here.

**Comment by eddelbuettel** [comment]
Come to think about, how to install R packages on the command-line is not all that specific to Rocker?

**Comment by 1beb** [comment]
Feel free to close. I'm just putting it out there as I had to search around to figure out how to prepare my environment the way I wanted and with private packages / github packages.
