### ISSUE TITLE
r-base on docker issues

### ISSUE THREAD

**Issue by IrinaMax** [rocker-org/rocker#173]
I try to pull r-base  on Docker for work with R version 3.2.3 (2015-12-10) on my MacBook, and I have problem alredy few day...  I need to work with laterst packege RevoR...   Any help?? 

`irinamacbookpro:~ irinamahmudjanova$ docker pull r-base
`
`Using default tag: latest
Pulling repository docker.io/library/r-base
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/r-base/images. You may want to check your internet connection or if you are behind a proxy.`

**Comment by eddelbuettel** [comment]
> Network timed out 

Nothing we can do here.  The container images _work_ and I just pulled a few at work last week.

Also not sure if this is meant as a practical joke regarding RevoR.  You may know what that stands for, where to get it, and where to ask for help.  In short: _not here_.

**Comment by eddelbuettel** [comment]
And I saw that you also just spammed me at home.  What is wrong with you?   Where does it say that I provide free R consulting _for projects I am not even associated with, or for Pete's sake, paid for_ ?

**Comment by IrinaMax** [comment]
I just ask for help. Thanks for be so nice.
