### ISSUE TITLE
Custom base url path

### ISSUE THREAD

**Issue by jgwerner** [rocker-org/rocker#174]
Hi, is there a way to override the base url when running the container? For example, instead of using the default path:

> http://192.168.99.100:8787/

Use something such as:

> http://192.168.99.100:8787/rstudio

This may be useful under scenarios where a reverse proxy needs to route sessions from one environment to the other without conflict.

**Comment by eddelbuettel** [comment]
Methinks that has nothing to do with Rocker but more with RStudio asking them to change which base URL they respond to.

**Comment by jgwerner** [comment]
Thanks, will research the issue with them directly.

**Comment by cboettig** [comment]
Note that this is pretty straight forward by adding a proxy server like
nginx in between, see the nginx proxy docs on RStudio page.

More simply, docker will let you bind to another port on the host end, even
though the 8787 is hardwired on RStudio end, e.g. use -p 80:8787 to bind to
port 80 on the host, which is the default HTTP port so no :80 needed in the
URL

On Tue, Mar 29, 2016, 7:49 AM Greg Werner <notifications@github.com> wrote:

> Closed #174 <https://github.com/rocker-org/rocker/issues/174>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rocker-org/rocker/issues/174#event-606799417>
>
-- 

http://carlboettiger.info

**Comment by eddelbuettel** [comment]
So do all sorts of networking, of course, starting with iptables.

But it is all a little deployment-specific.
