### ISSUE TITLE
Images are not tagged on docker-hub

### ISSUE THREAD

**Issue by fac2003** [rocker-org/rocker#175]
We like to use docker to enable reproducibility, but when rocker-base does offer only a "latest" tag, we cannot specify exactly what version of rocker-base we build upon in derived images.

If the goal of this repository is to support reproducibility, as I imagine, please do publish images tagged with a formal version number. Thank you for considering this request.

**Comment by eddelbuettel** [comment]
You are the third or fourth person to ask for it.  Please see our answers in the closed issue tags.

**Comment by eddelbuettel** [comment]
In short, they DO have a tag:

```bash
edd@max:~$ docker images r-base
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
r-base              latest              8b1651d59882        4 weeks ago         1.035 GB
r-base              3.2.3               7939bc63acf9        3 months ago        1.071 GB
r-base              3.2.2               d8d772db8b82        5 months ago        998.9 MB
r-base              3.2.1               38a6a6b62751        8 months ago        563.5 MB
r-base              3.2.0               c09b226d89bc        9 months ago        551.6 MB
r-base              3.1.3               8a0dd612a7f5        12 months ago       516.7 MB
r-base              3.1.2               c04052b3ddd2        12 months ago       483.5 MB
edd@max:~$ 
````

Once Docker merges by latest PR we will also have 3.2.4. 

I plan to close this in due course.

**Comment by fac2003** [comment]
I am not seeing any tags at https://hub.docker.com/r/rocker/r-base/tags/, which is the reason I asked. Perhaps the others looked in the same place and what you are seeing are just tags local to your machine.

**Comment by eddelbuettel** [comment]
`rocker/r-base`:   our development work which then gets 'promoted' to

`r-base/`  -- which is what my command listed above: the _official_ R images which are in fact the same as `rocker/r-base`.

Do `docker pull r-base:3.2.3` to get 3.2.3.   It is, as we explained, not ideal as rolling releases move forward but if your happiness depends on having something tagged, there it is.

**Comment by fac2003** [comment]
Thank you for the explanation. Note that you should be able to link to past issues like so: https://github.com/rocker-org/rocker/issues/168 (just pasting the URL). It may then be easier to point duplicate questions to the relevant information. 

I would also suggest to put this information in the README on the hub for rocker/r-base. i.e., if you need tags, use rocker/r-base.

**Comment by eddelbuettel** [comment]
Agreed.  If you want to suggest a nice paragraph ...

**Comment by fac2003** [comment]
"Note that this repository is used for development. If you require tagged stable releases, please use the official repository library/r-base instead. For instance:
>    docker pull library/r-base:3.2.3 

See https://hub.docker.com/r/library/r-base"
