### ISSUE TITLE
Old R versions

### ISSUE THREAD

**Issue by Black-Butterfly** [rocker-org/rocker#177]
HI, 

I'm trying to create a container with an old R version but I only get the latest one (which I really don't care). I've set up the cran to get the oldest version but nothing to do. All the time I have the latest version, which, as I said, I don't care. Can you help me to understand where I do something wrong in my dockerfile pls ? 

Thank's in advance !!

[Dockerfile.txt](https://github.com/rocker-org/rocker/files/231566/Dockerfile.txt)

**Comment by eddelbuettel** [comment]
First off, getting arbitrary old R versions is _not our design goal_ in any of our containers.

Second, you start off wrong via

```
#Get latest version of ubuntu
FROM ubuntu:latest
```

Pick an old release:  `FROM ubuntu:trusty` should get you the R version in trusty.

But you may be better off aiming at Debian and its [snapshots archive](http://snapshot.debian.org/).  But you will have to work out how to get which version from when.  They are all there.

**Comment by Black-Butterfly** [comment]
Ok I was thinking the same thing but was not sure about the ubuntu version. 
I know it's not your design goal and I respect the fact that you propose that latest version. It's just that we work with older version to have the same analysis result and that's why we need them. 

Thank's again for your answer, I'll test it right now. I hope that it will work. 

One last question. I had the idea to do a rstudio container but I saw that you propose one. If I use one of my "old version R", does it will work with them or do I have to build an R studio for each version ? (I'm not a R user but my colleague work with it so this is why I'm a little bit confuse .. )

**Comment by eddelbuettel** [comment]
Yes.

Whatever binary you want a container to run, you first have to put into that very container.

**Comment by Black-Butterfly** [comment]
That's awesome. Thank's again ! (I'm also still new to docker so it's more discovery for me ...) 

Have a nice day / evening :)
