### ISSUE TITLE
attach shared *.so files to the container?

### ISSUE THREAD

**Issue by RockScience** [rocker-org/rocker#181]
Hello,

Some R packages with compiled code depend on shared libraries located in `/lib` or `/usr/lib`.
To ensure perfect reproducibility, do we need to do anything special to enclose these shared libraries in the Rocker files? My concern is that I need the containers to have the same behavior on, let's say Ubuntu 12.04, 14.04 and 16.04 (that have different versions of the *.so shared libraries)

are the content of '/lib' and '/usr/lib' taken from the docker image or from the host os?

Thank you

**Comment by eddelbuettel** [comment]
I have no idea what you are talking about.

The shared libraries needed for a particular package are of course installed as needed, that is what the Depends: system does.   You seem to be wishing that you could swish a wand and different versions (spanning a four your period, no less) were the same.  They are not.

Please explain (or preferably demonstrate with an example) what you are after; else we have to close this for being a non-issue.

**Comment by cboettig** [comment]
@RockScience Note that the shared libraries are part of the Docker image and not used from the host machine.  e.g. if you install docker on different ubuntu releases and run the same rocker container, it will use the shared libraries from that container.  The only thing that comes from the host os is the linux kernel version itself.  If you install additional packages that build shared libraries, and then commit the container, once again the shared libraries live in the container, not the host.  These are really just general Docker questions so I would suggest consulting the Docker documentation and forums for further details. HTH.

**Comment by RockScience** [comment]
Thank you Carl, your answer makes perfect sense to me. Agree to close. 
Thank you.
