### ISSUE TITLE
3.3.1 puzzle?

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker#183]
hmm:

```
docker pull rocker/hadleyverse
docker run --rm -ti rocker/hadleyverse R --version
```

says: R is `3.3.1`

```
docker pull r-base
docker run --rm -ti r-base R --version
```

says R is `3.3.0`

how did that happen?

**Comment by eddelbuettel** [comment]
I think I may not yet have updated rocker.  Can do from here (at useR!) but if you want to charge ahead...

(Technical answer:  hadleyverse gets the package, it was rebuilt recently and hence gets the current 3.3.1; rocker / r-base has not yet. )

**Comment by eddelbuettel** [comment]
This should now be taken care, start to propagate through the builds.
