### ISSUE TITLE
r-base image >300 MB larger than R installlation on ubuntu:14.04 image

### ISSUE THREAD

**Issue by pcm32** [rocker-org/rocker#186]
Hi there,

I have been using the r-base image as base for a number of projects as I thought it would be the most optimised image for R. However, today I tried building some of our projects with the ubuntu:14.04 base image, to find that the r-base image was always around 300 MB larger than the same image if built from ubuntu 14.04. I traced down this difference to the version of gcc used on each image:

- r-base:
```
root@aa2be6a15004:/usr/lib/gcc/x86_64-linux-gnu# du -d 1 -h
443M	./5
4.0K	./4.9
4.0K	./6
443M	.
```
- Ubuntu based:
```
root@f6db11f28ca5:/usr/lib/gcc/x86_64-linux-gnu# du -h -d 1
66M	./4.8
4.0K	./4.9
66M
```

and particularly, to the sizes of cc1, cc1plus and f951, which on r-base are:
```
root@aa2be6a15004:/usr/lib/gcc/x86_64-linux-gnu/5# ls -ltrh
total 440M
...
-rwxr-xr-x 1 root root 130M Jun 11 12:23 cc1
-rwxr-xr-x 1 root root 139M Jun 11 12:24 cc1plus
-rwxr-xr-x 1 root root 133M Jun 11 12:25 f951
...
```
compared to the same files in the ubuntu-based image:
```
root@f6db11f28ca5:/usr/lib/gcc/x86_64-linux-gnu/4.8# ls -ltrh
total 65M
...
-rwxr-xr-x 1 root root  13M May  7 11:41 cc1
-rwxr-xr-x 1 root root  14M May  7 12:09 cc1plus
-rwxr-xr-x 1 root root  14M May  7 12:25 f951
...
```

I wonder whether there is a good reason for such massive size difference and if something can be done about it.

I'm I wrong in assuming that r-base is the image of choice for microservices that need to execute a single R script (plus dependencies)? If that is not the case, can you recommend a particular image to use? Maybe this image is geared more towards development or is very general?

Thanks!

**Comment by pcm32** [comment]
I can also add that on issue #169 @eddelbuettel posted an interesting table (please not size change from 3.2.1 to 3.2.2):

```
edd@max:~/git$ docker images rocker/r-base
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
rocker/r-base       latest              e70915135bfa        5 days ago          1.076 GB
edd@max:~/git$ docker images r-base
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
r-base              latest              8b1651d59882        3 weeks ago         1.035 GB
r-base              3.2.3               7939bc63acf9        11 weeks ago        1.071 GB
r-base              3.2.2               d8d772db8b82        4 months ago        998.9 MB
r-base              3.2.1               38a6a6b62751        8 months ago        563.5 MB
r-base              3.2.0               c09b226d89bc        9 months ago        551.6 MB
r-base              3.1.3               8a0dd612a7f5        11 months ago       516.7 MB
r-base              3.1.2               c04052b3ddd2        12 months ago       483.5 MB
edd@max:~/git$ 
```

I went to check on r-base:3.2.1 for the size of gcc, and this is what you get:

```
root@7bcb2ef3051f:/usr/lib/gcc/x86_64-linux-gnu# du -h -d 1
80M	./4.9
4.0K	./4.8
4.0K	./5
80M	.
```

so much similar to the Ubuntu case.

and then on 3.2.2:
```
root@14740b16c71e:/usr/lib/gcc/x86_64-linux-gnu# du -h -d 1
506M	./5
4.0K	./4.8
4.0K	./4.9
506M	.
```
so there you have ~400 MB additional, which is a lot I think.

**Comment by eddelbuettel** [comment]
Speaking as a C++ user, you want g++-5 though. 

And Ubuntu 14.04 is _outdated_ and no longer supported by Canonical as 16.04 is current.  Maybe try that.  I think we'll have to close this here as I see nothing actionable for us.

**Comment by pcm32** [comment]
Thanks for your response @eddelbuettel. Installing gcc 5.4 (same version as used in r-base) on ubuntu 16.04 still produces an installation that is 10 times smaller than the one in debian:testing:

```
root@40c13d6829b6:/usr/lib/gcc/x86_64-linux-gnu# du -d 1 -h
53M	./5
4.0K	./6
53M	.
```

Maybe there is something wrong with the debian gcc-5 package.

I actually wonder as well why do you use debian _testing_ instead of an stable version of debian for a dockerhub official image.

**Comment by eddelbuettel** [comment]
Maybe there is something wrong with Ubuntu?  I *do* use Ubuntu and notice that I can for example not use `clang++` out of the box (as the compilation fails over for lack of headers).

Let's end this here and now.  @cboettig and I have explained repeatedly why we are on Debian testing as a base; this is unlikely to change.

**Comment by eddelbuettel** [comment]
In short:  Debian testing can get stale; we had issues prior to the most recent release; we want more current software; testing gives it us (and allows us to even go to unstable as needed).  "Works for us".

There could well be an engineering issue _somewhere_.  So if you come up with something actionable and measurably different I'd be all ears.

**Comment by eddelbuettel** [comment]
Also: size of a package != single du of one top-level directory,  

Actual size is in the `dpkg -s packageName` output (ie stored) but you would have to walk the tree of Depends: to get all packages pulled in as well.
