### ISSUE TITLE
Are you interested in documentation on using the image with the new Docker for Windows?

### ISSUE THREAD

**Issue by znmeb** [rocker-org/rocker#188]
I'm currently running Windows 10 Pro with the Hyper-V Docker for Windows. Are you interested in a wiki page for that use case?

**Comment by cboettig** [comment]
sounds good to me.

**Comment by znmeb** [comment]
It's a giant leap forward over the old VirtualBox kludge. I'm now running Office, Firefox and Git native on Windows and doing everything else in a Docker image.

**Comment by eddelbuettel** [comment]
I would suggest to keep it short. Deployment under 1.12, just like any other Docker version, is orthogonal to our Rocker container content, and really a generic Docker deployment issue.  Might be a better topic to expand on via a blog post, with maybe a short reference here.
