### ISSUE TITLE
Fonts appearance differences

### ISSUE THREAD

**Issue by wch** [rocker-org/rocker#189]
I know this isn't exactly the right place to post this, but I'll ask here anyway... I've noticed that when I make plots from the r-base image, the fonts look significantly different compared to when I make them on my Ubuntu 16.04 machine.

Here's a table fonts created in Ubuntu 16.04:
![fonttable-ubuntu](https://cloud.githubusercontent.com/assets/86978/17944363/0f0cfc2c-6a05-11e6-8ea9-adfe9072ac7d.png)

And in r-base:
![fonttable-r-base](https://cloud.githubusercontent.com/assets/86978/17944380/18584994-6a05-11e6-8197-60a6d9db71fd.png)

Anyone know what needs to be done to make the fonts from r-base look like those from Ubuntu? I'd be happy to add a wiki article once I have this figured out.

This is the code used to generate the table:

```R
fonttable <- read.table(header=TRUE, sep=",", stringsAsFactors=FALSE,
                        text='
Short,Canonical
mono,Courier
sans,Helvetica
serif,Times
,AvantGarde
,Bookman
,Helvetica-Narrow
,NewCenturySchoolbook
,Palatino
,URWGothic
,URWBookman
,NimbusMon
URWHelvetica,NimbusSan
,NimbusSanCond
,CenturySch
,URWPalladio
URWTimes,NimbusRom
')

fonttable$pos <- 1:nrow(fonttable)

library(reshape2)
fonttable <- melt(fonttable, id.vars="pos", measure.vars=c("Short","Canonical"),
                  variable.name="NameType", value.name="Font")

library(ggplot2)
pf <- ggplot(fonttable, aes(x=NameType, y=pos)) + 
             geom_text(aes(label=Font, family=Font))

png('fonttable.png', width=480, height=480, res=96)
print(pf)
dev.off()
```

**Comment by eddelbuettel** [comment]
Pfffft.  

Fonts is a hard topic.  I usually just delegate to font-config.  Not sure what is going on here, or how to  go about it :-/

**Comment by wch** [comment]
Thanks, I have a feeling I'm going to spending some time trying to figure this out. :(

**Comment by cboettig** [comment]
@wch good luck, that looks like a tough one.  I don't suppose it just comes down to some different font libraries on ubuntu that you can apt-get.  Would be curious to hear if/when you figure it out.

**Comment by eddelbuettel** [comment]
That would be my gut feel too.   If you have a spare machine where you can install _exactly_ what the Dockerfile(s) install, it could make for a better / closer comparison.

**Comment by wch** [comment]
Here's what I found when queried fontconfig for various of these fonts, using `fc-match`.

On the r-base container:

```
# fc-match Times
DejaVuSerif.ttf: "DejaVu Serif" "Book"
# fc-match Helvetica
DejaVuSans.ttf: "DejaVu Sans" "Book"
# fc-match Courier
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
# fc-match Palatino
DejaVuSerif.ttf: "DejaVu Serif" "Book"
```

So it looks like r-base is using the DejaVu font family.

On my Ubuntu 16.04 computer:

```
$ fc-match Times
texgyretermes-regular.otf: "TeX Gyre Termes" "Regular"
$ fc-match Helvetica
texgyreheros-regular.otf: "TeX Gyre Heros" "Regular"
$ fc-match Courier
pcrr8a.pfb: "Courier" "Regular"
$ fc-match Palatino
texgyrepagella-regular.otf: "TeX Gyre Pagella" "Regular"
```

It turns out that these all come from a package called fonts-texgyre, except for the Courier font, which comes from texlive-fonts-recommended. Installing fonts-texgyre requires 19.5 MB of space, and installing texlive-fonts-recommended requires 528 MB, so I decided to install fonts-texgyre but not texlive-fonts-recommended.

On r-base with fonts-texgyre installed:

```
# fc-match Times
texgyretermes-regular.otf: "TeX Gyre Termes" "Regular"
# fc-match Helvetica
texgyreheros-regular.otf: "TeX Gyre Heros" "Regular"
# fc-match Courier
texgyrecursor-regular.otf: "TeX Gyre Cursor" "Regular"
# fc-match Palatino
texgyrepagella-regular.otf: "TeX Gyre Pagella" "Regular"
```

The output of the font table using r-base with fonts-texgyre looks like this:

![fonttable-r-base-texgyre](https://cloud.githubusercontent.com/assets/86978/17954470/e69499d0-6a40-11e6-88ef-07ce632c0708.png)

And as a recap, this is what it looks like on my Ubuntu computer:

![fonttable-ubuntu](https://cloud.githubusercontent.com/assets/86978/17954606/a050d762-6a41-11e6-9721-bb384ccef197.png)

Helvetica and Times now look exactly the same in both. Courier looks a little different, which is expected. Many of the other fonts are the same, and some of them are different, but I don't really care about any of them.

One slight difference between the two images is the text on the x-axis labels -- the font is slightly taller in the r-base+fonts-texgyre plot, compared to the Ubuntu plot. I don't know why that is, but it's something I can live with.

I suggest that if we want r-base to have nice-looking fonts out of the box (with results that look like what people get on their desktop systems), then we should add fonts-texgyre in r-base. But I can understand if you guys don't want to add it.

**Comment by eddelbuettel** [comment]
Nice work.  I think we can spare 20mb for fonts.

**Comment by cboettig** [comment]
Nice :+1:

**Comment by wch** [comment]
Awesome, I'll make a PR.
