### ISSUE TITLE
Support pandoc-crossref

### ISSUE THREAD

**Issue by jabranham** [rocker-org/rocker#194]
Hi, and thanks for your work on this project. 

Are there plans to add `pandoc-crossref` support to any of the docker images?

**Comment by cboettig** [comment]
Interesting, hadn't actually seen https://github.com/lierdakil/pandoc-crossref before.  Might be a good fit for the `rocker/hadleyverse` image?  Would you consider sending a PR?  Note that images like rstudio and hadleyverse rely on the versions of pandoc and pandoc-citeproc as packaged by RStudio; might complicate the install/setup.  Also would be good to do this in a one-line install that can remove unnecessary haskell baggage.

**Comment by jabranham** [comment]
I... can try. I use linux but am not super familiar with debian's apt-get nor am I familiar with docker. I'll look around to see how to do this, though.

**Comment by eddelbuettel** [comment]
Start with getting it installed and working in, say, `rocker/hadleyverse`.  Then take it from there...

**Comment by cboettig** [comment]
Users can always add this.  Meanwhile, see the `bookdown` R package for RStudio's way of handling a lot of these features.
