### ISSUE TITLE
rstudio initialization errors

### ISSUE THREAD

**Issue by ricoderks** [rocker-org/rocker#195]
Hi all,

For my projects I'am trying to setup a rstudio container with my prefered packages. For setting this up I have docker running in a virtual machine with Ubuntu 16.04 server. To reach my files on the local disk I setup a share in virtualbox which I can reach from within de VM on /media/sf_Projects/ 
From within the VM I can read and write files here. 

I started the rstudio image with -v /media/sf_Projects/:/home/rstudio/ The image starts with no errors, but  when I try to login to Rstudio I get the error "RStudio initialization error" "Unable to connect to service". 

Starting an interactive session allows me to write to /home/rstudio and the files showing up on my hard disk.

I also tried creating my own user making sure the UID is 1000.

Any idea why I can not login to rstudio?

Cheers, Rico

**Comment by eddelbuettel** [comment]
I cannot decypher what you wrote there.  What is your outermost operating system?  Is it Ubuntu 16.04?  If so, why are you running a VM to run Docker?

You have not demonstrated a reproducible error in Rocker here so we are likely to close this.  Carl and I are both busy professionals and cannot run Docker tutorials here, sorry.

**Comment by ricoderks** [comment]
I apologize for being unclear. I tried to keep the story short. You can close the issue. I just found out that I might can get my hands on a linux machine and that should solve my problem.

**Comment by eddelbuettel** [comment]
Even when you are on another OS, you should *not* need an explicit VM. Docker does all that for you.
