### ISSUE TITLE
Add Alpine Linux based images

### ISSUE THREAD

**Issue by artemklevtsov** [rocker-org/rocker#196]
Hi.

I suggest to add a Alpine based images.
More details about implementation and sizes: https://github.com/artemklevtsov/r-alpine
Each image contains a specific R-version with the same flags and options.

Could I make PR?

**Comment by eddelbuettel** [comment]
I am not sure I am on board. 

I admire that you did this on your end, I note the size reduction but _for my use_ I prefer to be in a know libc6 environment.  @cboettig : Your thoughts?

I'd be happy to add a link etc pp.

**Comment by cboettig** [comment]
Interesting; these look pretty promising.  If @artemklevtsov is interested in maintaining them and wants to do so under rocker-org, that sounds good to me.  I think a separate repo in rocker-org would make more sense than PR against this repo adding a subdirectory, since the different package manager etc for the alpine images would probably confuse users.  (and of course we couldn't take this approach for `r-base` etc since it would break all users downstream images)

**Comment by artemklevtsov** [comment]
I agree with @cboettig: a separate repo is good idea. Alpine provides a non standard environment so some users will faced with (musl?) specific problems.

**Comment by eddelbuettel** [comment]
I am still not sure I am on board now that @cboettig moved them in.

We had one maintained constant here:  all images built on top of each other with Debian testing as the base.   

That no longer holds.   I have nothing against Alpine, I simply don't use non libc6/Debian/Ubuntu based environments, and I fear it will create confusion here.   So moderately against.

**Comment by nuest** [comment]
Just want to document here that I came across https://github.com/sgerrand/alpine-pkg-glibc which runs `glibc` on Alpine, which could be interesting if someone wants to pick this up again.

**Comment by cboettig** [comment]
Thanks @nuest  for the follow up. From our side, I'm still skeptical that many of our images would really be meaningfully smaller on an alpine base once you add all the compilers, packages, and libraries back in (for comparison, the base debian instance is only ~ 48MB compressed.  We could switch to one of the `slim`-flavor of official debian images at ~22 MB but most of what is cut out we'd end up adding back in I think?)  

We haven't ever provided really stripped down images which cannot compile or have all the optional capabilities turned off.  

Note that @gaborcsardi has an interesting project for minimal alpine-based Docker images for R at https://github.com/r-hub/r-minimal.  He has a really clever approach there of a custom installer for cleaning up dev libraries to keep the resulting images as small as possible!
