### ISSUE TITLE
Setup question - how to setup automated builds for sub-directories?

### ISSUE THREAD

**Issue by rkrug** [rocker-org/rocker#197]
Sorry for this not being a directly rocker related question.

I am setting up some rocker based images for working with spatial date [https://github.com/rkrug/space-rocker](https://github.com/rkrug/space-rocker) and I would like to setup automated builds with each sub-directory an image (as in the rocker repo).

My question: how can I set this up so that the names in for the docker repo is as it is for rocker, i.e.

rocker-space/r-base-spatial
rocker-space/r-devel-spatial
...

I always get my username (rkrug) as the first part?

Thanks,

Rainer

**Comment by rkrug** [comment]
I have now created an organization on github. Do I need one at hub.docker as well? and why don't I see my new github organization?

**Comment by eddelbuettel** [comment]
I don't think there is magic -- create a Dockerfile, in a given git repo, irrespective of org/naming/whatnot

Connect a 'docker hub' build to that Dockerfile.  

Repeat for another Dockerfile.

**Comment by rkrug** [comment]
I am sure there is no magic - although Docker is already magic for me...

But I would like to have one repo with multiple directories, where in each directory is a different Dockerfile for a different image. I think I figured it out - one link for each docker direwctory with specific trigger rules and Dockerfile locations.

Thanks,

Rainer
