### ISSUE TITLE
Relative Rstudio PATH?

### ISSUE THREAD

**Issue by shrektan** [rocker-org/rocker#198]
Sorry I'm not an expert of Docker or Linux, but I do think the below code makes the system environment variable `PATH` in R being set to fixed and can't be modified via changing the `ENV PATH` when running the docker containers:

https://github.com/rocker-org/rocker/blob/master/rstudio/Dockerfile#L51

```
RUN echo "PATH=$PATH" >> /etc/R/Renviron.site
```

What the `Renviron.site` looks like in container is:

```
PATH=/usr/lib/rstudio-server/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

While I think it should be:

```
PATH=/usr/lib/rstudio-server/bin/:$PATH
```
Thanks.

**Comment by cboettig** [comment]
Thanks, I think you are right about that. Care to send a PR to fix this?

**Comment by shrektan** [comment]
Sure. I'll try to file a PR later :smiley:

**Comment by eddelbuettel** [comment]
It's pretty straightforward.  Give us a heads-up if you find anything about it confusing.

**Comment by shrektan** [comment]
Not sure what you mean. It's not confusing.  It's  modifying on Renviron.site causes the later changing on system env Path losing effect.

**Comment by eddelbuettel** [comment]
I was talking about the process of creating a PR.  But let's not overcomplicate things -- I'll just commit the fix you suggested now and then we are done.

Thanks for the heads-up. It is a genuine improvement.

**Comment by shrektan** [comment]
All right. I'm not very familiar with docker, so would like to rebuild the image to ensure the fix worked, but can't find the time today. Now it's ok.  Thank you, too.

**Comment by shrektan** [comment]
@eddelbuettel Dirk, I don't think your fix worked. I just pull the image, and the content in `Renviron.site` is still a fixed one:

```
PATH=/usr/lib/rstudio-server/bin/:/usr/lib/rstudio-server/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by shrektan** [comment]
In my option, the correct one should be:

```
RUN echo "PATH=/usr/lib/rstudio-server/bin/:${PATH}" >> /etc/R/Renviron.site
```

I'll build an image to see if it's ok. If so, I'll file a PR then.

**Comment by eddelbuettel** [comment]
Right. The `$PATH` got expanded then.  You may need to protect the `$`.

**Comment by eddelbuettel** [comment]
Now that you caught me not doing my home work ;-), here is a better minimal Dockerfile:

```
## Emacs, make this -*- mode: sh; -*-
 
FROM r-base

## This handle reaches Carl and Dirk
MAINTAINER "Carl Boettiger and Dirk Eddelbuettel" rocker-maintainers@eddelbuettel.com

RUN echo "PATH=\"/usr/lib/rstudio-server/bin/:\${PATH}\"" >> /etc/R/Renviron.site
```

which works:

```bash
edd@max:~/git/rocker/test(master)$ cat Dockerfile | docker build -t test -
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM r-base
 ---> d71dbb88b62d
Step 2 : MAINTAINER "Carl Boettiger and Dirk Eddelbuettel" rocker-maintainers@eddelbuettel.com
 ---> Using cache
 ---> 9e16144d8f68
Step 3 : RUN echo "PATH=\"/usr/lib/rstudio-server/bin/:\${PATH}\"" >> /etc/R/Renviron.site
 ---> Running in 4245e22bf989
 ---> aaba1eb1ad51
Removing intermediate container 4245e22bf989
Successfully built aaba1eb1ad51
edd@max:~/git/rocker/test(master)$ docker run --rm -ti test:latest /bin/bash
root@fa083498acf5:/# 
root@fa083498acf5:/# cat /etc/R/Renviron.site 
##                                              Emacs please make this -*- R -*-
## empty Renviron.site for R on Debian
##
## Copyright (C) 2008 Dirk Eddelbuettel and GPL'ed
##
## see help(Startup) for documentation on ~/.Renviron and Renviron.site

# ## Example ~/.Renviron on Unix
# R_LIBS=~/R/library
# PAGER=/usr/local/bin/less

# ## Example .Renviron on Windows
# R_LIBS=C:/R/library
# MY_TCLTK="c:/Program Files/Tcl/bin"

# ## Example of setting R_DEFAULT_PACKAGES (from R CMD check)
# R_DEFAULT_PACKAGES='utils,grDevices,graphics,stats'
# # this loads the packages in the order given, so they appear on
# # the search path in reverse order.
PATH="/usr/lib/rstudio-server/bin/:${PATH}"
root@fa083498acf5:/# 
```

**Comment by shrektan** [comment]
You're welcome. :smile: 

I actually rebuild the image on docker hub https://hub.docker.com/r/shrektan/rstudio-fix/builds/, and it works, via fix like below.

```
RUN echo "PATH=/usr/lib/rstudio-server/bin/:\${PATH}" >> /etc/R/Renviron.site
```

However, your version works, too. Cheers. :beers:

**Comment by eddelbuettel** [comment]
Right. The quotes appear to be optional in the Renviron files, the escape dollar sign is what matters and was missing.

Thanks again.
