### ISSUE TITLE
In an AWS EC2 Instance (CentOS), port 1410 doesn't get open.

### ISSUE THREAD

**Issue by rebordao** [rocker-org/rocker#199]
When I run a docker container from `rocker/rstudio` with `-p 8787:8787`:

1. if it's in my local machine, two ports get open `1410/tcp, 0.0.0.0:8787->8787/tcp`. Doing a `wget <docker_machine_ip>:8787` succeeds and I can use Rstudio Server without problems.
1. If it's in an AWS EC2 Instance (CentOS), port 1410 doesn't get open. It only opens  `0.0.0.0:8787->8787/tcp` and doing a `wget localhost:8787` gives me the following message:

`--2016-10-12 15:50:19--  http://localhost:8787/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8787... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
`

**It seems that port 1410 doesn't get open and that may cause problems.**

**I am running out of ideas about what can be the cause and solution for this. Any hint?**

I made a [gist here](https://gist.github.com/rebordao/f71eba9c3cea547f309ae8e991bfaf08) with the output of docker inspect <name of container>.

In the same EC2 instance I've spark notebooks and a nginx server working without any problem. In this cases, there are no authentication screens and at run time ports `9443/tcp` and `443/tcp` get open for spark and nginx, respectively.

**Comment by rebordao** [comment]
I made a [gist here](https://gist.github.com/rebordao/f71eba9c3cea547f309ae8e991bfaf08) with the output of docker inspect <name of container>.

**Comment by eddelbuettel** [comment]
That strikes me as issue with your side of things, and not something in our end of the court:

> if it's in my local machine, two ports get open

I would suggest to request some EC2 support.
