### ISSUE TITLE
Rename hadleyverse to tidyverse

### ISSUE THREAD

**Issue by hadley** [rocker-org/rocker#201]
I think it would be a good idea because there is now a formal definition for the tidyverse (i.e. all the dependencies of the tidyverse package).

**Comment by eddelbuettel** [comment]
The question came up before, which you could have seen by searching issue tickets, and we decided against.

**Comment by eddelbuettel** [comment]
And if I were as rude as you have been with issue tickets, I'd close this now.  See how much better it is to deal with a kind and understanding maintainer?  :grinning:

**Comment by hadley** [comment]
The only issue that comes up is this one: https://github.com/rocker-org/rocker/issues?utf8=✓&q=%20tidyverse. But if you don't want to change, I don't really care.

**Comment by eddelbuettel** [comment]
I guess it was [this issue in the same org but different repo -- sue me](https://github.com/rocker-org/hadleyverse/issues/8) which I had in mind.

I have not strong feelings either way but _on the margin_ prefer existing links to remain working.
