### ISSUE TITLE
Pandoc Error in knitr to PDF

### ISSUE THREAD

**Issue by jnobuyuki** [rocker-org/rocker#203]
I tried to make a pdf output with knitr in rocker/rstudio docker container.
I used to successfully do this. However, today I received error such as
"pandoc document conversion failed with error 41" and pdflatex was not found.

Thanks for your consideration of this issue!

Best regards,

Nobuyuki

**Comment by eddelbuettel** [comment]
That container may not have latex installed.

**Comment by cboettig** [comment]
Dirk is correct. Try the rocker/verse container instead

**Comment by jnobuyuki** [comment]
@eddelbuettel @cboettig 
Thanks for your quick reply.
I confirmed that the rocker/verse container could make a pdf ouput with knitr.

Best regards,

nobuyuki
