### ISSUE TITLE
Problem with using host user UID for macOS

### ISSUE THREAD

**Issue by rpln** [rocker-org/rocker#205]
I would like to share directories without changing the permissions on the host.

Following the advice here: https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine, passing the host user UID (``docker run -e USERID=$(id -u) -p 8787:8787 rocker/rstudio``) seems to make things work very nicely when the host is Linux. It doesn't work when the host is macOS. 

When using Linux as a host, my host user UID is 1001 - working.
When using macOS as a host, my host user UID is 502 - not working.

An example (user = rstudio, password = rstudio):

`docker run -e USERID=502 -p 8787:8787 rocker/rstudio` (at [localhost:8787](http://localhost:8787), I get: _Error: Incorrect or invalid username/password_)
`docker run -e USERID=1000 -p 8787:8787 rocker/rstudio` (success)
`docker run -e USERID=1001 -p 8787:8787 rocker/rstudio` (success)

I wondered if this was a general RStudio problem, but the only thing I could find is [an unrelated restriction](https://github.com/rstudio/rstudio/blob/master/src/cpp/server/extras/pam/rstudio#L2) for uid >= 500

**Comment by rpln** [comment]
Solved:
http://docs.rstudio.com/ide/server-pro/authenticating-users.html#restricting-access-to-specific-users

Seems to be due to:
```
docker exec -it e39856a21dbe /bin/bash
root@e39856a21dbe:/# cat /etc/login.defs | grep UID_MIN
UID_MIN			 1000
```

Solved with:
```
echo auth-minimum-user-id=499 >> /etc/rstudio/rserver.conf
```

**Comment by rpln** [comment]
This is the fix to add to `userconf.sh` (I don't know for which of the repos the PR should be opened, therefore putting here):

```
if [ "$USERID" -lt 1000 ]
# Probably a macOS user
	then
		echo "$USERID is less than 1000, setting minumum authorised user to 499"
		echo auth-minimum-user-id=499 >> /etc/rstudio/rserver.conf
fi
```

**Comment by cboettig** [comment]
@rpln Nice, thanks for the bug report and the solution.  Should be in the rstudio images soon.

**Comment by cboettig** [comment]
@rpln Can you take a look at issue #215 ?  Probably best to add some logic to check that id isn't already specified in `/etc/rstudio/rserver.conf` before appending the id minimum.  PR against https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/userconf.sh would be welcome
