### ISSUE TITLE
'rocker/rstudio:testing' cannot be started

### ISSUE THREAD

**Issue by tzerk** [rocker-org/rocker#211]
Hi, and first of all many thanks for this great project! 

I noticed that the latest commit a35c1df7e3dced0956cc4c33fd32ef71a443d8c4 produces an error (see below) when trying to run the `rocker/rstudio:testing` image. Unfortunately, I am not proficient enough to find out what change exactly caused this, let alone to provide a fix.

Note that the image builds without problems, it is only when creating a container. Maybe you could include a line in the `.travis.yml`

`- docker run -d rocker/rstudio:testing`

to check whether the service actually starts, just like for some of the other images/tags?

```
PS D:\DIR> docker run -d -p 8787:8787 rocker/rstudio:testing
043e35bbdb3081408fb2e54b509aa92302056992f03a0717c3ff97b56a745520
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid header field value "oci run
time error: container_linux.go:247: starting container process caused \"exec: \\\"/init\\\": stat /init: no such file or
 directory\"\n".
```

This is on Docker version 1.12.5, build 7392c3b (Windows), if it makes any difference.

**Comment by cboettig** [comment]
@tzerk Sorry about that, should be fixed as soon as hub re-builds the image with the above patch (https://hub.docker.com/r/rocker/rstudio/builds/).  Just out of curiosity, any particular reason you're using the `testing`-based image?

**Comment by tzerk** [comment]
Great, many thanks for the quick response and fix!

While I would have preferred to use the `rocker/rstudio:latest` image I had trouble installing the R package `rjags`, which requires JAGS 4.x.y. The Debain Jessie repository only has JAGS 3.4.0-1, which is why I opted for the `testing`-based image building on top of `debian:testing`. I did find some workarounds to install packages from testing in Debian stable, but I figured that for the time being relying on `debian:testing` was the easier approach compared to tinkering with the apt config files.

**Comment by cboettig** [comment]
@tzerk Thanks for the follow up! Yeah, I found apt-pinning to JAGS on Jessie annoying as well; the jags binaries are compiled against the newer compilers in testing and so you need to upgrade all of the compiler libs too.  In my own image I just install JAGS from source on jessie: https://github.com/cboettig/2016/blob/master/Dockerfile#L17-L20

Unrelated to docker, I actually use nimble (<www.r-nimble.org>) now instead of jags; tends to be a bit faster and no external libraries needed; and can be extended directly from R.  (uses code inspection to compile R-code into c++ on the fly).  pretty neat!

**Comment by eddelbuettel** [comment]
Installation from source works, but gets old if you have to do it often.  When I need or want something on a different flavor, I just create a .deb -- for Ubuntu-based use such as Travis I use Launchpad.  

I think you may be able to contribute 'backports' to Debian. So you should be able to take my package and have it rebuilt / rebuild it somewhere.   I personally do not care so much about 'stable' so I am a little out of the flow there...

**Comment by tzerk** [comment]
@cboettig Thank you for pointing out compiling JAGS from source, for some reason I haven't thought of it myself. I now build my docker images on the `:latest`-image, which is a lot more convenient. Also thanks for pointing out r-nimble, I will have a look at it. Only too bad I haven't heard of it any earlier, as the models are now already written in JAGS. But maybe I can convince the authors to convert them, getting rid of external dependencies is always nice. Happy New Year!
