### ISSUE TITLE
User specified UID < 1000 causes stopped container not start again

### ISSUE THREAD

**Issue by adlerpriit** [rocker-org/rocker#215]
If user specified UID is less than 1000 (which usually should be avoided, but on some legacy systems still happens). Then init script (some child of it) adds a rule to /etc/rstudio/rserver.conf file:
`auth-minimum-user-id=nnn` 
[nnn is some number less than specified UID].

This is fine the first time, but if you stop/crash the container, then the init script adds another such line to the conf file. And that prevents the rserver to start:
`Error reading /etc/rstudio/rserver.conf: option 'id' cannot be specified more than once`

Manually deleting the conf file allowed init script to behave as it should.

**Comment by adlerpriit** [comment]
I see now that it is caused by fix in #205.
It should not do blindly:
`echo auth-minimum-user-id=499 >> /etc/rstudio/rserver.conf`

**Comment by cboettig** [comment]
@adlerpriit Just mentioned this to @rpln in #205; feel free to send a PR against https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/userconf.sh to avoid writing `id` more than once in `rserver.conf`
