### ISSUE TITLE
Question: Best Practice for Backups & Multi-User installation

### ISSUE THREAD

**Issue by inkrement** [rocker-org/rocker#216]
I read the documentation, but I was not able to find information on multi-user setups. There was some advice how to mount volumes, but nothing in case of multi-user systems. 

How should I add additional users (At the moment I am just using a single user, which I created using the `--user` option)? Should I open a bash in the container, or extend the Dockerfile? I would also like to mount the `/home` dir to a host-volume (to persist the data on reboot/container update), but is this bad practice?

**Comment by cboettig** [comment]
By multi-user, do you mean a system where the host machine has multi-users, the docker image has multiple users, or both?  If the host has multiple users, you'll have to take care to map the relevant user id from the host to the creation of the same user id on the container, see: https://github.com/rocker-org/rocker/wiki/managing-users-in-docker .  The rocker image will set up a single user inside the container on launch, other users will need to be created inside the container like you would on any other linux system.  (RStudio will also use the linux system users/passwords).  

Sharing local volumes is a good way to backup data, but mounting all of `/home` probably isn't a great idea.  The directories of `/home` will have different permissions, so you'd have to take care to create all of the users inside the container with the same names and same userid numbers to avoid conflicting or changing permissions.   

A common multi-user setup is to create many users inside the container, on a host server that has just a single user (perhaps just root).  You can map the home directory of the docker container to whatever you want on the host (e.g. `/var/backup`).  Then multiple users can log into the container (e.g. via an RStudio instance) and keep their work in separate locations backed up on the host, but don't have access directly to the host machine so  you don't have to worry about coordinating user permissions between the host and the container.  Does that make sense?

**Comment by inkrement** [comment]
Hi, thanks for your answer! I mean a system where just the docker image has multiple users. We want to use the RStudio-Docker image for some courses (we want to give our students access to a ready-to-use R environment). So want to persist/backup the data, but I think you gave me already a (great) answer :) So I will just have a problem, if I loose the uid-information (the container crashes after I added some users), right? But when I create a "snapshot" right after, everything should be save.

**Comment by cboettig** [comment]
Yup.  If you create users in the same order on a new container, they'll get the same uids; otherwise you'll just have to change permissions on the host after the fact, but no data loss.  Note that snapshotting a docker container doesn't capture linked volumes on the host.
