### ISSUE TITLE
sudo errors after using -e ROOT=TRUE

### ISSUE THREAD

**Issue by kplaney** [rocker-org/rocker#217]
1) host OS: 16.04
2) trying the rstudio docker
3) launch command : docker run -d -p 8787:8787 -e ROOT=TRUE rocker/rstudio
I then tried to do a sudo install after logging into rstudio: system("sudo apt-get install -y install r-cran-xml")
4) What I expected: ability to run commands using sudo to install packages (the XML package, to be honest)
5) Instead I get the error: sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

I cleared out all my previous containers to make sure nothing was cached. Has anyone else experienced this error?  I don't need to do anything special after the run command above and logging in as user rstudio, correct? I've tried running a fresh container a few times and no luck.

System info: 
Ubuntu 16.04
Docker version 1.13.1, build 092cba3
Image ID: 63876f919c70

What's odd is in the Docker logs, I do see the message of making the user a sudo user:

```
 docker logs 51536243ce63 
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying... 
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] conf: executing... 
Adding user `rstudio' to group `sudo' ...
Adding user rstudio to group sudo
Done.
rstudio added to sudoers
[cont-init.d] conf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by eddelbuettel** [comment]
Not sure I follow.  Why would you need `sudo`?  You *are* root:

```
edd@max:~$ docker run --rm -ti rocker/r-base /bin/bash
root@5a162d4b103f:/# id
uid=0(root) gid=0(root) groups=0(root)
root@5a162d4b103f:/# 
```

That is a universal Docker property.

**Comment by cboettig** [comment]
@kplaney strange, I cannot replicate that error; the above works fine for me.  Double-check commands are as you typed them above?  (I also tested on Ubuntu 16.04 with the same `6387` image.  

Note that you can always try running `docker exec -ti <CONTAINER-ID> bash` and poke around to see what is up; note that as Dirk says the container itself is running as root so you'll be root when you exec in this way. This should let you install stuff via apt-get and is often a better way to do maintenance tasks than enabling sudo for user.  (Aside, do note that you'll need to run `apt-get update` first, and it would be better to install `libxml2-dev` and then install `XML` package from R on this image.  Also note you could just use the `rocker/tidyverse` image which has `libxml2-dev` already.  

@eddelbuettel kplaney is running this from within the RStudio R console; RStudio requires you to be a non-root user.

**Comment by eddelbuettel** [comment]
As an aside, probably easiest to  just install `r-cran-xml` which is a binary in the core distribution.

**Comment by kplaney** [comment]
Hi @eddelbuettel  - I did try installing r-cran-xml from the Rstudio using system() inside Rstudio and its "shell" window, but not via the exec command in Docker so I'll just try that route in the future if I run into issues (I did a similar trick on a Jupyter notebook docker to install r-cran-xml.) I think I'll just add R installations into my own copy of the last dockerfile and build that file, so that I have a record of everything I install.

Along those lines, thanks @cboettig for suggesting the rocker/tidyverse image as I am aiming for high reproducibility, and the final Dockerfile already has the XML-related packages I need.  I'll update this post when I'm able to retry those docker commands on the original  rstudio again (work calls first!)

**Comment by eddelbuettel** [comment]
It's a bit of a braindead situation as the main process is gobbled up with RStudio.  I use my Docker instances more lightly and usually start in bash ...  But one thought I had was to possibly try to circumvent the initial `CMD` and install what you need before launching.

The real fix, of course, is to derive a Dockerfile from ours and to add what you need...

And nightly 'dev' builds of RStudio, which I use happily day-to-day, have an actual full-featured console.  So even when you use Docker as an 'app' to deliver RStudio for you you should have a way out.
