### ISSUE TITLE
Change default UID behavior

### ISSUE THREAD

**Issue by brooksambrose** [rocker-org/rocker#218]
I understand the instructions for changing the UID when running, for instance, the `rocker/rstudio` container. Would it be possible to change the default behavior to assume that the owner of the process that runs the container should be the user launching `rstudio-server` within the container?

**Comment by cboettig** [comment]
Not sure I follow quite what you want or what the motivation is. The rstudio-server instance is launched as root, and if I'm not mistaken needs root privileges.  RStudio needs a non-root user to login, by default we don't give that user root privileges, which seems like a reasonable default but probably precludes launching the rstudio-server instance as the user.  

Note also that the rstudio-server instance is not run by root directly, but is handled by the s6 init system in the container.  This keeps the server instance up in detached mode, and gives us the usual control over logging, starting, stopping etc for the service or the container (using s6 also avoids the zombie pids that can happen with some other init systems, and is a bit more lightweight if less commonly used).

Not sure if that answered your question about the default UID behavior?  Feel free to reopen if I've missed something here.
