### ISSUE TITLE
Logout redirects to page with token error

### ISSUE THREAD

**Issue by inkrement** [rocker-org/rocker#219]
When I start a new container and logout after a successful login, I am referred to a page (mydomain.com/auth-sign-out) with the content
```
Missing or incorrect token.
```

The logout works, but this message is strange

**Comment by eddelbuettel** [comment]
Logout?  What do you mean?

```
edd@max:~$ docker run --rm -ti rocker/r-base /bin/bash
root@27ccc591f95f:/# whoami
root
root@27ccc591f95f:/# exit
exit
edd@max:~$ 
```

No token. No redirect. No login. No logout.  

Did you have a different container in mind?  Then maybe close this, and open a more appropriate (and, ideally, more actionable) issue there.

**Comment by inkrement** [comment]
Ah sorry. I am talking about the `rocker/rstdio` image. This image provides a web-login (based on RStudio Server), which returns the error.

**Comment by cboettig** [comment]
Sorry, but I've never seen that error before, and cannot reproduce it with the current `rocker/rstudio` image.  You'll really have to give us more details to have a chance at debugging this one.  As you may have seen when opening this issue, we request [the following details](https://github.com/rocker-org/rocker/blob/master/CONTRIBUTING.md) in contributing bug reports.  Thanks!

**Comment by inkrement** [comment]
It is really strange, I am also not able to reproduce it at the moment. I will close the issue now and reopen it, if I have more information.

**Comment by crawdaddy18** [comment]
I get the same issue.  I've been playing around with the PAM stack, so that my be what is causing my issue.  I am using pam_krb5 to verify a user before letting them in.
