### ISSUE TITLE
ODBC Driver installation error

### ISSUE THREAD

**Issue by juliezhu324** [rocker-org/rocker#224]
Hi Team,

I'm trying to install ODBC Driver 13 for SQL Server in Rocker environment. I'm using:
`FROM rocker/tidyverse:latest`

I followed the steps on this [page](https://msdn.microsoft.com/en-us/library/hh568454(v=sql.110).aspx), and the following error occurred:
`## msodbcsql : Depends: libc6 (>= 2.21) but 2.19-18+deb8u7 is to be installed`

However when I do:
`apt-get install libc6=2.21` 
or any higher versions, the error is always Version'2.xx' for 'libc6' was not found.

Could you please assist?

Thank you very much!

**Comment by eddelbuettel** [comment]
That pages cover Red Hat, Ubuntu and SuSE.  We are on Debian here.  I am afraid you will need to get help from Microsoft about how to use this on Debian.

@cboettig Per [this Debian libc6 package page](https://packages.debian.org/search?keywords=libc6) we are back on Debian stable if we run 2.19-18+deb8u7.  You know which may I lean about that :wink:

**Comment by eddelbuettel** [comment]
Once a *verse error filed at rocker (which is not where that code is). Will close.  Can you repo in the repo containing the Dockerfile you reference?
