### ISSUE TITLE
ubuntu xenial/yakkety images break apt-get

### ISSUE THREAD

**Issue by phlogisticfugu** [rocker-org/rocker#225]
We've been trying out the unofficial images inrocker/r-apt for Ubuntu 16.04 (xenial) and 16.10 (yakkety) and are running into problems where the ubuntu package repositories were deleted.

seems to be due to the last part of the Dockerfile's:
https://github.com/rocker-org/rocker/blob/master/r-apt/xenial/Dockerfile#L55
https://github.com/rocker-org/rocker/blob/master/r-apt/yakkety/Dockerfile#L55

**Comment by eddelbuettel** [comment]
Exactly what is you real or perceived problem?  I use these containers semi-regularly to check with r-cran-* packges are already in Michael's PPA and just fired one up this weekend.  You *always* need to start with `apt-get update` to get current cache information.

**Comment by cboettig** [comment]
Just a note that removing `/var/lib/apt/lists/*` is relatively standard practice in Dockerfiles, and should not create an issue as long as you are always running `apt-get update` in any Dockerfile layer which also calls `apt-get install`; which is [best practice anyhow](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#each-container-should-have-only-one-concern).  Can you verify that running `apt-get update` first avoids the problem you have been encountering?

I agree that it's not a lot of space you really save, and sometimes it is convenient to be able to launch an image and start apt-get installing stuff without having to apt-get update first, but it's also worth bearing in mind that the cached `apt/lists` might then be stale anyhow.    (Apologies if you're hitting a problem not solved by running `apt-get update`, and do provide more details in that case! hope this helps!)

**Comment by eddelbuettel** [comment]
(The funny bit is that I am the one often kvetching against the removal of those (typically stale) lists.)

**Comment by phlogisticfugu** [comment]
the problem I ran into was that I was making a new container using these as a base, and was trying to install packages via apt-get (but yes, without running apt-get update first) and getting errors.

Well, perhaps the different issue then is that this behavior is inconsistent between versions of ubuntu.  the `/var/lib/apt/lists/*` are removed for yakkity and xenial, but not for other versions.

**Comment by eddelbuettel** [comment]
I'll put that back to you then.  Run `apt-get update` and you will be in sync with the external resources you are trying to access.
