### ISSUE TITLE
tcl/tk dependency error 

### ISSUE THREAD

**Issue by rehans516** [rocker-org/rocker#229]
I am trying to run an R script through Docker build which contains the package RcmdrPlugin.Kmggplot2. Docker is not able to install the package as it throws an error related to tcl/tk dependencies that it cannot be downloaded. I have the tcl/tk support for the R that i am currently running on my linux machine. The following is the exact error that i get : 

`Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/usr/local/lib/R/library/tcltk/libs/tcltk.so':
  libtcl8.5.so: cannot open shared object file: No such file or directory
Error : package ‘tcltk’ could not be loaded`

**Comment by eddelbuettel** [comment]
Are you sure it is not a display issue?  The tcltk package, as I recall, requires a `$DISPLAY` so you may have to use in X11-forwarding mode.

**Comment by rehans516** [comment]
@eddelbuettel  i do not think it is a display issue because when i run the R script without Docker on linux then it's running fine but within docker as i try to build the Dockerfile it generates the error while loading RcmdrPlugin.Kmggplot package as it cannot fetch it's corresponding dependency "tcl/tk"

**Comment by eddelbuettel** [comment]
You are just repeating what you said, and I already believe you the first time.

Now, on Linux without Docker, do  `DISPLAY="" Rscript nameofthescript.R`.  That may fail with the same error, which _if you look closely_ is internal to initialisation of `libtcl8.5.so` as the later, I think, wants a DISPLAY.  

Witness:

```
edd@max:~$ docker run --rm -ti r-base /bin/bash
root@9771bd553440:/# echo $DISPLAY

root@9771bd553440:/# R --slave
library(tcltk)
Warning message:
no DISPLAY variable so Tk is not available 
```

**Comment by cboettig** [comment]
@rehans516 from the error message it looks like you may need to `apt-get update && apt-get -y install tcl8.5-dev tk8.5-dev` ?

**Comment by eddelbuettel** [comment]
@cboettig Maybe I am undercaffeniated but I don't think this holds. Look at the [package page at CRAN](https://cran.r-project.org/package=RcmdrPlugin.KMggplot2) -- the package is not a compiled one. 

It "just" wants to load tcltk and that "just" happens to require `$DISPLAY` (as my last message showed).  Do you have one of those 'x11 under Docker' tricks handy and could you try to do `library(tcltk)` with that?

**Comment by rehans516** [comment]
@cboettig i already installed the tcl/tk with the statement `apt-get  -y install tcl8.5-dev tk8.5-dev`. it is an issue of a $DISPLAY as the library requires a GUI to load. 
Although i still cannot figure out how to set up the environment at the time of building Dockerfile to overcome error  as most of the sources suggest setting DISPLAY and Xforwarding while executing Docker run. Don't want to go through the steps each time

**Comment by eddelbuettel** [comment]
>  i already installed the tcl/tk with the statement apt-get -y install tcl8.5-dev tk8.5-dev.

Also, the _run-time_ part is already present as a dependency of R and its tcltk package; the `-dev` part would only be needed if you compiled tcl or tk components from source.  Which CRAN packages (with one or two exceptions) don't do.

**Comment by eddelbuettel** [comment]
Ok, I gave that the Google one-minute (which I recently needed, and then failed at) finding [this page](http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/) and simple


```
$ docker run -ti --rm -e DISPLAY=${DISPLAY} -v /tmp/.X11-unix:/tmp/.X11-unix rocker/r-base

R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> x11()
> library(tcltk)
> 
```

This may be easier for me than it is for other folks as my host is Linux ... but no issue here.

**Comment by rehans516** [comment]
@eddelbuettel thanks for the detailed response. i ran the docker image that was created through "docker build" using the following statement but unfortunately it still generates the same error  :
 docker run -ti --rm \
>        -e DISPLAY=$DISPLAY \
>        -v /tmp/.X11-unix:/tmp/.X11-unix \
> 44589772e33b

**Comment by eddelbuettel** [comment]
My test wasn't good.  Docker started that way still doesn't seem to use x11.  But I still think that is your root cause, rather than dependencies.
