### ISSUE TITLE
Error occured while installing curl in container

### ISSUE THREAD

**Issue by rensoftoss** [rocker-org/rocker#230]
Hi,

Running the Dockerfile below on Docker Hub I bumped into the following issue:

> The following packages have unmet dependencies:
>  libcurl4-openssl-dev : Depends: libcurl3 (= 7.52.1-4) but 7.52.1-5 is to be installed
> 
> Unable to correct problems, you have held broken packages.
> Removing intermediate container 361968f9baef
> 
> The command '/bin/sh -c apt-get update 	&& apt-get install -y --no-install-recommends 		libcurl4-openssl-dev 		libssl-dev 		procps 	&& rm -rf /var/lib/apt/lists/* 	&& rm -rf /tmp/downloaded_packages/ /tmp/*.rds' returned a non-zero code: 100

Probably this issue comes from that debian:testing is used by r-base and the mentioned package is broken there currently.
However I could fix the issue with using the correct version (7.52.1-4) by the apt-get install for libcurl3,
I've just wanted to point out that maybe it would be more stable to inherit from a stable version of Debian, not from testing.

The Dockerfile looks as followed:

```
FROM r-base

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		libcurl4-openssl-dev \
		libssl-dev \
		procps \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /tmp/downloaded_packages/ /tmp/*.rds

# create an R user
ENV HOME /home/ruser

RUN useradd --create-home --home-dir $HOME ruser \
    && chown -R ruser:ruser $HOME

WORKDIR $HOME

ADD common/ common/
ADD models/ models/
ADD predict/ predict/

ADD packages.R packages.R
ADD libraries.R libraries.R

RUN Rscript packages.R

USER ruser

EXPOSE 8000

# set the command
ENTRYPOINT ["Rscript", "predict/PredictServer.R"]
```

**Comment by cboettig** [comment]
@rensoftoss Right, you probably want a `-t unstable` in your apt-get line to avoid this.

just a side note that you can already find rocker images based on debian stable over at https://github.com/rocker-org/rocker-versioned.  Of course there are advantages and disadvantages to building on stable.

**Comment by rensoftoss** [comment]
@cboettig That's great ! Thank you for your quick response. I think I'll try then with the versioned ones too.

**Comment by rensoftoss** [comment]
Thanks again ! Works perfectly with rocker/r-ver:latest
