### ISSUE TITLE
R-devel image not running compiled R

### ISSUE THREAD

**Issue by dandermotj** [rocker-org/rocker#236]
Hi, 

I just built r-devel and ran it. The container opened and ran (I think) the R binary from r-base. The current r-base I have on my machine is from R 3.3.3. When I run `docker run --rm -it r-base`:

```
R version 3.3.3 (2017-03-06) -- "Another Canoe"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```
Then when I run the newly built r-devel, `docker run --rm -it r-devel`:

```
R version 3.3.3 (2017-03-06) -- "Another Canoe"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

I suspect this is simply `CMD ["R"]` referring to the R installed in r-base, and not the newly compiled R version.

**Comment by eddelbuettel** [comment]
Look at `/usr/local/bin/RD` and old issues here.

**Comment by eddelbuettel** [comment]
Ie with freshly-pulled image I now get R-devel from three days ago:

```
edd@max:~$ docker run --rm -ti rocker/r-devel RD --version
R Under development (unstable) (2017-05-12 r72670) -- "Unsuffered Consequences"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.

edd@max:~$ 
```

**Comment by dandermotj** [comment]
Thanks Dirk for the swift reply. Sorry for missing that, should have worked that one out! I was blindly following the `docker run` command in the readme. Thanks for all your great work!

**Comment by eddelbuettel** [comment]
I acknowledge that this one is a wee bit confusing, but we once made the decision to have this as a superset of r-base with R-release as well.   Changing now may not be a good plan, so it sticks.

Once you know it's obvious :)
