### ISSUE TITLE
Persisting Package installs

### ISSUE THREAD

**Issue by schwab** [rocker-org/rocker#238]
Anyone know which folders need to be volumed so that r will persist the package installs across docker restarts?  I've getting a little frustrated re-installing the libraries everytime the docker server is rebooted ;)

**Comment by eddelbuettel** [comment]
Read up on Docker -- everything works in layers.  You can either derive from our Dockerfile(s) and build your own, or save the container you created, or just use `.libPaths()` pointing to a directory on your server.
