### ISSUE TITLE
Custom volumes for install directories

### ISSUE THREAD

**Issue by extrobe** [rocker-org/rocker#239]
Hi, first of all, if anything I say doesn't make sense, I apologise - I'm _very_ new to all of this!

I've used the rocker stack (specifically, rocker/tidyverse) to create a docker template to run on unRaid.

This works a charm, but have an issue with mapping directories to user volumes within the host unRaid environment.

I can _partially_ get around this;
I've mapped a host volume to **/home/rstudio** to save user created content - no real problems there

For user-installed packages, I've 'worked around' this by mapping a host volume to **/usr/local/lib/R/custom-library** and then ran `.libPaths( c( "/usr/local/lib/R/custom-library",.libPaths()) )` to add this as the default install location.

This does work, but not very clean, and doesn't take care of any user settings within RStudio.

From what I can gather from reading the rocker/r-ver dockerfile, whilst it creates the /R/site-library/ directory, it doesn't support this being mapped to a host path.

Is there a way to achieve this, or is there a chance to update the base docker file to support this?

Thanks!

ps - if it's of any interest, the xml file is [here](https://github.com/extrobe/un-r/blob/master/my-RStudio.xml) - but has some tidying up/finishing off to do still

**Comment by cboettig** [comment]
It would help if you could be more explicit about what you want to accomplish, conceptually. 

For instance, I really I don't think you want to be mapping directories from `.libPaths` into the host environment.  If you're overall objective is have packages you install persist across container removal/re-creation, we strongly suggest you look into saving your container (see `docker commit`) or writing a Dockerfile which adds the packages you need to an existing rocker image.  

The default user on rocker images is always a member of the `staff` group, which has read/write privileges to `$R_HOME/site-library`, which is where the images install their packages, is the default local lib, and is where we strongly suggest users install their packages to as well.  (If you're running rstudio with a multi-user environment, just add additional users to the `staff` group so they an install here). 

Okay, so hope this helps, sorry if I've misunderstood what you want to accomplish; feel free to clarify as needed.

**Comment by extrobe** [comment]
My apologies for not being very clear - but essentially you're right; I want to ensure changes I make to R Server (be it settings or adding packages) are persistent.

I'm not too familiar with saving the container - not sure if this is a setup unRaid supports. Most dockers created for unRaid will ask you to map a host volume for data / config locations.

A good example of this is perhaps the personal-storage cloud app [linuxserver/nextcloud](https://hub.docker.com/r/linuxserver/nextcloud/)
, where you provide a local host path for the /data folder (where your personal files will be saved), and a /config host path where the nextcloud config files would go.

I was looking to achieve something similar with Rserver, so any config changes and packages I add are essentially independent of the base docker image.

Again, sorry if I'm not making an awful lot of sense - still pretty new to this, and is just a little outside my experience/skill level, but enjoying trying to figure it out.

**Comment by eddelbuettel** [comment]
Closed this -- I am sure you get a chance to work this out as it is _an entirely generic Docker usage issue_ and there is by now enough documentation around on Docker so that Carl and I can step back from questions like this.  We quite frankly do not have the bandwidth to coach individual Docker users.  I hope you understand.
