### ISSUE TITLE
Avoid purging /var/lib/apt/lists/* after installation

### ISSUE THREAD

**Issue by krlmlr** [rocker-org/rocker#240]
`apt-get update` sometimes fails, see e.g. rocker-org/shiny#19. Maybe purging `/var/lib/apt/lists/*` ([code link](https://github.com/rocker-org/rocker/blob/324dae92a5e3623603615cbe1d51e375c24c466e/r-base/Dockerfile#L58)) is too aggressive (though this seems to originate from [Docker documentation](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run))?

The same documentation states that official Debian images don't really need the purging:

> Note: The official Debian and Ubuntu images [automatically run apt-get clean](https://github.com/moby/moby/blob/03e2923e42446dbb830c654d0eec323a0b4ef02a/contrib/mkimage/debootstrap#L82-L105), so explicit invocation is not required.

Would you be responsive of PRs that remove the manual purging of the apt cache?

**Comment by krlmlr** [comment]
To the contrary: Updating fails more reliably if the purge is done (it's currently not for the r-devel-ubsan-clang container).

**Comment by srinivasreddy42** [comment]
May I know the reason for closing this ticket? Is purging `/var/lib/apt/lists/*` still considered aggressive?

**Comment by krlmlr** [comment]
The relevant pull request has been merged.
