### ISSUE TITLE
R Docker Image Error

### ISSUE THREAD

**Issue by zsala** [rocker-org/rocker#241]
Hey everyone,

after I successfully create the docker image, I get the following error running the container:

"Fatal error: you must specify '--save', '--no-save' or '--vanilla'"

Cheers,
Laszlo

**Comment by eddelbuettel** [comment]
Sounds like a standard R user error.  See `man R` for the meaning of those options.

For what it is worth, it also does not happen with our contains.  So why did you think you needed to file a ticket here?

```bash
edd@max:~$ docker run --rm -ti r-base

R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> q()
Save workspace image? [y/n/c]: n
edd@max:~$ 
```

The `r-base` container is the same the basic `rocker` container, but relabeled as "official" for R.

**Comment by tioback** [comment]
No need for rudeness. Sometimes people might want to create their container based on something else.

Anyways, this type of error tends to happen when you forget to add an `ENTRYPOINT` to your Dockerfile.

Adding this usually helps:

    ENTRYPOINT ["sh", "-c"]
