### ISSUE TITLE
Permission to create folders

### ISSUE THREAD

**Issue by HeidiSeibold** [rocker-org/rocker#246]
How do I make sure that folders in /home/rstudio permit me to add subfolders?

A minimal example:

I run
`docker run --rm -p 8787:8787 rocker/verse:3.4.1`,
go to localhost:8787
and then do what is shown in the screenshot:

![image](https://user-images.githubusercontent.com/14146757/28166743-6a7cdbb8-67d9-11e7-8e05-194be7dfece7.png)

That means I can create a directory in /home/rstudio but not in /home/rstudio/kitematic.

For my own project I add folders and files, e.g. in the Dockerfile  have
`ADD analysis/simulation_all.R /home/rstudio/palmtree/analysis/`
but then want to allow `batchtools` to create a folder with the simulation results in /home/rstudio/palmtree/analysis/.

Any help would be very appreciated :)

**Comment by eddelbuettel** [comment]
@cboettig is more fluent on the userid options, we have something in the wiki about this too.

My go-to tool is the `-v $(pwd):/mnt` idiom.  I then just `cd /mnt` inside the container and create files as needed.  Note that if you do nothing else on the userid front, these will be root-owned.   As I mostly do this for testing (and treat `/mnt` as input to somewhat ephemeral test files) this does not matter,

**Comment by HeidiSeibold** [comment]
Maybe I should add a little info on what I want to use the container for:
I have a research project and I want people to be able to reproduce my simulation study. Since installation of all the right package version is tedious (also one of the packages is already archived) I want to provide a nice container that people can use (with all packages and R codes needed). For the simulation study I use batchtools, which creates a folder in the process.

So I am not sure if your suggestion helps with that problem.

**Comment by eddelbuettel** [comment]
Hm, I am not sure how that helps / is different.  You have a container.  It has content. Now you need to work out permissions.

Also, I think your application seems to replicate or at least overlap with [containerit](https://github.com/o2r-project/containerit).  Have you seen that?  I saw the useR! presentation, it is nice stuff.

**Comment by HeidiSeibold** [comment]
Thanks, that does look like a cool project. As I am in a bit of a rush and have basically everything else figured out, I think it is something to use for my next project... :woman_astronaut:

**Comment by nuest** [comment]
@HeidiSeibold looking forward to your feedback on `containerit` :-).

Until then, this section of the Wiki should help you: https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine#avoiding-permission-changes-when-sharing-volumes

Assuming you're on Linux, the following command should "match" your users inside and outside of the container (not tested yet, still pulling the image..):

```bash
docker run --rm -p 8787:8787 -e USERID=$UID -v$(pwd):/home$USER/foo rocker/verse:3.4.1
```

**Comment by eddelbuettel** [comment]
Thanks for acting as a virtual Carl ;-)

**Comment by HeidiSeibold** [comment]
Thanks guys! Seems to be working. You are saving my day!

Sorry for not reading the manual properly :see_no_evil:

**Comment by HeidiSeibold** [comment]
I only realised today that it actually still did not work.
Figured it out now though:

After adding a file to a folder, e.g.
`ADD analysis/simulation_all.R /home/rstudio/palmtree/analysis/`

add permissions for user rstudio to that folder
`RUN chown -R rstudio /home/rstudio/palmtree`

then I can simply use
`docker run --rm -p 8787:8787 heidiseibold/palmtree-project`

and everything works perfectly :)

**Comment by nuest** [comment]
@HeidiSeibold Can you post an error message on what did not work when mounting a folder?

Also, when you create directories in the container, I guess you know you can copy files to the host with `docker cp`?

**Comment by HeidiSeibold** [comment]
I still got permission denied in the folder where I wanted to create the batchtools folder as in the screenshot above.

**Comment by cboettig** [comment]
@HeidiSeibold not seeing a screenshot above. 

Sorry, can you give me a bit more context?  There's ~ 3 different strategies here, I use the first most:

- linking a local volume (on my computer) to the container, using `-v` (see below)


My usual strategy is to link a local volume for data:

```
docker run -d -p 8787:8787 -e PASSWORD=something -v /path/to/my/local/Documents:/home/rstudio/Documents  rocker/rstudio
```

That links the `/path/to/my/local/Documents` to the `/home/rstudio/Documents` directory on the rocker image.  Note on the image the user is called "rstudio", usually easiest to just leave it at that.  

Note that if your local user has a PID other than 1000 (on Linux) this can create permissions issues, you have to pass `USERID` as @nuest  shows:

```
docker run --rm -p 8787:8787 -e USERID=$UID -v$(pwd):/home/rstudio/foo rocker/verse:3.4.1
```

Note that I've corrected one small but important thing in the above example: the user is `rstudio` on the container instance, not `$USER`, (unless you also change that using `-e $USER:USER`).  


### Method 2

Much simpler but less flexible: pull all the local user data in by, e.g. checking out a Github project. Push back to github before closing down the docker instance. No need to mess around with `-v` volumes and ids.

### Method 3


Add files to a derivative Dockerfile first.  What you have above is absolutely the right way to do this:

```
ADD analysis/simulation_all.R /home/rstudio/palmtree/analysis/
RUN chown -R rstudio /home/rstudio/palmtree
```

**Comment by HeidiSeibold** [comment]
Method 3 was the solution for me, thanks. 

> I still got permission denied in the folder where I wanted to create the batchtools folder as in the screenshot above.

I meant my first post in this issue.

From my side everything is solved now (that is why I did not reopen the issue :smile:). Sorry if I caused confusion.
Thanks a lot for the great help! :cake:
