### ISSUE TITLE
shiny-r docker image rocker/shiny:latest gives root user warning 

### ISSUE THREAD

**Issue by simbo1905** [rocker-org/rocker#248]
Running with: 

docker run --rm -p 3838:3838 rocker/shiny

shows a warning: 

[2017-07-21 15:13:47.543] [WARN] shiny-server - Running as root unnecessarily is a security risk! You could be running more securely as non-root.
 
I want to deploy the image on OpenShift v3 Pro which has a security policy that doesn't allow the deployment of images that run as root. Images need a "USER xxxx" command in the Dockerfile to drop from root to be deployed on a public cloud that prohibits containers running as root. Also anyone using a private PaaS is also going to disable root usage so this image cannot be used on a lot of container engines until this is resolved.

**Comment by simbo1905** [comment]
My own template that simply drops to `USER shiny` doesn't give the warning: 

```
FROM rocker/shiny
USER shiny
CMD ["/usr/bin/shiny-server.sh"]

```

**Comment by simbo1905** [comment]
I have setup a build for that on hub.docker.com for folks to try out: 
https://hub.docker.com/r/simonmassey/shiny/

**Comment by eddelbuettel** [comment]
See the Rocker wiki -- you can set a user when you invoke the container. 

Your new Dockerfile pretty much does just that.  Two same ways of skinning the cat.

**Comment by paulrougieux** [comment]
You can set the `--user` option to `shiny` 

    docker run --rm --user shiny -p 3838:3838 rocker/shiny

The problem then is that shiny-server will complain about :

    Bookmark state directory creation failed: /var/lib/shiny-server/bookmarks

This is due to the fact that the shiny user doesn't have the right to create this directory in the container. It's possible to [use a docker entrypoint to change ownership of the bookmarks directory](https://stackoverflow.com/a/29799703/2641825) before running shiny-server. Another way to fix that may require the use of [user name spaces](https://docs.docker.com/engine/security/userns-remap/).

**Comment by cboettig** [comment]
now documented in shiny README.

**Comment by simbo1905** [comment]
And what happens if you aren’t using docker but a container orchestrator that uses one of the new alternatives (http://cri-o.io in Kubernetes makes docker optional and it won't be the default in future years). 

The correct approach is to set USER in the Dockerfile to use minimum privileges not to leave it as root and expect someone to read the wiki and set a none standard flag in a particular container runtime to be secure.
