### ISSUE TITLE
Inconsistency in MRAN snapshots in use case stacks depending on r-ver

### ISSUE THREAD

**Issue by nuest** [rocker-org/rocker#258]
I've just tried to explain the way that MRAN versions are fixed in the different versioned images. However, I find the following observations a bit confusing.

**No solutions yet**, just want to capture this before I finish work today and get your opinions. Maybe this is all a non-issue and I'm just not getting it.

## MRAN snapshot dates for `r-ver`

Let's take a look at the release dates of R first:

```
$ Rscript -e "require(rversions); tail(r_versions())"
Loading required package: rversions
    version                        date
100   3.3.0 2016-05-03T07:13:28.102867Z
101   3.3.1 2016-06-21T07:21:38.894907Z
102   3.3.2 2016-10-31T08:13:15.868949Z
103   3.3.3 2017-03-06T08:16:31.646592Z
104   3.4.0 2017-04-21T07:14:45.366247Z
105   3.4.1 2017-06-30T07:04:11.824142Z
```

What are the CRAN snapshots used in `r-ver` images?

```
$ docker run -it --rm rocker/r-ver:3.3.0 Rscript --quiet -e "getOption('repos')"
                                            CRAN 
"https://mran.microsoft.com/snapshot/2016-06-21" 

$ docker run -it --rm rocker/r-ver:3.3.1 Rscript --quiet -e "getOption('repos')"
                                            CRAN 
"https://mran.microsoft.com/snapshot/2016-10-31" 

$ docker run -it --rm rocker/r-ver:3.3.2 Rscript --quiet -e "getOption('repos')"
                       CRAN 
"https://cran.rstudio.com/" 

$ docker run -it --rm rocker/r-ver:3.3.3 Rscript --quiet -e "getOption('repos')"
                                            CRAN 
"https://mran.microsoft.com/snapshot/2017-03-24"

$ docker run -it --rm rocker/r-ver:3.4.0 Rscript --quiet -e "getOption('repos')"
                                            CRAN 
"https://mran.microsoft.com/snapshot/2017-05-08" 

$ docker run -it --rm rocker/r-ver:3.4.1 Rscript --quiet -e "getOption('repos')"
                                            CRAN 
"https://mran.microsoft.com/snapshot/2017-08-19"

$ docker run -it --rm rocker/r-ver:latest Rscript --quiet -e "getOption('repos')"
                       CRAN 
"https://cran.rstudio.com/" 
```

As to be expected, `latest` uses CRAN.

In `r-ver:3.4.1`, being the newest tagged version, the MRAN snapshot is just a few days old. Users should expect the snapshot to be updated until `r-ver:3.4.2` is released (Right? If so, I'd like to make a PR trying to explain this with a couple more examples in the README).

The snapshots for `3.3.0` and `3.3.1` are set to the release dates of the subsequent version. This _breaks_ for `3.3.2` which does not point to a snapshot, and for `3.3.3` and `3.4.0` the _dates are a bit off_.

## Snapshot dates for `verse`

```
$ docker run -it --rm rocker/verse:3.4.0 Rscript --quiet -e "getOption('repos')"
                                            CRAN 
"https://mran.microsoft.com/snapshot/2017-06-30" 

$ docker run -it --rm rocker/verse:3.3.3 Rscript --quiet -e "getOption('repos')"
                                            CRAN 
"https://mran.microsoft.com/snapshot/2017-04-21" 

$ docker run -it --rm rocker/verse:3.4.1 Rscript --quiet -e "getOption('repos')"
                       CRAN 
"https://cran.rstudio.com/" 

```

- Snapshots dates for `verse:3.3.3` is different from the one in `r-ver:3.3.3`. Could this be due to `verse` being build on a different day?
- `verse:3.4.1` does use CRAN, unlike `r-ver:3.4.1` on which it should be building.
- `verse:3.4.0` uses the correct snapshot date :tada:, i.e. the release date of `R 3.4.1` (unlike `r-ver:3.4.0`)

## Next steps

Maybe I should have done this from the start, but if it helps I can provide a script putting all data in a tibble for further analysis, and maybe even a little testthat suite checking the snapshot dates automatically, and across all the stacks. So far this is all manual testing.
@cboettig Do you think this is worth the effort?

**Comment by cboettig** [comment]
@nuest Thanks for taking a close look at this.  Looks like you have some stale `r-ver` images hanging around, make sure to run `docker pull` first.  I've added a [test script](https://github.com/rocker-org/rocker-versioned/blob/master/tests/test-versions.sh) (using a docker-compose file to make this simple) to illustrate:  

```
devel_1   |                        CRAN 
devel_1   | "https://cran.rstudio.com/" 
3.3.1_1   |                                             CRAN 
3.3.1_1   | "https://mran.microsoft.com/snapshot/2016-10-31" 
tests_devel_1 exited with code 0
tests_3.3.1_1 exited with code 0
latest_1  |                        CRAN 
latest_1  | "https://cran.rstudio.com/" 
3.4.1_1   |                                             CRAN 
3.4.1_1   | "https://mran.microsoft.com/snapshot/2017-08-19" 
3.3.2_1   |                                             CRAN 
3.3.2_1   | "https://mran.microsoft.com/snapshot/2017-03-06" 
3.4.0_1   |                                             CRAN 
3.4.0_1   | "https://mran.microsoft.com/snapshot/2017-06-30" 
3.3.0_1   |                                             CRAN 
3.3.0_1   | "https://mran.microsoft.com/snapshot/2016-06-21" 
3.3.3_1   |                                             CRAN 
3.3.3_1   | "https://mran.microsoft.com/snapshot/2017-04-21" 
```

looks like dates are as expected, yes?  

Haven't checked verse, but it would be easy to modify.   Since building all versions of the whole stack can take over a day on Docker-hub, it is possible for the `verse` versions to lag behind the `r-ver` versions at some points in time by a day or so.   

Prior to the fancy push hooks, the most recent tagged release (e.g. `3.4.1`) would have lagged by up to a month from the current date, since it was locked to MRAN and rebuilt only monthly.  I'm not actually sure what happens now with the tags, I kinda expected it would become (bitwise) identical to `latest` (and thus not use MRAN, which I guess is a bit unfortunate).

**Comment by nuest** [comment]
@cboettig Yes, the error was on my side. Good idea to test this with a compose configuration!

Re `3.4.1` being identical to `latest`: These are currently build with two configurations, the latter being based on the Dockerfile at `r-ver/Dockerfile`. The post_push hook would be able to tag the former `latest`, without using the Dockerfile at `r-ver/Dockerfile`. But then then `latest` would be fixed to an MRAN checkpoint, which afaics was not desired.

**Comment by cboettig** [comment]
Thanks, glad to confirm.  

Yup, right, that's the desired behavior for latest, so that makes perfect sense.  Looks like we're all set, though maybe tags should be documented in README.
