### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [rocker-org/rocker#259]
I build r-base/Dockerfile on arm64 and successed ,So I want to know that this image whether or not support arm64

**Comment by eddelbuettel** [comment]
I think it should just work as it is based on Debian packages which are being built for a large number of different architectures including arm64.

**Comment by longquan7** [comment]
@eddelbuettel There is a plan add this image to support arm64 ?

**Comment by eddelbuettel** [comment]
Just build it locally.  

Last time I checked the Docker build services did Intel architecture only.  Did I miss something?

**Comment by longquan7** [comment]
See https://github.com/docker-library/official-images#architectures-other-than-amd64 and https://github.com/docker-library/official-images#multiple-architectures for more information about multi-architecture official images. :+1:

**Comment by longquan7** [comment]
root@ubuntu:~/arm64pr/rocker/r-base# docker build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy -t r-base/arm64 .                           Sending build context to Docker daemon 11.26 kB
Step 1 : FROM arm64v8/debian:testing
 ---> 335b018db811
Step 2 : MAINTAINER "Carl Boettiger and Dirk Eddelbuettel" rocker-maintainers@eddelbuettel.com
 ---> Using cache
 ---> 88870f022557
Step 3 : RUN useradd docker     && mkdir /home/docker   && chown docker:docker /home/docker     && addgroup docker staff
 ---> Using cache
 ---> ad51f1694ffc
Step 4 : RUN apt-get update     && apt-get install -y --no-install-recommends           ed              less            locales                 vim-tiny             wget             ca-certificates                 fonts-texgyre   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> eb8991e2d52c
Step 5 : RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen        && locale-gen en_US.utf8        && /usr/sbin/update-locale LANG=en_US.UTF-8
 ---> Using cache
 ---> 88c11a51350e
Step 6 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> ece95b6ba5b5
Step 7 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 083a3c61ef0b
Step 8 : RUN echo "deb http://http.debian.net/debian sid main" > /etc/apt/sources.list.d/debian-unstable.list   && echo 'APT::Default-Release "testing";' > /etc/apt/apt.conf.d/default
 ---> Using cache
 ---> 233083f3e69c
Step 9 : ENV R_BASE_VERSION 3.4.1
 ---> Using cache
 ---> c0a2fb142b36
Step 10 : RUN apt-get update    && apt-get install -t unstable -y --no-install-recommends               littler                 r-cran-littler          r-base=${R_BASE_VERSION}*             r-base-dev=${R_BASE_VERSION}*           r-recommended=${R_BASE_VERSION}*         && echo 'options(repos = c(CRAN = "https://cran.rstudio.com/"), download.file.method = "libcurl")' >> /etc/R/Rprofile.site         && echo 'source("/etc/R/Rprofile.site")' >> /etc/littler.r        && ln -s /usr/share/doc/littler/examples/install.r /usr/local/bin/install.r   && ln -s /usr/share/doc/littler/examples/install2.r /usr/local/bin/install2.r   && ln -s /usr/share/doc/littler/examples/installGithub.r /usr/local/bin/installGithub.r       && ln -s /usr/share/doc/littler/examples/testInstalled.r /usr/local/bin/testInstalled.r         && install.r docopt   && rm -rf /tmp/downloaded_packages/ /tmp/*.rds  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 850adc9cb670
Step 11 : CMD R
 ---> Using cache
 ---> 3d8dd0d6f8c9
Successfully built 3d8dd0d6f8c9
root@ubuntu:~/arm64pr/rocker/r-base#

**Comment by longquan7** [comment]
Sending build context to Docker daemon 11.26 kB
Step 1 : FROM arm64v8/debian:testing
 ---> 335b018db811
Step 2 : MAINTAINER "Carl Boettiger and Dirk Eddelbuettel" rocker-maintainers@eddelbuettel.com
 ---> Using cache
 ---> 88870f022557
Step 3 : RUN useradd docker     && mkdir /home/docker   && chown docker:docker /home/docker     && addgroup docker staff
 ---> Using cache
 ---> ad51f1694ffc
Step 4 : RUN apt-get update     && apt-get install -y --no-install-recommends           ed              less            locales                 vim-tiny             wget             ca-certificates                 fonts-texgyre   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> eb8991e2d52c
Step 5 : RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen        && locale-gen en_US.utf8        && /usr/sbin/update-locale LANG=en_US.UTF-8
 ---> Using cache
 ---> 88c11a51350e
Step 6 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> ece95b6ba5b5
Step 7 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 083a3c61ef0b
Step 8 : RUN echo "deb http://http.debian.net/debian sid main" > /etc/apt/sources.list.d/debian-unstable.list   && echo 'APT::Default-Release "testing";' > /etc/apt/apt.conf.d/default
 ---> Using cache
 ---> 233083f3e69c
Step 9 : ENV R_BASE_VERSION 3.4.1
 ---> Using cache
 ---> c0a2fb142b36
Step 10 : RUN apt-get update    && apt-get install -t unstable -y --no-install-recommends               littler                 r-cran-littler          r-base=${R_BASE_VERSION}*             r-base-dev=${R_BASE_VERSION}*           r-recommended=${R_BASE_VERSION}*         && echo 'options(repos = c(CRAN = "https://cran.rstudio.com/"), download.file.method = "libcurl")' >> /etc/R/Rprofile.site         && echo 'source("/etc/R/Rprofile.site")' >> /etc/littler.r        && ln -s /usr/share/doc/littler/examples/install.r /usr/local/bin/install.r   && ln -s /usr/share/doc/littler/examples/install2.r /usr/local/bin/install2.r   && ln -s /usr/share/doc/littler/examples/installGithub.r /usr/local/bin/installGithub.r       && ln -s /usr/share/doc/littler/examples/testInstalled.r /usr/local/bin/testInstalled.r         && install.r docopt   && rm -rf /tmp/downloaded_packages/ /tmp/*.rds  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 850adc9cb670
Step 11 : CMD R
 ---> Using cache
 ---> 3d8dd0d6f8c9
Successfully built 3d8dd0d6f8c9

**Comment by cboettig** [comment]
Duplicated in #294, closing this one as discussion has moved to there.
