### ISSUE TITLE
rocker/rstudio throws errors at notebooks on shared folder

### ISSUE THREAD

**Issue by AlfonsoRReyes** [rocker-org/rocker#260]
Hello,
after creating a R project in a rocker/rstudio container there are errors generated when a notebook is run on a shared folder. The error  is:

`[rsession-rstudio] ERROR system error 1 (Operation not permitted); OCCURRED AT: rstudio::core::Error rstudio::core::{anonymous}::writeLockFile(const rstudio::core::FilePath&) /home/ubuntu/rstudio/src/cpp/core/file_lock/LinkBasedFileLock.cpp:224`

The steps to reproduce this are as follows:

1. Run a rocker/rstudio container with a shared folder with:
`docker run -d -p 8787:8787 -v ~/anyfolder:/home/rstudio/local rocker/rstudio`

Note: it makes no difference using `/c/Users/user` or `//c/Users/user ` as per fix in the wiki.

2. Open a browser with an RStudio session. It could be Chrome or Firefox.

3. Create a project on the host shared folder `/home/rstudio/local`. It will be created ok.

4. Add a notebook under the new project. Save it.

5. Run the notebook. It will trow errors related to file lock at LinkBasedFileLock.cpp:224.

**Observations**

* if the project and notebook are created on the native Linux system, it run with no errors.
* if a new user is added, same errors are generated.

**Comment by cboettig** [comment]
@AlfonsoRReyes thanks for the report, yes, have seen this on shared directories with host before; and think it might be related to whatever is causing issue https://github.com/rocker-org/rocker-versioned/issues/48 as well.  

I think this is essentially an RStudio issue; I'm not sure where it's gotten the idea to look in `/home/ubuntu` since that path doesn't exist in a Rocker container (you'll see the same path in the linked error above), but I'm not sure what is causing it; would probably need someone on their dev team who knows the relevant internals.

**Comment by AlfonsoRReyes** [comment]
Also tried with R 3.3.3 and RStudio 1.0.143 and get this:

`19 Sep 2017 20:03:33 [rsession-rstudio] ERROR system error 1 (Operation not permitted); OCCURRED AT: rstudio::core::Error rstudio::core::{anonymous}::writeLockFile(const rstudio::core::FilePath&) /home/ubuntu/rstudio/src/cpp/core/file_lock/LinkBasedFileLock.cpp:224;`

Same error.

**Comment by AlfonsoRReyes** [comment]
The only docker container that accepts shared local folders to save and run R projects and notebooks is opencpu/rstudio. The only thing I don't like is that runs an Apache server as well.

**Comment by cboettig** [comment]
Hi @AlfonsoRReyes Looks like you are on a Windows platform, yes?  Please note that the information we [request](https://github.com/rocker-org/rocker/blob/master/CONTRIBUTING.md) for any issue really is helpful to us in addressing your issues, the above steps do not replicate the error for me on Mac or Linux platforms. 

However, we do see other errors related to the `LinkBasedFileLock.cpp` show up in the console from time to time when working with shared directories.  Note that this "Error" just pertains to RStudio's mechanism for locking files that are being edited, though an error appears in your console, it is not actually a sign that anything else is not working and RStudio should work entirely as expected other then the presence of these messages in the console.  

In any event, I've pushed a patch to `rocker/rstudio:latest` that should avoid these errors by switching RStudio's behavior to use a more robust file-lock protocol.  It should build on the hub shortly, so please try to pull `rocker/rstudio:latest` again and let us know if it resolves the issue you are seeing.

**Comment by AlfonsoRReyes** [comment]
@cboettig Yes. It is Windows. Windows 10 specifically.

**Comment by AlfonsoRReyes** [comment]
@cboettig I am trying in Linux as well and getting a different problem.
This is the line I am running:

`docker run -d -p 8787:8787 -v ~/deep-004:/home/rstudio/kitematic  rocker/rstudio`

The folder `~/deep-004` in the Ubuntu host automatically gets ownership `root` and cannot create any folder; much less a R project. 

How does it look the docker command you are passing to run the container in a Linux host?

**Comment by cboettig** [comment]
I'm guessing that your user on the Ubuntu host does not have UID = 1000.  see https://www.rocker-project.org/use/#managing-users ?

**Comment by AlfonsoRReyes** [comment]
![image](https://user-images.githubusercontent.com/19330646/30616888-6bf3719a-9d59-11e7-8fac-29a0ce84a049.png)

**Comment by AlfonsoRReyes** [comment]
This line, of course, will not run RStudio in Ubuntu:
`docker run -d -p 8787:8787 -v $(pwd)/deep-007:/home/rstudio --user rstudio rocker/rstudio`. It refuses to start the container.

And this one either:
`docker run -d -p 8787:8787 -v ~/deep-008:/home/rstudio -e USER=rstudio  rocker/rstudio`

![image](https://user-images.githubusercontent.com/19330646/30617373-6284461e-9d5b-11e7-8da2-29f9ccd30dda.png)

**Comment by cboettig** [comment]
> This line, of course, will not run RStudio in Ubuntu:
> docker run -d -p 8787:8787 -v $(pwd)/deep-007:/home/rstudio --user rstudio rocker/rstudio. It refuses to start the container.

Correct, as we document, you cannot run rstudio with `--user`; it needs root to launch RStudio. (That has nothing to do with being on Ubuntu).  However, thie line

> docker run -d -p 8787:8787 -v ~/deep-008:/home/rstudio -e USER=rstudio rocker/rstudio

should run just fine.  It appears you are running Ubuntu inside virtualbox, which can certainly introduce any number of additional possible problems in how you are handling ports or forwarding volumes that you would be best consulting the general Docker and Virtualbox documentation sources for, none of these are Rocker-specific issues.  

Do see if the revised RStudio instance avoids the error message you referred to in the title issue.

**Comment by AlfonsoRReyes** [comment]
OK. I will trya pull of rocker/rstudio and later let you know.
Thanks a lot.

**Comment by AlfonsoRReyes** [comment]
Yeap. It works!
Now I can create R projects and notebooks in a Windows shared folder.
I will play with it a little bit more.

You are awesome sir.



![image](https://user-images.githubusercontent.com/19330646/30619251-1c8ce180-9d64-11e7-9b91-cd3f90eac0b4.png)

![image](https://user-images.githubusercontent.com/19330646/30619297-4a9f887a-9d64-11e7-8150-8c71c00a85fc.png)

![image](https://user-images.githubusercontent.com/19330646/30619341-851117a8-9d64-11e7-95ff-567a5d2d91f7.png)

![image](https://user-images.githubusercontent.com/19330646/30619319-5e37da04-9d64-11e7-96b4-25a217efb5fb.png)

**Comment by cboettig** [comment]
Nice, thanks for confirming.  I'll close this one out but ping this thread if the shared folder thing still isn't working on nicely on Windows 10.
