### ISSUE TITLE
Latest 3.4.2 update breaks r-api-3

### ISSUE THREAD

**Issue by majoras-masque** [rocker-org/rocker#264]
After the recent upgrade, our Docker builds are failing due to r-api-3 not being included in the r-base-core. Seeing the following error: 
```
The following packages have unmet dependencies:
 r-cran-rodbc : Depends: r-api-3
E: Unable to correct problems, you have held broken packages.
```

Please see our Dockerfile below:
```
FROM r-base
WORKDIR /usr/local/src/myscripts

## Run updates
RUN apt-get update

## Get rJava
RUN apt-get -y install default-jre \
  && apt-get -y install default-jdk \
  && R CMD javareconf \
  && touch installrJava.R \
  && echo "install.packages(\"rJava\")" > installrJava.R \
  && Rscript installrJava.R \
  && rm installrJava.R \

## Get RODBC
  && apt-get -y install unixodbc-dev \
  && apt-get -y install r-cran-rodbc \

## Install ROCR
  && apt-get -y install r-cran-rocr \

## Install pROC
  && touch installpROC.R \
  && echo "install.packages(\"pROC\")" > installProc.R \
  && Rscript installProc.R \
  && rm installProc.R \

## Install data.table
  && touch installdatatable.R \
  && echo "install.packages(\"data.table\")" > installdatatable.R \
  && Rscript installdatatable.R \
  && rm installdatatable.R \

## Install plyr
  && touch installplyr.R \
  && echo "install.packages(\"plyr\")" > installplyr.R \
  && Rscript installplyr.R \
  && rm installplyr.R \

## Install dtplyr
  && touch installdtplyr.R \
  && echo "install.packages(\"dtplyr\")" > installdtplyr.R \
  && Rscript installdtplyr.R \
  && rm installdtplyr.R \

## Install readr
  && touch installreadr.R \
  && echo "install.packages(\"readr\")" > installreadr.R \
  && Rscript installreadr.R \
  && rm installreadr.R \

## Install lubridate
  && touch installlubridate.R \
  && echo "install.packages(\"lubridate\")" > installlubridate.R \
  && Rscript installlubridate.R \
  && rm installlubridate.R \

## Install glmnet
  && touch installglmnet.R \
  && echo "install.packages(\"glmnet\")" > installglmnet.R \
  && Rscript installglmnet.R \
  && rm installglmnet.R \

## Install xlsx
  && touch installopenxlsx.R \
  && echo "install.packages(\"openxlsx\", dependencies=TRUE)" > installopenxlsx.R \
  && Rscript installopenxlsx.R \
  && rm installopenxlsx.R \

## Install magrittr
  && touch installmagrittr.R \
  && echo "install.packages(\"magrittr\")" > installmagrittr.R \
  && Rscript installmagrittr.R \
  && rm installmagrittr.R \

## Install Boruta
  && touch installBoruta.R \
  && echo "install.packages(\"Boruta\")" > installBoruta.R \
  && Rscript installBoruta.R \
  && rm installBoruta.R \

## Install PresenceAbsence
  && touch installPresenceAbsence.R \
  && echo "install.packages(\"PresenceAbsence\")" > installPresenceAbsence.R \
  && Rscript installPresenceAbsence.R \
  && rm installPresenceAbsence.R \

## Install rpart
  && touch installrpart.R \
  && echo "install.packages(\"rpart\")" > installrpart.R \
  && Rscript installrpart.R \
  && rm installrpart.R \

## Install FreeTDS
  && apt-get install unixodbc unixodbc-dev freetds-dev freetds-bin tdsodbc

## Run your code
CMD ["Rscript", "main.R"]
```

From everything I've found online, it seems we need to install r-base-core to get r-api-3, however the initial r-base should be covering that.

**Comment by eddelbuettel** [comment]
I am deeply aware of the issue as I was the very Debian maintainer whose hand was forced in order to introducde r-api-3.4 for a change which I myself don't happen to consider an API change.

This is managed in Debian here [at this tracker](https://release.debian.org/transitions/html/r-base-3.4.html) and seems to be progressing reasonably.  You will need to either wait for your missing package, or (worst case) provide them locally.   But `r-api-3.4` it is now.

**Comment by eddelbuettel** [comment]
And if you check the tracker (make sure you "click" on good packages) you will see that `r-cran-rodbc` has been rebuilt everywhere.  For now, just fetch it from unstable.

**Comment by cboettig** [comment]
@majoras-masque Unrelated, but in case it's helpful: you have an unnecessarily verbose pattern for installing individual packages.    `install2.r rpart PresenceAbsence Boruta ...` should do the same thing as the above.

**Comment by majoras-masque** [comment]
@cboettig - Yah... the above Dockerfile could easily remove like 80% of it's lines lol It's verbose like that because the developers I'm helping w/this are data-scientists with little-to-no dev experience: trying to make it nice and easy for them to read/understand so they feel comfortable taking this over. I've already overwhelmed them with information I think as none of them have worked in unix or vm's let alone containers. :(

@eddelbuettel - I'm not familiar with the R language at all, was just asked to help provide a Jenkins pipeline for our data-science team. From your response + that tracker, it seems the issue lies in the compatibility between r-core 3.4.2 and Debian, is that correct? Are there any strait-forward version changes I could add/change/force to our Dockerfile to allow our images to build until the r-api-3.4 transition is complete? Thanks for your help guys, really really appreciate it!
