### ISSUE TITLE
Use RStudio Server 1.1.383

### ISSUE THREAD

**Issue by SommerEngineering** [rocker-org/rocker#265]
It would be great to upgrade to RStudio Server 1.1.xxx (right now, 1.1.383). Would like to use the new features as the terminal tab on server side.

**Comment by cboettig** [comment]
Which rocker image are you using? Are you sure you have run `docker pull` recently to make sure you are testing the most recent build of the image?

The `rocker/rstudio` image automatically installs the latest version of RStudio, and `latest` (and `devel`) tags in the whole [rocker-versioned](https://github.com/rocker-org/rocker-versioned) are built nightly, so you should be seeing 1.1.383 now.  

(Sometimes it takes an extra day or so to propagate through the stack if any of the hub builds hit a hiccup; there system has been overloaded recently, so even though 1.1.383 release was 10/09, it may have been not until late yesterday this made it through verse).I see 1.1.383 on those images now.   

Thanks for filing the issue, always reassuring to hear that users are on top of these things!

**Comment by SommerEngineering** [comment]
Thanks for your fast response. I will re-deploy and check my containers :) I will come back and close the issue.

**Comment by SommerEngineering** [comment]
Thanks @cboettig -- it works fine.
