### ISSUE TITLE
contribution: using texlive tlmgr instead of installing texlive-latex-extra and texlive-fonts-extra

### ISSUE THREAD

**Issue by kforner** [rocker-org/rocker#266]
For what it is worth, I wanted to share my LaTex config...

In the process of reducing the size of our R docker in Quartz Bio, I identified TexLive and especially the .deb **texlive-fonts-extra** and **texlive-latex-extra** as space-hungry packages.

So I decided to use directly TexLive tlmgr to install the needed LaTeX packages.
We heavily use Rmd/Rnw rmarkdown/knitr for our reports and until now it has worked for our needs for years:

Here's my current working related Dockerfile script:
```
##### TEX related ########
# N.B: texlive-base may prompt a question about default paper size for applications
# setting DEBIAN_FRONTEND=noninteractive  force a default choice
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  dvipng \
  ghostscript \
  texinfo \
  texlive-base \
  texlive-extra-utils \
  texlive-fonts-recommended \
  texlive-generic-recommended \
  texlive-latex-base \
  texlive-latex-recommended

## extra fonts (uarial...)
RUN curl -OL http://www.tug.org/fonts/getnonfreefonts/install-getnonfreefonts && \
  texlua ./install-getnonfreefonts && \
  rm -f install-getnonfreefonts && getnonfreefonts --sys arial-urw

## attempt at using custom texlive
RUN apt-get install -y --no-install-recommends lmodern xzdec
# fix tlmgr which does not has correct exit status
RUN tlmgr init-usertree --usertree /usr/local/share/texmf/; true

RUN tlmgr --usertree /usr/local/share/texmf/ install \
      acronym background bigfoot blindtext cleveref enumitem etoolbox everypage \
      floatrow framed \
      inconsolata pgf multirow preprint soul titling xstring && \
    texhash && updmap-sys
```

Unfortunately, it was a while ago and I forgot how much space it saves.

**Comment by eddelbuettel** [comment]
I am also a little stunned as to just how effing massive these TeXlive packages are.  Then again, they provide a lot of goodies and we tend to use more and more fonts and things.

So for Rocker, I think the default is still sensible.  Worse if someone wants a rich TeX environment.

Now, for local deployment and tailoring, what you suggest is fine.   Another thing to keep in mind is whether the Docker Hub (or whatever they call it now) allows you / others to distribute things with restrictions.  "nonfreefonts" suggests there are things requiring a closer look.   Relying on Debian (or CRAN) tends to make matters easier for us.  Which matters to us ;-)

**Comment by kforner** [comment]
> Another thing to keep in mind is whether the Docker Hub (or whatever they call it now) allows you / others to distribute things with restrictions. "nonfreefonts" suggests there are things requiring a closer look. 

My bad: I just pasted my whole setup, but the non-free fonts part is completely independent. I mean they are not provided by texlive-fonts-extra and texlive-latex-extra, and you can remove these lines from the script:
```
## extra fonts (uarial...)
RUN curl -OL http://www.tug.org/fonts/getnonfreefonts/install-getnonfreefonts && \
  texlua ./install-getnonfreefonts && \
  rm -f install-getnonfreefonts && getnonfreefonts --sys arial-urw
```

**Comment by eddelbuettel** [comment]
Just read the README over there, may actually the opposite case (restriction is simply "don't charge money" which is a restriction on use in the Debian non-free sense).

And for what it is worth, you can edit posts here so you could remove this yourself.   But I suggest you keep it.  It's informative :)

**Comment by kforner** [comment]
> Just read the README over there, may actually the opposite case (restriction is simply "don't charge money" which is a restriction on use in the Debian non-free sense).

As you said, you probably can not include them in a distribution, like a _public_ docker.

> And for what it is worth, you can edit posts here so you could remove this yourself. But I suggest you keep it. It's informative :)

ok.

**Comment by cboettig** [comment]
(doing some cleanup on stale issues here, don't mind the dust broom!) Looks like this is largely resolved.  As a note, `rocker/verse` now uses `tlmgr`, via  Yihui's  `tinytex` package, to help users add in additional tex stylesheets etc that way.

**Comment by kforner** [comment]
sure, thanks.

**Comment by MichaelChirico** [comment]
@cboettig just happened on this issue while looking to shrink my GitLab CI build...

Was looking around for `tlmgr` and can't seem to see it in the code, maybe I'm missing something? If there's been another shift away from that as well would be nice to see the evolution. Only thing `TeX`-related I see in `r-base` is `fonts-texgyre` but that is not enough to satisfy `texi2dvi`.

**Comment by cboettig** [comment]
@MichaelChirico `tlmgr` is added via the scripts of the `tinytex` R package to `rocker/verse` https://github.com/rocker-org/rocker-versioned/blob/master/verse/Dockerfile, which saves a little space relative to the texlive meta packages and integrates nicely with rmarkdown to automatically call tlmgr.  (Note `verse` builds on `r-ver` not `r-base`). HTH

**Comment by MichaelChirico** [comment]
thanks for the link!
