### ISSUE TITLE
Yet another openBlas question

### ISSUE THREAD

**Issue by kforner** [rocker-org/rocker#267]
**Context**
I've become aware of **openBlas** after updating our home docker, when some tests failed, and one colleague told me that some code parallelized with parallel::mclapply was acting weirdly. 
The cause was openBlas being used in a rocker (actually a BioConductor rocker-based) docker.
It seemed that there are some edge cases on which the implementations differ (from https://cran.r-project.org/doc/manuals/r-release/R-admin.html#BLAS:

> External BLAS implementations often make less use of extended-precision floating-point registers and will almost certainly re-order computations. This can result in less accuracy than using the internal BLAS, and may result in different solutions, e.g. different signs in SVD and eigendecompositions.
)

At the time, I rebuilt everything from scratch without openBlas and forgot about it

Now I'm considering updating my docker build process, and I've looked again at the different rocker images that you guys kindly provide.
As others did, I noticed that:

  -  **r-base** and **r-devel** use the _netlib_ Blas, as provided by the libblas-dev debian package. 
  -  **r-ver** (and hence **rstudio**), use openBLAS, as provided by the libopenblas-dev.

**Correct Implementation ?**

I suppose there is no definitive choice for the Blas implementation to use. But as mentioned by Dirk in https://cran.r-project.org/web/packages/gcbd/vignettes/gcbd.pd, it is possible to switch implementations:

> That last feature is key here:  it offers us the ability to use different BLAS implementations
> in a ‘plug and play’ mode which facilitates comparisons.  So because of both the standardised
> interface of the BLAS, and the fact that we have several alternative implementations at our
> disposal, we can switch between these alternatives.

So to test this idea, and also based on that post: https://www.r-bloggers.com/for-faster-r-use-openblas-instead-better-than-atlas-trivial-to-switch-to-on-ubuntu/, I tried to switch between Blas implementations in **r-dev**:
```
%docker run -ti  rocker/r-devel:latest bash
# install lsof to test the actual Blast that R uses
apt-get update && apt-get install lsof
# check that R uses libblas
R -q -e "grep('blas', system2('lsof', c('-p', Sys.getpid()), stdout=TRUE), value = TRUE)"
> grep('blas', system2('lsof', c('-p', Sys.getpid()), stdout=TRUE), value = TRUE)
[1] "R       419 root  mem       REG   0,63   445768    4281 /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1"
# install Debian openBlas
apt-get install libopenblas-base
# check that now R has switched to openBlas
R -q -e "grep('blas', system2('lsof', c('-p', Sys.getpid()), stdout=TRUE), value = TRUE)"
> grep('blas', system2('lsof', c('-p', Sys.getpid()), stdout=TRUE), value = TRUE)
[1] "R       465 root  mem       REG   0,63  6903688    4417 /usr/lib/x86_64-linux-gnu/openblas/liblapack.so.3"
[2] "R       465 root  mem       REG   0,63 34213352    4414 /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so"
[3] "R       465 root  mem       REG   0,63   370904    4416 /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3"  

# revert to libblas
update-alternatives --set libblas.so.3-x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/blas/libblas.so.3
update-alternatives --set liblapack.so.3-x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3
# check that R has switched back to  R Blas
R -q -e "grep('blas', system2('lsof', c('-p', Sys.getpid()), stdout=TRUE), value = TRUE)"
> grep('blas', system2('lsof', c('-p', Sys.getpid()), stdout=TRUE), value = TRUE)
[1] "R       510 root  mem       REG   0,63   445768    4281 /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1"
```
I also checked using the a Blas benchmark that each of these Blas were functional.

## At last my point

Using these assumptions (please correct me if I'm wrong):

  - in r-ver, R is compiled with openBlas, but not in the "shared Blas" setting, i.e. without the internal R Blas, and it is not possible to switch back to another implementation
  - there should be no difference between using openBlas as it is currently in r-ver, and openBlas in a shared Blas setting.
  - it can be useful to switch to another Blas implementation, such as R Blas, for example to troubleshoot a problem, being able to tell if it is related to Blas

wouldn't it be nice if:
  - all rocker/* dockers were able to easily switch between liblas and openBlas, using a simple script, e.g. _switch_r_to_openblas_
  - all rocker/* default to the same implementation ? 

P.S
From this post: http://sites.psu.edu/theubunturblog/2013/08/13/multi-threaded-openblas-backported-to-recent-ubuntu-releases/, it seems that at one point some openBlas were not multithreaded, but if I understood there are alternative repositories.

@eddelbuettel It seems that openBlas was not tested in https://cran.r-project.org/web/packages/gcbd/vignettes/gcbd.pdf (or I missed it), is there a particular reason ? thanks.

**Comment by eddelbuettel** [comment]
> is there a particular reason ?

It didn't exist at the time.  It is the successor to GOTO Blas.

**Comment by kforner** [comment]
> It didn't exist at the time. It is the successor to GOTO Blas.

good to know. thanks.

**Comment by cboettig** [comment]
@kforner Thanks for your attention to these issues.  As you know, Dirk's the blas expert so I generally defer to him.  

Big-picture wise, images in the base stack r-base, r-devel, etc do the standard things (like default to R's BLAS) and leave it to the user to customize however they see fit.  The r-ver stack is more of a 'batteries included' approach that feeds into a linear stack (rstudio, tidyverse, verse, geospatial etc) with the emphasis on expecting more minimal config from the user and doing the same thing every time.  Given these different use cases I'm not sure it makes sense to standardize the blas across all `rocker/*` images.

That said, it sounds like there would be  no harm to adjusting the build recipe in r-ver to include support for shared BLAS there; it's just not in my area of expertise so I didn't build that in.  I'd welcome a PR that supported that as option!

**Comment by eddelbuettel** [comment]
The `r-base-core` package has "always" used that shared library approach, that is what permits the switching.  And as Karl found, via update-alternatives you get both default settings that work (ie: if you install openblas on Debian / Ubuntu it will be used) as well as local tweak (eg if you want to bother with MKL).  

And IIRC when we build from source we may rely on R's internal BLAS.

**Comment by kforner** [comment]
> That said, it sounds like there would be no harm to adjusting the build recipe in r-ver to include support for shared BLAS there; it's just not in my area of expertise so I didn't build that in. I'd welcome a PR that supported that as option!

@cboettig so would you still want a PR for r-ver ?

**Comment by cboettig** [comment]
yup, if you think it would be useful, PR away

**Comment by kforner** [comment]
**Erratum**: 
r-base and r-dev use the libblas (netlib?) implementation, not the internal RBlas one.
Should I correct my misleading post ? 

P.S
The internal RBlas and the libblas are probably related, since they have vert similar benchmark results.

**Comment by eddelbuettel** [comment]
> Should I correct my misleading post ?

Sure

> The internal RBlas and the libblas are probably related

Unoptimized reference blas, which the Debian package skips because there is not point in duplicating code.  Plus, in order to be able to _switch between blas_ you need the external interface.

**Comment by kforner** [comment]
> Unoptimized reference blas, which the Debian package skips because there is not point in duplicating code. Plus, in order to be able to switch between blas you need the external interface.

ok ok, that's why. Thanks.

**Comment by eddelbuettel** [comment]
I should clarify: "skips using the code shipped with R because a) we already have it and b) if we did, you couldn't switch between BLAS post-build"

**Comment by kforner** [comment]
> skips using the code shipped with R because a) we already have it 

Does "already have it" mean that there are the same implementations ?

> and b) if we did, you couldn't switch between BLAS post-build"

actually I could, using the method mentioned in the R installation manual, basically switching symlinks to libRBlas.so
Using this system, I could switch between RBlas, libblas (netlib) and openblas. 
That's how I realized that the benchmark timings were really similar between RBlas and libblas.

Could you confirm that it is useless to have both RBlas and libblas ?

**Comment by eddelbuettel** [comment]
Sorry, this is not the r-sig-debian or r-devel list. Will close this as we are drifting a little afar here.

All this is open source.  If in doubt, don't listen to me but test.
