### ISSUE TITLE
nginx load balancing app dose not works

### ISSUE THREAD

**Issue by kuzmenkov111** [rocker-org/rocker#270]
Hello!

Thank you for work! Have you ever scaled shiny app in docker container? F.e. run N containers with shiny app and nginx load balancer in front of it? I tried , but nginx start infint balancing loop.
my compose file
 

nginx:
    build: ./nginx
    links:
        - shinyserv1:shinyserv1
        - shinyserv2:shinyserv2
        - shinyserv3:shinyserv3
    ports:
        - "80:80"
shinyserv1:
    image: kuzmenkov/shinyserv
    volumes:
        - /srv/shiny-server/:/srv/shiny-server/
    ports:
        - "3838"
shinyserv2:
    image: kuzmenkov/shinyserv
    volumes:
        - /srv/shiny-server2/:/srv/shiny-server/
    ports:
        - "3838"
shinyserv3:
    image: kuzmenkov/shinyserv
    volumes:
        - /srv/shiny-server1/:/srv/shiny-server/
    ports:
        - "3838"
 
And my nginx.conf
`worker_processes 4;

events { worker_connections 1024; }

http {

	upstream node-app {
	      least_conn;
	      server shinyserv1:3838 weight=10 max_fails=3 fail_timeout=30s;
	      server shinyserv2:3838 weight=10 max_fails=3 fail_timeout=30s;
	      server shinyserv3:3838 weight=10 max_fails=3 fail_timeout=30s;
	}
	 
	server {
	      listen 80;
	 
	      location / {
	        proxy_pass http://node-app;
	        proxy_http_version 1.1;
	        proxy_set_header Upgrade $http_upgrade;
	        proxy_set_header Connection 'upgrade';
	        proxy_set_header Host $host;
	        proxy_cache_bypass $http_upgrade;
	      }
	}
}
`

Have you experince how to load balance containers with shiny app?

**Comment by cboettig** [comment]
I'm afraid nginx support is out of our scope, but I don't suspect this issue is specific to the rocker image.  I generally use [caddy](https://caddyserver.com/features) for reverse proxy / load balancing, imho it is much easier to configure for such things.
