### ISSUE TITLE
RStudio Logging?

### ISSUE THREAD

**Issue by crawdaddy18** [rocker-org/rocker#271]
Rocker Team--
Thank you for the Docker distro of RStudio.  I have ported it to Centos7 and it works great.  

I am having an issue with "RStudio Initialization Error: Error Occurred During Transmission" which I believe is related to the Kerberos I just enabled so that RStudio could pull from HDFS.  All was working well until this change.

I'd like to look at the logs, but I cannot find where RStudio is writing them out to.  None of the usual places appear to be in use.

On a side note, I am able to use the R CLI to authenticate and pull from HDFS with no problems.  This error just occurs in RStudio.

**Comment by eddelbuettel** [comment]
i)  Please see our notes and comments about redistribution of RStudio programs. We happen to have permission.  I doubt it just passes on to the next user of our Dockerfiles.
ii)  We don't use CentOS so you're on your own there.  Maybe try RStudio help, or CentOS forums.
