### ISSUE TITLE
"Deep learning" container?

### ISSUE THREAD

**Issue by eddelbuettel** [rocker-org/rocker#273]
Discussion with @jjallaire (and @uwesterr) here: https://github.com/rstudio/keras/issues/207

Thoughts?

**Comment by uwesterr** [comment]
i think it would be great to have such a docker with
- RStudio
- tidyverse
- keras package with tf backend
- with gpu support
which would run in the nvidia-docker.
since i am not skilled in docker i can offer support by testing the docker image on my ubuntu 16.04 machine with V PCIe Nvidia Quadro K2200 4GB PNY 4 GB GDDR5, PCIe 2.0 x16, DVI, 2 x DisplayPort, 640 CUDA-Kerne

**Comment by eddelbuettel** [comment]
I think my card is a K1200 which is close.  

In my mind, tidyverse is orthogonal, and we can possibly put that on top later; ditto for RStudio.  

Right now I think we should focus on getting nvidia and R working together so that tf + keras get loaded reliably.  I'd be happy to stop there and let other put what user-facing apps and packages they want; that part is easy once we have a base.   Available time is, as always, a different issue.

**Comment by cboettig** [comment]
This sounds great, I think we definitely should support a GPU-oriented  image.  A few quick thoughts:

- I agree with Dirk that it makes sense to start this as a base image; once we get that working we can discuss more what else it should include by default (RStudio, tidyverse, etc), which should be easy enough to add.

- I'm not an expert in this area; but two salient observations: (a) obviously there's a lot of existing work on Docker+GPU, and (b) Docker+GPU is still super complicated.  In addition to getting the software dependencies set up, the user just faces a lot of runtime arguments to get devices linked properly to the containers.  Nvidia has [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) what I think is basically a drop-in runtime replacement for the default `docker-engine` to run Docker containers and handle some of this; could be the obvious thing to build on (e.g. following the strategy of Google's [tensorflow containers](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker).  

- Not sure if there are likely to be any licensing issues in distributing the software side; I know at one time the free Nvidia libraries were still only proprietary binaries; though maybe the open source libraries are sufficient now.  In any event, we should be able to follow the strategy of other containers in this space.

**Comment by cboettig** [comment]
@uwesterr quick experimental example here: https://github.com/rocker-org/ml, Dockerfile is identical in each case but just with different base images.  I don't have an Nvidia card here so I haven't tested, but it seems like we'd either need to build on Nvidia's Docker images (e.g. [nvidia/cuda](https://hub.docker.com/r/nvidia/cuda/)) or just leave it the user to register for and add [cudnn](https://developer.nvidia.com/cudnn) themselves.  My example shows installing the open source dependencies, fwiw.

**Comment by uwesterr** [comment]
@cboettig  i tested your docker file and tried to extend it with cudnn
try to combine ML docker from cboettig and fchollet/keras

Get from https://github.com/fchollet/keras/blob/master/docker/Dockerfile
ARG cuda_version=8.0
ARG cudnn_version=6
FROM nvidia/cuda:${cuda_version}-cudnn${cudnn_version}-devel
and add to dockerfile from cboettig so we get
ARG cuda_version=8.0
ARG cudnn_version=6
FROM nvidia/cuda:${cuda_version}-cudnn${cudnn_version}-devel
FROM rocker/verse
RUN apt-get update && apt-get -y install \
    python-virtualenv \
    python-pip && \
    pip install h5py pyyaml requests Pillow scipy && \
    install2.r --error keras && \
    R -e "keras::install_keras(tensorflow='gpu')"

build image
 nvidia-docker build -t mlcboettig .
Run docker
nvidia-docker run -d -p 8788:8787  mlcboettig
in RStudio

> library(keras)
> model <- keras_model_sequential()
ImportError: No module named keras
Use the install_keras() function to install the core Keras library
Error: Error loading Python module keras
install_keras(tensorflow = "gpu")
model <- keras_model_sequential()
> library(keras)
> model <- keras_model_sequential()
Using TensorFlow backend.
Error: ImportError: Traceback (most recent call last):
  File "/home/rstudio/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rstudio/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rstudio/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above
since this failed try
library(keras)
model <- keras_model_sequential()
model <- keras_model_sequential()
install_keras(tensorflow = "gpu")
library(keras)
model <- keras_model_sequential()
devtools::install_github("rstudio/keras")
devtools::install_github("rstudio/reticulate")
devtools::install_github("rstudio/keras")
library(reticulate)
devtools::install_github("rstudio/reticulate")
library(reticulate)
devtools::install_github("rstudio/keras")
devtools::install_github("rstudio/keras", force=TRUE)
model <- keras_model_sequential()
library(keras)
model <- keras_model_sequential()
install_keras(tensorflow = "gpu")
library(keras)
model <- keras_model_sequential()

end up with 
> model <- keras_model_sequential()
Using TensorFlow backend.
Error: ImportError: Traceback (most recent call last):
  File "/home/rstudio/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rstudio/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rstudio/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above

**Comment by uwesterr** [comment]
i then tried the other way round integrate rocker makerfile into fchollet/keras

ARG cuda_version=8.0
ARG cudnn_version=6
FROM nvidia/cuda:${cuda_version}-cudnn${cudnn_version}-devel

ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH

RUN mkdir -p $CONDA_DIR && \
    echo export PATH=$CONDA_DIR/bin:'$PATH' > /etc/profile.d/conda.sh && \
    apt-get update && \
    apt-get install -y wget git libhdf5-dev g++ graphviz openmpi-bin && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh && \
    echo "c59b3dd3cad550ac7596e0d599b91e75d88826db132e4146030ef471bb434e9a *Miniconda3-4.2.12-Linux-x86_64.sh" | sha256sum -c - && \
    /bin/bash /Miniconda3-4.2.12-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-4.2.12-Linux-x86_64.sh

ENV NB_USER keras
ENV NB_UID 1000

RUN useradd -m -s /bin/bash -N -u $NB_UID $NB_USER && \
    mkdir -p $CONDA_DIR && \
    chown keras $CONDA_DIR -R && \
    mkdir -p /src && \
    chown keras /src

USER keras

# Python
ARG python_version=3.5

RUN conda install -y python=${python_version} && \
    pip install --upgrade pip && \
    pip install tensorflow-gpu && \
    pip install https://cntk.ai/PythonWheel/GPU/cntk-2.1-cp35-cp35m-linux_x86_64.whl && \
    conda install Pillow scikit-learn notebook pandas matplotlib mkl nose pyyaml six h5py && \
    conda install theano pygpu bcolz && \
    pip install sklearn_pandas && \
    git clone git://github.com/fchollet/keras.git /src && pip install -e /src[tests] && \
    pip install git+git://github.com/fchollet/keras.git && \
    conda clean -yt


ENV PYTHONPATH='/src/:$PYTHONPATH'

WORKDIR /src

EXPOSE 8888
FROM rocker/verse
RUN apt-get update && apt-get -y install \
    python-virtualenv \
    python-pip && \
    pip install h5py pyyaml requests Pillow scipy && \
    install2.r --error keras && \
    R -e "keras::install_keras(tensorflow='gpu')"

EXPOSE 8889

build image
 nvidia-docker build -t mlcboettig .

Run docker
nvidia-docker run -d -p 8889:8889 -p 8888:8  mlcboettig
no application is started in browser try different port
nvidia-docker run -d -p 8889:8889 -p 8888:8787  mlcboettig
in RStudio
devtools::install_github("rstudio/reticulate")
devtools::install_github("rstudio/keras")
install_keras(tensorflow = "gpu")
library(keras)
model <- keras_model_sequential()
Using TensorFlow backend.
Error: ImportError: Traceback (most recent call last):
  File "/home/rstudio/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rstudio/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rstudio/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above

**Comment by eddelbuettel** [comment]
I would like to get back to what Carl and I said above: RStudio and all that jazz is somewhat extraneous in general, and particularly for now.  I think it would be best to focus on a simple container (see Carl's) and add complextity one step at a time.  So maybe adding keras to rocker/r-base, or adding R to fchollet/keras.  If and when that works, we can add other layers.

**Comment by uwesterr** [comment]
@eddelbuettel ok, maybe i aimed too high.
@cboettig i tests your dockerfile https://github.com/rocker-org/ml/tree/master/verse 
Test experimental ML docker from cboettig
Build image from /cboettig/ml-master/verse
```
nvidia-docker build -t mlcboettig .
nvidia-docker run -d   mlcboettig
```
within R command line
```
> library(keras)
> model <- keras_model_sequential()
Using TensorFlow backend.
```

Run MNIST examples https://keras.rstudio.com/
works as well but GPU utilization is never beyond 3%
next test https://keras.rstudio.com/articles/examples/cifar10_cnn.html
works as well but GPU utilization is never beyond 3%

is this the expected outcome?

**Comment by cboettig** [comment]
@uwesterr As I mentioned, the images I had previously added didn't have `cudnn` installed, so I'm assuming they are just running on the CPU, hence the basic absence of GPU utilization.  

I've just added an image that simply installs R an the other dependencies on top of the official NVIDIA `nvidia/cuda` image here: https://github.com/rocker-org/ml/blob/master/gpu/Dockerfile (and queued a build on Hub as `rocker/ml:gpu`, see https://hub.docker.com/r/rocker/ml/builds/). Can you test that one?  (I've no easy access to NVidia hardware right now)...

**Comment by uwesterr** [comment]
build image
 nvidia-docker build -t mlcboettig .

Run docker
nvidia-docker run -it mlcboettig bash

Run MNIST examples https://keras.rstudio.com/ 
> library(keras)
> mnist <- dataset_mnist()
Error: Python module keras was not found.

Detected Python configuration:

python:         /root/.virtualenvs/r-tensorflow/bin/python
libpython:      /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
pythonhome:     /usr:/usr
virtualenv:     /root/.virtualenvs/r-tensorflow/bin/activate_this.py
version:        2.7.12 (default, Nov 20 2017, 18:23:56)  [GCC 5.4.0 20160609]
numpy:          /root/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/numpy
numpy_version:  1.13.3
keras:          /root/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/keras

python versions found: 
 /root/.virtualenvs/r-tensorflow/bin/python
 /usr/bin/python
 /usr/bin/python3

**Comment by ryangarner** [comment]
This is my base Dockerfile that I build on a P2 EC2 instance: Deep Learning Base AMI (Ubuntu) Version 1.0 - ami-a1e534d9.

```
## Dockerfile
FROM nvidia/cuda:8.0-cudnn6-runtime

RUN apt-get update -q && apt-get upgrade -y -q

## R installation
RUN sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" >> /etc/apt/sources.list'
RUN gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
RUN gpg -a --export E084DAB9 | apt-key add -
RUN apt-get update
RUN apt-get install -y r-base r-base-dev libxml2-dev libxt-dev libssl-dev libcurl4-openssl-dev imagemagick

## Python dependencies
RUN apt-get update && apt-get -y upgrade
RUN apt-get install python-pip python-virtualenv -y
RUN pip install virtualenv

## R packages
RUN R -e "install.packages('devtools', repos = 'https://cloud.r-project.org')"
RUN R -e "devtools::install_github('rstudio/tensorflow')"
RUN R -e "devtools::install_github('rstudio/keras')"
RUN R -e "keras::install_keras(tensorflow = 'gpu')"
```

```
nvidia-docker build -t r-gpu .
nvidia-docker run -it r-gpu bash
```

```
root@4c58c53526da:/# nvidia-smi
Wed Dec  6 23:35:06 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:17.0 Off |                    0 |
| N/A   45C    P8    27W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 00000000:00:18.0 Off |                    0 |
| N/A   35C    P8    28W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 00000000:00:19.0 Off |                    0 |
| N/A   50C    P8    28W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 00000000:00:1A.0 Off |                    0 |
| N/A   38C    P8    29W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           On   | 00000000:00:1B.0 Off |                    0 |
| N/A   47C    P8    26W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           On   | 00000000:00:1C.0 Off |                    0 |
| N/A   37C    P8    29W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           On   | 00000000:00:1D.0 Off |                    0 |
| N/A   50C    P8    27W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   41C    P8    30W / 149W |      1MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```
root@4c58c53526da:/# R         

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(keras)
> library(tensorflow)
> with(tf$device("/gpu:0"), {
+   model <- keras_model_sequential() 
+   model %>% 
+     layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
+     layer_dropout(rate = 0.4) %>% 
+     layer_dense(units = 128, activation = 'relu') %>%
+     layer_dropout(rate = 0.3) %>%
+     layer_dense(units = 10, activation = 'softmax')
+ })
Using TensorFlow backend.
```

**Comment by eddelbuettel** [comment]
@ryangarner That looks pretty good. We can work on that. 

I could also do what I usually and create .deb packages for tensorflow and keras over at [my PPA](https://launchpad.net/~edd/+archive/ubuntu/misc) so that we'd have "everything" as a .deb.  Now, where did I leave the spare time again ...

**Comment by uwesterr** [comment]
@ryangarner hi ryan,
i tested your docker on my machine ( ubuntu 16.04 machine with V PCIe Nvidia Quadro K2200 4GB PNY 4 GB GDDR5, PCIe 2.0 x16, DVI, 2 x DisplayPort, 640 CUDA-Kerne), ended up with an error message that
`Error: Python module tensorflow was not found.`
i guess the difference is that i run local where you run on the EC2 instance. 
details as follows 
nvidia-docker run -it r-gpu bash
root@04893a3900fb:/# R

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(keras)
> library(tensorflow)
> with(tf$device("/gpu:0"), {
+ model <- keras_model_sequential() 
+  model %>% 
+ layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
+ layer_dropout(rate = 0.4) %>% 
+ layer_dense(units = 128, activation = 'relu') %>%
+ layer_dropout(rate = 0.3) %>%
+ layer_dense(units = 10, activation = 'softmax')
+ })
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /root/.virtualenvs/r-tensorflow/bin/python
 /usr/bin/python2.7
 /usr/bin/python3.5

You can install TensorFlow using the install_tensorflow() function.
> 
> install_tensorflow(version = "gpu")
Using existing virtualenv at  ~/.virtualenvs/r-tensorflow 
Upgrading pip ...
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
Successfully installed pip-9.0.1
Upgrading wheel ...
Collecting wheel
  Using cached wheel-0.30.0-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.30.0
Upgrading setuptools ...
Collecting setuptools
  Using cached setuptools-38.2.4-py2.py3-none-any.whl
Installing collected packages: setuptools
Successfully installed setuptools-38.2.4
Installing TensorFlow ...
Collecting tensorflow-gpu
  Using cached tensorflow_gpu-1.4.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting h5py
  Using cached h5py-2.7.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyyaml
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting Pillow
  Using cached Pillow-4.3.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scipy
  Using cached scipy-1.0.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting mock>=2.0.0 (from tensorflow-gpu)
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting tensorflow-tensorboard<0.5.0,>=0.4.0rc1 (from tensorflow-gpu)
  Using cached tensorflow_tensorboard-0.4.0rc3-py2-none-any.whl
Collecting numpy>=1.12.1 (from tensorflow-gpu)
  Using cached numpy-1.13.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting backports.weakref>=1.0rc1 (from tensorflow-gpu)
  Using cached backports.weakref-1.0.post1-py2.py3-none-any.whl
Collecting wheel (from tensorflow-gpu)
  Using cached wheel-0.30.0-py2.py3-none-any.whl
Collecting six>=1.10.0 (from tensorflow-gpu)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting protobuf>=3.3.0 (from tensorflow-gpu)
  Using cached protobuf-3.5.0.post1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34>=1.1.6 (from tensorflow-gpu)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting olefile (from Pillow)
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorflow-gpu)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0.0->tensorflow-gpu)
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Collecting bleach==1.5.0 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu)
  Using cached bleach-1.5.0-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu)
Collecting futures>=3.1.1; python_version < "3.2" (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu)
  Using cached futures-3.2.0-py2-none-any.whl
Collecting markdown>=2.6.8 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu)
Collecting werkzeug>=0.11.10 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.3.0->tensorflow-gpu)
  Using cached setuptools-38.2.4-py2.py3-none-any.whl
Installing collected packages: six, funcsigs, pbr, mock, html5lib, bleach, wheel, numpy, futures, setuptools, protobuf, markdown, werkzeug, tensorflow-tensorboard, backports.weakref, enum34, tensorflow-gpu, h5py, pyyaml, urllib3, idna, chardet, certifi, requests, olefile, Pillow, scipy
Successfully installed Pillow-4.3.0 backports.weakref-1.0.post1 bleach-1.5.0 certifi-2017.11.5 chardet-3.0.4 enum34-1.1.6 funcsigs-1.0.2 futures-3.2.0 h5py-2.7.1 html5lib-0.9999999 idna-2.6 markdown-2.6.9 mock-2.0.0 numpy-1.13.3 olefile-0.44 pbr-3.1.1 protobuf-3.5.0.post1 pyyaml-3.12 requests-2.18.4 scipy-1.0.0 setuptools-38.2.4 six-1.11.0 tensorflow-gpu-1.4.0 tensorflow-tensorboard-0.4.0rc3 urllib3-1.22 werkzeug-0.12.2 wheel-0.30.0

Installation complete.

> with(tf$device("/gpu:0"), {
+ model <- keras_model_sequential() 
+  model %>% 
+ layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
+ layer_dropout(rate = 0.4) %>% 
+ layer_dense(units = 128, activation = 'relu') %>%
+ layer_dropout(rate = 0.3) %>%
+ layer_dense(units = 10, activation = 'softmax')
+ })
Error: Python module tensorflow was not found.

Detected Python configuration:

python:         /root/.virtualenvs/r-tensorflow/bin/python
libpython:      /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
pythonhome:     /usr:/usr
virtualenv:     /root/.virtualenvs/r-tensorflow/bin/activate_this.py
version:        2.7.12 (default, Nov 20 2017, 18:23:56)  [GCC 5.4.0 20160609]
numpy:          /root/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/numpy
numpy_version:  1.13.3
keras:          /root/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/keras

python versions found: 
 /root/.virtualenvs/r-tensorflow/bin/python
 /usr/bin/python
 /usr/bin/python3
layer_dropout(rate = 0.3) %>%
layer_dense(units = 10, activation = 'softmax')
})

**Comment by eddelbuettel** [comment]
@ryangarner thumbs up.  I just caught up, installed `nvidia-docker` and all that jazz and repeated your example.  Nice.

There are some simple tricks we can do the Dockerfile we have (from which I started) but nice job.

**Comment by restonslacker** [comment]
just a quick note that after trying @ryangarner's example, i recieved the following error

```
Error in initialize_python(required_module, use_environment):
  Python shared library '/usr/lib/libpython2.7.so' not found, Python bindings not loaded.
```

i was able to solve this with `apt-get install libpython2.7`

**Comment by eddelbuettel** [comment]
Can you try [this Dockerfile](https://github.com/rocker-org/ml/blob/master/gpu/Dockerfile) and if needed provide a simple PR?

Worked for me when I wrote it, but since then Docker and nvidia upgraded and I am not sure I currently have a working `nvidia-docker` -- needed to uncomment something to get `docker-ce` upgraded.

**Comment by restonslacker** [comment]
@eddelbuettel sure thing.  look for a PR tonight or tomorrow morning.

**Comment by eddelbuettel** [comment]
Nice.  But what I was trying to say:   test that one first.  It worked for me loading keras etc from R, which would imply working / complete Python.

**Comment by restonslacker** [comment]
Yes, I understood what you were asking and I had enough time to verify that
your file didn’t work as written for me. It did when I added `libpython2.7`
to the install commands. I did not have enough time right then to submit a
proper PR, but did want to let you know that I am working on it and intend
to do so (when i’m Not using my phone to add comments on GH ;)

**Comment by pbhogale** [comment]
here is a dockerfile inspired by the `rocker/ml` gpu Dockerfile, built on `nvidia/cuda:9.0-cudnn7-runtime` that has rstudio server and the tidyverse. I'm far from an expert, so many improvements are possible.
https://github.com/pbhogale/gpu-keras-rstudio

**Comment by KaiLicht** [comment]
Since it seems to be pretty hard to get things up and running without proprietary NVIDIA stuff why not just directly use their nvidia gpu container registry (NGC)? They have ready to use and optimized tensorflow containers based on Ubuntu 16.04. You can just install R on top of that. Works like a charm. Like [this](https://github.com/KaiLicht/DataScience_Toolbox/blob/master/dockerfiles/Rbase_keras_tf/Dockerfile) dockerfile.
