### ISSUE TITLE
Error occured during transmission

### ISSUE THREAD

**Issue by vanaraj-az** [rocker-org/rocker#276]
I have created multiple containers with custom username and password. While accessing container in the browser I got the error "Error occured during transmission". But it's working with default rstudio user. 

Can you please provide any solution to fix this issue?

**Comment by eddelbuettel** [comment]
Does this [dcoumentation from our wiki](https://github.com/rocker-org/rocker/wiki/managing-users-in-docker) help ?

**Comment by cboettig** [comment]
Closing this out for inactivity, but feel free to reopen with more details necessary to reproduce the problem if the above documentation did not resolve the issue.
