### ISSUE TITLE
Terminal does not open

### ISSUE THREAD

**Issue by Gramler** [rocker-org/rocker#278]
Opening a terminal results in no terminal session being open.
Using latest version of rstudio / tidyverse

docker version 
18.02.0-ce, build fc4de44

docker logs:
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying... 
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] add: executing... 
Nothing additional to add
[cont-init.d] add: exited 0.
[cont-init.d] userconf: executing... 
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by eddelbuettel** [comment]
Can you check the discussion at https://github.com/rocker-org/rocker-versioned/issues/70  ?

(Sadly our issue tickets cannot be seen in a unified ways ...)

**Comment by Gramler** [comment]
It describes the issue quite accurately, apart from the fact that if I turn of all extensions and add-ons I still get this issue. Version of FireFox is 
Version 58.0.1 (64-bit), running on Ubuntu

I also tried Chrome (And FireFox on another Ubuntu machine)

**Comment by znmeb** [comment]
I ran into this a few weeks ago too. It worked on Chromium / Linux and Edge / Windows 10 Pro but not on Firefox 58 on either system. In any event, 

1. it's not a Rocker bug, and
2. I fixed it by going into the RStudio "Global" options for "Terminal" and disabling WebSockets.

**Comment by cboettig** [comment]
It's been suggested to me this only happens when also behind a proxy (a common setting), but otherwise I guess we could make disabling WebSockets the default behavior in the image.  Anyway, definitely good to have the documented work-around above, thanks @znmeb.  Closing this out.
