### ISSUE TITLE
Running rocker/rstudio or rocker/tidyverse with port other than 8787?

### ISSUE THREAD

**Issue by cscn** [rocker-org/rocker#280]
Hi all,

Relatively new to docker here so apologies if this is a basic question, but is it possible to run the rstudio container on ports besides 8787? Or if not is there some other way to run multiple rstudio containers at once?

**Comment by cboettig** [comment]
yup, `docker run -p 8888:8787 rocker/rstudio` will run on port 8888.  The second number should always be 8787 for inside the container, but you can make the first number whatever port you want.  This isn't rocker-specific but is true for ports on any Docker system.  

We'll eventually get more of this up on https://www.rocker-project.org/use/networking/ ....

**Comment by cscn** [comment]
Thanks so much! That was ridiculously fast!
