### ISSUE TITLE
parallel job fails

### ISSUE THREAD

**Issue by dashaub** [rocker-org/rocker#283]
I'm trying to track down some mysterious failures that happen when running a parallel job inside a Docker container, and I think it might be something related to the R build used in this container.

Summary of the issue:
I have a `lapply()` job that completes, and when using a socket cluster the job also works fine inside the Docker container. However, when the parallel backend uses forking, many of the workers unpredictably and unreproducibly return `NULL`. I can run the job on OSX with any of the above configurations successfully. Any ideas what could be going on?

See details in https://github.com/psolymos/pbapply/issues/35

**Comment by eddelbuettel** [comment]
It is supposed to work?  Rember that Docker is a 'single process on steroids', not a virtual machine.  That would simply rule out forking.

**Comment by dashaub** [comment]
I don't see any reason why multiple processes/threading _shouldn't_ work (there are plenty of containers with multithreaded services such as Kafka/Elasticsearch/Cassandra on DockerHub, and multiple processes are definitely allowed, e.g. `yes & bash`). I thought it might be fixed by running the container with `--init`, but that didn't seem to help. The best solution for this specific case I have right now is to use a socket cluster.

Also when I try a simple forking example without any package dependencies it works:
```
library(pbapply)
repList <- rep(list(1:100), 10000)
res <- pblapply(repList, mean, cl = 6)
> table(as.numeric(res))

 50.5 
10000
```

I guess if we don't really have any further ideas we might as well close this since it seems difficult to replicate on other data and might be related to my code in some way.
