### ISSUE TITLE
Password Plain text in container env

### ISSUE THREAD

**Issue by HanjoStudy** [rocker-org/rocker#285]
When using the specified command from the documentation to start the container:
`docker run  --name rstudio -d -p 8787:8787 -e USER=user_name -e PASSWORD=Pass1234 rocker/rstudio`

One can view the password in plain text using:
```
docker exec -it rstudio bash
set
```
The output produces
```
:
:
PASSWORD=Pass1234
PATH=/usr/lib/rstudio-server/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
:
:
UID=0
USER=user_name
```

Is there a better way to specify the user and password when starting the container?

**Comment by cboettig** [comment]
Sure, you can always docker-exec into your container and change the user password using the standard linux tools.  Providing a default password and the option to set a password in the environmental variable is there for convenience; i.e. when you have secure control over who has access to `docker exec` into your machine, which is nearly always the case(?)

Note that someone who can docker-exec into the container as in your example means they have access to the host machine, are part of the docker group on the host machine, and once they docker-exec into the container, they have root privileges to do just about anything on the container. These are obviously very high privileges, so  a person with that level of access obviously needs to be trusted.  (i.e. is almost always the person who created this password).  

I agree that in general you don't want an admin to see other users passwords, that really only matters in multi-user setups.  (In which case, the admin can change or create new users who can set there password with the usual linux way).

**Comment by HanjoStudy** [comment]
I agree with you that for a single user, its a case of just changing the password using basic linux tools. But as docker + Rstudio moves to a philosophy of production environment for multiple-users it might be useful to have a feature where one can add users, already on the OS, to the docker instance when one kicks off the image using `docker run`? Unfortunately, how one would go about this, might be a challenge

**Comment by HanjoStudy** [comment]
Thanks, the link proved to be a good example on how one could go about the process in a clean manner. In future it would be nice to see such features integrated into a docker image through some parameter setting when starting a container. But for now, this is perfect
