### ISSUE TITLE
I have added sudo permission to the docker user of r-base, what is the password?

### ISSUE THREAD

**Issue by russelljjarvis** [rocker-org/rocker#286]
I have added sudo permission to the docker user of r-base, what is the password?

**Comment by russelljjarvis** [comment]
So say if you expect to run r-scripts as a standard (de-esculated user), and also I want to sudo apt-get additional packages in the interactive terminal, before I append them to a more elaborate Dockerbuild that is derived from r-base.

I want to start using python from R and r from python, I want install python pip to pip install various things, and I also want to run R, and python as a non root user. Running scripts as non root has more generality, and appeals to established software conventions.

**Comment by eddelbuettel** [comment]
Please see what I wrote, and demonstrated.  You *are* root in Docker. That is how we install things.

**Comment by russelljjarvis** [comment]
I can see what you mean now. Docker-base is the foundation, for more derived docker images, it does not make sense for the foundation to have sudo, only the derivatives should have sudo.

**Comment by eddelbuettel** [comment]
Yes, I had the feeling we were not talking about the same thing. Some of Carl's derived containers set the uid, and you may need sudo there.  But I still don't think of containers as vm replacements -- I would just prep the container beforehand.  But there are certainly different use cases, and I don't always manage to express that view all that well...
