### ISSUE TITLE
E: The value '“testing”' is invalid for APT::Default-Release as such a release is not available in the sources

### ISSUE THREAD

**Issue by kuamit5516** [rocker-org/rocker#287]
oot@kalilinux:/home/user# sudo apt-get install aptitude
Reading package lists... Done
E: The value '“testing”' is invalid for APT::Default-Release as such a release is not available in the sources

**Comment by eddelbuettel** [comment]
I just answered this [here](https://github.com/rocker-org/rocker/issues/167#issuecomment-387374954); there is no need to report things multiple times.
