### ISSUE TITLE
moved R 3.5 repo

### ISSUE THREAD

**Issue by mirekphd** [rocker-org/rocker#289]
The GitHub repo https://eddelbuettel.github.io/drr35/ referenced in the Dockerfile no longer exists. Could you repair the broken link and verify the Dockerfile compilation works using docker build?

**Comment by eddelbuettel** [comment]
It's there: https://github.com/eddelbuettel/drr35  

Maybe something happened with the https serving.

**Comment by eddelbuettel** [comment]
Also, which "Dockerfile" are referencing?  I think I only blogged about this referring to a local and unpublished Dockerfile.

**Comment by eddelbuettel** [comment]
I think you were just confused about the lack of an `index.html` in the top level. Try eg retrieving the `docs/Packages` file per this link:   https://eddelbuettel.github.com/drr35/Packages -- it _downloads_ just fine and that is all that `apt-get` and friends need:

```sh
edd@rob:/tmp$ wget https://eddelbuettel.github.io/drr35/Packages; head Packages
--2018-05-30 12:05:33--  https://eddelbuettel.github.io/drr35/Packages
Resolving eddelbuettel.github.io (eddelbuettel.github.io)... 185.199.111.153, 185.199.110.153, 185.199.109.153, ...
Connecting to eddelbuettel.github.io (eddelbuettel.github.io)|185.199.111.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 54395 (53K) [application/octet-stream]
Saving to: ‘Packages’

Packages                                            100%[===================================================================================================================>]  53.12K  --.-KB/s    in 0.03s

2018-05-30 12:05:34 (1.94 MB/s) - ‘Packages’ saved [54395/54395]

Package: littler
Architecture: all
Version: 0.3.3-1.2
Priority: optional
Section: gnu-r
Maintainer: Dirk Eddelbuettel <edd@debian.org>
Installed-Size: 20
Depends: r-cran-littler
Filename: ./littler_0.3.3-1.2_all.deb
Size: 12692
```

**Comment by mirekphd** [comment]
Thank you, but I still cannot install R 3.5 on Ubuntu 16.04 (I tried to use [this Dockerfile](https://github.com/rocker-org/rocker/blob/master/r-base/Dockerfile)). 
Docker Hub image is no good in my case, as I need to incorporate R installation in our R data science container. Should I stick to 3.4.4?

**Comment by eddelbuettel** [comment]
See http://rubuntu.netlify.com/ and http://rubuntu.netlify.com/post/2018-05-25-announcing-c2d4u3-5/ 

Also realize that Debian != Ubuntu so this repo was never for you.

For all the rest: please don't post to random Github repos.  We *do* have a [mailing list for R on Debian and Ubuntu](https://stat.ethz.ch/mailman/listinfo/r-sig-debian) so please subscribe and ask there.

**Comment by eddelbuettel** [comment]
I beg to differ. Claiming that because humungous (commercial) self-contained third party archives which bundle all their shared libraries outside of the package manager and have a single entry "can be used on both" is correct, but not useful as you are looking for fine-grained packages _within_ the package management system.   

I am locking this now.
