### ISSUE TITLE
Containers for older versions of R

### ISSUE THREAD

**Issue by hadley** [rocker-org/rocker#29]
Would be useful to have some containers locked to specific versions, 3.0.2, 3.1.1 etc

**Comment by shabbychef** [comment]
Would it be possible to manually tag `rocker/r-base` just before an update of the R version occurs? By 'manually', I mean go to the 'build settings' tab in docker hub, and triggering a build with the corresponding Docker tag name.

**Comment by eddelbuettel** [comment]
If I hear "manual" I don't want yet another job to take care of / have to remember.  What we have now is not all that bad:

```
edd@max:~$ docker images r-base
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
r-base              3.2.3               7939bc63acf9        13 days ago         1.071 GB
r-base              latest              7939bc63acf9        13 days ago         1.071 GB
r-base              3.2.2               d8d772db8b82        11 weeks ago        998.9 MB
r-base              3.2.1               38a6a6b62751        6 months ago        563.5 MB
r-base              3.2.0               c09b226d89bc        6 months ago        551.6 MB
r-base              3.1.3               8a0dd612a7f5        9 months ago        516.7 MB
r-base              3.1.2               c04052b3ddd2        10 months ago       483.5 MB
edd@max:~$ 
```

Good enough?

[ And yes, some of those where off. I think 3.1.2 and 3.1.3 both are 3.1.3 etc pp.  But _preservation of old versions is *not really* the stated goal of this project_, irrespective of how many times people nudge us that way. We *do* have some related projects. ]

**Comment by shabbychef** [comment]
I think this might, thanks @eddelbuettel . (One of my packages apparently does not CRAN-check on R 3.1, and I am trying to hunt this down, so I need access to an 'old' version of R, preferrably via docker.) Given the mapping from tag to image ID, I think I can access these images from docker-hub by using the `FROM image@digest` syntax which was introduced in Docker 1.6. I will write this up if/when I get it working.  thanks again,

**Comment by eddelbuettel** [comment]
I'd add `Depends: R (>= 3.2.0)`. 

<ducks>

**Comment by gmbecker** [comment]
Steven,

If you have issues installing/managing appropriately old versions of your
package's dependencies, my switchr package (
https://github.com/gmbecker/switchr) is designed to help with that. See
specifically ?rVersionManifest to get a manifest of appropriate tarballs
for use in install_packages.

Please feel free to drop me a line if you have any questions or it doesn't
seem to meet your needs in some way (or doesn't work).

On Mon, Jan 11, 2016 at 10:02 AM, Steven Pav <notifications@github.com>
wrote:

> I think this might, thanks @eddelbuettel <https://github.com/eddelbuettel>
> . (One of my packages apparently does not CRAN-check on R 3.1, and I am
> trying to hunt this down, so I need access to an 'old' version of R,
> preferrably via docker.) Given the mapping from tag to image ID, I think I
> can access these images from docker-hub by using the FROM image@digest
> syntax which was introduced in Docker 1.6. I will write this up if/when I
> get it working. thanks again,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rocker-org/rocker/issues/29#issuecomment-170635771>.
>



-- 
Gabriel Becker, PhD
Associate Scientist (Bioinformatics)
Genentech Research

**Comment by shabbychef** [comment]
I think @eddelbuettel's half jest solution wins him a cigar, at least for now.
