### ISSUE TITLE
Can't stop rocker/rstudio container

### ISSUE THREAD

**Issue by BaileyGlen** [rocker-org/rocker#290]
I have just begun testing out your rstudio image. 
I ran: 
docker run -d -p 8787:8787 rocker/rstudio
and was able to sign on to the server etc. 
However, docker stop <container name>, docker kill <container name> etc. don't seem to be working. Any suggestions?

**Comment by cboettig** [comment]
@BaileyGlen Since you didn't give it a name, you'll need to know the automatically given name or the hash of your container to stop it...  see: https://docs.docker.com/engine/reference/commandline/stop/#extended-description

e.g. try `docker ps` to see a list of all your running containers, and remember `stop` is not the same as `rm`.

**Comment by BaileyGlen** [comment]
I put the <container name> as a place holder. I was using the container
name from docker ps.

On Jun 7, 2018 12:08 AM, "Carl Boettiger" <notifications@github.com> wrote:

@BaileyGlen <https://github.com/BaileyGlen> Since you didn't give it a
name, you'll need to know the automatically given name or the hash of your
container to stop it... see:
https://docs.docker.com/engine/reference/commandline/stop/#extended-description

e.g. try docker ps to see a list of all your running containers, and
remember stop is not the same as rm.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rocker-org/rocker/issues/290#issuecomment-395286605>,
or mute the thread

**Comment by cboettig** [comment]
@BaileyGlen sorry, it was hard to tell what you typed or how familiar you might be with starting and stopping generic docker containers from the minimal information you provided.  In any event, the rstudio container can be stopped and removed like any other docker container run in the background (i.e. with `-d`), but without knowing what you are typing and what you are seeing it's hard to provide much help.  As this sounds like a generic docker issue and not specific to the rocker container, you might try a more general forum like stackoverflow for general docker support; we try and keep this focused on issues specific to rocker containers and associated documentation.

**Comment by BaileyGlen** [comment]
This is the only docker image I have ever had this issue with. I was able
to start and stop other docker images while this was ongoing, including
your base R image. I will provide some more details and testing this
afternoon.

**Comment by cboettig** [comment]
Closing as stale and not reproducible on our end.  Please re-open if with details on how to reproduce this or at least the system-specific details requested for bug-reports if this problem persists.  Thanks!

**Comment by moxgreen** [comment]
I have the same problem:

```
$ docker run --rm -p 8788:8788 -e PASSWORD=pippo123 rocker/rstudio
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] userconf: executing... 
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

After press `CTRL-C`

```
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
```
and hang. I do not get the prompt and the container is still present in `$ docker ps` output.

Also `docker stop <CONTAINER ID>` hangs.

Docker version is 19.03.9
