### ISSUE TITLE
Package "ggmap" can not install.

### ISSUE THREAD

**Issue by chiahuaw** [rocker-org/rocker#291]
I tried to install the package ggmap but failed.

The error message is as follows:
---

> * installing *source* package ‘png’ ...
> ** package ‘png’ successfully unpacked and MD5 sums checked
> ** libs
> gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include   `libpng-config --cflags` -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c read.c -o read.o
> /bin/bash: libpng-config: command not found
> read.c:3:17: fatal error: png.h: No such file or directory
>  #include <png.h>
>                  ^
> compilation terminated.
> /usr/local/lib/R/etc/Makeconf:159: recipe for target 'read.o' failed
> make: *** [read.o] Error 1
> ERROR: compilation failed for package ‘png’
> * removing ‘/usr/local/lib/R/site-library/png’
> * installing *source* package ‘jpeg’ ...
> ** package ‘jpeg’ successfully unpacked and MD5 sums checked
> ** libs
> gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c read.c -o read.o
> In file included from read.c:1:0:
> rjcommon.h:11:21: fatal error: jpeglib.h: No such file or directory
>  #include <jpeglib.h>
>                      ^
> compilation terminated.
> /usr/local/lib/R/etc/Makeconf:159: recipe for target 'read.o' failed
> make: *** [read.o] Error 1
> ERROR: compilation failed for package ‘jpeg’
> * removing ‘/usr/local/lib/R/site-library/jpeg’
> ERROR: dependency ‘png’ is not available for package ‘RgoogleMaps’
> * removing ‘/usr/local/lib/R/site-library/RgoogleMaps’
> ERROR: dependencies ‘RgoogleMaps’, ‘png’, ‘jpeg’ are not available for package ‘ggmap’
> * removing ‘/usr/local/lib/R/site-library/ggmap’
> 
> The downloaded source packages are in
>         ‘/tmp/RtmpCxflbh/downloaded_packages’
> Warning messages:
> 1: In install.packages("ggmap") :
>   installation of package ‘png’ had non-zero exit status
> 2: In install.packages("ggmap") :
>   installation of package ‘jpeg’ had non-zero exit status
> 3: In install.packages("ggmap") :
>   installation of package ‘RgoogleMaps’ had non-zero exit status
> 4: In install.packages("ggmap") :
>   installation of package ‘ggmap’ had non-zero exit status

---

Is there anything I should do, but I did not do it?

**Comment by cboettig** [comment]
You haven't told us *which* rocker image you are using (see https://www.rocker-project.org/images/).  I suggest trying with the `rocker/geospatial` image to get started.

**Comment by chiahuaw** [comment]
I am sorry for that. I was try rocker/rstudio and rocker/tidyverse,and all have the same issue.

And I will try to use rocker/geospatial,it is install ggmap packages successful. Thanks you.
