### ISSUE TITLE
Where are my directories on rocker/tidyverse?

### ISSUE THREAD

**Issue by alexhallam** [rocker-org/rocker#292]
I have rstudio server which I loaded onto AWS via the docker image, rocker/tidyverse. I would like to use cron to schedule an Rscript to run every day. The problem is that I can't seem to find my working directory. While in rstudio server I type getwd() and get `/home/rstudio/my_dir`, but this directory does not exist on my AWS instance. How do I access my directories and files?

**Comment by amoeba** [comment]
Hey @alexhallam this is more of a Docker question than a rocker one, but here's my 2c. I'm not much of a Docker expert but I think I see what's going on.

To make files and folders from your host (say, on your EC2 instance's filesystem) available within the rstudio Docker container, you'll need to explicitly tell Docker to do that when it launches the container. If you're launching the RStudio container via `docker run`, add the `-v` command-line arg, like:

`docker run --name rstudio -v /path/to/folder/:/home/rstudio/some_path`.

For example, I can mount the current working directory to the `work` directory in the container like this:

`docker run --name rstudio -p 8787:8787 -v $(pwd):/home/rstudio/work rocker/rstudio`

If you're launching the container another way, you'll need to consult that documentation.

**Comment by cboettig** [comment]
@alexhallam Like @amoeba says, sounds like you may not have linked the local volumes.  Note that you can also set up your `cron` job directly from the (bash) terminal in RStudio; no need to do this from the host machine.  Or you might also want to check out the [cronR](https://cran.r-project.org/web/packages/cronR/) R package to schedule your cron jobs directly from R.

**Comment by alexhallam** [comment]
Thanks, this is a question that is more about my inexperience with docker. @amoeba  had the solution that will work for me. For some reason my terminal on rstudio server is not operational, so starting a `cron` job from there will not work in my particular case. I may also try `cronR`.

**Comment by eddelbuettel** [comment]
By the way, a friend and fellow Debian'er recently posted a truly clever trick of taking `cron` and `crontab` inside the Docker container -- see his post [here](https://www.preining.info/blog/2018/05/docker-cron-mail-and-logs/) which may be of help to you depending on what you want to do.
