### ISSUE TITLE
Add Support for ARM64V8 architecture 

### ISSUE THREAD

**Issue by odidev** [rocker-org/rocker#294]
Hi,

The R-Base docker package is building and running fine at my end for ARM64v8 architecture.

Branch used to build is: r base

Please suggest, what needs to be done to raise the request to add support for ARM64v8 arch at official docker library too.

Regards,

**Comment by eddelbuettel** [comment]
I can only test on x86 so that makes me a little hesitant.

**Comment by odidev** [comment]
I have verified the working of this package on AARCH64 (ARM64v8) architecture as I have this with me.
The package has been built and run using Docker.
The running container is working fine for me.

Can you please let me know what needs to be done to provide complete verification of working.

**Comment by eddelbuettel** [comment]
We could possible work with you and link to / endorse the new project(s) _you_ start to run via these facilities.  I just don' think we can do this, as Carl so eloquently explained.  Sorry.

**Comment by odidev** [comment]
@cboettig : Although I am not very much familiar with cloud-based services to support docker builds as I have arm64v8 based hardware platforms with me, But for sure I can assure you that I have verified working on my end.

This activity is being done for most of the repositories and which is well accepted by their communities too. Maybe need to look at other requests to check cloud-based services used by them.

Also, in my view Rbase shouldn't have any such architecture based dependencies and going with this notion, we can enable support for ```arm64v8``` in the official build too.

The same is being followed [here](https://github.com/docker-library/official-images/pull/4599).
In this, mainatiners ahve enabled support for all archs with a view in mind that if any issue arises in future then it will be take care off at that time.

Regards,

**Comment by mmarmm** [comment]
@cboettig Hi Carl, Shippable supports free Arm64 CI/CD and I believe Codefresh does too (both 64-bit and 32-bit for both providers):

https://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture
http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

CodeFresh Beta signup: https://goo.gl/forms/aDhlk56jZcblYokj1

If you need raw infrastructure the WorksOnArm project will supply full servers if you want to deal with metal: https://github.com/worksonarm/cluster/

Would really love to see R on aRm! < see what I did there? ;)

CC: @tianon @lag-linaro

**Comment by odidev** [comment]
Thanks @mmarmm for providing helpful guidance.

**Comment by lag-linaro** [comment]
@mmarmm sounds perfect.  Thanks for the info.

@cboettig, @eddelbuettel, sounds like you already have lots of offers for help here, but I too am happy to offer some assistance if required.

**Comment by mmarmm** [comment]
Unsure what happened but r-base support just showed up: 
  https://hub.docker.com/r/arm64v8/r-base/
Thank you r-base DOI maintainers!

**Comment by eddelbuettel** [comment]
You may want to discuss that over [here in #4738](https://github.com/docker-library/official-images/pull/4738)

**Comment by vielmetti** [comment]
r-base credit goes to @tianon

**Comment by eddelbuettel** [comment]
This can now be closed we merged the PR for the r-base container.
