### ISSUE TITLE
RStudio not accessible from local browser when using rocker/rstudio

### ISSUE THREAD

**Issue by dkincaid** [rocker-org/rocker#298]
I'm working through the Applications with R and Docker workshop from the recent useR conference. I'm running Ubuntu 18.04 and trying to launch RStudio using `docker run -d -p 8787:8787 --rm rocker/rstudio`. Everything seems to startup fine and the container is running, but when I try to open http://localhost:8787 in a browser (tried Chrome and Firefox) it doesn't local. It just says "Waiting for localhost..." and hangs there. When I kill the container and try this I get a connection refused, so something is happening.

I connected to the Docker container using `docker exec` to look for RStudio logs, but couldn't find any in `/var/log/rstudio-server`.

Here is what `ps -ax` looks like inside the container:

```
root@83cd5615d001:/# ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 s6-svscan -t0 /var/run/s6/services
   24 ?        S      0:00 s6-supervise s6-fdholderd
  118 ?        S      0:00 s6-supervise rstudio
  121 ?        Ssl    0:00 /usr/lib/rstudio-server/bin/rserver --server-daemonize 0
  164 pts/0    Ss     0:00 bash
  171 pts/0    R+     0:00 ps ax
```

Is there something wrong with the Docker image or something on my side? Could someone point me in the right direction?

docker ps output:
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                    NAMES
9647b901b587        rocker/rstudio      "/init"             9 seconds ago       Up 7 seconds        0.0.0.0:8787->8787/tcp   xenodochial_easley
```
docker logs:
```
➜  ~ docker logs 9647b901b587 
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying... 
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] add: executing... 
Nothing additional to add
[cont-init.d] add: exited 0.
[cont-init.d] userconf: executing... 
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by cboettig** [comment]
hmm, not sure, that looks ok.  A few questions: 

- I don't think you want to combine the `--rm` and `-d` options, if you're running in background/daemonized (`-d`) omit the auto-remove.

- It would be useful to see `docker ps` output after you launch the container, and also `docker logs` for the instance.  

just confirm ubuntu is the native OS, you're not running ubuntu in, say, a virtualbox vm or docker toolbox instance?  You've checked any firewall setup on your machine etc?

**Comment by dkincaid** [comment]
Well, I just found the problem. My corporate VPN is blocking something here. When I disconnected the VPN it now comes up. My apologies for wasting anyone's time.

**Comment by eddelbuettel** [comment]
No worries, it happens. It is good to minimise the setup to exclude such side-effects.

(and just to state the obvious, on Ubuntu you can run RStudio directly but I presume you are really just testing Rocker images...)
