### ISSUE TITLE
Some inconsistencies in comments

### ISSUE THREAD

**Issue by dmenne** [rocker-org/rocker#299]
https://hub.docker.com/r/rocker/tidyverse/~/dockerfile/

The comment is a bit outdated: ggplot(2) and rmarkdown are not or no longer included.

```
## Notes: Above install2.r uses --deps TRUE to get Suggests dependencies as well, 
## dplyr and ggplot are already part of tidyverse, but listed explicitly to get their (many) suggested dependencies. 
## In addition to the the title 'tidyverse' packages, devtools is included for package development. 
## RStudio wants formatR for rmarkdown, even though it's not suggested. 
## remotes included for installation from heterogenous sources including git/svn, local, url, and specific cran versions
```

**Comment by cboettig** [comment]
ggplot2 is included via tidyverse already, just not all of ggplot `Suggests` deps (which got a bit too bloated).  Was there something on the suggests list of ggplot2 that you wanted?

The `rmarkdown` comment is explaining why `formatR` is included and it is still accurate, `formatR` is still installed explicitly in the dockerfile.  Apologies for these comments being confusing, they were mostly for my reference.  https://tidyverse.org does a good job of defining what is in the tidyverse, and all those packages are here.

**Comment by dmenne** [comment]
It's fine, just trying to understand....

**Comment by cboettig** [comment]
hehe, me too. RStudio team has a habit of interpreting 'soft' dependencies somewhat liberally; I see why they do it but it's annoying when some function from the tidyverse wants me to install some additional package before it can run.  so this list does need to be revisited from time to time rather than just relying on the dependencies to sort themselves out automatically.

**Comment by cboettig** [comment]
Ah, for the record, I stopped pulling in the full `ggplot2` suggest list once it started suggesting `sf`, which is a really heavy package (particularly when you try to support it's full suite of features -- for which we already have the `rocker/geospatial` image).  ah, fun with dependency chains.
