### ISSUE TITLE
Enable plotting for r-base container via X-Forwarding

### ISSUE THREAD

**Issue by holgerbrandl** [rocker-org/rocker#302]
Since graphics are a main selling point of R it would be great if this would be possible when using the dockerized r-base image.  Currently nothing seems to happen, when doing
``` 
docker run --rm -it  rocker/r-base
plot(1:10)
```
The plot is rendered into Rplots.pdf within the container, but it's unclear how to access it.

I've noticed https://www.rocker-project.org/use/other_topics/ but it's unclear when "soon" might be.

**Comment by eddelbuettel** [comment]
You could run a Rocker container with RStudio Server, connect your webbrowser to it and enjoy that setup.  It includes all features of the RStudio IDE, including plotting.

`r-base` is just that: a base to build on, and to a first approximation head-less.  You can export X11 credentials as we "mention" but do not detail.  Any other Docker tutorial showing how to export X11 display should work.

**Comment by holgerbrandl** [comment]
I typically prefer the simple interactive command line shell.

I could not find a working tutorial which details out the processing of exporting credentials on a mac and/or linux machine. Could you point me to something that worked for you?

**Comment by eddelbuettel** [comment]
I work natively on Linux and do use Rocker's r-base that way as I use it for headless tasks. 

If you prefer the shell, then why not plot to file and view those?  If you want interactivity, use RStudio as I mentioned, or run R natively.  The `r-base` Rocker containre is meant to be minimal; maybe you are projecting less-than-ideally-matching expectations onto it.

**Comment by eddelbuettel** [comment]
A [standard Google search](https://www.google.com/search?q=stackoverflow+docker+x11&oq=stackoverflow+docker+x11) leads to [one popular StackOverflow answer](https://stackoverflow.com/a/25334301/143305) which I followed step by step and all is good:

![image](https://user-images.githubusercontent.com/673121/44313991-e4fecc80-a3d7-11e8-896e-294c8c572962.png)

The plot window comes from the container and appears on my (x11) desktop.

(I had done another search query a few days ago with adding 'stackoverflow' as the term and also arrived at this one, this time I just revisited.)

If you have some spare energy, maybe review this and contribute a write up for our wiki and/or the website?  I am closing this question now as there it nothing missing in Rocker per se...

**Comment by wds15** [comment]
I just went through setting up rocker on my Mac in a way so that I can use TRAMP from Emacs and get plots being displayed over the X11 protocol. How should I contribute these instructions?

In a nutshell:

- add an sshd to the image and make that startup
- open up XQuartz on macOS to allow connects from the network
- send X11 traffic to the "right place"

It's not super fast as the X11 protocol is send over the network (despite being local). On Linux one can - as I read - mount the X11 socket into the container for better speed, but that's is not an option in macOS.

In case there are better (faster) plotting options which come to mind, then these should be considered, but I don't know any (possibly via http given RStudio goes over that layer).

**Comment by eitsupi** [comment]
@wds15 Hi, would you like to try [the httpgd package](https://github.com/nx10/httpgd)?
https://github.com/rocker-org/rocker-versioned/issues/136#issuecomment-878175787

**Comment by wds15** [comment]
This looks super cool! Will try this out and get back to you. Thanks for the pointer.

**Comment by wds15** [comment]
I just produced my first few plots with this backend... very impressive work. I would like to configure this as the default device in the docker image. However, for that it would be great to make the default address and the default port go the had call configurable via the usual "options" mechanism. This way I can set these options up as part of the image and ease the startup. For now I will work around it with a custom R function for the startup.

From the very first plot I did, I got the impression that transmission speed is a bit delayed as compared to X11 raw device, but it's much better than my current setup and the plotting quality is great. I still have to find out how stable this thing is in a daily use environment (which is something the X11 protocol forwarding was not great). In any case, I like so far a lot what I see! Thanks for pointing this thing out.

**Comment by eitsupi** [comment]
Yes, I also think being able to set the address and port to be displayed in the option would be very useful in the use case of using it in Docker containers.
If you like httpgd, the author may be happy to discuss it in an issue. (like https://github.com/nx10/httpgd/issues/66)
