### ISSUE TITLE
Better Docker ergonomics: fail when package installation fails

### ISSUE THREAD

**Issue by davclark** [rocker-org/rocker#306]
I started talking to folks on Twitter about this, and realized that my use-case is pretty similar to your own reproducible R via Docker mission... so similar in fact that I assumed the install2.r script would be the solution! But interestingly, that script also returns a non-error 0 code even when package installation fails. This is in stark contrast to other command-line package management operations, where an error code is returned when installation fails, thus causing a RUN line to fail in a Docker build as well (which I would see as the right behavior, or at least a behavior that I can get easily).

Indeed, it's not TOO hard to do something like the following:

```{r}
if(!devtools::install_github("some_repo/some_package")) q(status=1)
```

But that gets really hard to read if you're putting it directly into your docker file. So, anyway, I'll put together what I think is a reasonable approach, but wanted to drop in here and see if you've already thought / done stuff about this.

Unless you tell me not to, I'll also share what I'm doing back here!

**Comment by cboettig** [comment]
reading quickly here about to get off a train -- I think you're looking for the `--error` flag in `install2.r` ?

**Comment by eddelbuettel** [comment]
If so there are a few use cases across different Dockerfiles.

**Comment by davclark** [comment]
Thanks for pointing that out @cboettig! That does indeed do exactly what I was asking about. I think I missed it because I was reading quickly and looking for q() or quit() instead of stop().

I'm still thinking about some functionality that would make a more efficient package installer for R (and that would be relevant also to your use case - as you can also assume a fairly specific configuration of a linux distribution). But I'll close this issue for now and loop back when I have more to share!
