### ISSUE TITLE
Cannot install system packages with apt-get into a running container on rocker/tidyverse

### ISSUE THREAD

**Issue by theclue** [rocker-org/rocker#307]
Hi,

I'm crafting my custom Dockerfile starting from rocker/tidyverse:latest

No problems while installing additional packages using apt-get from Dockerfile

But when I try to do the same from a exec bash interactive session of a running container (for ex. curl), for testing my env, no remote packages seems to be found (ie "Unable to find package curl" error).

Aside that, the image works perfectly (also the network is ok)

tnx allot for your support and providing such fantastic images to the community!
gabriele

**Comment by cboettig** [comment]
@theclue Sorry about that.  R is installed from source on these images and thus won't play nicely with R packages installed from binary; see https://github.com/rocker-org/rocker-versioned#notes.

We recommend you simply install R packages with `install.packages()` or `install2.r` script, as you'll see we do in, e.g. the [tidyverse Dockerfile](https://github.com/rocker-org/rocker-versioned/blob/master/tidyverse/Dockerfile).  (This will ensure consistent / latest versions of the packages being installed, though it can require a little extra work if the package needs a system library that's not already installed.)  

Please chime back in here if any of this is unclear; still working on clarifying the docs.  Note that if you use the `r-base` image, you can install R packages from apt-get no problem.

**Comment by theclue** [comment]
Sorry, i think i was not clear in my report (just fixed the title). Although your clarification was still useful on its own hands :)

what I meant is that it's not possible to install _system_ packages at runtine, not _R_ packages

![image](https://user-images.githubusercontent.com/1724406/45593641-be0dc900-b98a-11e8-963f-1b4a8eefafae.png)

**Comment by obarisk** [comment]
You have to 
```
apt-get update
```
or 
```
apt update
```
To get package information first.

**Comment by theclue** [comment]
Gosh...tnx...i'm feeling really stupid atm.

I forgot I added a rm command to clean the apt registry in my Dockerfille

Sorry for reporting such a stupid thing and tnx for support.
