### ISSUE TITLE
Install ODBC on this container

### ISSUE THREAD

**Issue by pchiguvare** [rocker-org/rocker#308]
How do i install OBDC package on this container? I would like to connect to a remote sql server install. 

I am getting the error below: 

![image](https://user-images.githubusercontent.com/25052905/46609794-41918480-cb09-11e8-9f9b-8cfb81f1db81.png)

**Comment by eddelbuettel** [comment]
Remember that ODBC requires _two_ drivers on your system: first the ODBC driver to connect to an ODBC-compliant server and API, but also the ODBC driver for the given DB system to talk to actually exporting OBDC streams.

So in short we'd have to support half a dozen SQL backends.  This probably done better in a derived container.

**Comment by cboettig** [comment]
Which container are you using?  You’ll find these already installed in rocker/tidyverse
