### ISSUE TITLE
Change R_LIBS_USER to a custom directory

### ISSUE THREAD

**Issue by vnijs** [rocker-org/rocker#311]
Changing the value of `R_LIBS_USER` seems to work fine adding the command below, which I copied from /etc/R/Renviron and customized, to the Dockerfile. However, now `Sys.getenv("R_LIBS_USER")` returns `~/.rsm-msba/R/@R_PLATFORM@-library/@MAJ_MIN_VERSION@` without expanding `@R_PLATFORM@` or `@MAJ_MIN_VERSION@`. Is there perhaps a way around this?

```
RUN echo "R_LIBS_USER=${R_LIBS_USER-'~/.rsm-msba/R/@R_PLATFORM@-library/@MAJ_MIN_VERSION@'}" >> /etc/R/Renviron
```

My current workaround is to use the code below but that seems a bit iffy

```
RUN sed -i -e 's/~\/R\/x86_64/~\/.rsm-msba\/R\/x86_64/' /etc/R/Renviron
```

**Comment by eddelbuettel** [comment]
If I understand you correctly, this is a *feature* as the _environment variable_ is a system _constant_ whereas what R does _at run-time_ is in fact interpolated to what that R version -- now e.g. 3.5, in a year 3.6.

**Comment by vnijs** [comment]
Hmmm. I'd expect that `Sys.getenv` would then also expand `@R_PLATFORM@` and `@MAJ_MIN_VERSION@` in the customized command. It doesn't seem to however.

**Comment by eddelbuettel** [comment]
It's a wrapper to a system which just fetches the value.  It brings it to R and which point someone (you?) could deal with the interpolation...

**Comment by vnijs** [comment]
OK. Thanks @eddelbuettel. I'll look into this more
