### ISSUE TITLE
Error response from daemon: manifest for rocker/r-apt:latest not found

### ISSUE THREAD

**Issue by layik** [rocker-org/rocker#313]
Am I missing something?

**Comment by eddelbuettel** [comment]
What command are you trying to run?  Are you assuming there would be a `:latest` when maybe there isn't?

```sh
rob:~$ docker pull rocker/r-apt:bionic
bionic: Pulling from rocker/r-apt
124c757242f8: Already exists 
9d866f8bde2a: Already exists 
fa3f2f277e67: Already exists 
398d32b153e8: Already exists 
afde35469481: Already exists 
b65a6fbf71f3: Pull complete 
d7da221d8ed4: Pull complete 
8ab04b077524: Pull complete 
4dd4138351d1: Pull complete 
Digest: sha256:e5d21f8d5f840154dea1f3f1d9adb5b874ecbcfc03af59decc7caa6a70bfd5e4
Status: Downloaded newer image for rocker/r-apt:bionic
rob:~$ 
```

This is also a rather specialised container (series).  It may not do what you think it does.

**Comment by layik** [comment]
Thanks for all your efforts @eddelbuettel, I am new to the whole rocker world and trying to install as many packages as I can using binaries. Hitting few bumps along the way.

To answer your question yes, I was trying to `docker pull rocker/r-apt` as one would from looking at the hub [page](https://hub.docker.com/r/rocker/r-apt/).

**Comment by layik** [comment]
Not sure how I should contribute this bit to other people who might want to have access to those ~4k binaries. Any tips would be great @eddelbuettel.

**Comment by eddelbuettel** [comment]
Well to blunt you misunderstand completely (as did a recent tweet).  This container has *nothing* to do with that.

*Any* suitable Ubuntu installation, container or real, can point to that repo.  And BAM there are your 4k package.  The fact that this container has `apt` in its name *means something completely different*.

In short, you are looking at the wrong place. Start [maybe here](https://cloud.r-project.org/bin/linux/ubuntu/README.html), read some Ubuntu/Debian docs about add repositories and if you need help ask on `r-sig-debian`.

**Comment by layik** [comment]
Right, I did start there and I failed. Will start again, I added two lines to the wiki, which might also need a reset, I will see if I can do it myself. Thanks for your time.

**Comment by eddelbuettel** [comment]
What wiki? I have no idea what you are talking about.

If you find Michael's write-up unclear, or missing something, may I suggest you to Michael, not me?

For *all* the rest please use the `r-sig-debian` list (subscribe first) not this ticket which I will now lock.  It is not the place for this discussion. Honestly.

**Comment by eddelbuettel** [comment]
I'll try to clarify the README for rocker-apt, and maybe create the container you really wanted for 18.04.
