### ISSUE TITLE
unable to install some R packages

### ISSUE THREAD

**Issue by fionarhuang** [rocker-org/rocker#314]
Hi, 

I tried to launch R directly for interactive work, and found some packages can't be installed.

Here are the commands I have run.
`$ docker run -ti --rm r-base`
In the R, 
`install.packages("BiocManager")`
`library(BiocManager)`
`install("tximeta")`

**Comment by eddelbuettel** [comment]
And?  `r-base` contains the term 'base', it is meant to say "not comprehensive".

You are likely missing some build dependencies _for the particular package you are after_. Not really our bug. 

You would need to install them first, maybe even create an augmented Docker container.  But this is not the place for a tutorial on that.
