### ISSUE TITLE
Support for Rstudio 1.2

### ISSUE THREAD

**Issue by alexhallam** [rocker-org/rocker#317]
Thanks for the great docker image. I use `rocker` all of the time!

I am currently wanting to test Rstudio Server with iOS. Extra support for iOS, such as functioning arrow keys, are [merged](https://github.com/rstudio/rstudio/pull/2508) with [Rstudio 1.2](https://www.rstudio.com/products/rstudio/download/preview/). 

Are there plans to make an rocker image with Rstudio 1.2?

**Comment by cboettig** [comment]
Ok, `rocker/rstudio-daily` is now set to give you the daily build of RStudio with `latest` R release (e.g. 3.5.1 tag right now).  `rocker/rstudio-daily:devel` gives you R-devel, so the tagging convention is now consistent with that used by the `rocker/rstudio` image. (may be a delay before Docker ~~Hub~~  Cloud builds these).   Ed, does this work for you?  

Re `devel` version, it's whatever the svn `devel` gives me (e.g. Unsuffered Consequences), I'm actually not sure if that corresponds to 3.5.2 or 3.6.0 right now; you or Dirk probably know better.

**Comment by eddelbuettel** [comment]
Should be the 'release candidate' of R 3.5.2 due Dec 20 with R 3.6.0 further out -- likely April.

**Comment by znmeb** [comment]
Ah - the release candidate is the one I want - thanks!!

**Comment by cboettig** [comment]
great!  So `rocker/rstudio-daily:devel` should be what @znmeb wants now (looks like hub has built the updated images), and `rocker/rstudio-daily:latest` should be a good choice for @alexhallam and anyone wanting RStudio 1.2 while still on the current R release.
