### ISSUE TITLE
Slower Execution in verse docker as compared to Execution of script in Rstudio server ubuntu

### ISSUE THREAD

**Issue by sfahad1414** [rocker-org/rocker#321]
I executing the script which use doparallel to use lime package for model explanation but it work fast on rstudio server running on ubuntu it takes 17 seconds but via docker it takes 50 seconds

**Comment by cboettig** [comment]
One would really need a lot more information regarding the choice of compilers, BLAS libraries, etc to understand what is going on here.  You can easily see how these are configured in our Dockerfiles and compare to your local environment.  These images are made to be general-purpose and are not tuned for maximum performance, though it is quite possible you could significantly improve the performance in certain contexts with different choices.  Stackoverflow might be a better venue for general-purpose questions benchmarking different software configurations.
