### ISSUE TITLE
Coudn't use source function on RStudio editor

### ISSUE THREAD

**Issue by seufagner** [rocker-org/rocker#322]
Hi,

How i can `source` some file, at the same path, from RStudio editor?

I got this error:
`source("/Home/edumobi/somos_common_functions.R")`

> Error in file(filename, "r", encoding = encoding) : 
>   cannot open the connection
> In addition: Warning message:
> In file(filename, "r", encoding = encoding) :
>   cannot open file '/Home/edumobi/somos_common_functions.R': No such file or directory
>

**Comment by obarisk** [comment]
what `getwd()` shows.

**Comment by seufagner** [comment]
Thank you for your quick response
*/Home/edumobi/s* path

**Comment by seufagner** [comment]
> what `getwd()` shows.

Thank you for your quick response
/Home/edumobi/s path

**Comment by eddelbuettel** [comment]
Can we close this?

**Comment by seufagner** [comment]
The file exists there, but it not found

**Comment by eddelbuettel** [comment]
I fail to see where you demonstrated that this is a bug in our container -- as opposed to you being at a loss about how to navigate directories to find files.
