### ISSUE TITLE
how do you set a unique password during docker build rather than at runtime?

### ISSUE THREAD

**Issue by vsrdharca** [rocker-org/rocker#323]
Hello:

I have a custom docker image built from rocker/rstudio. When I build the image I run "RUN usermod --password $(echo passwordisnotdefault | openssl passwd -1 -stdin) rstudio" in the Dockerfile to change the default password for the rstudio user.

When I deploy the docker image to GCP VM running Container-Optimized OS I get an error complaining that I must a unique password not the default rstudio (see log snippet below).

I would appreciate any help please.

docker logs --follow --timestamps c96aa7a62a6a |more

2019-01-11T21:46:46.921216022Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
2019-01-11T21:46:47.016614645Z [s6-init] ensuring user provided files have correct perms...exited 0.
2019-01-11T21:46:47.018362606Z [fix-attrs.d] applying ownership & permissions fixes...
2019-01-11T21:46:47.026735679Z [fix-attrs.d] done.
2019-01-11T21:46:47.027113285Z [cont-init.d] executing container initialization scripts...
2019-01-11T21:46:47.030273389Z [cont-init.d] add: executing... 
2019-01-11T21:46:47.036007993Z Nothing additional to add
2019-01-11T21:46:47.037117925Z [cont-init.d] add: exited 0.
2019-01-11T21:46:47.038968086Z [cont-init.d] userconf: executing... 
2019-01-11T21:46:47.053210949Z 
2019-01-11T21:46:47.053338037Z 
2019-01-11T21:46:47.054969127Z ERROR: You must set a unique PASSWORD (not 'rstudio') first! e.g. run wit
h:
2019-01-11T21:46:47.055126923Z docker run -e PASSWORD=<YOUR_PASS> -p 8787:8787 rocker/rstudio

**Comment by vsrdharca** [comment]
@cboettig Much thanks for your reply. We basically don't use the default rstudio user at all. Users use their own linux login id and password to access the container app. 

Thanks for that environment variable. I am presume Google GCP automatically starts the container via CMD ["/init"] defined in the Dockerfile. Do you know if I can define the DISABLE_AUTH=true flag in the Dockerfile or another way of passing this to the container startup?

**Comment by cboettig** [comment]
@vsrdharca I believe you can set custom environmental variables for GCP, see https://cloud.google.com/functions/docs/env-var.  I think it would work to set `DISABLE_AUTH=true` in the image build if you wanted to, but that seems hack-y to me.  Setting environmental variables is probably the most common way to handle these things, so I think it would be worth considering setting  password at runtime this way as well.

You can set a custom username at runtime, though it sometimes creates issues; in general for setups where each user has their own container we tend to just set custom passwords and leave all users with the default `rstudio` name.

**Comment by vsrdharca** [comment]
@cboettig Thanks. I'll give this a try by setting env variables.

**Comment by cboettig** [comment]
May not have had the best link, try https://cloud.google.com/compute/docs/containers/configuring-options-to-run-containers#setting_environment_variables

**Comment by vsrdharca** [comment]
@cboettig Thanks for the link. Setting the environment variable in the instance config works.

If we didn't want to open up the session by setting DISABLE_AUTH=true and if we wanted the users to use their linux accounts on the instance would you recommend setting the PASSWORD environment variable for the rstudio user which would launch the instance and then each user can log in using their own linux credentials?

Would you have any other best practice suggestions where would would have 1 GCP instance and multiple users sharing the rocker/rstudio container?

**Comment by cboettig** [comment]
yup, that's exactly what I do with my classroom -- custom rstudio user pw and then a script to create user accounts.

**Comment by vsrdharca** [comment]
Thank you @cboettig
