### ISSUE TITLE
get the lovely r-rmd a qpdf

### ISSUE THREAD

**Issue by rnuske** [rocker-org/rocker#325]
I dearly love the new `r-rmd` docker container and use it in a continuous integration tool (drone.io) to check the package [komaletter](https://github.com/rnuske/komaletter). Which is -I believe- very close to the raison d'être of `r-rmd`.

`r-rmd` builds vignettes perfectly. But I would like to also do check `--as-cran`. Which currently produces a [warning](https://cloud.drone.io/rnuske/komaletter/3/1/2) complaining about `qpdf`missing. 

If I understood the discussion in [linl](https://github.com/eddelbuettel/linl/pull/20) correctly, `r-rmd` was created to build vignettes and thus provides already knitr, rmarkdown and some texlive. Wouldn't `qpdf` be a natural fit to `r-rmd`?

**Comment by eddelbuettel** [comment]
Howdy -- I think I saw that when you kindly linked back.   `qpdf` is indeed small and cheap so I will add it.

As I have you here:  I recall glancing at your repo and not understanding why you were using three different CI services.  Care to clue me in?

**Comment by rnuske** [comment]
Thanks a lot!

Oh, well...

`Travis` is a traditional and was easy to start as a newbie **w/o vignettes**. `AppVeyor` does windows builds. And `Drone` is the new cool kid which I got to know via [gitea](https://github.com/go-gitea/gitea) and just had to give it a try. So, i guess they just accumulated.

**Comment by eddelbuettel** [comment]
Love `gitea` too, followed it and `gogs` for some time.

May have looked at `drone.io` at some point in the past.  I think even Azure now tries to lure us...  

And yes, "bring your own container" is the best.  Will make this one better.

**Comment by rnuske** [comment]
We use `gitea` internally and it's proving valuable.

**Comment by eddelbuettel** [comment]
Looked again at drone.io and remain confused about the pricing plan: 'free' is limited to 5 users, 5 repos?

**Comment by rnuske** [comment]
hmm, `R CMD check --as-cran` now [complains](https://cloud.drone.io/rnuske/komaletter/4/1/2) about missing GhostScript executable.

It seems to be even smaller than qpdf. Could you add `ghostscript` as well?

**Comment by eddelbuettel** [comment]
Re hosting: noted. Makes sense for the local gitea then.  That is actually even more compelling:  local "fancy" githost _and_ local CI? Neat.

I'll add `ghostscript`.

**Comment by rnuske** [comment]
works perfectly now.

Thanks a lot!
