### ISSUE TITLE
GitLab Pages cause Error with r-ver

### ISSUE THREAD

**Issue by surmann** [rocker-org/rocker#327]
I'm using GitLab pipelines with `rocker/r-ver` because this is the most minimalistic container with different versions.

It works fine to check my package: [GitLab Pipeline](https://gitlab.com/surmann/CornerstoneR/-/jobs/157165821)
However, it fails when using pkgdown to deploy static help pages: [GitLab Pipeline](https://gitlab.com/surmann/CornerstoneR/-/jobs/157165824)
These pipeline uses the following gitlab [yml](https://gitlab.com/surmann/CornerstoneR/blob/086903633f882dd33fe807ede13510494238b996/.gitlab-ci.yml) file.

I changed the image to `rocker/rstudio` and `pkgdown` runs like a charm: [GitLab Pipeline](https://gitlab.com/surmann/CornerstoneR/-/jobs/157190310)
The last pipeline uses this [yml](https://gitlab.com/surmann/CornerstoneR/blob/59c127d9880ac92df0c14a460d81bb1310de6a99/) file.

Do you have an idea about this issue?

**Comment by cboettig** [comment]
`pkgdown` probably requires some system libraries that aren't included in the very minimalistic `r-ver` image.  You'll either need to install these yourself, or simply use one of our prebuilt images like `rocker/rstudio` that already has them.  Sounds like you already have that working!

**Comment by surmann** [comment]
You are right, it´s working with `rocker/rstudio`. However, I would like to understand what is missing to get `pkgdown` to work with `rocker/r-ver`. For me it is important to know what is missing because I don't use the functionality of RStudio inside this container.
For instance, I switched form `rocker/tidyverse` to `rocker/r-ver` and saved a traffic of seven times 400 MB but had to install three libs manually. This made my pipeline much more efficient.

Do you have an idea what is missing to solve the error with `rocker/r-ver`?

**Comment by cboettig** [comment]
You can just check the RStudio Dockefile to see what it installs, though I'd bet you at least need libcurl dev libs, e.g. https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/3.5.2/Dockerfile#L18, and also  libssl-dev (for the openssl dependency).  It's almost always something from apt-get lines that you'll want to add to your image.   

Note that pkgdown has incredibly heavy dependencies, I think you'll find once you fully install those you aren't saving all that much by starting on r-ver.  I'm sure you can get a lighter image if you're willing to work at it, but you'll want to be pretty familiar with managing linux dependencies to go the route of rolling your own image. Note that Stackoverflow is probably a better place for general linux+R install help if you want to go that route...

**Comment by surmann** [comment]
Ok, thanks!
