### ISSUE TITLE
r-parallel

### ISSUE THREAD

**Issue by HenrikBengtsson** [rocker-org/rocker#328]
UPDATE 2019-03-25: We now have https://hub.docker.com/r/rocker/r-parallel

I'd like to propose my https://github.com/HenrikBengtsson/r-base-parallel to be transferred to rocker-org.  It's is a Docker image (based on rocker/r-base) that provides packages for parallel processing in R.

**Comment by eddelbuettel** [comment]
(Henrik and I had chatted via DM.)

Minor nits re Dockerfile:  Many sequential commands can be chained into one; `install.r` takes multiple arguments and `install2.r` will even install in parallel. 

But in general: thumbs up.  Thoughts, @cboettig ?

**Comment by HenrikBengtsson** [comment]
> Minor nits re Dockerfile: Many sequential commands can be chained into one; ...

I'm quite a rookie when it comes to "optimize" Dockerfile:s.  I tried to put lightweight, rarely changing packages on top since those layers will be updated less frequently and thereby also won't have to be redownloaded that often. But, I don't have an objection to install everything in fewer lines.

**Comment by cboettig** [comment]
:+1: This looks very good to me as well.  Yup, had the same thought about chaining -- back in the early days of Rocker the total cap on number of layers you could have was way tighter, so our style tends to reflect that.  

Wonder if a bit more in the README might help outlining the frameworks covered here (or just linking to other resources) would help?  

@eddelbuettel any take on installing these from source vs apt-get here?  Since they'll be prebuilt by the image it probably doesn't matter.

**Comment by cboettig** [comment]
@HenrikBengtsson oh, one thing you do want to do is be sure the `apt-get update` is on the same line as the `apt-get install` commands.  You don't want `update` to be cached and `install` not to be.

**Comment by HenrikBengtsson** [comment]
I've updated Dockerfile to use `apt-get update` & `apt-get install` on the same line;

https://github.com/HenrikBengtsson/r-base-parallel/blob/59d777f67fadb912b2a5e885c2f981b0741ca443/Dockerfile#L8-L11

I've also updated the README with some basic examples for parallelization.

**Comment by HenrikBengtsson** [comment]
Regarding dependencies on upstream `r-base` or `r-ver`; if there will be support for both in the future, is there a naming convention to follow?  Should I rename `r-base-parallel` to `r-parallel`, or even just `parallel`?

**Comment by cboettig** [comment]
LGTM.  good question on names, maybe `parallel` or `r-parallel` is better?  Might just be me but `r-base-parallel` makes me think of an image that is tweaking the way base R is built to use parallel libraries, rather than adding parallelization packages on top

**Comment by eddelbuettel** [comment]
Maybe `r-partools` or something?  But that may be a package name we'd clobber. [Check. Indeed, by Norm.]

Something along those lines? Ideas?

**Comment by HenrikBengtsson** [comment]
I went ahead and renamed it to [`r-parallel`](https://github.com/HenrikBengtsson/r-parallel).

I'd like to keep the `r-` prefix such that the repos name reflects that we're dealing with R, e.g. when forked by some where their user/org name doesn't suggest R, but also for the default name when if pulled down as a Singuarity image file (`singularity pull docker://henrikbengtsson/r-parallel` then launching R in this image using `./r-parallel.simg`, cf. `R`).

About `-parallel`: I think `r-parallel` reflects the intention fairly well and since the `parallel` package is already part of the core distribution, there's (hopefully) little risk for confusions.

I'm open for alternative, if there are objections to `r-parallel`.

**Comment by eddelbuettel** [comment]
Carl's point is a good one. I think the name is too generic and will misleads newbs into expecting a parallel interpreter.  But maybe I am too paranoid.

OTOH it has a nice ring and simplicity -- and to us it is clear what it means.

**Comment by HenrikBengtsson** [comment]
I read Carl's comment as a concern about `r-base-*` rather than `*-parallel`.  

hehe ... I think you're paranoid :P  `r-parallel-extras` but that suggests there's a `r-parallel` in the first place.

**Comment by HenrikBengtsson** [comment]
I've updated the [README](https://github.com/HenrikBengtsson/r-parallel/blob/master/README.md) with more examples.  Let me know if there's anything else I can do here.

**Comment by HenrikBengtsson** [comment]
A friendly bump ...

**Comment by cboettig** [comment]
LGTM

**Comment by eddelbuettel** [comment]
@cboettig Shall we merge?

**Comment by cboettig** [comment]
yup, full steam ahead 🚢

**Comment by HenrikBengtsson** [comment]
Great. What should the next step be? Should I transfer my GitHub repos to the rocker-org organization, or how is "transfer/merge" done?

**Comment by HenrikBengtsson** [comment]
Another friendly bump/ping. How to proceed now?

**Comment by eddelbuettel** [comment]
I am not sure. Maybe transfer to the org is what is needed.

@cboettig ?

**Comment by cboettig** [comment]
yup, transfer seems like the way to go.  then I can set up an autobuild on hub/cloud

**Comment by HenrikBengtsson** [comment]
Ok, I just attempted a 'Transfer' but it says that is only possible if I already have privileges to create a repos in the receiving organization.  So, I guess I need to be added to some rocker-org team.

**Comment by cboettig** [comment]
Ah right, ok, invite sent

**Comment by HenrikBengtsson** [comment]
Invite accepted.  Still lacking permission to create a repos though ("You don’t have the permission to create repositories on rocker-org").  That's also what I get when I try to create a fresh repos ("insufficient privileges" )

**Comment by cboettig** [comment]
yeah, I think I can only change your privileges after you accept.  should work now?

**Comment by HenrikBengtsson** [comment]
Success. Transferred. I'll try to push updates of README (to use rocker-org) next.

**Comment by HenrikBengtsson** [comment]
README updated (https://github.com/rocker-org/r-parallel/commit/388161b71534aef6c2904977bb3e25a2916ede73).

Are you pushing to/bringing it into Docker Hub?

**Comment by cboettig** [comment]
yup, up on hub https://cloud.docker.com/u/rocker/repository/registry-1.docker.io/rocker/r-parallel

**Comment by HenrikBengtsson** [comment]
Thxs - great. Now I also see https://hub.docker.com/r/rocker/r-parallel (placeholder for now).  Is there something else you need me to do right now?

**Comment by eddelbuettel** [comment]
Looks like someone (you?) needs to define a build rule. We have mix of 'build on commit to underlying repo' as well as a finely woven mesh of 'build if something else built' over in Carl's corner.  I think starting with the simplest build when committed (or triggered) should be fine.

**Comment by eddelbuettel** [comment]
Do we have to add Henrik to the Docker Hub / Cloud group for Rocker as well?

**Comment by cboettig** [comment]
It's in the build queue, but yeah, we should create a Docker Cloud group as well. @HenrikBengtsson , what's your Docker Cloud username?

**Comment by HenrikBengtsson** [comment]
I'm https://hub.docker.com/u/henrikbengtsson

Will be offline soon - on my way to PG

**Comment by cboettig** [comment]
no worries, the build is in the queue already, sometimes the new cloud queue can be real slow.  You should have management privileges over  https://hub.docker.com/r/rocker/r-parallel  now too

**Comment by HenrikBengtsson** [comment]
Thanks. I've confirmed that `docker pull rocker/r-parallel` now works.

Docker Hub: I can now see 'rocker' under my https://cloud.docker.com/u/rocker/repository/list package.  However, when I go to [and rocker/r-parallel](https://cloud.docker.com/u/rocker/repository/docker/rocker/r-parallel/general), I don't seem to have any priviligies to update/edit things, e.g. I can edit neither the Description nor the Full Description.

**Comment by HenrikBengtsson** [comment]
Before I'm closing, note that:

> I don't seem to have any priviligies to update/edit things [in Docker Hub], e.g. I can edit neither the Description nor the Full Description.

It's not critical for now, but might be needed later if the README need to be updated
