### ISSUE TITLE
r-base:3.4.3 is actually 3.4.2

### ISSUE THREAD

**Issue by jakegalson** [rocker-org/rocker#329]
When running the following:

docker run -ti --rm r-base:3.4.3

It is actually R version 3.4.4 that is run instead of version 3.4.3, so the tag appears to be incorrect. I cannot find a tag that runs 3.4.3.

**Comment by eddelbuettel** [comment]
Yes, please see old issues here or in the other Rocker repos.  We since tightened the regular expression to avoid getting bitten by inadvertent rolls to newer versions.

**Comment by cboettig** [comment]
ps if you really need 3.4.3 you can always use rocker/r-ver:3.4.3
-- 
---
Carl Boettiger
http://carlboettiger.info/
