### ISSUE TITLE
r-apt:xenial has an out of date r-cran-rcpp

### ISSUE THREAD

**Issue by mculhane1** [rocker-org/rocker#330]
1. Ubuntu Xenial
2. r-apt:xenial
3. docker build .
4. Successful build
5. Build failed with this message 
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : namespace ‘Rcpp’ 0.12.19 is being loaded, but >= 1.0.0 is required

Since Rcpp was recently updated, the r-apt:xenial build needs to be rerun. This is currently breaking any container built off r-apt:xenial that uses dplyr.

**Comment by eddelbuettel** [comment]
"5\. Build failed" is not reproducible.  If you do derived work, maybe install an update Rcpp first?

**Comment by eddelbuettel** [comment]
Also, it is refreshing to see this being used as a base layer but ... I happen to be the one who built these and I never meant them to be used as a base layer, and never advertised or recommended that use.  

I think of Rocker's r-base that way, and use it that way.

These containers are/were for poking into the set of prebuilt r-cran-* packages and if/when/where those may be good for deployment is a whole different discussion.

**Comment by mculhane1** [comment]
I can fix this on my side, I was just adding the issue given that r-cran-rcpp is specifically installed in the r-apt dockerfiles.

I'm not sure I'd recommend anyone else use these how we are either, but they do work well enough for our purposes.

**Comment by eddelbuettel** [comment]
Rcpp is needed and used by the RcppAPT package installed on these, giving them the name.

I'll trigger an update unless I get distracted and forget.

**Comment by eddelbuettel** [comment]
The `xenial` container is fine.  If you want to straddle this weird mix of an outdated LTS (bionic is current, xenial is ancient) while at the same requiring bleeding edge CRAN components then you certainly can -- but it is up to you to run `apt-get update; apt-get dist-upgrade`.  After which

```
root@7ef6ae3a6cf0:/# apt-cache policy r-cran-rcpp
r-cran-rcpp:
  Installed: 1.0.0-1ubuntu2~ubuntu16.04.1~ppa1
  Candidate: 1.0.0-1ubuntu2~ubuntu16.04.1~ppa1
  Version table:
 *** 1.0.0-1ubuntu2~ubuntu16.04.1~ppa1 500
        500 http://ppa.launchpad.net/marutter/c2d4u/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     0.12.3-1 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
root@7ef6ae3a6cf0:/#
```

Is that not good enough?  I think we can close this.  The container does what it promises it would do.
