### ISSUE TITLE
Can't run rstudio in browser

### ISSUE THREAD

**Issue by HaroldNelson** [rocker-org/rocker#332]
I have tried to follow the instructions at https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image.

Here is my terminal session

Last login: Tue Mar 12 09:19:17 on ttys001
Harolds-Retina-Pro:~ haroldnelson$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
useR-vm   -        virtualbox   Running   tcp://192.168.99.100:2376           v18.09.3   
Harolds-Retina-Pro:~ haroldnelson$ docker-machine ip default
Docker machine "default" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
Harolds-Retina-Pro:~ haroldnelson$ docker-machine ip useR-vm 
192.168.99.100
Harolds-Retina-Pro:~ haroldnelson$ sudo docker run -d -p 8787:8787 -e PASSWORD=xxxxxx --name rstudio rocker/rstudio
Password:
568d73504a5db8ceb56c55560fc35b2150c07b3ffa02979f51472a1acaea5edc
Harolds-Retina-Pro:~ haroldnelson$ 

This is what I get in trying to run from my browser (Chrome). This is after waiting 10 minutes.

This site can’t be reached 192.168.99.100 refused to connect.
Search Google for 192 168 100 8787
ERR_CONNECTION_REFUSED

This is macOS 10.14.2

Docker version  18.09.2, build 6247962

**Comment by cboettig** [comment]
It's no longer necessary to use `docker-machine` to access an RStudio server instance on a Mac (using Docker CE as you have).  `docker` is now running natively, so you will want to point your browser to

    localhost:8787

and not the the address giving by the docker-machine.  (Apologies that the wiki isn't up-to-date on this, we're volunteers and these details have continued to evolve.  Do see https://rocker-project.org for more up-to-date documentation).  It is actually possible to run over docker-machine instead, but probably not what you want to do.
