### ISSUE TITLE
Running docker inside the Rocker image

### ISSUE THREAD

**Issue by davisidarta** [rocker-org/rocker#333]
Hello there, rocker team! I love your image and I'm using it for some bioinformatics analysis in my local university server :)

However, I came to a problem latelly. One of the R packages I'm trying to use requires Docker (dyno, https://github.com/dynverse/dyno). It won't acknowledge its already running on a Docker container, which makes me believe I would have to run a docker instance inside the Rocker image for it to work.

I'm very sorry if this question is very basic (I'm quite new to dealing with Docker containers), but is there any way to do that?

I'm currently using the rocker:tidyverse image. The server runs on Ubuntu 18.04.2 LTS.

Best regards!!
Davi

**Comment by cboettig** [comment]
Unfortunately it's not possible out of the box. Though this can be done by modifying the container, it's usually unadvisable, see https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

On the other hand, it's very common to *compose* docker containers by having services provided in different containers all running at the same time, but on the same host, not nested in each other.  It might be worth contacting the `dynverse` folks about that; it seems likely that their software should be able to access any of the containerized services running in a separate container instead.  That approach is much cleaner and more reliable.

**Comment by znmeb** [comment]
@cboettig @davisidarta Hmmm ... the paper referenced above shows a possible implementation of something similar - a container starting other containers in the Docker host. It's also a security problem - there's lots of things like privileged containers to worry about - but you can start a Rocker container with the host socket mounted into it, install the Docker command line, and start another container on the host. I've done it - but again, it's not recommended for security reasons.
