### ISSUE TITLE
Environment Variables for rocker containers

### ISSUE THREAD

**Issue by pohndorff** [rocker-org/rocker#334]
I'm creating a container network using `docker-compose` for an upcoming workshop and was wondering about the available environment variables for rocker containers.

So far I only found `USER` and `PASSWORD` to setup login credentials. I also read about adding custom packages through environment variables but couldn't figure out how.

Is there any full list on available environment variables?
Thanks in advance!

**Comment by cboettig** [comment]
That's a good question, we should document those more clearly.  

For user configuration, there's `USER`, `PASSWORD`, `USERID`, `GROUPID`, `UMASK`, and `ROOT`
https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/userconf.sh#L4-L9

Also, there is `DISABLE_AUTH=true` for local use which skips needing to login with a password.  

Really there's no great need to set `USER` ever, and no need to set `USERID`, `GROUPID`, `UMASK` unless needed for matching permissions when volume binding.  `ROOT=true` will enable root permissions for the user (e.g. for apt-get), but use with care.

Lastly, there's the rather specialized and probably not ideal `ADD=shiny` which will install shiny on start-up (making the initial startup slow).  

Documentation for these has mostly mentioned them under the related task (e.g. https://www.rocker-project.org/use/managing_users/), but I don't think they all show up in one place.  Of course you can add other env vars or override existing env vars (like `MRAN` repo setting) as well.

**Comment by pohndorff** [comment]
Thanks for clearing that up. Your answer helped a lot.
