### ISSUE TITLE
Issues Installing some R Packages, even from CRAN list

### ISSUE THREAD

**Issue by apremgeorge** [rocker-org/rocker#335]
Docker in Windows
Getting errors installing some packages like tidyverse, mlr, devtools from CRAN list
Tried using *.tar.gz still showing same error
Tried installing XML, xml2 separately, getting "Cannot find xml2-config"

My PC have Rstudio, all packages were successful, I have used Rstudio Connect in browser it install perfect

Can you please help me on this, Thanks

1. tidyverse package
* installing *source* package ‘xml2’ ...
** package ‘xml2’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=
Using PKG_LIBS=-lxml2
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libxml-2.0 was not found. Try installing:
 * deb: libxml2-dev (Debian, Ubuntu, etc)
 * rpm: libxml2-devel (Fedora, CentOS, RHEL)
 * csw: libxml2_dev (Solaris)
If libxml-2.0 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libxml-2.0.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘xml2’
* removing ‘/usr/local/lib/R/site-library/xml2’
Warning in install.packages :
  installation of package ‘xml2’ had non-zero exit status
ERROR: dependency ‘xml2’ is not available for package ‘rvest’
* removing ‘/usr/local/lib/R/site-library/rvest’
Warning in install.packages :
  installation of package ‘rvest’ had non-zero exit status
ERROR: dependencies ‘haven’, ‘rvest’, ‘xml2’ are not available for package ‘tidyverse’
* removing ‘/usr/local/lib/R/site-library/tidyverse’
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

2. mlr package

* installing *source* package ‘XML’ ...
** package ‘XML’ successfully unpacked and MD5 sums checked
checking for ……………………...
checking for xml2-config... no
Cannot find xml2-config
ERROR: configuration failed for package ‘XML’
* removing ‘/usr/local/lib/R/site-library/XML’
Warning in install.packages :
  installation of package ‘XML’ had non-zero exit status
ERROR: dependency ‘XML’ is not available for package ‘mlr’
* removing ‘/usr/local/lib/R/site-library/mlr’
Warning in install.packages :
  installation of package ‘mlr’ had non-zero exit status

3. devtools package

See `config.log' for more details
ERROR: configuration failed for package ‘git2r’
* removing ‘/usr/local/lib/R/site-library/git2r’
Warning in install.packages :
  installation of package ‘git2r’ had non-zero exit status
ERROR: dependency ‘git2r’ is not available for package ‘usethis’
* removing ‘/usr/local/lib/R/site-library/usethis’
Warning in install.packages :
  installation of package ‘usethis’ had non-zero exit status
ERROR: dependencies ‘git2r’, ‘usethis’ are not available for package ‘devtools’
* removing ‘/usr/local/lib/R/site-library/devtools’
Warning in install.packages :
  installation of package ‘devtools’ had non-zero exit status

4. XML package
Cannot find xml2-config
ERROR: configuration failed for package ‘XML’
* removing ‘/usr/local/lib/R/site-library/XML’
Warning in install.packages :
  installation of package ‘XML’ had non-zero exit status

**Comment by eddelbuettel** [comment]
You are having elementary problems with installing from source; these are adddressed at length elsewhere see eg [here on StackOverflow](https://stackoverflow.com/questions/15292905/how-to-solve-the-error-missing-required-header-gl-gl-h-while-installing-the-p/) (and dozens like it).

You are also ignoring the fact that we give Rocker containers with `tidyverse` and whatnot, see our [RJournal paper](https://journal.r-project.org/archive/2017/RJ-2017-065/index.html).

Lastly, and I need to expand on this again, I showed on my blog how to install a _binary_ `r-cran-rstan` with all it depends (also on rocker) [in this post](http://dirk.eddelbuettel.com/blog/2017/12/22#014_finding_binary_deb_packages). You could modify that for `r-cran-tidyverse`, then install RStudio etc pp.

**Comment by apremgeorge** [comment]
Sorry for my basic questions, Thanks for the support, I am new to the Docker setup, so thinking of the installation path for packages, anyway thanks much appreciated.

**Comment by eddelbuettel** [comment]
No problem, but we don't have the bandwidth for explaining R on Linux, packages, installation, ...  There are other tutorials for that, and we need to focus on Rocker proper here.  As there is no bug in Rocker, I'll close this.  If you have an actual Rocker issue feel free to file another ticket.
