### ISSUE TITLE
Rocker container suddenly crashing by no apparent reason

### ISSUE THREAD

**Issue by davisidarta** [rocker-org/rocker#340]
Hello rocker team!

Recently I've noticed that the rocker container sometimes simply ceases to be, specially when I get stuff running overnight (which is quite frustrating).  The RStudio web API pops an "Disconnected from R Session" error and the following error appears in the HPC server log:

`
[rsession-rstudio] ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:563
`

I've searching this down and it seems to have something to do with RStudio Server itself. However, nobody seems to have solved it. Besides, it is a even bigger problem when this happens on a docker container, since any changes of modifications that happened can't be tracked and are lost.

Any hints?

**Comment by cboettig** [comment]
hmm, not sure, but would probably need more details to be helpful. I  have not observed a container "ceasing to be" before -- so the container is completely lost from the `docker ps -a` list when you return the next morning?  

Also, are you running the container using linked volumes to the host platform?
