### ISSUE TITLE
Running RStudio 1.3 on rocker/verse to improve iOS compatibility

### ISSUE THREAD

**Issue by bastianolea** [rocker-org/rocker#345]
Thank you so much for your work!

I have a problem choosing the correct container for using RStudio remotely on iPad, as the latest containers of `rstudio` and `verse` seem to have different RStudio versions:

On one hand, `rocker/rstudio-daily:devel` runs RStudio 1.3.322, which solves many compatibility issues on iOS, particularly a bug that made impossible to scroll on the source panel. But on the downside, I can't install certain packages on this container, particularly `jpeg`.

On the other hand, `rocker/verse:devel` has no problem installing `jpeg`, but it uses RStudio 1.2.1.335 so scrolling doesn't work correctly on iOS.

Is it possible to get a container of `verse` with a higher RStudio build, such as 1.3 just like `rstudiodaily:devel` does, in order to get the latest iOS compatibility fixes?

**Comment by cboettig** [comment]
@rndzvs yeah, we need better documentation on these topics.  `jpeg`, like many R packages, has system dependencies (libjpeg in this case) that need to be added using `apt-get` if the container does not already have them.  There's a few ways to do this:

If your container is already running, you can `docker exec` into it and then run `apt update && apt -y install libjpeg-dev` on your `rstudio-daily` container.  Or, you can enable root for your RStudio user [when you create the container](https://github.com/rocker-org/rocker-versioned/tree/master/rstudio#give-the-user-root-permissions-add-to-sudoers), and then do `sudo apt update && apt -y install ...` from the bash shell inside RStudio whenever you need to add a system library.  Lastly, you can create a custom Dockerfile that extends one of these base images and adds software you commonly use (just look at some of the current Dockerfiles for examples, e.g.  how `rocker/tidyverse` extends `rocker/rstudio`).  A bunch of this is covered in the rOpenSci Rocker tutorial too: https://ropenscilabs.github.io/r-docker-tutorial/

HTH

**Comment by cboettig** [comment]
we're on 1.3 now; & looking  forward to the 1.4 release
