### ISSUE TITLE
r-ubuntu pull command incorrect

### ISSUE THREAD

**Issue by csgillespie** [rocker-org/rocker#350]
At https://hub.docker.com/r/rocker/r-ubuntu the suggested pull command is

```
docker pull rocker/r-ubuntu
```
But this should be 
```
docker pull rocker/r-ubuntu:18.04
```
as the default looks for latest (that doesn't exist)

**Comment by eddelbuettel** [comment]
Would you know how to edit that hub.docker.com page?   I don't,

**Comment by csgillespie** [comment]
Could you create a `latest` image instead?

**Comment by eddelbuettel** [comment]
I guess when I set it up I feared that would be misleading.  This is for use with the PPAs, and those only come at LTS releases.   Hence not latest (ie 19.04 right now, or 18.10 before it) but just 18.04.

**Comment by csgillespie** [comment]
Ok. What about cheating and just updating the README ;)

**Comment by eddelbuettel** [comment]
Yes, will do.

**Comment by eddelbuettel** [comment]
See ff3cfd0
