### ISSUE TITLE
Installing latest R on docker 

### ISSUE THREAD

**Issue by germayneng** [rocker-org/rocker#351]
Hi, I am trying to install the latest R in my docker environment along with python. But i cant seem to install the latest r version.  i am not sure if this is the right place to ask but i am able to install the latest using your dockerfile directly. Issue is i want python as well in my docker env.

Here is my dockerfile: 

``` 
FROM tiangolo/python-machine-learning:python3.6

# Make port 80 available to the world outside this container
EXPOSE 80

# Set the working directory to /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
#RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN conda update conda
RUN conda install jupyter

RUN apt-get update
RUN apt-get install -y r-base
```

The result is my R is at: 

![image](https://user-images.githubusercontent.com/22788747/63338828-31c40d00-c376-11e9-8b99-19c31f3285d3.png)

**Comment by eddelbuettel** [comment]
This is not a problem with the Rocker Project, and I am leaning towards closing this.  You start from

```
FROM tiangolo/python-machine-learning:python3.6
```

and _you_ need to figure out how to start with that constraint.  _We_ here use Debian testing/unstable so you can / could add Python that way too -- and some of our containers already have Python:

```
edd@rob:~$ docker run --rm -ti rocker/tidyverse python --version
Python 2.7.13
edd@rob:~$ docker run --rm -ti rocker/tidyverse python3 --version
Python 3.5.3
edd@rob:~$ python3 --version
Python 3.7.3
edd@rob:~$ 
````

(Not sure why `tidyverse` is a 3.5; I am sure we could move it to 3.6 or 3.7 if we wanted to.)

We also have an entire set of [ML containers](https://github.com/rocker-org/ml).

**Comment by germayneng** [comment]
Thanks for the fast reply. Then i can build my image from here and am i able to install conda to manage python?

**Comment by eddelbuettel** [comment]
I cannot comment on mixing `conda` and standard Debian/Ubuntu -- it may work for you, it may not.  I only see error messages from people who try _and_ need help.  I use plain Debian/Ubuntu.  Good luck.

**Comment by eddelbuettel** [comment]
And again, depending on what you want to do, our [ML containers](https://github.com/rocker-org/ml) may be of help.  If your focus is more on Python then maybe start with what you started with and learn how to add /current/ R -- maybe see CRAN below the bin/linux/  URL.

**Comment by germayneng** [comment]
Yes i need R to integrate rpy2 with python. There are some packages i need with R. Which is why i am trying to install R. However, i am not sure why 3.3.3 is the latest version in my context.
