### ISSUE TITLE
Multi-Stage Builds; Copy R Folders

### ISSUE THREAD

**Issue by MarWeUMR** [rocker-org/rocker#352]
Hey,

I would like to use the r-base image as an intermediate layer. I'm new to docker and this is kind of an exercise for me. 
Now I'm stuck on which folders to copy to my build image.
Is there a general list of folders I have to copy and links/envs to create?

Thanks in advance

**Comment by eddelbuettel** [comment]
Welcome to Docker.  I would recommend _any_ decent tutorial.  

There is really no magic: you just use `r-base` and add on top.  See for example the very simple [r-rmd Dockerfile](https://github.com/rocker-org/rocker/blob/master/r-rmd/Dockerfile) where I just added a few packages to process markdown (via a script `render.r`).  Just write `RUN` commands as you would for any other Docker customization. 

That said, we can't really teach you Docker here.  Please try to rely on available documentation and come back if/when you have a concrete Rocker question or bug.  Ok?

**Comment by MarWeUMR** [comment]
Alright, thank you for the fast response. 

Feel free to close/delete this issue.
