### ISSUE TITLE
Override MRAN checkpoint date

### ISSUE THREAD

**Issue by rensa** [rocker-org/rocker#353]
Hi there,

Is it possible to override the checkpoint date used in a given rocker image? I tried putting the following in my dockerfile (basically copy-and-pasting from the r-ver dockerfile) after `FROM rocker/shiny-verse:3.6.0` but before I run any R package installation commands:

```
RUN echo MRAN=https://mran.microsoft.com/snapshot/2019-08-25 \
  && echo MRAN=$MRAN >> /etc/environment \
  && export MRAN=$MRAN \
  && echo "options(repos = c(CRAN='$MRAN'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rpr
```
But the subsequent package installations still used the r-ver checkpoint date. I'm also guessing that since the images install packages themselves (eg. the tidyverse), they wouldn't be affected even if my own installations were. (I'm not super worried about that: it's more that I'd like to reduce a couple of non-CRAN package dependencies that have hit CRAN in the last few months while still having some control over the checkpoint date).

Is it possible to override the MRAN checkpoint date in my dockerfile (even if it's just for subsequent package installations)? My suspicion is that the last line of the above block maybe results in `repos` and `download.file.method` being set twice.

**Comment by eddelbuettel** [comment]
I am afraid that is not fully reproducible.  But consider a simpler example -- setting `options("repos")` just works.  So you must have a simple typo, or non expansion of `$MRAN` inside single instead of double quotes, or whatnot.

```sh
edd@rob:~$ docker run --rm -ti r-base bash
root@57d14057eed7:/# echo "options(repos=c(\"CRAN\"=\"https://mran.microsoft.com/snapshot/2019-08-25\"))" >> /etc/R/Rprofile.site
root@57d14057eed7:/# install.r dang   # small zero depends package of mine
trying URL 'https://mran.microsoft.com/snapshot/2019-08-25/src/contrib/dang_0.0.10.tar.gz'
Content type 'application/octet-stream' length 15951 bytes (15 KB)
==================================================
downloaded 15 KB

* installing *source* package ‘dang’ ...
** package ‘dang’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (dang)

The downloaded source packages are in
        ‘/tmp/downloaded_packages’
root@57d14057eed7:/# 
```

**Comment by cboettig** [comment]
@rensa We've just added some docs on this, thanks to a recent PR from @robinlovelace, see: https://www.rocker-project.org/use/extending/

basically your approach is fine but a bit overkill, as Dirk notes you just need se `options()` in Rprofile.  Maybe it's just a copy-paste error but your block is writing to `/usr/local/lib/R/etc/Rpr`, which is not `/usr/local/lib/R/etc/Rprofile.site`.  You can always peek in Rprofile.site (or a user-level `.Rprofile` to make sure that you actually set the MRAN value.  HTH

**Comment by eddelbuettel** [comment]
Thanks @cboettig for the follow-up.  I think we close this.   @rensa if you think this needs reopening please do so and if possible and some examples of what is failing for you.

**Comment by rensa** [comment]
Thanks for the prompt reply, everyone! I'm stumbling through here a little with the environment variables, but copying an `.Rprofile` across with the changed option seems like a simple solution. Thanks again!
