### ISSUE TITLE
install.packages() incredible slow in tidyverse image, but fine in r-base image

### ISSUE THREAD

**Issue by vlandau** [rocker-org/rocker#354]
I'm noticing that if I install a package via `install.packages()` in the tidyverse image (whether from RStudio itself or from the the command line), it hangs for more than 5 minutes before installing.

Alternatively, if I use the r-base image, it runs just fine (<15 seconds). The only thing that has changed recently is my that my local operating system (Ubuntu 18.04) has gotten some updates, so I'm wondering if it might be that the rocker/tidyverse image is using some aspect of the local machine for configurations while r-base is not?

Any help would be much appreciated. Thanks!

**Comment by eddelbuettel** [comment]
No, neither one should "call  home" or "reach to the host".  It will be something.  

You could try profiling ....

**Comment by vlandau** [comment]
> No, neither one should "call home" or "reach to the host". It will be something.
> 
> You could try profiling ....

Thanks. How would I go about doing this? Using a secondary stack trace monitor?

**Comment by vlandau** [comment]
@eddelbuettel the same issue of hanging on package install appears with r-ver:3.6.1, so maybe it's an issue with debian:stable vs. debian:testing?

**Comment by eddelbuettel** [comment]
No, not _systematically_ and to the dramatic effect you quote.  

I tend to work more with our smaller container and I never have issues based on testing, or the ubuntu-based one (which I currently use for teaching/marking as I can get the over 4k binary packages easily -- see this blog post http://dirk.eddelbuettel.com/blog/2019/06/09#022_rocker_and_ppas).

**Comment by eddelbuettel** [comment]
Oh, I have a hunch:  "them intertubes" are full of issues about intermittent issues at MRAN.  That may be it -- and external resource some of these hit, and others don't.  That's likely it.

**Comment by eddelbuettel** [comment]
Eg https://twitter.com/maxheld/status/1168911398904221696 and the one preceding it by Chase.

**Comment by vlandau** [comment]
Ah, thanks very much!! I suspect that's the issue as well. Hopefully it will be resolved in a matter of time. I'll close the issue in that case. Thanks for looking into it.
