### ISSUE TITLE
rstudio 3.6.1 image hit "Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2019-09-02/src/contrib:" when try to install package

### ISSUE THREAD

**Issue by tinghf** [rocker-org/rocker#355]
Hi there, 

I'm trying to build a image base on rocker/rstudio:3.6.1,  somehow I keep seeing issuing when it gets to the point of installing packages, with error like: 

> Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2019-09-02/src/contrib:
>  cannot open URL 'https://mran.microsoft.com/snapshot/2019-09-02/src/contrib/PACKAGES'
> 

I try to curl that snapshot address and it seems like it's not available? have anyone seen this and know what's the workaround? 

> curl https://mran.microsoft.com/snapshot/2019-09-02/src/contrib/PACKAGES
> The specified CGI application encountered an error and the server terminated the process.

The detailed error during my docker-compose build command is as follows: 

> Step 8/28 : RUN Rscript -e "install.packages(c('magrittr', 'knitr', 'sp'))"
>  ---> Running in 22454ead3bf8
> Installing packages into ‘/usr/local/lib/R/site-library’
> (as ‘lib’ is unspecified)
> Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2019-09-02/src/contrib:
>   cannot open URL 'https://mran.microsoft.com/snapshot/2019-09-02/src/contrib/PACKAGES'
> Warning message:
> packages ‘magrittr’, ‘knitr’, ‘sp’ are not available (for R version 3.6.1)
> Removing intermediate container 22454ead3bf8
>  ---> 5576b6eafa10
> Step 9/28 : RUN Rscript -e "install.packages(c('tidyr','lubridate'))"
>  ---> Running in b751b0d3fc93
> Installing packages into ‘/usr/local/lib/R/site-library’
> (as ‘lib’ is unspecified)
> Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2019-09-02/src/contrib:
>   cannot open URL 'https://mran.microsoft.com/snapshot/2019-09-02/src/contrib/PACKAGES'
> Warning message:
> packages ‘tidyr’, ‘lubridate’ are not available (for R version 3.6.1)
> Removing intermediate container b751b0d3fc93

**Comment by eddelbuettel** [comment]
See issue #354 from yesterday

**Comment by tinghf** [comment]
thanks @eddelbuettel   also found a relevant discussion on Microsoft technet: https://social.technet.microsoft.com/Forums/en-US/e7db8c6e-3dad-4248-b9c3-79f4bb499b76/cannot-install-any-packages-from-mran?forum=ropen

Seems like a infrastructure issue, closing this ticket.
