### ISSUE TITLE
how to create password for using rstudio docker

### ISSUE THREAD

**Issue by chenhongbayer** [rocker-org/rocker#359]
from your documentation of running rocker/rstudio, it needs PASSWORD=<yourpassword>, where do i go set up this password?

**Comment by cboettig** [comment]
apologies for the confusion, that's where you specify your own password -- anything you want, so long as it is a secret!  (the password cannot be "rstudio").

**Comment by chenhongbayer** [comment]
great. thank you! I tried and got error below, not sure what issue it is:
ubuntu@ip-172-31-38-113:~/EAAS$ docker run -it -e PASSWORD=kSUtest -p 8787:8787 rstudio
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] add: executing... 
Nothing additional to add
[cont-init.d] add: exited 0.
[cont-init.d] userconf: executing... 
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
20 Sep 2019 16:41:47 [rserver] DEBUG (PID 212): Acquired lock: /var/run/rstudio-server/revocation-list.lock

20 Sep 2019 16:41:47 [rserver] DEBUG (PID 212): Released lock: /var/run/rstudio-server/revocation-list.lock

^C[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
20 Sep 2019 16:41:50 [rserver] INFO Reloading logging configuration...
20 Sep 2019 16:41:50 [rserver] INFO Successfully reloaded logging configuration
20 Sep 2019 16:41:50 [rserver] INFO Successfully reloaded all configuration
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by cboettig** [comment]
Apologies again, those are not error messages!  `[services.d] done.` is just telling you that it has successfully brought up RStudio for you, and is waiting for you to connect.  Unfortunately you haven't bound an internet port, you probably wanted a `-p 8787:8787` in your arguments to docker , see [docs](https://www.rocker-project.org/#i-classfa-farocketi-getting-started)

**Comment by chenhongbayer** [comment]
got it. thank you for the help!
actually my goal is pretty simple, which is to run a simple R script. So maybe instead of using rocker/rstudio, is there an image that has r-base + devtools that allow me to install python3-pip and libcurl4-openssl-dev libssl-dev libssh2-1-dev libxml2-dev on top of the image?

**Comment by eddelbuettel** [comment]
In that case you more-or-less started with the wrong container :)  

Maybe scan our R Journal paper for an overview?  Personally,  I do a fair amount of customization on top of the `r-base` image that is the same as `rocker/r-base`.

**Comment by chenhongbayer** [comment]
thanks Carl and Dirk!
I used r-base add on top of it a couple of developing tools building an image of my own and it eventually worked for my script.

**Comment by eddelbuettel** [comment]
Ok, if you're all good I will close this ticket.

**Comment by chenhongbayer** [comment]
Sure. Thanks!

Best regards,

Chenhong Zhang
Data Manager

////////////////////

Bayer U.S. – Crop Science
Research & Development
700 Chesterfield Pkwy West
Building CC212-G
Chesterfield, 63017, USA
Tel:        +1 636 737 7102
E-mail:   chenhong.zhang@bayer.com
Web:      http://www.bayer.com

/// Follow Bayer on:
/// Twitter<https://twitter.com/Bayer> /// Facebook<https://www.facebook.com/Bayer> /// Instagram<https://www.instagram.com/bayerofficial/> /// LinkedIn<https://www.linkedin.com/company/1893/> /// YouTube<https://www.youtube.com/user/BayerTVinternational>
]
