### ISSUE TITLE
Minimal image to run R CMD check?

### ISSUE THREAD

**Issue by mllg** [rocker-org/rocker#360]
Is there an image which ships R-release and comes with all system libraries required to run a full R CMD check?

I'm looking for something like `verse` w/o rstudio and tidyverse, or something like r-base + tex + pandoc.

**Comment by eddelbuettel** [comment]
`R CMD check ` of _what_ ?   A hypothetical `hello, world` package?

`r-base` should do as it contains R.   For `tinyverse` packages that ought to be enough.

**Comment by eddelbuettel** [comment]
I have a few repos (typically with more completed library depencecies such as vowpalwabbit or mlpack) where I built minimal containers by just adding these.   Else, it is often `knitr` or `rmarkdown` biting us.

**Comment by cboettig** [comment]
@mllg Jeroen maintains `cran/debian`, https://hub.docker.com/r/cran/debian/tags, based I believe on a debian metapackage that Kurt Hornik maintains for CRAN.  

(Note that it's 5.5 GB compressed, so about 5x the size of `rocker/verse` which has pandoc, rstudio, and tidyverse, but should have ~ all of the system libraries used in CRAN packages).

**Comment by eddelbuettel** [comment]
Yes using the `apt-get`-able repo with the their Debian meta-packages (which has some weird Austrian Assocation for Statistics or some such name -- not hidden, just less known).

Still no full guarantee.  _System-level_ dependencies are _hard_.  @opencpu just filed a wishlist bug report for R, seemingly based on chatter at DSC (which sadly I could not attend).    

See https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17615 for that.

**Comment by eddelbuettel** [comment]
If however you just want to run something in a small container, this just worked for me

```sh
$ docker run --rm -ti -v$PWD:/work -w /work r-base \
           R CMD check --no-manual --no-vignettes tinytest_1.0.0.tar.gz
```

**Comment by eddelbuettel** [comment]
> I'm looking for something like verse w/o rstudio and tidyverse, or something like r-base + tex + pandoc.

And I have [`r-rmd`](https://github.com/rocker-org/rocker/blob/master/r-rmd/Dockerfile) which should come close.  I use that (among other things) for my four RMarkdown-using packages.   If something is missing that you need may be able to add.  Its TexLive is reasonably, but not all-encompassing (as I relearned the hard way recently with a bug in `pinp` which wants rarer fonts etc).

**Comment by mllg** [comment]
Sorry, my request was quite imprecise. To be more clear: I'm looking for an image which allows me to run `R CMD check --as-cran` on a package with no extra system dependencies. I don't need any R packages pre-installed in the image (I can do this myself), but I want to be able to run all checks also performed by CRAN. AFAICT at least the following extra packages would be required to get something like an `r-base-dev` image:

* texlive or tinytex to build the manual
* pandoc to check NEWS.md, README.md and HTML vignettes

I can stitch something like this together, I was just curios if nobody else ever wanted to run all checks in a container.

Thanks for the linked repositories, they are a very good start.

**Comment by eddelbuettel** [comment]
Yes, try `r-rmd` then.  (I am often "lazy" / "in a hurry" so I often skip manual and/or vignettes but these Rmarkdown packages need that, obviously, so t

```sh
edd@rob:~/git/tint(master)$ docker run --rm -ti -v$PWD:/work -w /work rocker/r-rmd R CMD check tint_0.1.2.tar.gz
* using log directory ‘/work/tint.Rcheck’
* using R version 3.5.2 (2018-12-20)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘tint/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘tint’ version ‘0.1.2’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for .dll and .exe files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘tint’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... NONE
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘simple.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
   ‘tintHtmlIntro.Rmd’ using ‘UTF-8’ ... OK
   ‘tintPdfIntro.Rmd’ using ‘UTF-8’ ... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: OK

edd@rob:~/git/tint(master)$
```

That said, the set of package is also common and I run the same R version on essentially the same OS so there is no point for me to do this regularly.  But I needed it at some point and so _this_ container was made ...

**Comment by mllg** [comment]
Sounds terrific, I'll give it a try.
