### ISSUE TITLE
The base image should be a stable version

### ISSUE THREAD

**Issue by bkimbrough-bw** [rocker-org/rocker#363]
The current base image is using `debian:testing`, which isn't something I'd suggest using in a production system. So I'd like to see it changed to `debian:stable`.

**Comment by cboettig** [comment]
@bkimbrough-bw You can already find a `debian:stable` based images in https://github.com/rocker-org/rocker-versioned, e.g. `rocker/r-ver`.  There are also good reasons we provide `debian:testing` based images, as we discuss in https://doi.org/10.32614/RJ-2017-065
