### ISSUE TITLE
Running R commands before RStudio Server opens

### ISSUE THREAD

**Issue by austingrosel** [rocker-org/rocker#369]
I'm new to Rocker so I apologize if this is a dumb question or it has been asked already. I currently have a rocker project that has a developer run a shell script to open RStudio:

```
LOCAL_PATH=$1
IMAGE_NAME=$2

docker run \
	--rm \
	-it \
	-p 8787:8787 \
	-e "RENV_PATHS_CACHE=/renv/cache" \
	-v ${LOCAL_PATH}:/renv/cache \
	-v ${LOCAL_PATH}:/home/rstudio/project1 \
	--name p1_ctnr \
	-e PASSWORD='p1_password' \
	${IMAGE_NAME} 
```
As you can see, `renv` is used to keep track of the package versions. What I would like to happen is to add a `setwd('/home/rstudio/project1')`command to this docker run and then to activate the `renv` environment. Something like this:

```
LOCAL_PATH=$1
IMAGE_NAME=$2

docker run \
	--rm \
	-it \
	-p 8787:8787 \
	-e "RENV_PATHS_CACHE=/renv/cache" \
	-v ${LOCAL_PATH}:/renv/cache \
	-v ${LOCAL_PATH}:/home/rstudio/project1 \
	--name p1_ctnr \
	-e PASSWORD='p1_password' \
	${IMAGE_NAME}  \
        R -e "setwd('/home/rstudio/project1'); renv::activate()"
```
So the project automatically sets the project to the project folder and activates `renv` when a user opens RStudio Server. But this code above does not work. 

Is there any way to do this? Or does a user have to go into RStudio and set the window and activate `renv` every time he or she wants to use RStudio Server through Docker.

**Comment by cboettig** [comment]
If you want arbitrary R code to execute (as user, not root(?)) when RStudio starts up, maybe you want to put that code in a `.Rprofile`?  

e.g. if you put your `setwd('/home/rstudio/project1'); renv::activate()` in a `.Rprofile` in `/home/rstudio/project1`, I think this would be run when starting `project1` in RStudio, while also not impacting projects in other directories.  likewise you could make it take effect for all projects of a given user by using a `~/.Rprofile` instead.   Haven't tested this wrt `renv` though, lemme know if it works or if you've already tried that unsuccessfully...

**Comment by austingrosel** [comment]
Thanks for responding so quickly. I will try this idea tomorrow and let you know!

**Comment by austingrosel** [comment]
So your first suggestion did not end up working. Putting an `.Rprofile` with those commands in `/home/rstudio/project1` did not automatically run when RStudio was pulled up. I guess I'm a bit confused of your second suggestion. How could I give the user an `.Rprofile` in the `/home/rstudio/` directory? Does this need to be written in the Dockerfile for the image build?

**Comment by cboettig** [comment]
`.Rprofile` should be run when the R session starts... that's not specific to Docker.  Are you sure you have the file in the right location with the right permissions?

as to putting a file in the home directory, sure, you can either put a file there at build time or link it using shared volumes (e.g. `-v /path/to/.Rprofile:/home/rstudio/.Rprofile`) at runtime like you're already doing for other shared volumes.
