### ISSUE TITLE
tlmgr path add errors

### ISSUE THREAD

**Issue by Midnighter** [rocker-org/rocker#370]
I'm using the following Dockerfile built on top of `rocker/verse`. This worked fine about half a year ago but now I'm getting an error with the line `tlmgr path add` and the message is not very helpful.

```dockerfile
ARG TAG=3.6.1

FROM rocker/verse:${TAG}

WORKDIR /opt

RUN set -eux \
    && apt-get update \
    && apt-get install --yes \
        libudunits2-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/install_requirements.R ./

RUN Rscript install_requirements.R

RUN set -eux \
    && tlmgr install \
        colortbl \
        environ \
        makecell \
        multirow \
        placeins \
        tabu \
        threeparttable \
        threeparttablex \
        trimspaces \
        ulem \
        varwidth \
        wrapfig \
        xcolor \
    && tlmgr path add

WORKDIR /home/rstudio

USER rstudio
```

The error that I see is:

```
+ tlmgr path add
tlmgr: action path returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.
```

Does anyone have a  clue how to solve this?

**Comment by Midnighter** [comment]
My temporary workaround is:

```dockerfile

RUN set -ux \
    && tlmgr install \
        colortbl \
        environ \
        makecell \
        multirow \
        placeins \
        tabu \
        threeparttable \
        threeparttablex \
        trimspaces \
        ulem \
        varwidth \
        wrapfig \
        xcolor \
    && tlmgr path add || true
```

which doesn't seem to affect anything I'm doing afterwards with the Docker image.

**Comment by cboettig** [comment]
@Midnighter Thanks for the report.  If I understand correctly, it looks like `tlmgr` is throwing an error message that is arresting your build when you run with `set -e` option, but that this error message appears to be erroneous and things work as expected if you simply don't force the shell to stop on error message, yes?  

It sounds like this may be related to the changes of https://github.com/rocker-org/rocker-versioned/pull/171; @riccardoporreca may have a better idea what is happening here to cause this?

**Comment by Midnighter** [comment]
> @Midnighter Thanks for the report. If I understand correctly, it looks like tlmgr is throwing an error message that is arresting your build when you run with set -e option, but that this error message appears to be erroneous and things work as expected if you simply don't force the shell to stop on error message, yes?

Exactly!

> It sounds like this may be related to the changes of rocker-org/rocker-versioned#171; @riccardoporreca may have a better idea what is happening here to cause this?

Looks like that might be it. I will roll with this workaround but definitely interested to know when it's fixed.

**Comment by cboettig** [comment]
@Midnighter we'll see what we can do.  Note that this is due to a bug in the upstream `tlmgr` itself, see https://tex.stackexchange.com/questions/313678/tlmgr-path-add-yields-errors-but-makes-symlinks/314079#314079.  

As you probably saw in https://github.com/rocker-org/rocker-versioned/pull/171 we allowed the default install method for `tinytex` instead of a version-stable one.  Of course it is ironic that efforts to make things more version stable brakes your earlier recipe, but of course we should have had a version-stable texlive pinning from the start for these versioned stack images.  We may be able to include a patched stable version instead.

**Comment by Midnighter** [comment]
Thank you for your efforts @cboettig. If you find a fix to apply to a future version that's great but I honestly would give this issue a rather low priority myself. Maybe it'll be sorted out by an upstream fix eventually.

**Comment by riccardoporreca** [comment]
> It sounds like this may be related to the changes of [rocker-org/rocker-versioned#171](https://github.com/rocker-org/rocker-versioned/pull/171); @riccardoporreca may have a better idea what is happening here to cause this?

This is actually something we had to workaround in PR rocker-org/rocker-versioned#171, as mentioned in the PR description
> * Work around known non-breaking errors of `tlmgr path add` in TeXLive 2016 (https://tex.stackexchange.com/a/314079).

The workaround is actually pretty much the same as @Midnighter is doing above:
https://github.com/rocker-org/rocker-versioned/blame/65cc85813f64aea22a96d17535b3baa60d0cee79/verse/Dockerfile#L59-L61
(Note however the `|| true` is limited to `tlmgr path add` there.)

So I think it is fair to recommend the same workaround in other `Dockerfile`s based on `rocker/verse` where the  version-stable TeX Live 2016 is used.

**Comment by riccardoporreca** [comment]
@cboettig, I was actually looking more into a possible "patch" at our end, following your comment in https://github.com/rocker-org/rocker-versioned/pull/171#issuecomment-563067807. I will follow up there...
