### ISSUE TITLE
Update to current debian stable

### ISSUE THREAD

**Issue by bartbkr** [rocker-org/rocker#372]
debian stable has been updated to buster since 2019-11-16:

https://wiki.debian.org/DebianStable

The current version of R packages like RQuantLib require versions of system packages that are only available in testing if stretch is used as the base image.

Could the base image for r-ver use `debian:stable` rather than `debian:stretch`? This *should* allow switching to `buster` while maintaining the project claim that r-ver builds on `debian:stable` (see [rocker README](https://github.com/rocker-org/rocker/blob/master/README.md)).

**Comment by eddelbuettel** [comment]
Kinda on-topic / off-topic:  I maintain, inter alia, Rocker's r-base and Debian's RQuantLib.  You could just use r-base and install the package from testing/unstable.  Works like a charm.

Or, better still, as I switched a few repos to do CI via Docker, pick the _pre-built_ Docker container:  
https://hub.docker.com/repository/docker/rquantlib/run/general

(Now, that one was behind too but I just tickled a build.)

That said, the r-ver stack may need an update.  We apologize for the number of repositories but for that issue you more or less filed in the wrong repo.  It happens a lot, so no worries.

**Comment by cboettig** [comment]
@bartbkr Thanks!  Yup, we will bump `rocker/r-ver:latest` to `debian:buster` on the next R release (3.6.2, yeah, I know I'm a few days behind, it's the holidays!).  

note that `buster` wasn't stable at the R 3.6.1 release.  (see [VERSIONS.md](https://github.com/rocker-org/rocker-versioned/blob/master/VERSIONS.md))

As we describe in our [R journal piece](https://doi.org/10.32614/RJ-2017-065), the versioned stack aims to have Dockerfiles that will always rebuild the same environment.  Like Dirk says, the `r-base` stack already provides rolling images (pinned to `debian:testing`.  We know that having separate "stable" and "rolling" release stacks makes things a bit confusing, but it helps cover the different use cases.   Issues for versioned stack live over at https://github.com/rocker-org/rocker-versioned/issues

HTH!

**Comment by cboettig** [comment]
p.s. meanwhile just a note taht `r-ver:devel` has been on `debian:buster` since buster was released, in case you need a quick `buster` platform.

**Comment by cboettig** [comment]
@bartbkr `latest` tags for the `r-ver` stack (rstudio, tidyverse, verse) are now on buster. thanks.
