### ISSUE TITLE
rstudio container, View() not working

### ISSUE THREAD

**Issue by cmikovits** [rocker-org/rocker#374]
Dear all,

I haven't found anything on this so far, and am absolutely unsure if this is related to the container or something else:

When using rstudio desktop calling View(data) opens a new tab with (usually) a table with the data.
Running this command with rstudio server (docker-container) nothing is showing in the view tab (the tab itself is there)

Is anyone experiencing the same problem?

Version: rocker/rstudio:latest under Ubuntu LTS

**Comment by cboettig** [comment]
@cmikovits thanks for the bug report, can you give us a little more information?  I use `View()` regularly with datasets in the Rocker rstudio container and it has always worked well.  (here's a screenshot:

<img width="1275" alt="Screen Shot 2020-01-08 at 11 11 21 AM" src="https://user-images.githubusercontent.com/222586/72007969-aa354880-3207-11ea-9667-fdf81c987397.png">


What do you mean "nothing is showing"?  Are you using a particularly large dataset (or maybe a remote connection)?  Have you tried with a standard dataset like `mtcars`?  What browser are you using?

**Comment by cmikovits** [comment]
Hello.

Thanks for the feedback.

![screen](https://user-images.githubusercontent.com/45256992/72055301-e1b8f900-32ca-11ea-8e05-ff3948ad07f5.png)

The dataset I wanted to show is usually large. But also mtcars is showing a blank tab, see screenshot. Browser is latest firefox (72); but also colleagues (chrome) who log into the same docker rstudio instance are having this problem.

Is there a way to provide more information? /var/log/rstudio-server/ within the docker container is empty.

**Comment by cboettig** [comment]
Very strange. I wonder if this is a stylesheet problem with the theme you're using by any chance?  Can you test in a vanilla rstudio container with the default theme?

**Comment by cmikovits** [comment]
Thank you very much for the help. I narrowed the problem down to the nginx config (not sure what exactly the problem is), direct access via the exposed port works flawlessly. I'm very sorry to have bothered you.

**Comment by cboettig** [comment]
thanks for the follow-up.  

You probably ain't lookin for suggestions on reverse proxy, but after too much struggle with nginx configs I now use caddyserver with my RStudio instances :-).
