### ISSUE TITLE
environment variables passed through the docker run command are not visible in RStudio

### ISSUE THREAD

**Issue by AndreaPi** [rocker-org/rocker#376]
OS: 
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
```
Docker image: `rocker/verse:latest`
image id: 
```
$ docker images -q rocker/verse
def324c74d22
```

I'm behind a corporate proxy, so I run containers by passing the proxy as an environmental variable:

```
docker run -e http_proxy -e https_proxy -e no_proxy -e USERID=<myuid> -e PASSWORD=<mypwd> --rm -it --name rstudio_test -p 8787:8787  rocker/verse
```

I then point my browser to ...:8787 and from RStudio I try

```
> install.packages("pacman")
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘pacman’ is not available (for R version 3.6.2)
```

This is **not** a a problem with me not being able to access the Internet, because if I connect to the running Docker container, and run a `bash` shell there with

`docker exec -it db1dce8100a8 /bin/bash`

I'm able to connect to CRAN **from inside the container**:

```
root@db1dce8100a8:/#  wget -p https://cran.rstudio.com/src/contrib/PACKAGES -O /dev/null
WARNING: combining -O with -r or -p will mean that all downloaded content
will be placed in the single file you specified.

--2020-02-18 11:24:44--  https://cran.rstudio.com/src/contrib/PACKAGES
Resolving **xxx** (**xxx**)... 3.198.224.35
Connecting to **xxx** (**xxx**)|3.198.224.35|:80... connected.
Proxy request sent, awaiting response... 200 OK
Length: 3299549 (3.1M)
Saving to: ‘/dev/null’

/dev/null                                                   100%[=========================================================================================================================================>]   3.15M  8.48MB/s    in 0.4s

2020-02-18 11:24:45 (8.48 MB/s) - ‘/dev/null’ saved [3299549/3299549]

FINISHED --2020-02-18 11:24:45--
Total wall clock time: 0.7s
Downloaded: 1 files, 3.1M in 0.4s (8.48 MB/s)
```

So, I can see CRAN from inside the running Docker container, but I cannot see it from RStudio. Apparently, the enviroment variables `http_proxy`, `https_proxy`,`no_proxy` are not passed to RStudio. Why?

**Comment by eddelbuettel** [comment]
(This is somewhat slightly the wrong repo. Code and discussion for `r-ver` is mostly over at [rocker/r-ver](https://github.com/rocker-org/rocker-versioned) where @cboettig has explained this a few times; you should find prior discussion in the issues there, and possibly here as others have filed here too. One recent one is https://github.com/rocker-org/rocker-versioned/issues/175 .)

**Comment by AndreaPi** [comment]
I'll close the issue here if this is not the right repo, but the issue you mention doesn't seem  directly related. The environment variables I set (`http_proxy` & friends) are not set again in `.Renviron`, so I don't see how they could be overriden through the mechanism described by @cboettig. Proof:

```
### etc/Renviron.  Generated from Renviron.in by configure.
###
### ${R_HOME}/etc/Renviron
###
### Record R system environment variables.

R_PLATFORM=${R_PLATFORM-'x86_64-pc-linux-gnu'}
## Default printer paper size: first record if user set R_PAPERSIZE
R_PAPERSIZE_USER=${R_PAPERSIZE}
R_PAPERSIZE=${R_PAPERSIZE-'letter'}
## Default print command
R_PRINTCMD=${R_PRINTCMD-'/usr/bin/lpr'}
# for Rd2pdf, reference manual
R_RD4PDF=${R_RD4PDF-'times,inconsolata,hyper'}
## used for options("texi2dvi")
R_TEXI2DVICMD=${R_TEXI2DVICMD-${TEXI2DVI-'/usr/bin/texi2dvi'}}
## used by untar(support_old_tars = TRUE) and installing grDevices
R_GZIPCMD=${R_GZIPCMD-'/bin/gzip'}
## Default zip/unzip commands
R_UNZIPCMD=${R_UNZIPCMD-'/usr/bin/unzip'}
R_ZIPCMD=${R_ZIPCMD-'/usr/bin/zip'}
R_BZIPCMD=${R_BZIPCMD-'/bin/bzip2'}
## Default browser
R_BROWSER=${R_BROWSER-'xdg-open'}
## Default editor
EDITOR=${EDITOR-${VISUAL-vi}}
## Default pager
PAGER=${PAGER-'/usr/bin/pager'}
## Default PDF viewer
R_PDFVIEWER=${R_PDFVIEWER-'/usr/bin/xdg-open'}
## Used by libtool
LN_S='ln -s'
MAKE=${MAKE-'make'}
## Prefer a POSIX-compliant sed on e.g. Solaris
SED=${SED-'/bin/sed'}
## Prefer a tar that can automagically read compressed archives
TAR=${TAR-'/bin/tar'}

## System and compiler types.
R_SYSTEM_ABI='linux,gcc,gxx,gfortran,gfortran'

## Strip shared objects and static libraries.
R_STRIP_SHARED_LIB=${R_STRIP_SHARED_LIB-'strip --strip-unneeded'}
R_STRIP_STATIC_LIB=${R_STRIP_STATIC_LIB-'strip --strip-debug'}

#R_LIBS_USER=${R_LIBS_USER-'~/Library/R/3.6/library'}

### Local Variables: ***
### mode: sh ***
### sh-indentation: 2 ***
### End: ***
R_LIBS_USER=${R_LIBS_USER-'/usr/local/lib/R/site-library'}
R_LIBS=${R_LIBS-'/usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib/R/library'}
PATH=/usr/lib/rstudio-server/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PATH=/usr/lib/rstudio-server/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/TinyTeX/bin/x86_64-linux/
PATH=/usr/lib/rstudio-server/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/TinyTeX/bin/x86_64-linux/
PATH=/usr/lib/rstudio-server/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/TinyTeX/bin/x86_64-linux/

```

**Comment by eddelbuettel** [comment]
(I just recall that we had prior discussions about some env vars being swallowed by RStudio, but I don't have a pointer.  Maybe wait for @cboettig to pipe in, but in the mean time maybe search among issue in other rocker repos too.  Having several repos dilutes the bug reporting clarity, sadly, ...)

**Comment by AndreaPi** [comment]
will do the search, thank you.

**Comment by cboettig** [comment]
Yeah, for better or worse, this is how RStudio works.  We echo env vars into `$R_HOME/etc/Renviron` when we want those env vars available in RStudio.

**Comment by cbessey** [comment]
I just ran into the same issue. actually the environment variables (set in a docker run command) are not getting echoed into $R_HOME/etc/Renviron.  This should be obvious from AndreaPi's output above. I just ran into the same issue. envoriomnet variables set with "-e ..." in a docker run command simply disappear. they do not get echoed into $R_HOME/etc/Renviron. Please check this yourself.

**Comment by eddelbuettel** [comment]
(Wrong repo, rocker/versioned2 is better -- and discussed a few times before, please see closed issues.  The matter appears to be due to RStudio simply not passing the environment variables on.)
