### ISSUE TITLE
R(studio) from docker on Linux

### ISSUE THREAD

**Issue by vnijs** [rocker-org/rocker#377]
We are having some issues with R running *very* slow from a docker container. Running the same code from docker on macOS takes about 15seconds but on the server it takes > 10 minutes. The server is running ubuntu 18.04. We are trying to restrict the number of CPUs each container can use to 4 but R still starts a *lot* of threads as if it does have access to all 88 CPUs.

On macOS setting "--cpus=1" limits the number of CPUs the container can see. However, running the commands below `lscpu` can still "see" all containers on our linux server. 

Have you seen something like this before? Any suggestions? 

```
vnijs@sc1 ~ docker run --cpus=1 --rm -it rocker/tidyverse /bin/bash
root@fe4cde3d0a68:/# lscpu 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 48 bits virtual
CPU(s):              88
On-line CPU(s) list: 0-87
Thread(s) per core:  2
Core(s) per socket:  22
```

**Comment by eddelbuettel** [comment]
Minimally reproducible examples would be great.  Here is my machine, following `example(lm.fit)`:

```
R> system.time(replicate(lm.fit(X,y), n=1e5))
   user  system elapsed 
  2.632   0.016   2.648 
R> 
```

and here is Rocker's r-base doing the same on the same machine but via Dockre

```
> system.time(replicate(lm.fit(X,y), n=1e5))
   user  system elapsed 
  3.506   0.059   3.565 
> 
```

which is different, but not dramatically so. And checking `extSoftVersion()` confirms my first guess which is OpenBLAS on my system, and reference blas for r-base.

**Comment by vnijs** [comment]
Thanks @eddelbuettel. Reproducible example below. 

`docker run --cpus=1 --rm -it rocker/r-base /bin/bash`

Using the `r-base` container on macOS and the Linux server we get approximately the same time so that is great.

> Sys.time() - t1
Time difference of 4.44944 secs

However, when using the `tidyverse` container the duration is about 4 minutes on our Linux server instead of 4 seconds. Would love to hear any suggestions you might have.

`docker run --cpus=1 --rm -it rocker/tidyverse /bin/bash`

> Sys.time() - t1
Time difference of 3.932377 mins

**Example:**
```
n <- 1000000
X <- data.frame(matrix(rnorm(n * 20), ncol = 20))
X$y <- ifelse(runif(n, 0, 1) > 0.5, TRUE, FALSE)

t1 <- Sys.time()
glm(y ~ ., family = binomial(link = "logit"),  data = X)
Sys.time() - t1
```

**Comment by eddelbuettel** [comment]
(For the `tidyverse` container you are kinda in the wrong repo as it is over here: https://github.com/rocker-org/rocker-versioned -- but I am sure @cboettig will pipe in time permitting.)

Maybe you can drill down and simplify / compare?  It should not be that drastic in any event...

**Comment by vnijs** [comment]
The `tidyverse` image has openblas (see below). Could this be the cause of time-difference? I have other images I use that also have openblas and they all show the same big slow-down in estimation. Do you have a version of r-base with openblas installed perhaps?

```
> extSoftVersion()
                                              zlib 
                                          "1.2.11" 
                                             bzlib 
                              "1.0.6, 6-Sept-2010" 
                                                xz 
                                           "5.2.4" 
                                              PCRE 
                                 "8.39 2016-06-14" 
                                               ICU 
                                            "63.1" 
                                               TRE 
                         "TRE 0.8.0 R_fixes (BSD)" 
                                             iconv 
                                      "glibc 2.28" 
                                          readline 
                                             "7.0" 
                                              BLAS 
"/usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so" 
```

**Comment by eddelbuettel** [comment]
Did you say lots of cores on the server?  I am not sure Docker misbehaves there but there are standard way to throttle the number of threads / cores used, even [from R via a CRAN package](http://cloud.r-project.org/package=RhpcBLASctl). Maybe that can help?

**Comment by vnijs** [comment]
Yes. 88 cores on the box. The sys admin thinks the problem is that docker tries to restrict access to cores but that R (openblas?) still sees all the cores and starts a ton of threads without actual access to the cores. The argument is then that this doesn't happen on macOS because "lscpu" and R can only see the actually assigned cores. 

In addition to your suggestion, the thread below has some ideas that seem to address the slow-down. @eddelbuettel Would you recommend doing this from R or through environment variables in Docker? Is there a way to automatically set the environment variables in docker based on the assigned number of CPUs that you know of?

`export OPENBLAS_NUM_THREADS=4 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4`

https://stackoverflow.com/questions/48410130/is-r-creating-too-many-threads-on-startup

**Comment by eddelbuettel** [comment]
There are indeed many different ways. As [RhpcBLASctl](http://cloud.r-project.org/package=RhpcBLASctl) it can be done from R, you can as you seem to know also do it from Docker.  Maybe worth trying to see what the speed difference is, if any, on a more normal box.

**Comment by cboettig** [comment]
@vnijs thanks, that's interesting.  Can you try setting the CPU assignment explicitly in your `docker run` calls?  e.g. 

```
docker run --cpuset-cpus=0 
```

instead of `--cpus=1`

Thanks!

**Comment by vnijs** [comment]
@cboettig I thought I had already tried `--cpuset-cpus` but it seems not as that does also seem to work. `lscpu` still "see" all 88 cpus however. I believe `--cpuset-cpus` assigns actual cpus to a specific user I believe. Could that be an issue since we have 70+ students using the same box off-and-on?

**Comment by eddelbuettel** [comment]
I also think that goes exactly as @vnijs said earlire: main process gets one core, call BLAS which see many and go and take them.  So for many processes on the box, much contention. 

Easy but blunt fix: replace OpenBLAS with, say, (default) Atlas. Less blunt, of course, would be to manage to tame the hunger for cores.

**Comment by cboettig** [comment]
@vnijs weird.  In my test, doing `docker run --cpuset-cpus=0 --rm -ti rocker/tidyverse R` on a 32 core machine, I don't see the delay ( ~ 4 sec run).  If I run with `--cpus=1`, I do see the delay (your example takes ~ 44 secs for me).

**Comment by vnijs** [comment]
@cboettig No that seems pretty consistent with what I found. Except, with "--cpus=1" I get a much stronger delay (5min vs your 4 seconds). Perhaps that difference is because the box we are working on has 88 cores vs 32 cores on your test machine?

**Comment by vnijs** [comment]
FYI For some reason, even with `OPENBLAS_NUM_THREADS` and `OMP_NUM_THREADS` set in `/etc/R/Renvironment.site` we were still seeing (much) slower calculation speeds. Adding `RhpcBLASctl::blas_set_num_threads` and `RhpcBLASctl::omp_set_num_threads` to /etc/Rprofile.site, however, got the calculation time down do 4-5 seconds. See example code linked below.

https://github.com/radiant-rstats/docker/blob/master/rsm-jupyterhub/Dockerfile#L60-L70
