### ISSUE TITLE
No /usr/bin/bash in r-base?

### ISSUE THREAD

**Issue by earcanal** [rocker-org/rocker#381]
When I follow [the instructions to connect to bash on the r-base container](https://hub.docker.com/_/r-base) I get an error:

```
$ docker run -ti --rm r-base /usr/bin/bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/usr/bin/bash\": stat /usr/bin/bash: no such file or directory": unknown.
```

**Comment by eddelbuettel** [comment]
Nice catch. I think the kernel and linux distros moved things around there a while back.  FWIW I only ever said  `bash`  there in all those years with Docker, and that always worked and of course still does:

```sh
edd@rob:~$ docker run --rm -ti r-base bash
root@0e0376cc6a4c:/# which bash
/bin/bash
root@0e0376cc6a4c:/# 
```

But now I can't remember where the source to that README lives. @cboettig do you?  How to we get the official-images repo to refresh that?  I see no link in our r-base file :-/

**Comment by eddelbuettel** [comment]
Found it and will take care of it.

**Comment by eddelbuettel** [comment]
Thanks again for catching this. I forked the upstream repo containing that page, PR'ed the fix and at the same time updated the logo (which, ahem, may need some scaling... another time).
