### ISSUE TITLE
rebuild of rocker/r-ver:devel

### ISSUE THREAD

**Issue by nturaga** [rocker-org/rocker#383]
Hi @cboettig 

Can you issue a rebuild of rocker/r-ver:devel on dockerhub, so that it captures the latest revision of r-devel (r78000) ?

When I try to build locally, I get the error

```
checking whether PCRE support suffices... no
configure: error: PCRE2 library and headers are required, or use --with-pcre1 and PCRE >= 8.32 with UTF-8 support
/bin/sh: 1: Rscript: not found
```

Best regards,

Nitesh

**Comment by eddelbuettel** [comment]
Wrong repo. As you already [opened a duplicate](https://github.com/rocker-org/rocker-versioned/issues/197), I am closing this.
