### ISSUE TITLE
Error mounting volume

### ISSUE THREAD

**Issue by ahdee** [rocker-org/rocker#386]
Hi I'm trying to mount a volume according the tutorial.  But I keep getting this error 

```
docker run --rm -p 1000:8787 -e PASSWORD=<password> -e ROOT=TRUE -v $(pwd):/home/rstudio rocker/rstudio

docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/volumes/a77d19a50419f27e21449a1a953e50b2924c8df7b3ff1f5edc0672d57e6cc603/_data\\\" to rootfs \\\"/var/lib/docker/overlay2/a4d0b44537994af490d68a558b6a63610f347a9318bd9cb64ef7f8064ce60f6f/merged\\\" at \\\"/home/rstudio/kitematic\\\" caused \\\"lstat /var/lib/docker/overlay2/a4d0b44537994af490d68a558b6a63610f347a9318bd9cb64ef7f8064ce60f6f/merged/home/rstudio/kitematic: permission denied\\\"\"": unknown.

```

I can by pass this error by mounting this on another directory but I can't seem to be able to acccess this directory.  

`docker run --rm -p 1000:8787 -e PASSWORD=<password> -e ROOT=TRUE -v $(pwd):/data/ rocker/rstudio`

edit: above command semi works in that if I use sudo I can access it however in rstudio I cannot ( or don't know how) to execute with sudo.  Is there a way to set the permission so that rstudio can aceess the folder?

its strange because for "home" all I see is the directory kinematic and I can't seem to navigate anywhere else!  thanks.

**Comment by eddelbuettel** [comment]
It very much looks like a permission issue.  Did you review available docs such as [this wiki page](https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine) ?

**Comment by ahdee** [comment]
@eddelbuettel  yes just looked at it more carefully; the trick was to set both uid and gid thanks!
