### ISSUE TITLE
resolution issues

### ISSUE THREAD

**Issue by ahdee** [rocker-org/rocker#387]
Hi I was wondering if there is a way to increase the resolution?  Visually the plots are a bit blurry. Here is a side by side comparison with a plot generated from another rstudio server with AWS. 

https://i.imgur.com/tv0oWFO.png

**Comment by eddelbuettel** [comment]
1. Don't post links. One can include images in markdown.
1. This repo is for the Rocker project.  Your question appears to be more generic in nature.
1. Please ask generic R question on StackOverflow or the r-help list.  We do not really have the capacity to answer these questions here.

**Comment by ahdee** [comment]
ok apologize for that. I did not find a place to embed the images.  Also I didn't think it was generic since I thought the resolution was due to some configuration issue I'm not aware of.

**Comment by eddelbuettel** [comment]
> I did not find a place to embed the images.

Look at the bottom of these boxen when you edit. 'Attach files by dragging & dropping, selecting or pasting them'.
