### ISSUE TITLE
Creating multiple rocker containers on different ports

### ISSUE THREAD

**Issue by achamess** [rocker-org/rocker#388]
Hi,
I've been using Rocker successfully to run genomics analyses. But I'm at the stage now where I want to create multiple separate Rocker containers for different projects. I'm assuming the way to do that is to assign to different ports. The default I know is `8787`

This is a naive question since I'm new to docker, but what other ports can I use? In other words, what other numbers besides `8787` can I assign for my containers? I've tried just random other four-digit numbers and it doesn't work. Any guidance would be appreciated.

**Comment by eddelbuettel** [comment]
When you say "port" and only mention "8787", do you mean for multiple RStudio instances?  You may be running into an RStudio design issue---the daemon service providing RStudio Server (by default) only offers 8787.

That said, you can run multiple services on multiple ports.  But doing so is more general "how do I ..." question for Unix and not Rocker-specific and we do not have the bandwidth to coach that here.  Maybe try https://unix.stackexchange.com or https://serverfault.com/ -- or the RStudio Community site.

**Comment by cboettig** [comment]
@achamess just a quick note you can change which port you use on the host while always using 8787 in the container. This lets you have lots of instances on the same host.  e.g.

```
docker run -p 8787:8787 ...
dicker run -p 8888:8787 ...
docker run -p 8989:8787 ...
```
etc.  

You could also consider setting up a reverse proxy server (like caddyserver) in front of your instance with different subdomain names for each instance.

**Comment by achamess** [comment]
Thank you! That's helpful. My question was also about which numbers are permissible before the 8787 (e.g. 8989, 8888, etc). I'll figure it out. But I appreciate your help.

Best,
Alex
________________________________
