### ISSUE TITLE
Error in file(con, "wb") : cannot open the connection

### ISSUE THREAD

**Issue by ogola89** [rocker-org/rocker#390]
Hi there, 

I'm following the below tutorial:
https://www.youtube.com/watch?v=O42w5P3A1_8

I have NCGHM installed on my local computer(R-Studio) and loaded the data successfully:

`library(NGCHM)

data('TCGA.GBM.EXPR')
` 

When I run the command to create a new heatmap, I get the error:
`Error in file(con, "wb") : cannot open the connection`

This is my input:
`hm <- chmNew(name = 'test-chm',data = TCGA.GBM.EXPR)`

The traceback leading to the error is as follows:

```
Error in file(con, "wb") : cannot open the connection

10.
file(con, "wb")

9.
writeBinLines(props.json, file.path(blobdir, "properties.json"))

8.
shaidyAddFileBlob(shaidyRepo, "dataset", blobfiles, filenames, properties = c(list(format = format), properties))

7.
ngchmAddDatasetBlob(shaidyRepo, format, filename, props)

6.
ngchmSaveAsDatasetBlob(ngchm.env$tmpShaidy, "tsv", data)

5.
chmNewDataLayer(sprintf("Layer %d", length(chm@layers) + 1), layer)

4.
chmAddLayer(chm, item)

3.
chmAddLayer(chm, item)

2.
chmAddList(chm, list(...))

1.
chmNew(name = "test-chm", data = TCGA.GBM.EXPR)
```

I'm not really familiar with this package and not sure where the con and 'wb' are coming from.

Could you please help?

Thanks.

**Comment by eddelbuettel** [comment]
Please contact the video author / package author for details, and look around on Google for 'Docker and file permission'.  By being on Docker you may end up in a directory you do have access to.

There is no Rocker issue here.

In the example below I *explicitly* mount my current directory (where I can write), tell Docker to start there and touch a file.

```sh
edd@rob:~$ docker run --rm -ti -v${PWD}:/work -w /work rocker/r-base bash
root@320168ee5e94:/work# touch foo
root@320168ee5e94:/work# ls -l foo
-rw-r--r-- 1 root root 0 Apr  2 15:16 foo
root@320168ee5e94:/work# exit
edd@rob:~$ 
```

**Comment by eddelbuettel** [comment]
Forgot to add:  Our wiki has pointers too.  See https://github.com/rocker-org/rocker/wiki
