### ISSUE TITLE
rocker/r-apt:disco seems bionic?

### ISSUE THREAD

**Issue by greg-minshall** [rocker-org/rocker#393]
hi.  running an image `rocker/r-apt:disco` (s/b Ubuntu 19.04?), it appears i'm really in bionic (supposedly Ubuntu 18.04?).

```
{1025} sudo docker ps
CONTAINER ID        IMAGE                COMMAND             CREATED             STATUS              PORTS               NAMES
80ab92e8da78        rocker/r-apt:disco   "bash"              22 hours ago        Up 22 hours                             eager_wiles
```

but, in container

```
root@80ab92e8da78:/tmp # lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

cheers.

**Comment by eddelbuettel** [comment]
Howdy -- thanks for runnning `rocker/r-apt` containers!  A more esoteric breed :)  

I may have to check my notes but if memory serves I think I at one point had a really good reason to stick with LTS releases.  Ah yes -- `r-apt` helps us _inter alia_ to navigate the Rutter PPAs and c2d4u with its over 4000 packages.  And that PPA is now LTS releases only.

So yes, the 'disco' image still exists but should maybe be disregarded.  Unless you have a specific need in which case we could roll a non-Rutter-PPA build.   

Does that make sense?

**Comment by greg-minshall** [comment]
Dirk, thanks to you.  no, i have no particular Ubuntu (sorry, i confuse the linux "distros") need, just something that builds, runs, etc., which they all pretty much do.  keeping to the LTS makes sense.

i guess my only question would be, does it make sense to have a tag for a non-LTS release?  (i have *no* comment, being totally ignorant.)

closing this, and, again, thanks!

**Comment by eddelbuettel** [comment]
Well _the_ bread-and-butter container from which many of mine are derived is `rocker/r-base` aka `r-base`.  It is Debian based.

Because having Ubuntu is nice too we added `rocker/r-apt` and `rocker/r-ubuntu` too.

**Comment by greg-minshall** [comment]
thanks.  i picked `r-apt` because of [this post](https://www.r-bloggers.com/docker-images-for-r-r-base-versus-r-apt/), specifically the issue of the amount of time to spin up a docker image with all the packages my code requires, and didn't look much at `r-base`.  (plus, i ran Ubuntu for a few years before converting to arch.)

**Comment by eddelbuettel** [comment]
Yes. But the better container for that is [r-ubuntu](https://hub.docker.com/r/rocker/r-ubuntu) which I actually talked about myself, and as recently as [yesterday](http://dirk.eddelbuettel.com/blog/2020/04/11#024_rocker_r_4_0_0_testing).  `r-apt` kinda sorta works, `r-ubuntu` may be better which is why started promoting it more.  Main post was [this one](http://dirk.eddelbuettel.com/blog/2019/06/09#022_rocker_and_ppas) upon which yesterday's post follows in way.

**Comment by greg-minshall** [comment]
Dirk, thanks.  if i go to [r-ubuntu](https://hub.docker.com/r/rocker/r-ubuntu) as you mentioned, there is a `Docker Pull Command` which, if i copy and paste, gives me an error:

```
(master): {1067} sudo docker pull rocker/r-ubuntu
Using default tag: latest
Error response from daemon: manifest for rocker/r-ubuntu:latest not found: manifest unknown: manifest unknown
```

to figure out what tags are available for `r-ubuntu`, i do (something like) this:

```
surf https://registry.hub.docker.com/v1/repositories/rocker/r-ubuntu/tags
```

i'm not sure how else i am to know what tag to use.  am i missing the obvious?

also, i note that `r-ubuntu` is not listed on the left hand of its page (where, e.g., `r-base` and `r-apt`, among otherse, are listed).

anyway, mostly just trying to be helpful (plus gain clarity).  cheers.

**Comment by eddelbuettel** [comment]
```
docker pull rocker/r-ubuntu:18.04
docker pull rocker/r-ubuntu:20.04
```

as the page at https://hub.docker.com/repository/docker/rocker/r-ubuntu shows _no_ tag latest.

**Comment by greg-minshall** [comment]
Dirk, thanks!  (now i realize why :20.04 was so light on R packages -- thanks.)

i would suggest some verbiage on the docker [rocker/r-ubuntu page](https://hub.docker.com/r/rocker/r-ubuntu) telling people what tags to use (18.04, 20.04).  and, if possible, change the example `Docker Pull Command`on that page to include one of the two tags.  just to help the naive user actually figure out how to do a pull.  cheers!
