### ISSUE TITLE
Installing libmagick++-dev fails on latest 3.6.3 r-base release

### ISSUE THREAD

**Issue by hallfjonas** [rocker-org/rocker#394]
## Issue
I am working with a docker image based on r-base:3.6.3 in which I install the r package [magick](https://cran.r-project.org/web/packages/magick/). This package depends on `libmagick++-dev (deb)`. Installation of this package fails with the following error:
```
The following packages have unmet dependencies:
 libmagick++-dev : Depends: libmagick++-6.q16-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I tried `unholding` and using `aptitude install` as recommended [here](https://askubuntu.com/questions/363200/e-unable-to-correct-problems-you-have-held-broken-packages). Nothing worked.

## Reproduce
Build the docker file
```
FROM r-base:3.6.3
RUN apt-get update && apt-get install -y libmagick++-dev
```

## Information on docker r-base version
I did not have this issue until the updated r-base:3.6.3 version on 4/16/2020 at 11:13 pm.

## Dockerversion
Docker Toolbox for Windows:
Docker version 19.03.1, build 74b1e89e8a

**Comment by eddelbuettel** [comment]
(Wrong repo.  This should have been reported here: https://github.com/rocker-org/rocker-versioned/issues)

**Comment by eddelbuettel** [comment]
Thanks for carrying it over. Nuking this one.
