### ISSUE TITLE
R compile error

### ISSUE THREAD

**Issue by dipterix** [rocker-org/rocker#395]
I installed rstudio server docker following the instructions and R cannot run `solve()` function. I guess the latest R didn't compile correctly? 
I'm new to docker so please let me know if I should make extra configurations

![image](https://user-images.githubusercontent.com/8163576/79791956-c1f68f80-8313-11ea-9f5c-a5e420858bd0.png)

The native system is MacOS Catalina

**Comment by eddelbuettel** [comment]
I cannot reproduce this:

```sh
edd@rob:~$ docker run --rm -ti r-base Rscript -e 'solve(matrix(1:4,2))'
     [,1] [,2]
[1,]   -2  1.5
[2,]    1 -0.5
edd@rob:~$ 
```

Ditto in my normal (on the system) R.  You are doing something else wrong.  (Also, `solve` usually require something to solve _for_ ...)

**Comment by dipterix** [comment]
@eddelbuettel I tried that. It worked fine, but when I run rocker/rstudio, R raise error

**Comment by eddelbuettel** [comment]
Oh, and you, just like most people, opened a bug report on another Rocker container in the base Rocker repo.  No bug here, if you feel like opening it in the correct repo go to https://github.com/rocker-org/rocker-versioned

**Comment by cboettig** [comment]
Just a note that this issue doesn't occur on rocker-versioned rstudio image either:

```r
 docker run --rm -ti rocker/rstudio Rscript -e 'solve(matrix(1:4,2))'
     [,1] [,2]
[1,]   -2  1.5
[2,]    1 -0.5
```
