### ISSUE TITLE
Unable to install newest package version when when building a container

### ISSUE THREAD

**Issue by robertoromor** [rocker-org/rocker#397]
I am tryng to deploy the app using docker and shiny proxy and getting this error

> ^[[AError: 'bundle_resources' is not an exported object from 'namespace:golem'

I suppose the golem version that I am using is behind the golem version that has this function

This is the one that I have in my containerX right now

`sudo docker run -p containerX R -e 'packageVersion("golem")'`

>  packageVersion("golem")
> [1] ‘0.1’

and in local RStudio my package version is

>  packageVersion("golem")
> [1] ‘0.2.1’
> 

I tried installing the new version using this:

`sudo docker run -p containerX R -e 'install.packages("golem")'`
and it does not do update

Do you know why I cant update my package in my container?

**Comment by cboettig** [comment]
Can you give us a reproducible example of the issue you are experiencing?

**Comment by robertoromor** [comment]
This is my dockerfile:

```
FROM rocker/tidyverse:3.6.1
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
RUN R -e 'remotes::install_cran("shiny")'
RUN R -e 'remotes::install_cran("golem")'
RUN R -e 'remotes::install_cran("processx")'
RUN R -e 'remotes::install_cran("attempt")'
RUN R -e 'remotes::install_cran("dplyr")'
RUN R -e 'remotes::install_cran("shinyjs")'
RUN R -e 'remotes::install_cran("DT")'
RUN R -e 'remotes::install_cran("glue")'
RUN R -e 'remotes::install_cran("htmltools")'
RUN R -e 'remotes::install_cran("timevis")'
RUN R -e 'remotes::install_cran("googledrive")'
RUN R -e 'remotes::install_cran("shinyWidgets")'
RUN R -e 'remotes::install_cran("neurobase")'
RUN R -e 'remotes::install_github("MarkEdmondson1234/gentelellaShiny")'
RUN R -e 'remotes::install_github("muschellij2/papayaWidget")'
RUN R -e 'remotes::install_cran("config")'
COPY dicom/ ./dicom
COPY Rprofile.site /usr/lib/R/etc/
COPY rappExt_*.tar.gz /app.tar.gz
RUN R -e 'remotes::install_local("./app.tar.gz")'
```
this is the command to create the container

`sudo docker build -t radioApp .
`
and this is the command I am using to notice the package is behind the latest package version (https://cran.r-project.org/web/packages/golem/index.html)

`sudo docker run -p radioApp R -e 'packageVersion("golem")
`

> packageVersion("golem")
> [1] ‘0.1’

**Comment by cboettig** [comment]
why are you building on 3.6.1?  Why are you using `remotes::install_cran()`?  Also, check out the `install2.r --help` for a more concise way to install packages, you'll see examples in our Dockerfiles.  

Please note you are building on one of the *versioned* stack images, which are explicitly designed to give reproducible builds when run on *old versions of R*.  See https://github.com/rocker-org/rocker-versioned#version-tags.  In particular, these images set a default CRAN repo to an MRAN snapshot.  

If you want the `latest` versions of packages from CRAN etc, please consider building on an image that uses the tag `latest` if you are using the versioned stack.  

Note that you can find the versioned-stack repos actually live over here: https://github.com/rocker-org/rocker-versioned, yeah, we know that's confusing.

**Comment by robertoromor** [comment]
The structure of the Dockerfile get created in a predetermined way (including installing packages using 'remotes'). I am currently using golem as a framework to build an app. So I did not change many things and trusted the initial setup.

so and MRAN snaphot is sort of an predetermined enviroment for me to use. So what I would need to do is use a newer version as you mentioned

Thanks for the help!
