### ISSUE TITLE
Mapping to a share drive on windows

### ISSUE THREAD

**Issue by joxborrow** [rocker-org/rocker#399]
Hi, I am tried to use the "-v" option of a rocker based docker container to access a share drive on my local windows system. The share drive letter is "Q:", but I cannot get "-v /q:/home/rstudio/{folder}" to work. Thx for any help.

**Comment by eddelbuettel** [comment]
The syntax and example on Linux is `-vLOCAL:DOCKER`.  Note that the colon is a meta-character here: it separates a pair of values.  As such, try to pass `q:/` or `q:\\` will be difficult,

In any event, this is more of a basic Docker-on-Windows question for which we are not the best resource -- so please allow me to close this as it is not a genuinely specific question for Rocker.

Feel free to reopen with anything pertaining more specifically to Rocker.
