### ISSUE TITLE
set HTTPUserAgent to work with RSPM

### ISSUE THREAD

**Issue by maxheld83** [rocker-org/rocker#400]
[RStudio Package Manager (RSPM)](http://packagemanager.rstudio.com) now offers checkpointed binaries *and* Rocker seems to me migrating to Ubuntu (which is one of the supported binaries).

Currently, even when using `image:  "rocker/rstudio:3.6.3-ubuntu18.04"` and `repos = "https://packagemanager.rstudio.com/all/__linux__/bionic/279"`, packages are installed from source.

```yaml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test

jobs:
  setup-r:
    runs-on: ubuntu-16.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/xenial/latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: "3.6"
      - name: Test RSPM
        run: |
          source("https://docs.rstudio.com/rspm/admin/check-user-agent.R")
        shell: Rscript {0}
  rocker:
    runs-on: ubuntu-18.04
    container:
      image: "rocker/rstudio:3.6.3-ubuntu18.04"
    env:
      RSPM: https://packagemanager.rstudio.com/all/__linux__/bionic/latest
    steps:
      - uses: actions/checkout@v2
      - name: Test RSPM
        run: |
          source("https://docs.rstudio.com/rspm/admin/check-user-agent.R")
        shell: Rscript {0}
      - name: Test Install a Binary
        run: |-
          install.packages("remotes", repos = Sys.getenv('RSPM'))
        shell: Rscript {0}
```

reprex is live [here](https://github.com/maxheld83/rspm-bintest).

I think this is because the `option("HTTPUserAgent")` isn't set as RSPM expects:

```bash
2020-05-12T12:00:35.4263629Z ##[group]Run source("https://docs.rstudio.com/rspm/admin/check-user-agent.R")
2020-05-12T12:00:35.4264040Z [36;1msource("https://docs.rstudio.com/rspm/admin/check-user-agent.R")[0m
2020-05-12T12:00:35.4266455Z shell: Rscript {0}
2020-05-12T12:00:35.4266558Z env:
2020-05-12T12:00:35.4266685Z   RSPM: https://packagemanager.rstudio.com/all/__linux__/bionic/latest
2020-05-12T12:00:35.4266804Z ##[endgroup]
2020-05-12T12:00:35.8448182Z R version: R version 3.6.3 (2020-02-29)
2020-05-12T12:00:35.8451910Z OS version: Ubuntu 18.04.4 LTS
2020-05-12T12:00:35.8453016Z HTTPUserAgent: R (3.6.3 x86_64-pc-linux-gnu x86_64 linux-gnu)
2020-05-12T12:00:35.8453719Z Download method: libcurl
2020-05-12T12:00:35.8454356Z Download extra args: 
2020-05-12T12:00:35.8456095Z 
2020-05-12T12:00:35.8458178Z ----------------------------
2020-05-12T12:00:35.8458897Z 
2020-05-12T12:00:35.8463629Z You must configure your HTTP user agent in R to install binary packages.
2020-05-12T12:00:35.8464964Z 
2020-05-12T12:00:35.8466274Z In your site-wide startup file (Rprofile.site) or user startup file (.Rprofile), add:
2020-05-12T12:00:35.8466374Z 
2020-05-12T12:00:35.8466766Z # Set default user agent
2020-05-12T12:00:35.8467039Z options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os)))
2020-05-12T12:00:35.8467262Z 
2020-05-12T12:00:35.8467407Z 
2020-05-12T12:00:35.8467524Z Then restart your R session and run this diagnostic script again.
```

From the [RSPM docs](https://docs.rstudio.com/rspm/admin/serving-binaries/#binary-user-agents):

> If this diagnostic fails, R should be configured to include the R version and OS in the user agent header:
>
> ```r
> # Set the default HTTP user agent
> options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os)))
> ```

I think it'd be nice to set the user agent as RSPM expects:

- it's harmless -- the UserAgent is an arbitrary string anyway
- it does not require any reliance on RSPM; but *when* people set `repos = "https://packagemanager.rstudio.com/all/__linux__/bionic/279"`, they have one less arcane thing to worry about.

**Comment by eddelbuettel** [comment]
Nice. I actually poked my head into this seeing how well it works on RStudio Cloud -- but hit that very barrier and was not sure if this was, or was not, supposed to work. Your issue is therefore quite helpful.

Note, however, that a number of Rocker containers remain Debian based (as e.g. `r-base`).  The versioned2 is stack uses Ubuntu, as does my `r-ubuntu`.  We'll likely play.

**Comment by maxheld83** [comment]
Yeah, this one was hard to figure out. 

I kind of assumed that all necessary information for the RSPM server to pick the right binary was included in the URL `repos = "https://packagemanager.rstudio.com/all/__linux__/bionic/279"`, because that *does* include `bionic`, which also might have been more transparent to the user.

I'm sure there were good reasons for using the user agent, but I'm wondering how many other people, in different circumstances, will stumble over this.

**Comment by eddelbuettel** [comment]
@maxheld83  One cold or hot drink of your choosing on me :)

I must have been in a rush---I had missed how the documentation does it infact mention the header
identication and even provides a helper script.  Anyway, moot now, point taken.  

I just edited two lines in `/etc/R/Rprofile.site` to a) no longer point at CRAN but b) point at the RSPM repo _and_ set the header:

```r
> system("tail -4 /etc/R/Rprofile.site")
    r["RSPM"] <- "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"
    options(repos = r)
    options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), 
                 paste(getRversion(), R.version$platform, 
                       R.version$arch, R.version$os)))
})
> 
```

and that in fact fetch me a binary on demand:

```r
> install.packages("digest")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.rstudio.com/all/__linux__/bionic/latest/src/contrib/digest_0.6.25.tar.gz'
Content type 'binary/octet-stream' length 263523 bytes (257 KB)
==================================================
downloaded 257 KB

* installing *binary* package ‘digest’ ...
* DONE (digest)

The downloaded source packages are in
        ‘/tmp/RtmpyDAEx5/downloaded_packages’
>
```

I am using `rocker/r-ubuntu:18.04` here.

**Comment by cboettig** [comment]
@maxheld83 I'm not getting any luck even after setting HTTPUserAgent in options:

```
docker run --rm -ti rocker/r-ver:4.0.0-ubuntu18.04 R -e 'options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os))); install.packages("crayon", repos = "https://packagemanager.rstudio.com/all/__linux__/bionic/279", type = "binary")'
```

Not sure if there are some other subtle assumptions going on here.  e.g. one difference is that r-ver installs R itself from source, where-as rocker/r-ubuntu18.04 where @eddelbuettel reports success installs R from binary, but not sure if that matters?

**Comment by eddelbuettel** [comment]
Two quick comments
-  I used `.../latest` not 279 so simpler case.  
-  I didn't append `type=binary`; this is something I looked into on the weekend but no luck.

**Comment by cboettig** [comment]
@eddelbuettel good call!   Yeah, `type="binary"` is not supported (I was confused to see it download a tarball from `src/contrib` path, but as you show it does indeed install binary.  

Also, I was testing on R `4.0.0`, for which it appears binaries don't yet exist.  (likewise for `focal`).  If I drop back to `3.6.3` and drop the `type` arg, it works!


```
docker run --rm -ti rocker/r-ver:3.6.3-ubuntu18.04 R -e 'options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os))); install.packages("digest", repos = "https://packagemanager.rstudio.com/all/__linux__/bionic/279")'
```

```
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.rstudio.com/all/__linux__/bionic/279/src/contrib/digest_0.6.25.tar.gz'
Content type 'binary/octet-stream' length 263523 bytes (257 KB)
==================================================
downloaded 257 KB

* installing *binary* package ‘digest’ ...
* DONE (digest)

The downloaded source packages are in
        ‘/tmp/RtmpeEsBXQ/downloaded_packages’
> 
```
:tada:

**Comment by eddelbuettel** [comment]
Doh, should have picked up on that.  I also tested (and failed) with 4.0.0.

**Comment by maxheld83** [comment]
yeah, I can confirm that this is (another) issue I stumbled over: RSPM doesn't have binaries for 4.0.0 yet. I reached out to the team and [asked them to place this info more prominently on the web UI](https://community.rstudio.com/t/surface-binary-availability-for-r-versions-in-rspm) (I think it's super easy to miss).

Sorry should've warned you.

**Comment by cboettig** [comment]
yup.  I think it's worth mentioning the issue re `type` as well in that RSPM approach deviates from the documentation of `install.packages`.  Explicitly requesting `type="source"` *does not install from source if a binary is available when using RSPM, and  explicitly stating `type="binary"` will incorrectly say 'no binary is available' and throw an error.
