### ISSUE TITLE
Rstudio Desktop with UI binding

### ISSUE THREAD

**Issue by kieran-mace** [rocker-org/rocker#402]
I was reading [this article](https://dev.to/darksmile92/run-gui-app-in-linux-docker-container-on-windows-host-4kde) and realized it would be possible to run a gui app within docker. 

While Rstudio Server through the browser is great, I miss having the local keybindings (such as alt-tab to switch applications).

Would it be possible to create a rocker image using rstudio desktop, and allowing users to run the rstudio desktop (with its gui) on their machines?

**Comment by cboettig** [comment]
@kieran-mace it's possible, but far less portable, and I'm not entirely clear on the motivation (e.g. alt-tab should still switch between applications -- and you can have multiple rstudio-servers open in different tabs and your hotkeys for switching between browser tabs should work just as well).  I believe RStudio desktop is built on the same css/javascript stack that server uses, and should be very much feature compatible.  I believe supporting GUI app would introduce considerably more hurdles for users to setup, & would not be effective with remote servers.

If you are interested in non-RStudio GUI based interfaces, we suggest taking a look at our X11 documentation, e.g. https://github.com/rocker-org/rocker-versioned/tree/master/X11 .  This works when you need it, but as you see becomes much more finicky and host-platform-specific...
