### ISSUE TITLE
git is broken in Ubuntu Focal R v4.0.0 RStudio 

### ISSUE THREAD

**Issue by tyson-swetnam** [rocker-org/rocker#408]
Followed this error up stream from `rocker/geospatial:latest` back into `rocker/rstudio:latest` 

Clone with HTTPS broken in containers with tags `4.0.0` and `latest` 

Error in Terminal: 

```
rstudio@590a9e31239e:~$ git clone https://github.com/rocker-org/rocker
Cloning into 'rocker'...
fatal: unable to access 'https://github.com/rocker-org/rocker/': gnutls_handshake() failed: An unexpected TLS packet was received.
rstudio@590a9e31239e:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
rstudio@590a9e31239e:~$ 
```

Googling suggests that git needs to be rebuilt against libcurl and opessl:

https://stackoverflow.com/questions/51088635/git-clone-error-gnutls-handshake-failed-an-unexpected-tls-packet-was-receive

Thanks for all these amazing container recipes! We're utilizing them extensively in our platform.

**Comment by cboettig** [comment]
Thanks for the report.  I cannot the error at this at this time, are you sure you have the latest version?  clone works fine for me on `rocker/geospatial:latest`  (with `sha256:33fa4f8bc9833d44c200c022000cb1413db4e481b86df0fd6af389d4cbb68355`)

It does look like it has the wrong libcurl though, so we need to fix.  We build with libcurl4-openssl-dev, but there's a handful of `apt` packages that depend on the gnutils version and pull that in, silently removing the openssl version.  We'll have to track down where that is happening and re-install the openssl version I think...

**Comment by tyson-swetnam** [comment]
Thanks for investigating this Carl. I now think this has to do with our University / CyVerse firewalls - I can run the `latest` containers on my home computer and it can pull from Github. When I run the container on my workstation over VPN it breaks and in CyVerse it breaks. All of our Rocker <v3.6.3 containers still work for `git` 

I've submitted this to the CyVerse core software folks to see if they can turn up the issue.

**Comment by tyson-swetnam** [comment]
last follow up -- our folks took a look and it appears to be an Ubuntu 20.04 issue https://ubuntuforums.org/showthread.php?t=2442861

**Comment by cboettig** [comment]
@tyson-swetnam ok, `verse` and `geospatial` etc should all be using `libcurl4-openssl-dev` instead of the gnutils one now. Can you try pulling fresh images and see if that helps things?

**Comment by tyson-swetnam** [comment]
`git clone` still failing over HTTPS in the `4.0.0` and `latest` tags that are using ubuntu20.04

Success for `git` in both `:4.0.0-ubuntu18.04` tags for `verse` and `geospatial` 

from `docker pull rocker/verse:4.0.0`:
```
$ docker inspect rocker/verse:4.0.0
[
    {
        "Id": "sha256:1b1fd2860f4889c478bd715cd3b3c1512c7a0ccfcab4678508e78e1a77dc3db0",
        "RepoTags": [
            "rocker/verse:4.0.0"
        ],
        "RepoDigests": [
            "rocker/verse@sha256:bf0e9a5bd67d6899a9645f6482d32d818405916a843328adeb31068971c0c2a3"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2020-06-30T03:59:09.916106489Z",

```

`rocker/geospatial:4.0.0`:
```
$ docker inspect rocker/geospatial:4.0.0
[
    {
        "Id": "sha256:f9d2f7aed1aa820a20f996f176e9569b7daaa133e795f5a8d2ec5a6c73015052",
        "RepoTags": [
            "rocker/geospatial:4.0.0"
        ],
        "RepoDigests": [
            "rocker/geospatial@sha256:a14c7fcb21dea18bc06fe8b9c72d076abafaf7aece907e75b66fd4c44c861690"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2020-06-30T05:33:15.045559247Z",
```

We're able to run the `4.0.0-ubuntu18.04` in CyVerse
