### ISSUE TITLE
license for rocker/rstudio docker image?

### ISSUE THREAD

**Issue by sclan** [rocker-org/rocker#410]
Hello I understand that the rocker/rstudio docker image is a rstudio server image. Do we have a official license information for this? I just want to make sure it is OK for distributing in the commercial setting. Thanks.

According to 
https://support.rstudio.com/hc/en-us/articles/217801078-What-license-is-RStudio-available-under-#:~:text=RStudio%20is%20available%20under%20the,software%20for%20all%20its%20users.

The RStudio has AGPL v3.0 which is free to share and change the software. But nothing is mentioned for the Rstudio server (not Rstudio server pro).

**Comment by eddelbuettel** [comment]
The Rocker Project has explicit permission from RStudio to distribution rstudio and shiny server.  I am not a lawyer but I do not think this carries over to products derived from Rocker containers.
