### ISSUE TITLE
podman does not run /init

### ISSUE THREAD

**Issue by btreut** [rocker-org/rocker#414]
Similar to closed case #202 using rocker images with podman, it is necessary to run /init manually (see also [endless os community](https://community.endlessos.com/t/problems-running-rstudio-via-podman/13683/8))

**Comment by cboettig** [comment]
Yup, RStudio server wants to run as root, `podman` doesn't.  One day we'll figure out a work-around but we don't have one yet.

**Comment by btreut** [comment]
> Yup, RStudio server wants to run as root, `podman` doesn't. One day we'll figure out a work-around but we don't have one yet.

apparently [resolved with podman 2.2.0](https://github.com/rstudio/rstudio/issues/3079#issuecomment-740030699)

**Comment by btreut** [comment]
maybe related to this [issue for rodman](https://github.com/nuest/rodman/issues/1)

**Comment by eddelbuettel** [comment]
This discussion is in the wrong repo.  You probably meant rocker/versioned-2 and I will transfer this now.
