### ISSUE TITLE
R-devel entrypoint is R not R-devel

### ISSUE THREAD

**Issue by hhoeflin** [rocker-org/rocker#416]
I pulled the latest R-devel container and when I ran it, I was dropped into version 4.0.2 of R instead of R-devel.

Is this intentional? My expected behavior would be that the entrypoint is set to Rdevel in the rocker/r-devel container.

Thanks for providing these!

**Comment by eddelbuettel** [comment]
It is, believe it or not.  Because we derive from the r-base container, R is always just R.

You want `RD`.  Same for containers `drd` (== daily r-devel, but now weekly) and `drp` (== daily r-patched).  There is not too much difference between r-devel and drd, the latter is likely a little smaller.

**Comment by hhoeflin** [comment]
Thanks. Closing.

**Comment by eddelbuettel** [comment]
I apologise for the poor documentation on this, but it 'has been like this for years' so we can't just change the behavior now. The (excellent) r=debug container by @wch1 does the same so at least using `r-devel` or `drd` and their `RD` use prepares you for later sessions with `RDsan` or `RDvalgrind` :)
