### ISSUE TITLE
rocker/rstudio should allow for --drop-cap=all when running in a Docker environment. 

### ISSUE THREAD

**Issue by TtheBC01** [rocker-org/rocker#428]
Its typically helpful for security purposes to drop all unnecessary kernel capabilities for a docker container, however, running rocker/rstudio with all capabilities dropped

 docker run -it --rm  --env PASSWORD=hello --cap-drop=all rocker/rstudio

produces a system permission error that is difficult to circumvent, even when the container user is root. Jupyter notebook containers allow for reduced kernel capabilites, so I imagine it must be possible in this scenario as well.

**Comment by eddelbuettel** [comment]
We are not authors of RStudio (but simply have their permission to ship it in our containers).  Your request, it seems, concerns design issues in their product and may therefore be more appropriate at their repo.

**Comment by TtheBC01** [comment]
bummer, I'll try over there then. Thanks!
