### ISSUE TITLE
instead of 3.6.2 I got 3.6.3

### ISSUE THREAD

**Issue by degr** [rocker-org/rocker#430]
![image](https://user-images.githubusercontent.com/9214659/101398134-acec6200-38de-11eb-8773-297055a8c307.png)

**Comment by eddelbuettel** [comment]
Yeah. Stuff happens. It was a combination of lax design and bad timing on my part which is how the RC release crept in. In hindsight, I regret both.

But see the current page giving you clearly identifiable tags from 3.6.3 onwards:  https://hub.docker.com/r/rocker/r-base/tags?page=1&ordering=last_updated

(Also, please don't post images. That was easily copy-and-pasteable text.)

**Comment by degr** [comment]
I did not get, is it possible to make docker image with r version 3.6.2?
>Also, please don't post images
Ok, I'm not very smart

**Comment by eddelbuettel** [comment]
Also _most_ other version still work under the official label `r-base` which is identical, i.e. our container.  I.e. I have a variety here:

```sh
edd@rob:~$ docker images | grep ^r-base
r-base                               4.0.3               f6f1f4182a9d        7 weeks ago         766MB
r-base                               latest              f6f1f4182a9d        7 weeks ago         766MB
r-base                               4.0.2               194fa228510e        4 months ago        824MB
r-base                               4.0.1               0836c59d7d07        6 months ago        699MB
r-base                               4.0.0               502b38518c3c        6 months ago        692MB
r-base                               3.6.3               3aad1ffccc53        9 months ago        679MB
r-base                               3.6.2               46edce0e80af        9 months ago        677MB
r-base                               3.6.1               4e55790c88ae        17 months ago       642MB
r-base                               3.6.0               6dfc0dec6d66        19 months ago       662MB
r-base                               3.5.3               62c848eeb175        20 months ago       649MB
r-base                               3.5.2               578644a0540c        23 months ago       650MB
r-base                               3.5.1               93ca38345db2        2 years ago         678MB
r-base                               3.5.0               fb43e8fe1667        2 years ago         698MB
r-base                               3.4.4               d1325eaa28ad        2 years ago         667MB
r-base                               3.4.3               d1e1c25485af        2 years ago         670MB
r-base                               3.4.2               02d3b7e00020        3 years ago         651MB
r-base                               3.4.0               5a6c58403310        3 years ago         656MB
r-base                               3.3.3               88436550cddc        3 years ago         635MB
r-base                               3.3.1               7ba1baf9d8bb        4 years ago         657MB
edd@rob:~$ 
```

Those were _all_ downloaded (as what I build locally usually gets a prefix `local-*`).  

You can build locally whatever you want. We have nothing to do with that.  R sources are on the CRAN mirrors; if you want to use Debian binaries you can using archive.debian.org for old binaries.

**Comment by eddelbuettel** [comment]
And in the very narrow sense we here provide `rocker/r-base` which is binary identical to `r-base` as those official builds use our files.  _But we do not control or influece their builds_ which is how 3.6.3 RC slipped in for the last 3.6.2 build as I was late flipping to the 3.6.3 label.  Without a time machine there is nothing we can for _that pre-made container_.  But you can build yourself a better one by running the steps by hand (and archive.debian.org should give you the old files) and we changed our processes with 3.6.3 to not repeat this.  

For both those reasons I closed the ticket.  Again, I am sorry that you got 3.6.3 RC when you expected 3.6.2.  That wasn't the plan, but that is all there is right now.  3.6.1 is still 3.6.1:

```sh
edd@rob:~$ docker run --rm -ti r-base:3.6.1 Rscript --version
R scripting front-end version 3.6.1 (2019-07-05)
edd@rob:~$ 
```

**Comment by cboettig** [comment]
p.s. there's also the versioned stack, e.g.
```
docker run --rm -ti rocker/r-ver:3.6.2 R
```
