### ISSUE TITLE
R-base Image for s390x

### ISSUE THREAD

**Issue by anujajakhade** [rocker-org/rocker#432]
Hi,

I tried to build r-base docker image on s390x using the Dockerfile shared [here](https://github.com/rocker-org/rocker/blob/master/r-base/4.0.3/Dockerfile).
The [Dockerfile](https://github.com/rocker-org/rocker/blob/master/r-base/4.0.3/Dockerfile) works good on s390x.
Also Debian Image for s390x is provided by the [Dockerhub](https://hub.docker.com/_/debian?tab=tags&page=1&ordering=last_updated).
Is it possible for you to provide the R-Base image for s390x architecture?

**Comment by eddelbuettel** [comment]
I am not sure.  All our images _within the Rocker Project_ build on Docker Hub in standard "amd64" form (aka "x86_64").  I have never seen a toggle or switch to build different images though I presume there might be one somewhere. Do you know?

What I can do is request a change in the _official_ R image built off our `r-base` container you used here.  We currently build for three architectures, adding a fourth should be straightforward:

https://github.com/docker-library/official-images/blob/5a3dabae9155aa096c4795f28035cdd9a23e4e87/library/r-base#L6

**Comment by anujajakhade** [comment]
@eddelbuettel Thank you for the reply. 
I think adding s390x support in the mentioned [file](https://github.com/docker-library/official-images/blob/5a3dabae9155aa096c4795f28035cdd9a23e4e87/library/r-base#L6), can help in creating a manifest for s390x in `r-base` image.

**Comment by eddelbuettel** [comment]
Pull request made -- which was just merged. 

So as soon as that goes to build you should have an r-base image for s390x.
