### ISSUE TITLE
docker pull r-bspm manifest unknown

### ISSUE THREAD

**Issue by verajosemanuel** [rocker-org/rocker#436]
hi

Trying  to test bspm docker container but command pull raises an error:

```
docker pull rocker/r-bspm
Using default tag: latest
Error response from daemon: manifest for rocker/r-bspm:latest not found: manifest unknown: manifest unknown
```

regards

###############

Solved calling specific tag. ("latest" is not available)

**Comment by eddelbuettel** [comment]
There is no latest.  There are `18.04` and `20.04` for Ubuntu, and `testing` for Debian, see https://hub.docker.com/r/rocker/r-bspm/tags?page=1&ordering=last_updated

Because there are two "competing" distro we cannot have one promoted to `latest`.

(@cboettig There is a minor nuisance in that the top-level README.md still "squats" on all the subdirectories. At one point I had carefully written README.md entries (sadly, direcly at hub.docker.com) for a handful of my image directories ... only to see them replaced by the generic one. :crying_cat_face:  Something to clean up one days I suppose.)

**Comment by cboettig** [comment]
@eddelbuettel yeah totally.  At some point we need to tidy up READMEs and come up with a better strategy to help users find the right repos

**Comment by MatthieuStigler** [comment]
sorry @verajosemanuel , could you please share a few more details on what you mean by _Solved calling specific tag_ ? How did you proceed exactly, i.e. which command/tag? Thanks!

**Comment by eddelbuettel** [comment]
@MatthieuStigler The standard Docker identification is

    $ docker pull  [repo/]/NAMESPACE/IMAGE_NAME[:tag]

We almost never use the first and fall back to the Docker repository, but there is `ghcri.io` for GitHub's.  We sometimes omit the tag at the end and get `latest` if it exists.  

As an illustration I have these for r-bspm accumulated here and could pick any one:

```sh
edd@rob:~$ docker images | grep r-bspm
rocker/r-bspm                        f38             a95027b18f0c   7 days ago      808MB
rocker/r-bspm                        22.04           dc915499b6d8   6 weeks ago     790MB
rocker/r-bspm                        jammy           dc915499b6d8   6 weeks ago     790MB
rocker/r-bspm                        focal           822f1a0721d4   6 weeks ago     759MB
rocker/r-bspm                        20.04           14dbaac4a2e0   6 weeks ago     759MB
rocker/r-bspm                        testing         f8d638093496   6 months ago    912MB
rocker/r-bspm                        <none>          e088566db42b   10 months ago   785MB
rocker/r-bspm                        18.04           4e20bf46aca2   13 months ago   659MB
edd@rob:~$ 
```

Note that I have not designed any one as `latest` but using the Ubuntu (or Fedora) release id gets me _precisely_ what I want.

(Also consider [r2u](https://eddelbuettel.github.io/r2u/) and its `rocker/r2u` images,  They are an improved _superset_ with a (much) richer repo behind them.

**Comment by bbolker** [comment]
Is this documented somewhere more prominent?  If not, could it be?  I went to to [images page](https://rocker-project.org/images/) and encountered the same issue (with the same solution). .e.g., tell people to look at https://hub.docker.com/r/rocker/r-bspm/tags?page=1&ordering=last_updated for the list of possible tags ...
