### ISSUE TITLE
Question - running studio server and installing packages in linked volume (folder)

### ISSUE THREAD

**Issue by rkrug** [rocker-org/rocker#441]
I would like to use the studio rocker image as a studio server. This works, and I can access it. But I would like to have the package library in a linked volume. I know how I can sweep linked volumes (https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine), but what is the `/FOLDER/IN/DOCKER` in the docker image?

```
docker run -v /Users/bob/R/library:/FOLDER/IN/DOCKER [...]
``` 

Also - is there anything else I have to do, so that this directory will be used?

Thanks.

**Comment by eddelbuettel** [comment]
(Untested)

`/FOLDER/IN/DOCKER` is any folder you make accessible to Docker / inside Docker. For example:  `/opt/R/packages/`.  You then probably need to (from the outside too) set `R_LIBS` or `R_LIBS_USER` to adjust your `.libPaths` to add `/opt/R/packages`. You could also try editing `/etc/R/*` files in the container and re-commit it but the "transient" use of environment variables may be simpler.

**Comment by rkrug** [comment]
Thanks Dirk - sounds perfect with using the environmental variable.
Now I just have to figure out how I can start a docker image on startup of my Mac.
