### ISSUE TITLE
Request - A new rocker image for a miniCRAN server

### ISSUE THREAD

**Issue by kieran-mace** [rocker-org/rocker#449]
Requesting a new rocker image to host a miniCRAN server. 

I found this: https://hub.docker.com/r/crazycapivara/minicran but fear it has not been maintained for over 3 years.

**Comment by eddelbuettel** [comment]
We are volunteers here so 'requesting' is a little dicey -- we can only spread ourselves so thinly.  Moreover, the container you point to appears to have little to nothing to do with us so I think I am in my right to close this here as there is no issue _in an existing Rocker container_ demonstrated here.  Should we have overlooked any Rocker issues please feel free to reopen.

The best next step might be for you to build a miniCRAN-capable container based off an existing container (which might well be a Rocker container too).  We are generally happy to help with tips and errors.

**Comment by kieran-mace** [comment]
Sorry didn't mean to sound presumptuous. Thank you for all you do. I just thought it was a neat idea, and be a valuable addition to the already wonderful rocker ecosystem.

**Comment by eddelbuettel** [comment]
I so agree, which is part of the problem -- there are simply too many "nice to have" packages around so unfortunately we have to draw a line somewhere, and right now at a somewhat "foundational" level seems to make sense as it allows other to build on it.

So sorry to be a bearer of bad news, and I am glad you sympathise.

**Comment by kieran-mace** [comment]
Understand 100%. thanks Dirk.
