### ISSUE TITLE
Launching rocker/rstudio on HPC

### ISSUE THREAD

**Issue by ATpoint** [rocker-org/rocker#456]
Hello,

I see many issues related to that, none with a satisfying answer so far. Could you provide a solution for this, or give advise on where to start debugging. Do you need more details from me, if so which? Thank you!

```
singularity pull --name rstudio.simg docker://rocker/rstudio:4.0.3

$ singularity exec rstudio.simg rserver --www-address=127.0.0.1
04 May 2021 09:28:13 [rserver] ERROR database error 7 (sqlite3_statement_backend::loadOne: attempt to write a readonly database) [description: Could not delete expired revoked cookies from the database, description: Could not read revoked cookies from the database]; OCCURRED AT virtual rstudio::core::Error rstudio::core::database::Connection::execute(rstudio::core::database::Query&, bool*) src/cpp/core/Database.cpp:480; LOGGED FROM: int main(int, char* const*) src/cpp/server/ServerMain.cpp:729
```

**Comment by cboettig** [comment]
@ATpoint Thanks, yes, we are a volunteer open source project and our support on Singularity has been provided almost entirely by community members like yourself.  It is helpful if you can post your issue under the related thread as it is more visible.  (RStudio-based images are actually hosted over in rocker-versioned2 stack, where you may find more comments if you haven't already?  I'd recommend starting with
https://github.com/rocker-org/rocker-versioned2/issues/105#issuecomment-799848638 and see if those options resolve the issue?)

HTH!

**Comment by ATpoint** [comment]
Thank you for your comment. It turns out that the linked solution (mounting various of the /var folders) works indeed fine and previously it was simply a pebkac on my side, apologies for that.
