### ISSUE TITLE
 Lookinf for 4.1.1 (Kick Things) and its R-devel  (Unsuffered Consequences")

### ISSUE THREAD

**Issue by ZheFrench** [rocker-org/rocker#466]
I was wondering when you will post the new release and its associated devel version.

Actually ,The rocker/r-devel  contains :

```
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
R Under development (unstable) (2021-07-24 r80661) -- "Unsuffered Consequences" 
```

The very last one should be ; 
```
R version 4.1.1 (Kick Things) has been released on 2021-08-10.
NEWS for R Under development (unstable) (2021-09-06 r80864)
```

Is this possible to make an update :) 

Thanks.

**Comment by eddelbuettel** [comment]
There are several issues at play here.  The main one is that Docker, the company, turned autobuilds off, breaking my cronjob.

I have started to manually (or cron-tab'ed) build and push and will do so for now:

```sh
edd@rob:~$ docker run --rm -ti rocker/drd Rscript --version
R scripting front-end version 4.1.1 (2021-08-10)
edd@rob:~$ docker run --rm -ti rocker/drd RDscript --version
R scripting front-end version 4.2.0 Under development (unstable) (2021-09-05 r80859)
edd@rob:~$ 
```

The other issue is that `rocker/drd` and `rocker/r-devel` have a lot of overlap so I had not yet added r-devel to the mix.  Can you live with `rocker/drd` ?

**Comment by eddelbuettel** [comment]
I am building rocker/r-devel now, it should be up in a bit.

**Comment by ZheFrench** [comment]
Thanks.
