### ISSUE TITLE
please upgrade bspm -> R4.1

### ISSUE THREAD

**Issue by mpadge** [rocker-org/rocker#468]
@eddelbuettel We at rOpenSci have built an entire automated checking system using your `bspm` images, but absent build for R4.1, any code with native pipes crashes the entire thing. Please upgrade asap!!!

**Comment by eddelbuettel** [comment]
Hi @mpadge can and will do.  In my excuse the fustercluck of Docker stopping builds set me (just like others) back a little. I started this week (for drd, drp, r-devel) to add autobuilds from GitHub Actions, I will add more.    And ... now that I _know_ this used in prod I will of course look after it too.  I had mostly assumed it was used .... just by me as everybody is doing things in different ways (as everybody is free too).

Now, as there are 'multiple' bspm builds:  Which one(s) are you on?  Ubuntu 20.04?  Debian testing?  Fedora (hi @enchufa2 !) ?

**Comment by mpadge** [comment]
Ubuntu 20.04, if you please good sir!!

**Comment by eddelbuettel** [comment]
Coming right up where "right" is rate limited by my asymmetric retail broadband ....

**Comment by eddelbuettel** [comment]
```sh
edd@rob:~/git/rocker/r-bspm/focal(master)$ dkrr rocker/r-bspm:20.04 Rscript --version    # dkrr is a local alias
R scripting front-end version 4.1.1 (2021-08-10)                                                                                                                                                                   
edd@rob:~/git/rocker/r-bspm/focal(master)$ 
```

**Comment by eddelbuettel** [comment]
Should be there now.  Give it a whirl.

**Comment by mpadge** [comment]
Thanks so much for the fabulously prompt response! All works perfectly
