### ISSUE TITLE
running as root

### ISSUE THREAD

**Issue by paupaiz** [rocker-org/rocker#476]
I used the -e ROOT=true option and still got the issue on the picture attached (i.e. running whoami still returns rstudio). Any suggestions greatly appreciated!
<img width="376" alt="Screen Shot 2021-11-23 at 8 11 42 AM" src="https://user-images.githubusercontent.com/59720098/143061528-7e21793f-719e-47db-993c-67b216288dce.png">

**Comment by eddelbuettel** [comment]
> running whoami still returns rstudio

So you're not the `root` user.  This depends also on how you launch docker.

```
$ docker run -ti --rm r-base whoami
root
$ 
```

**Comment by paupaiz** [comment]
In the container I am. In rstudio I am not but I want to access a bind mount that is on root dir (I tried putting it after /home/.cache but for some reason gets changed to /root/.cache) 
<img width="172" alt="Screen Shot 2021-11-23 at 8 39 00 AM" src="https://user-images.githubusercontent.com/59720098/143066050-bcd1e54f-b94b-462e-b457-7a6d67a6bd48.png">

**Comment by eddelbuettel** [comment]
We are in the wrong repo within rocker here.  You are having rstudio usage questions (the RStudio product runs as user 'rstudio') so I suggest I transfer this to repo rocker-versioned2.  

One short way out is to look into `docker exec` to get yourself a second shell inside the running container.

**Comment by eddelbuettel** [comment]
Closing this as refiled in versioned2.
