### ISSUE TITLE
Unable to install system dependencies

### ISSUE THREAD

**Issue by paulimer** [rocker-org/rocker#488]
Hi,
Switching my base image (from r-ver:4.0.5 to 4.1.3), I've run into an issue trying to install system dependencies of some R packages  (devtools mostly). Those are with the `libcurl'-*-dev` packages. As I'm not very proficient with apt, I don't know if I can resolve this issue during the building of my container. Is it expected behavior?
More details : 

- OS : Fedora 35
- Docker container tried : rocker/r-ver:4.1.3, rocker/r-base:latest
- Command launched : 
```docker
RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    libharfbuzz-dev \
    libpng-dev \
    libfontconfig1-dev \
    libfreetype6-dev \
    libtiff-dev \
    libfribidi-dev \
    libjpeg-dev \
    libcurl4-openssl-dev \
    libgit2-dev \
    libxml2-dev \
    libicu-dev \
    && rm -rf /var/lib/apt/lists/*
```
- What I was expecting : All the dependencies to be normally installed, as has been the case with the other base image (r-ver:4.0.5) I've been using for a few months now. 
- The error I get : 
With the rocker/r-base:latest base image : 
```sh
The following packages have unmet dependencies:
 libcurl4-gnutls-dev : Conflicts: libcurl4-openssl-dev but 7.82.0-2 is to be installed
 libcurl4-openssl-dev : Conflicts: libcurl4-gnutls-dev but 7.82.0-2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

With the rocker/r-ver:4.1.3 base image : 
```sh
The following packages have unmet dependencies:
 libcurl4-gnutls-dev : Conflicts: libcurl4-openssl-dev but 7.68.0-1ubuntu2.7 is to be installed
 libcurl4-openssl-dev : Conflicts: libcurl4-gnutls-dev but 7.68.0-1ubuntu2.7 is to be installed
E: Unable to correct problems, you have held broken packages
```

Thanks

**Comment by eitsupi** [comment]
My understanding is that only one of `libcurl4-openssl-dev` or `libcurl4-gnutls-dev` can be installed (installing the other will uninstall the other).
Please see the following.
https://serverfault.com/questions/331794/what-is-the-difference-between-installing-libcurl4-gnutls-dev-or-libcurl4-nss-de

I don't know why your Dockerfile says that, but you need to remove one or the other.

**Comment by paulimer** [comment]
Yes indeed that was it! I gathered dependencies from different sources, leading to this unfortunate collision. 
Thanks
