### ISSUE TITLE
persistence of home directory

### ISSUE THREAD

**Issue by geoHeil** [rocker-org/rocker#497]
This:

`docker run --rm -ti -p 8788:8787 -v /path/to/my/work:/workspace rocker/rstudio`

fails to start up - even when docker is creating a fresh empty directory.

How can the UIDs be mapped in a way that this works?

**Comment by cboettig** [comment]
`/workspace` is a path below the "home" directory and thus not in the user's space, and requires root access.  Please try specifying a location using a subdirectory under the default user's home directory: e..g 

```
docker run --rm -ti -p 8788:8787 -v /path/to/my/work:/home/rstudio/workspace rocker/rstudio
```

when sharing volumes.

**Comment by cboettig** [comment]
(note that you should be able to map to directories below `/home/rstudio` as in your above example, it is only that inside the container, the default user will not have access to that directory.  I'm not entirely sure what "fails to start up" means, but your command shouldn't result in an error, it just doesn't give the `rstudio` user access to the volume you are sharing.  Can you be more specific?)

**Comment by geoHeil** [comment]
This is the error I get:
<img width="414" alt="RStudio" src="https://user-images.githubusercontent.com/1694964/181877088-be861503-fd36-466f-b7aa-bf5aba993ed9.png">

when running your docker command:

```
docker run --rm -ti -p 8788:8787 -v /path/to/work:/home/rstudio/workspace rocker/rstudio
```

**Comment by geoHeil** [comment]
thanks this already gives me the right hints.
