### ISSUE TITLE
Distroless R?

### ISSUE THREAD

**Issue by atursams** [rocker-org/rocker#499]
### What operating system related to this question?

Linux

### Question

Hi Dirk,
You have been very kind to help me in the past! Here is hoping you can do so twice.:)
Our customer wants our R solution in a distroless image. Is that even possible?
I know there are python/java/rust distroless but never heard of R.
How would one go about making R distroless with bazel?

Best regards,
Atur Sams

**Comment by eitsupi** [comment]
Related to #492, GoogleContainerTools/distroless#1115

**Comment by eddelbuettel** [comment]
@eitsupi we should probably go over a few of those and close them -- they are all feature requests that are not without merit, but we are limited in what _we_ can provide as volunteers here.  So as in this, case actively envourage the OPs to experiment with such (nice and possibly complementary to Rocker) technologies but we do not have the bandwidth to go off on it ourselves.
