### ISSUE TITLE
Non-root users, shared volumes, & RStudio

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker#50]
Docker does some kinda unexpected things when it comes to handling non-root users and shared volumes.  With the rstudio image, we have to create a non-root user with a password that can be set at runtime for security purposes, which we do by running a custom [userconf.sh](https://github.com/rocker-org/rocker/blob/master/debian/rstudio/userconf.sh) on startup.  

RStudio wants to start in the users home directory (regardless of the value of --workdir).  First crazy thing is: if the userconf.sh script does not run a `chown` command (as we have currently), that directory is not owned by the user `rstudio` (or other user specified with the environment variable `$USER`.  Lacking write permissions, RStudio cannot even start up.  Surprisingly, the directory `/home/rstudio` is owned by the user `docker`!

If we run `chown -R $USER:$USER /home/$USER` at the end of the userconf.sh script, RStudio can now log in.  But if we have linked a home directory, `chown`ing to anything other than the the `docker` user (Why the docker user?  Just the first non-root user added to docker?) means that the permissions on the linked directory _outside_ of the container will be changed to some other user.  Attempting to match the host user name with the $USER value on the container isn't any different than just leaving the container $USER as docker.  

The only way out of this that I see is to have only one user (e.g. hardwire the user `docker`, and just set the password interactively.  breaks previous instructions and feels inelegant).  Can't be sure if this problem existed before we added a default user `docker`, perhaps removing that would avoid these issues?  

Anyway, curious if you might confirm any of this behavior, and I'll see what I can come up with.

**Comment by dyndna** [comment]
@cboettig : Although a non-root user can share folders with running container, it is not a good idea to allow sharing of entire user home `~/`, worse if shared folder is above `~/`.

```
docker run -d -P -v $(pwd)/home/$USER/foo \
-e USER=$USER  -e USERID = $UID rocker/rstudio
```

Running docker container as daemon with above command **recursively and irreversibly** sets owner permission to $UID and **removes SUID, if set**. At present, `docker stop <container_id>` has no mechanism to reset original owner persmission for all files and folders below working directory.

Although such behavior may be acceptable if one has specified $USER home `~/` or below as working directory, it is certainly a bad idea if user goes above `~/` which is either `/home/` in linux or `/Users/` in mac,  or working directory is a block partition where other disks are mounted, e.g., `/dev/sdb1` on `/scratch`. I had several system level configurations at `/scratch/`, where some folders were owned by root and SUID set. Following `docker run` command as above made my system unstable and had hard time to locate original owner level permission for several files and folders.

If a user run like following by switching to root block partition `/`, that is guaranteed system failure! 

```
cd /
docker run -d -P -v $(pwd)/home/$USER/foo \
-e USER=$USER  -e USERID = $UID rocker/rstudio
```

I tried it on dummy system and only way to recover is to access hard drive from different system and go file by file to revert to root as owner and set SUID for at least following binaries [source](http://blog.tutum.co/2015/02/03/hardening-containers-disable-suid-programs/).

```
/sbin/unix_chkpwd
/usr/bin/chage
/usr/bin/passwd
/usr/bin/mail-touchlock
/usr/bin/mail-unlock
/usr/bin/gpasswd
/usr/bin/crontab
/usr/bin/chfn
/usr/bin/newgrp
/usr/bin/sudo
/usr/bin/wall
/usr/bin/mail-lock
/usr/bin/expiry
/usr/bin/dotlockfile
/usr/bin/chsh
/usr/lib/eject/dmcrypt-get-device
/usr/lib/pt_chown
/bin/ping6
/bin/su
/bin/ping
/bin/umount
/bin/mount
```

**Comment by cboettig** [comment]
@dyndna Yes, messing with the root file system can always cause trouble.  If you are running docker with a non-root user, you should not have permissions to create, delete, or edit anything above `$HOME` (`~/`), just as in usual *NIX, so I'm not sure how you modified `/` files simply with the command shown.  In any event, I wouldn't recommend ever linking host volumes above `$HOME`.

**Comment by dyndna** [comment]
Agree and non-root user usually has no read-write permission above `$HOME`. We have shared mount disk at `/scratch` which has sticky bits set for user-level read-write operations. 

Although I have not tested, I believe your `docker run` command seems to instruct container root to set recursive owner permissions to host `$UID` at and below `pwd`. If that's true, then I doubt if host user permissions has any effect on read-write above user `$HOME`. 

My 2 cents: 
*    I see `-u` flag in `docker run` manual to force docker container use non-root user, and that may be relevant here.
```
$foo:
cd /home/foo/dummy/
docker run -d -P -u $UID -v $(pwd)/home/$USER/foo \
-e USER=$USER  -e USERID = $UID rocker/rstudio
```
*   `docker run` has a few options to play with SUID, SGID at https://docs.docker.com/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration I have not tested those though.

Thanks

**Comment by cboettig** [comment]
@dyndna Yes, you're running the container as a root, so of course it has root permissions and can change the root directories. Note in the examples above we suggest running the container as a non-root user with the `--user` flag.  I think you're confusing this with the suggestion to use things like `e USER=$USER`, which is for a different purpose entirely: setting the user name for the RStudio user (a non root-user, even though rstudio-server itself must be launched with root privileges on the container, hence we do not use `--user` for RStudio instances.  Anyone logging into the RStudio console won't have root privileges and cannot generally write above `$HOME`.  

In your example, since you run the container as root and mount a root directory on the host to the home directory of the container.  If we did not change permissions on that home directory (recursively), the rstudio user would not be able to access it or the files contained in it.  Like you observe, docker volume linking prevents you  from modifying things above the linked volume. 

Thanks for your comments, we should probably add some clarifications to the Wiki on not linking volumes above $HOME.  

Maybe there's a way we can avoid any call to change permissions if volumes are linked; e.g. https://github.com/rocker-org/rocker/blob/master/rstudio/userconf.sh#L55;

**Comment by Robinlovelace** [comment]
Hi @cboettig I'm just hitting into issues with user permissions. I've read this and advice on [StackOverflow](https://stackoverflow.com/questions/34031397/running-docker-on-ubuntu-mounted-host-volume-is-not-writable-from-container) but I find that setting --user makes the docker fail. The 'nuclear option' ` chmod a+rwx geoops  ` works fine but wondered if there's any better advice for people (I'm thinking of updating the advice here in case it fails: https://github.com/Robinlovelace/geocompr#running-geocompr-code-in-docker  )

**Comment by cboettig** [comment]
Hi @Robinlovelace , nice to hear from you.  Just taking a quick look at https://github.com/Robinlovelace/geocompr#running-geocompr-code-in-docker, seems like you're binding to `/data` on the container: 

```
docker run -d -p 8787:8787 -v $(pwd):/data robinlovelace/geocompr
```

If I'm going to be accessing the container with RStudio, I almost always just bind to `/home/rstudio/data` instead:

```
docker run -d -p 8787:8787 -v $(pwd):/home/rstudio/data robinlovelace/geocompr
```

Can  you consider switching to that?  Otherwise you will want to change permissions of `/data` on the container, which is owned by root by default.


Sidenote: binding to `/data` is fine when running in command-line mode as root, e.g.: `docker run -ti  -v $(pwd):/data robinlovelace/geocompr R` since you are then a root user inside the container and can happily write to `/data`.  The downside of this is that back on the host the files you create or modify in that working directory will also now be owned by root.

**Comment by Robinlovelace** [comment]
Many thanks for this lucid explanation. Entendido!

I will update the README (and my own usage of docker) accordingly.

**Comment by Robinlovelace** [comment]
++ PR v welcome (I see you've forked the book ; )

**Comment by Robinlovelace** [comment]
Update @cboettig I've updated the readme following your advice - see here: https://github.com/Robinlovelace/geocompr/commit/a02d3f9adf72acb3c3f88f867f1dbacf572558fe

I'm still getting messages saying RStudio doesn't have the right permissions to open the project. This is separate from the previous issue but my solution is still to do, for example

```bash
 chmod a+rwx geocompr
```

It works out of the box on my windows machine so wonder if its a question of docker set-up. Thanks loads in any case!

**Comment by alexrblohm** [comment]
So I was having the same issues and it was fixed by changing the listening port (sorry, I'm new to this and may be describing it wrong).  I used a docker-compose and did
ports:
        - '50:8787'

That was the big fix for me!
