### ISSUE TITLE
libk5crypto in r-base image doesn't work: "Random number generator could not be seeded while getting initial credentials"

### ISSUE THREAD

**Issue by yrro** [rocker-org/rocker#502]

**Comment by yrro** [comment]
Uuh sorry I hit enter too soon. I'm editing the bug report above to include the actual bug report... please check back soon :)

**Comment by eddelbuettel** [comment]
(Note that you can edit via the ... menu as well as delete so just alter the first box and remove the second)

Does the RNG maybe need elevated rights from the host / docker?   Does not sound like something specific to Rocker ...

**Comment by yrro** [comment]
No it's purely an outdated package - it'll be fixed when you do a new build from a current Debian testing snapshot.

**Comment by eddelbuettel** [comment]
Ok, so you too can do `apt update -qq && apt upgrade -y` and we're done here.  So I think I can close this.

**Comment by yrro** [comment]
FYI `apt upgrade` is currently failing with:

```
Selecting previously unselected package usrmerge.
(Reading database ... 18539 files and directories currently installed.)
Preparing to unpack .../archives/usrmerge_30_all.deb ...
Unpacking usrmerge (30) ...
Setting up usrmerge (30) ...

Warning: overlayfs detected, /usr/lib/usrmerge/convert-usrmerge will not
be run automatically. See #1008202 for details.

If this is a container then it can be converted by unpacking the image,
entering it with chroot(8), installling usrmerge and then repacking the
image again.

E: usrmerge failed.
dpkg: error processing package usrmerge (--configure):
 installed usrmerge package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 usrmerge
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

A targetted upgrade (`apt install libk5crypto3`) avoids running into this problem.

**Comment by eddelbuettel** [comment]
Strange. I _literally_ minutes ago built a local container off my usual starting point, `r-base`.   And I did this in the first two lines:

    FROM r-base

    RUN apt-get update && apt-get install -y -t unstable --no-install-recommends \

**Comment by yrro** [comment]
Looks like you don't `apt upgrade` before installing stuff?

I think this is happening because `init-system-helpers` on testing now Depends on `usrmerge | usr-is-merged`. The current `debian:testing` image has `usr-is-merged` installed, so upgrades don't pull in `usrmerge`. But `r-base:latest` does not currently have `usr-is-merged`, so upgrades pull in `usrmerge` which fails because (I guess) it's not supposed to be used inside a container.

**Comment by eddelbuettel** [comment]
Good point and catch.  Must have skipped that in a rush.  I usually do ...

The usrmerge transition is very new.  Debian unstable something has to live up to its name, I have found these moments to be rare but it can happen.
