### ISSUE TITLE
rocker/r-base:4.2.1: addgroup: addgroup with two arguments is an unspecified operation.

### ISSUE THREAD

**Issue by bathyscapher** [rocker-org/rocker#504]
Hello everyone,

I just wanted to update `rocker/r-base:4.2.0` to `rocker/r-base:4.2.1` using the respective [Dockerfiles](https://github.com/rocker-org/rocker/tree/master/r-base). While the image build process went fine some months ago (July 2022), it now fails with the error `addgroup: addgroup with two arguments is an unspecified operation.` for both Dockerfiles `4.2.0` and `4.2.1`

```sudo docker build -t tst . 
Sending build context to Docker daemon   7.68kB
Step 1/11 : FROM debian:testing
testing: Pulling from library/debian
Digest: sha256:1259c7959ad6824834c9075c3cbd0dde3977680dd334c58de5b8a06ec121c9a1
Status: Downloaded newer image for debian:testing
 ---> e0fbe927d84b
Step 2/11 : LABEL org.opencontainers.image.licenses="GPL-2.0-or-later"       org.opencontainers.image.source="https://github.com/rocker-org/rocker"       org.opencontainers.image.vendor="Rocker Project"       org.opencontainers.image.authors="Dirk Eddelbuettel <edd@debian.org>"
 ---> Using cache
 ---> 0adb35a86905
Step 3/11 : RUN useradd docker 	&& mkdir /home/docker 	&& chown docker:docker /home/docker 	&& addgroup docker staff
 ---> Running in c6425591592f
addgroup: addgroup with two arguments is an unspecified operation.
The command '/bin/sh -c useradd docker 	&& mkdir /home/docker 	&& chown docker:docker /home/docker 	&& addgroup docker staff' returned a non-zero code: 1
```
If `docker build` is run without the line `&& addgroup docker staff` in the Dockerfile, the build process succeeds and the image can be run in containers (and so far without any errors).

The same behaviour appears on
* Debian 11 + Docker 20.10.18, build b40c2f6
* Amazon Linux 2 + Docker 20.10.17, build 100c701
* MacOS 12.6 + Docker 20.10.17, build 100c701

Do you have any idea why this error appears?
Thank you! :)

**Comment by bathyscapher** [comment]
Thank you for the quick response! :)

Okay, good and good to know! Sure, changing for the `latest` is more than fine! I'm just a bit confused now: isn't 4.2.1 identical with latest?

**Comment by eddelbuettel** [comment]
Yes, and I hesitated updating it but our preference is to (as much as possible) keep these as 'how they were when built' -- plus knowing with get R 4.2.2 on October 31 leads to leaving it as.  We have a new 'versioned' one in a few weeks.

(There is another headache as you may have experience with /usrmerge ongoing in Debian. Starting from fresh `debian:testing` (and that I did too for `latest` works but `apt upgrade` of existing, non-prepared for /usrmerge containers, breaks.  These happesn are annoying but they usually only happen once every few years for a good enough reason so ...)
