### ISSUE TITLE
r-base:4.1.2 and higher on ppc64le does not work.

### ISSUE THREAD

**Issue by Someone894** [rocker-org/rocker#505]
Hello,

lately the ppc64le version of the r-base image seems to contain a bug: It quits with a `ERROR: R_HOME ('/usr/lib/R') not found` message. Below you can find a bash snippet that shows that this bug is present at 4.1.2 and higher.

Do you have any idea how to fix this?
If there is something you want me to try out on my power mashine to help you fix the problem just let me know, I'm happy to help.

```bash
user@server:~> uname -m
ppc64le
user@server:~> docker run -it --rm r-base:4.1.1
Unable to find image 'r-base:4.1.1' locally
4.1.1: Pulling from library/r-base
7695f94c27f2: Pull complete
4cf77696e867: Pull complete
946a3786f7cd: Pull complete
e767a06850ad: Pull complete
2e2f5e9c5c6d: Pull complete
fd9d61c392e5: Pull complete
5af26b229962: Pull complete
Digest: sha256:e1dfb1ad27c72d414d7f77088155e2b9c7bd585dd0d5497418f522975c684e98
Status: Downloaded newer image for r-base:4.1.1

R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: powerpc64le-unknown-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

>
Save workspace image? [y/n/c]: n
user@server:~> docker run -it --rm r-base:4.1.2
Unable to find image 'r-base:4.1.2' locally
4.1.2: Pulling from library/r-base
abb89d61badc: Pull complete
29f98cc64611: Pull complete
163347143238: Pull complete
7dbce397a552: Pull complete
4dbf3d094059: Pull complete
9d2441e84b79: Pull complete
0dc258d97a04: Pull complete
Digest: sha256:4cb382e24f5cd07d5c15d8d6587aac7e24d5179e89d5b5ab2039f6add40da616
Status: Downloaded newer image for r-base:4.1.2
ERROR: R_HOME ('/usr/lib/R') not found
user@server:~> 
```

**Comment by eitsupi** [comment]
It looks like the same issue of #489.

What is your Docker version?
You may be able to work around this by using the latest Docker (and there may be no other way to work around it...)

**Comment by Someone894** [comment]
Thank you for the fast reply.
Before I opened this Issue I was looking for errors like "ppc64le not working" but the https://github.com/rocker-org/rocker/issues/489 eluded me.
However on my ppc64le machine I use quite a new docker version:
```bash
user@server:~> docker --version
Docker version 20.10.17-ce, build a89b84221c85
user@server:~>
``` 

Do you believe an update to the newest version (20.10.18) would fix this issue?

**Comment by eitsupi** [comment]
I have little understanding of this issue and don't even know why it still occurs with ppc64le.
However, this does not seem to be an R issue, so I think it would be best to ask the question in the Docker community.

**Comment by Someone894** [comment]
You can fix this bug by updating to SLES15 SP3
