### ISSUE TITLE
`'lib = "/usr/local/lib/R/site-library"' is not writable` error when install R packages by non-root user

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker#513]
An error occurred when I tried to install R packages via `install2.r` command as a non-root user (docker) on r-base (`r-base@sha256:ad49725f24f2abf3f3cb8010abfd00b74d424bc47c4e3841f10e805143e5a6fa`).

I don't think this is the intended behavior as described in the comments below, but is this a bug that occurs only in my environment?

https://github.com/rocker-org/rocker/blob/2f92c6c8b8da7b3e61aabc44cacc0439bf267d31/r-base/latest/Dockerfile#L10-L12

**Comment by eddelbuettel** [comment]
Is that user part of `staff` (or sometimes I use `adm`) ?

Overall it's a bit of a mess, and I guess the comment is stale / got copied from the Debian package setup. 

I like having the system directory _a lot_ but sometimes you either need to `chown` as `root` first, or use `sudo`.  Such is life.  I find I do not use that many containers as a non-root.  If you have a suggestion, let me hear it but this is also 'de facto' behavior now.

**Comment by eitsupi** [comment]
Yes, I am surprised that I and other users have not noticed this behavior before.

```sh
$ groups docker
docker : docker staff
$ ls -la /usr/local/lib/R
total 12
drwxr-xr-x 3 root root 4096 Nov  1 20:21 .
drwxr-xr-x 1 root root 4096 Nov  1 20:21 ..
drwxr-xr-x 2 root root 4096 Nov  1 20:21 site-library
```

Perhaps the `staff` group is not being used?

In `rocker/r-ver`, the site-library is owned by the `staff` group, so users belonging to `staff` can install R packages.
https://github.com/rocker-org/rocker-versioned2/blob/348e1f38af99934f515530714d0d1884e3dafd6c/scripts/install_R_source.sh#L143

I would say this is a bug, but I don't know if it should be changed or not, as changing this behavior would definitely affect existing users...

**Comment by eddelbuettel** [comment]
Maybe it is a recent-ish change:

```sh
edd@rob:~$ docker run --rm -ti rocker/r-base id
uid=0(root) gid=0(root) groups=0(root)
edd@rob:~$ docker run --rm -ti r-base id
uid=0(root) gid=0(root) groups=0(root)
edd@rob:~$ 
```
