### ISSUE TITLE
installation testing fails

### ISSUE THREAD

**Issue by shug0131** [rocker-org/rocker#537]
I'm wanting to carry out the installation testing as described in the manual

https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Testing-a-Unix_002dalike-Installation

I can get past the first step of tools::testInstalledBasic("both"),  by modifying the basic install_R_source.R to add a couple of extra lines ( make install-tests ; chmod a+w /usr/local/lib/R/tests/)  . See my fork https://github.com/shug0131/rocker-versioned2/blob/master/scripts/install_R_source.sh

But the subsequent two lines fail.   Running it on your unaltered image (docker desktop on windows), and my altered one gives the same results.

docker run --rm -ti -e DISABLE_AUTH=true -p 8787:8787 rocker/verse

The then command and output

> tools::testInstalledPackages(scope="base")
Testing examples for package ‘base’
Testing examples for package ‘tools’
Testing examples for package ‘utils’
Running vignettes for package ‘utils’
  Running ‘Sweave.Rnw’

*** Source Errors ***

File Sweave.R:
Running 'texi2dvi' on 'example-1.tex' failed.
LaTeX errors:
! LaTeX Error: File `grfext.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

! Emergency stop.
<read *> 
         
l.179   \RequirePackage{grfext}\relax
                                     ^^M
!  ==> Fatal error occurred, no output PDF file produced!

*** Weave Errors ***

File Sweave.Rnw:
 chunk 2 
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'example-1.tex' failed.
LaTeX errors:
! LaTeX Error: File `grfext.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

! Emergency stop.
<read *> 
         
l.179   \RequirePackage{grfext}\relax
                                     ^^M
!  ==> Fatal error occurred, no output PDF file produced!

Testing examples for package ‘grDevices’
Testing examples for package ‘graphics’
Testing examples for package ‘stats’
Running vignettes for package ‘stats’
  Running ‘reshape.Rnw’
Testing examples for package ‘datasets’
Testing examples for package ‘methods’
Testing examples for package ‘grid’
Running vignettes for package ‘grid’
  Running ‘displaylist.Rnw’
  Running ‘frame.Rnw’
  Running ‘grid.Rnw’
  Running ‘grobs.Rnw’
  Running ‘interactive.Rnw’
  Running ‘locndimn.Rnw’
  Running ‘moveline.Rnw’
  Running ‘nonfinite.Rnw’
  Running ‘plotexample.Rnw’
  Running ‘rotated.Rnw’
  Running ‘saveload.Rnw’
  Running ‘sharing.Rnw’
  Running ‘viewports.Rnw’
Testing examples for package ‘splines’
Testing examples for package ‘stats4’
Testing examples for package ‘tcltk’
Error: testing 'tcltk' failed

-----

Any advice to fix this is very welcome.   Thanks Simon

**Comment by eitsupi** [comment]
You seems opening the issue in the wrong repository.
I think you opened rocker-org/rocker-versioned2#760, so closing this.
