### ISSUE TITLE
Installing packages fails due to broken openssl package in debian testing

### ISSUE THREAD

**Issue by superpuffin** [rocker-org/rocker#549]
When using r-base as a base image, packages such as httr won´t install since they depend on libssl-dev being installed. Trying to install this package using apt results in the following message: 

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssl3t64 : Breaks: libssl3 (< 3.2.1-3)
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

Is there a reason this image is based on an unstable release?

EDIT: using r-base:4.3.3

**Comment by eddelbuettel** [comment]
Please see recent issues, this has been raised before, is entirely due to changes at Debian and can addressed by using the package from unstable.

**Comment by eddelbuettel** [comment]
As an aside, we recommended using `rocker/r2u` where you can just say `install.packages("httr")` and you the *binary* thanks to how [r2u](https://eddelbuettel.github.io/r2u) works.
