### ISSUE TITLE
502 Returned by Rstudio Server when executing 'client_init'

### ISSUE THREAD

**Issue by auddin1-hs** [rocker-org/rocker#557]
User reported running a long script before leaving the session idle. I am assuming that reloading the large backed up session might be causing this issue.

You can reproduce this error if you load a large amount of data into memory and refreshing the page. 

I tried increasing the [rsession-proxy-max-wait-secs](https://support.posit.co/hc/en-us/articles/18239026094359-Status-Code-502-returned-by-RStudio-Server-when-executing-client-init) to 300 seconds but it did not help. I get the same error msg as the link above.

Docker image: rocker/rstudio:4.4

**Comment by eitsupi** [comment]
Please open the issue on the correct repo.
https://github.com/rocker-org/rocker-versioned2
