### ISSUE TITLE
Using r-base 4.2.1 and 3.6.1 against current repos results in error 

### ISSUE THREAD

**Issue by hahahaL** [rocker-org/rocker#559]
info：
  R-base:4.2.1 05eb7a258125 Debian GNU/Linux bookworm/sid \n \l
  R-base:3.6.1 29c68e92c148 Debian GNU/Linux bullseye/sid \n \l
When I use these img， I cannot install sys-packages with apt-get ，exp apt-get install libxml2-dev，the message like these
![1](https://github.com/user-attachments/assets/663e94f7-104e-420d-a2bc-2e619cf3dfe6)
docker-sys:
![2](https://github.com/user-attachments/assets/9c00ae19-2de6-4234-98d0-8120065961e7)
![3](https://github.com/user-attachments/assets/c485eed6-14e5-4722-8e84-b778310520fc)

**Comment by eddelbuettel** [comment]
What is your question?  Can you please post _code_ formatted as text, not in images.

It may help to add a sentence or two explaining

- what you tried to do
- what you did
- what you expected to happen
- what you think happened

**Comment by eddelbuettel** [comment]
I presume you are aware that R 3.6.* and R 4.2.* are, respectively, two and four years old.  What distribution are trying to hit now?  _Current_ Debian unstable / testing?  Expect differences.  

Also please see [issue #1 in rocker/r-devel](https://github.com/rocker-org/r-devel/issues/1) which I answered earlier today.

**Comment by hahahaL** [comment]
> I presume you are aware that R 3.6.* and R 4.2.* are, respectively, two and four years old. What distribution are trying to hit now? _Current_ Debian unstable / testing? Expect differences.
> 
> Also please see [issue #1 in rocker/r-devel](https://github.com/rocker-org/r-devel/issues/1) which I answered earlier today.
I think the issue is based on debian not about with R version.
If we want to use apt-get install command in 05eb7a258125 or 29c68e92c148,we should change the reference docker-R-sys version to make use the filepath like bin lib should be a symbolic link
