### ISSUE TITLE
r-base:latest is still 4.4.0

### ISSUE THREAD

**Issue by lldelisle** [rocker-org/rocker#561]
Hi,
Thank you very much for providing these docker images.
I don't know if it is on purpose but the r-base:latest point to 4.4.0 version.

**Comment by lldelisle** [comment]
Here: https://hub.docker.com/r/rocker/r-base/tags

**Comment by eddelbuettel** [comment]
I see.  While 4.4.1 is there, latest may be at 4.4.0.  I will see about correcting.  Thanks for catching it.

In the meantime, if you use 'r-base:lastest' in lieu of 'rocker/r-base:latest' you should have 4.4.1 too.

**Comment by lldelisle** [comment]
Ah... Thanks

**Comment by eddelbuettel** [comment]
I built and pushed a new rocker/r-base:latest.  Thanks again for catching that.

**Comment by lldelisle** [comment]
You're welcome. Happy to help.
