### ISSUE TITLE
libpath for RD --vanilla lacks /usr/lib/R/library

### ISSUE THREAD

**Issue by wch** [rocker-org/rocker#67]
As discussed in #54, the reason for R-devel to use `/usr/lib/R/library` is so that it can use some standard packages installed via .deb packages, even though they're for R-release.

However, when `RD --vanilla` is used, that directory is not added to the libpath. Here's what happens when you don't use `--vanilla` -- everything works as expected:

```
$ docker run --rm rocker/r-devel RDscript -e ".libPaths()"
[1] "/usr/local/lib/R/site-library" "/usr/local/lib/R/library"     
[3] "/usr/lib/R/library"           

$ docker run --rm rocker/r-devel RDscript -e "library(MASS)"
[No output]
```

When you use `--vanilla`, here's what happens when you try to do the same things:

```
$ docker run --rm rocker/r-devel RDscript --vanilla -e ".libPaths()"
[1] "/usr/local/lib/R/site-library" "/usr/local/lib/R/library"     

$ docker run --rm rocker/r-devel RDscript --vanilla -e "library(MASS)"
Error in library(MASS) : there is no package called ‘MASS’
Execution halted
```

In my case, this results in problems for `RD CMD check --as-cran`, because it uses `--vanilla`, and many times, the check requires standard packages like MASS and codetools, which reside in `/usr/lib/R/library`.

I think it makes more sense for the libpath to be the same whether or not you use `--vanilla`.

I believe the way to fix this is to set the R_LIBS in Renviron instead of setting R_LIBS_SITE in Renviron.site, which is what is currently done in the Dockerfile. For example:

```
$ docker run --rm -ti rocker/r-devel
# RDscript --vanilla -e ".libPaths()"
[1] "/usr/local/lib/R/site-library" "/usr/local/lib/R/library"  

# cd /usr/local/lib/R/etc

# echo "R_LIBS=\${R_LIBS-'/usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib/R/library'}" >> Renviron

# rm Renviron.site 

# RDscript --vanilla -e ".libPaths()"
[1] "/usr/local/lib/R/site-library" "/usr/local/lib/R/library"     
[3] "/usr/lib/R/library"           

# RDscript --vanilla -e "library(MASS)"
[No output]
```

It also works if you set `R_LIBS_SITE` instead of `R_LIBS` in Renviron, though I think that `R_LIBS` makes more sense.

**Comment by cboettig** [comment]
looks like we can close this now (?)
